// generated by newgenasym  Thu May 29 14:08:07 2014


module adv7511ktsz (avdd1, avdd2, avdd3, bgv_dd, cec_clk, cec_in, clk, d0, d1,
        d10, d11, d12, d13, d14, d15, d16, d17, d18, d19, d2, d20, d21,
        d22, d23, d24, d25, d26, d27, d28, d29, d3, d30, d31, d32, d33,
        d34, d35, d4, d5, d6, d7, d8, d9, ddcscl, ddcsda, de, dsd0, dsd1,
        dsd2, dsd3, dsd4, dsd5, dsd_clk, dvdd1, dvdd2, dvdd3, dvdd4,
        dvdd5, gnd1, gnd10, gnd11, gnd2, gnd3, gnd4, gnd5, gnd6, gnd7,
        gnd8, gnd9, \heac+ , \heac- , hpd, hsync, i2s0, i2s1, i2s2, i2s3,
        int, lrclk, mclk, mvdd, pd, plvdd, pvdd1, pvdd2, r_ext, scl,
        sclk, sda, spdif, spdif_out, \tx0+ , \tx0- , \tx1+ , \tx1- , \tx2+ ,
        \tx2- , \txc+ , \txc- , vsync);
    inout avdd1;
    inout avdd2;
    inout avdd3;
    inout bgv_dd;
    inout cec_clk;
    inout cec_in;
    inout clk;
    inout d0;
    inout d1;
    inout d10;
    inout d11;
    inout d12;
    inout d13;
    inout d14;
    inout d15;
    inout d16;
    inout d17;
    inout d18;
    inout d19;
    inout d2;
    inout d20;
    inout d21;
    inout d22;
    inout d23;
    inout d24;
    inout d25;
    inout d26;
    inout d27;
    inout d28;
    inout d29;
    inout d3;
    inout d30;
    inout d31;
    inout d32;
    inout d33;
    inout d34;
    inout d35;
    inout d4;
    inout d5;
    inout d6;
    inout d7;
    inout d8;
    inout d9;
    inout ddcscl;
    inout ddcsda;
    inout de;
    inout dsd0;
    inout dsd1;
    inout dsd2;
    inout dsd3;
    inout dsd4;
    inout dsd5;
    inout dsd_clk;
    inout dvdd1;
    inout dvdd2;
    inout dvdd3;
    inout dvdd4;
    inout dvdd5;
    inout gnd1;
    inout gnd10;
    inout gnd11;
    inout gnd2;
    inout gnd3;
    inout gnd4;
    inout gnd5;
    inout gnd6;
    inout gnd7;
    inout gnd8;
    inout gnd9;
    inout \heac+ ;
    inout \heac- ;
    inout hpd;
    inout hsync;
    inout i2s0;
    inout i2s1;
    inout i2s2;
    inout i2s3;
    inout int;
    inout lrclk;
    inout mclk;
    inout mvdd;
    inout pd;
    inout plvdd;
    inout pvdd1;
    inout pvdd2;
    inout r_ext;
    inout scl;
    inout sclk;
    inout sda;
    inout spdif;
    inout spdif_out;
    inout \tx0+ ;
    inout \tx0- ;
    inout \tx1+ ;
    inout \tx1- ;
    inout \tx2+ ;
    inout \tx2- ;
    inout \txc+ ;
    inout \txc- ;
    inout vsync;


    initial
        begin
        end

endmodule
