-- generated by newgenasym Tue Jan 17 15:59:26 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lb is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC);
end lb;
