// generated by newgenasym  Mon Apr 17 17:11:01 2006


module sn74lvc1g14 (a, gnd, nc, vcc, y);
    input a;
    input gnd;
    inout nc;
    input vcc;
    output y;


    initial
        begin
        end

endmodule
