-- generated by newgenasym Mon Apr 17 17:11:01 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sn74lvc1g14 is
    port (    
	A:         IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	Y:         OUT    STD_LOGIC);
end sn74lvc1g14;
