// generated by newgenasym  Tue Mar 14 17:04:23 2023


module nts0104pw (a1, a2, a3, a4, b1, b2, b3, b4, gnd, nc1, nc2, oe, vcca, vccb);
    inout a1;
    inout a2;
    inout a3;
    inout a4;
    inout b1;
    inout b2;
    inout b3;
    inout b4;
    inout gnd;
    inout nc1;
    inout nc2;
    inout oe;
    inout vcca;
    inout vccb;


    initial
        begin
        end

endmodule
