-- generated by newgenasym Tue Mar 14 17:04:23 2023

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity nts0104pw is
    port (    
	A1:        INOUT  STD_LOGIC;    
	A2:        INOUT  STD_LOGIC;    
	A3:        INOUT  STD_LOGIC;    
	A4:        INOUT  STD_LOGIC;    
	B1:        INOUT  STD_LOGIC;    
	B2:        INOUT  STD_LOGIC;    
	B3:        INOUT  STD_LOGIC;    
	B4:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC;    
	NC2:       INOUT  STD_LOGIC;    
	OE:        INOUT  STD_LOGIC;    
	VCCA:      INOUT  STD_LOGIC;    
	VCCB:      INOUT  STD_LOGIC);
end nts0104pw;
