// generated by newgenasym  Tue Dec 13 19:45:12 2016


module max4224 (\in+ , \in- , out, \shdn* , vcc, vee);
    inout \in+ ;
    inout \in- ;
    inout out;
    inout \shdn* ;
    input vcc;
    inout vee;


    initial
        begin
        end

endmodule
