-- generated by newgenasym Tue Dec 13 19:45:12 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max4224 is
    port (    
	\in+\:     INOUT  STD_LOGIC;    
	\in-\:     INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	\shdn*\:   INOUT  STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	VEE:       INOUT  STD_LOGIC);
end max4224;
