// generated by newgenasym  Sat Nov 22 16:23:19 2025


module ams1117 (gnd, vin, vout, vout1);
    inout gnd;
    inout vin;
    inout vout;
    inout vout1;


    initial
        begin
        end

endmodule
