-- generated by newgenasym Sat Nov 22 16:23:19 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ams1117 is
    port (    
	GND:       INOUT  STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC;    
	VOUT:      INOUT  STD_LOGIC;    
	VOUT1:     INOUT  STD_LOGIC);
end ams1117;
