// generated by newgenasym  Tue May 23 20:28:26 2017


module lmr62014 (fb, gnd, \shdn* , sw, vin);
    inout fb;
    inout gnd;
    inout \shdn* ;
    inout sw;
    inout vin;


    initial
        begin
        end

endmodule
