-- generated by newgenasym Tue May 23 20:28:26 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lmr62014 is
    port (    
	FB:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	\shdn*\:   INOUT  STD_LOGIC;    
	SW:        INOUT  STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC);
end lmr62014;
