-- generated by newgenasym Tue Feb 22 12:11:20 2005

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity RN is
    generic (
        size:positive:= 1
            );
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0);    
	B:         INOUT  STD_LOGIC_VECTOR (size-1 DOWNTO 0));
end RN;
