// generated by newgenasym  Tue Oct 16 22:27:16 2012


module iso7240c (en, gnd1_1, gnd1_2, gnd2_1, gnd2_2, ina, inb, inc, ind, nc,
        outa, outb, outc, outd, vcc1, vcc2);
    input en;
    input gnd1_1;
    input gnd1_2;
    input gnd2_1;
    input gnd2_2;
    input ina;
    input inb;
    input inc;
    input ind;
    inout nc;
    output outa;
    output outb;
    output outc;
    output outd;
    input vcc1;
    input vcc2;


    initial
        begin
        end

endmodule
