-- generated by newgenasym Tue Oct 16 22:27:16 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity iso7240c is
    port (    
	EN:        IN     STD_LOGIC;    
	GND1_1:    IN     STD_LOGIC;    
	GND1_2:    IN     STD_LOGIC;    
	GND2_1:    IN     STD_LOGIC;    
	GND2_2:    IN     STD_LOGIC;    
	INA:       IN     STD_LOGIC;    
	INB:       IN     STD_LOGIC;    
	INC:       IN     STD_LOGIC;    
	IND:       IN     STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	OUTA:      OUT    STD_LOGIC;    
	OUTB:      OUT    STD_LOGIC;    
	OUTC:      OUT    STD_LOGIC;    
	OUTD:      OUT    STD_LOGIC;    
	VCC1:      IN     STD_LOGIC;    
	VCC2:      IN     STD_LOGIC);
end iso7240c;
