// generated by newgenasym  Thu Jul 20 11:05:55 2023


module n25q128a13ese40f (c, dq0, dq1, \hold_n/dq3 , \s* , vcc, vss, \w_n/vpp/dq2 );
    inout c;
    inout dq0;
    inout dq1;
    inout \hold_n/dq3 ;
    inout \s* ;
    inout vcc;
    inout vss;
    inout \w_n/vpp/dq2 ;


    initial
        begin
        end

endmodule
