-- generated by newgenasym Thu Jul 20 11:05:55 2023

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity n25q128a13ese40f is
    port (    
	C:         INOUT  STD_LOGIC;    
	DQ0:       INOUT  STD_LOGIC;    
	DQ1:       INOUT  STD_LOGIC;    
	\hold_n/dq3\: INOUT  STD_LOGIC;    
	\s*\:      INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC;    
	VSS:       INOUT  STD_LOGIC;    
	\w_n/vpp/dq2\: INOUT  STD_LOGIC);
end n25q128a13ese40f;
