// generated by newgenasym  Thu Apr 27 14:58:28 2006


module usb_con (a1, a2, a3, a4, a5, a6);
    inout a1;
    inout a2;
    inout a3;
    inout a4;
    inout a5;
    inout a6;


    initial
        begin
        end

endmodule
