-- generated by newgenasym Thu Apr 27 14:58:28 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity USB_CON is
    port (    
	A1:        INOUT  STD_LOGIC;    
	A2:        INOUT  STD_LOGIC;    
	A3:        INOUT  STD_LOGIC;    
	A4:        INOUT  STD_LOGIC;    
	A5:        INOUT  STD_LOGIC;    
	A6:        INOUT  STD_LOGIC);
end USB_CON;
