`timescale 1ns/1ns

module zc702video ();
// generated by  HDL Direct 15.70-p002 31-May-2006
// on Wed Nov 05 18:59:12 2014
// from sch_lib/ZC702VIDEO/sch_1

  // global signal glbl.gndd;
  // global signal glbl.p3_3v;
  // global signal glbl.p5v;

  wire  \+12v ;
  wire  vcc_1v8;
  wire  unnamed_3_c_i10_1;
  wire  unnamed_3_c_i10_2;
  wire  unnamed_3_c_i26_1;
  wire  unnamed_3_c_i26_2;
  wire  unnamed_3_c_i29_1;
  wire  unnamed_3_c_i31_1;
  wire  unnamed_3_c_i31_2;
  wire  unnamed_3_c_i33_1;
  wire  unnamed_3_c_i44_1;
  wire  unnamed_3_c_i45_1;
  wire  unnamed_3_c_i48_1;
  wire  unnamed_3_c_i48_2;
  wire  unnamed_3_c_i6_1;
  wire  unnamed_3_c_i8_1;
  wire  unnamed_3_c_i8_2;
  wire  unnamed_3_c_i9_1;
  wire  unnamed_3_leds_i56_a;
  wire  unnamed_3_r_i13_b;
  wire  unnamed_3_r_i25_a;
  wire  unnamed_3_r_i40_a;
  wire  unnamed_3_r_i46_b;

  wire  gndd;
  wire  page3_gndd;
  wire  p3_3v;
  wire  page3_p3_3v;
  wire  p5v;
  wire  page3_p5v;

  assign gndd = glbl.gndd;
  assign page3_gndd = gndd;
  assign p3_3v = glbl.p3_3v;
  assign page3_p3_3v = p3_3v;
  assign p5v = glbl.p5v;
  assign page3_p5v = p5v;

  assign gndd  = glbl.gndd;
  assign p3_3v  = glbl.p3_3v;
  assign gndd  = glbl.gndd;
  assign p5v  = glbl.p5v;
  assign gndd  = glbl.gndd;
  assign gndd  = glbl.gndd;
  assign gndd  = glbl.gndd;

// begin instances 

  mt41j128m16 page2_i1  (.a0(/* unconnected */),
	.a1(/* unconnected */),
	.a2(/* unconnected */),
	.a3(/* unconnected */),
	.a4(/* unconnected */),
	.a5(/* unconnected */),
	.a6(/* unconnected */),
	.a7(/* unconnected */),
	.a8(/* unconnected */),
	.a9(/* unconnected */),
	.\a10/ap (/* unconnected */),
	.a11(/* unconnected */),
	.\a12/bc# (/* unconnected */),
	.a13(/* unconnected */),
	.ba0(/* unconnected */),
	.ba1(/* unconnected */),
	.ba2(/* unconnected */),
	.\cas# (/* unconnected */),
	.ck(/* unconnected */),
	.\ck# (/* unconnected */),
	.cke(/* unconnected */),
	.\cs# (/* unconnected */),
	.dml(/* unconnected */),
	.dmu(/* unconnected */),
	.dql0(/* unconnected */),
	.dql1(/* unconnected */),
	.dql2(/* unconnected */),
	.dql3(/* unconnected */),
	.dql4(/* unconnected */),
	.dql5(/* unconnected */),
	.dql6(/* unconnected */),
	.dql7(/* unconnected */),
	.dqsl(/* unconnected */),
	.\dqsl# (/* unconnected */),
	.dqsu(/* unconnected */),
	.\dqsu# (/* unconnected */),
	.dqu0(/* unconnected */),
	.dqu1(/* unconnected */),
	.dqu2(/* unconnected */),
	.dqu3(/* unconnected */),
	.dqu4(/* unconnected */),
	.dqu5(/* unconnected */),
	.dqu6(/* unconnected */),
	.dqu7(/* unconnected */),
	.\nc/a14 (/* unconnected */),
	.\nc/a15 (/* unconnected */),
	.nc_j1(/* unconnected */),
	.nc_j9(/* unconnected */),
	.nc_l1(/* unconnected */),
	.nc_l9(/* unconnected */),
	.odt(/* unconnected */),
	.\ras# (/* unconnected */),
	.\reset# (/* unconnected */),
	.vddq_a1(/* unconnected */),
	.vddq_a8(/* unconnected */),
	.vddq_c1(/* unconnected */),
	.vddq_c9(/* unconnected */),
	.vddq_d2(/* unconnected */),
	.vddq_e9(/* unconnected */),
	.vddq_f1(/* unconnected */),
	.vddq_h2(/* unconnected */),
	.vddq_h9(/* unconnected */),
	.vdd_b2(/* unconnected */),
	.vdd_d9(/* unconnected */),
	.vdd_g7(/* unconnected */),
	.vdd_k2(/* unconnected */),
	.vdd_k8(/* unconnected */),
	.vdd_n1(/* unconnected */),
	.vdd_n9(/* unconnected */),
	.vdd_r1(/* unconnected */),
	.vdd_r9(/* unconnected */),
	.vrefca(/* unconnected */),
	.vrefdq(/* unconnected */),
	.vssq_b1(/* unconnected */),
	.vssq_b9(/* unconnected */),
	.vssq_d1(/* unconnected */),
	.vssq_d8(/* unconnected */),
	.vssq_e2(/* unconnected */),
	.vssq_e8(/* unconnected */),
	.vssq_f9(/* unconnected */),
	.vssq_g1(/* unconnected */),
	.vssq_g9(/* unconnected */),
	.vss_a9(/* unconnected */),
	.vss_b3(/* unconnected */),
	.vss_e1(/* unconnected */),
	.vss_g8(/* unconnected */),
	.vss_j2(/* unconnected */),
	.vss_j8(/* unconnected */),
	.vss_m1(/* unconnected */),
	.vss_m9(/* unconnected */),
	.vss_p1(/* unconnected */),
	.vss_p9(/* unconnected */),
	.vss_t1(/* unconnected */),
	.vss_t9(/* unconnected */),
	.\we# (/* unconnected */),
	.zq(/* unconnected */));

  xrp7664 page3_i1  (.bs(unnamed_3_c_i10_1),
	.comp(unnamed_3_c_i8_1),
	.en(unnamed_3_c_i6_1),
	.ep(glbl.gndd),
	.fb(unnamed_3_r_i13_b),
	.gnd(glbl.gndd),
	.in(\+12v ),
	.ss(unnamed_3_c_i9_1),
	.sw(unnamed_3_c_i10_2));

  cp page3_i2  (.\1 (\+12v ),
	.\2 (glbl.gndd));

  c page3_i3  (.\1 (\+12v ),
	.\2 (glbl.gndd));

  r page3_i5  (.a(unnamed_3_c_i6_1),
	.b(\+12v ));

  c page3_i6  (.\1 (unnamed_3_c_i6_1),
	.\2 (glbl.gndd));

  r page3_i7  (.a(glbl.gndd),
	.b(unnamed_3_c_i8_2));

  c page3_i8  (.\1 (unnamed_3_c_i8_1),
	.\2 (unnamed_3_c_i8_2));

  c page3_i9  (.\1 (unnamed_3_c_i9_1),
	.\2 (glbl.gndd));

  c page3_i10  (.\1 (unnamed_3_c_i10_1),
	.\2 (unnamed_3_c_i10_2));

  l page3_i11  (.a(unnamed_3_c_i10_2),
	.b(glbl.p3_3v));

  r page3_i13  (.a(glbl.gndd),
	.b(unnamed_3_r_i13_b));

  r page3_i14  (.a(unnamed_3_r_i13_b),
	.b(glbl.p3_3v));

  cp page3_i15  (.\1 (glbl.p3_3v),
	.\2 (glbl.gndd));

  c page3_i16  (.\1 (glbl.p3_3v),
	.\2 (glbl.gndd));

  c page3_i17  (.\1 (glbl.p3_3v),
	.\2 (glbl.gndd));

  cp page3_i18  (.\1 (glbl.p3_3v),
	.\2 (glbl.gndd));

  cp page3_i19  (.\1 (glbl.p5v),
	.\2 (glbl.gndd));

  c page3_i20  (.\1 (glbl.p5v),
	.\2 (glbl.gndd));

  cp page3_i22  (.\1 (glbl.p5v),
	.\2 (glbl.gndd));

  c page3_i23  (.\1 (glbl.p5v),
	.\2 (glbl.gndd));

  l page3_i24  (.a(unnamed_3_c_i26_2),
	.b(glbl.p5v));

  r page3_i25  (.a(unnamed_3_r_i25_a),
	.b(glbl.p5v));

  c page3_i26  (.\1 (unnamed_3_c_i26_1),
	.\2 (unnamed_3_c_i26_2));

  xrp7664 page3_i27  (.bs(unnamed_3_c_i26_1),
	.comp(unnamed_3_c_i31_1),
	.en(unnamed_3_c_i33_1),
	.ep(glbl.gndd),
	.fb(unnamed_3_r_i25_a),
	.gnd(glbl.gndd),
	.in(\+12v ),
	.ss(unnamed_3_c_i29_1),
	.sw(unnamed_3_c_i26_2));

  c page3_i29  (.\1 (unnamed_3_c_i29_1),
	.\2 (glbl.gndd));

  r page3_i30  (.a(glbl.gndd),
	.b(unnamed_3_c_i31_2));

  c page3_i31  (.\1 (unnamed_3_c_i31_1),
	.\2 (unnamed_3_c_i31_2));

  r page3_i32  (.a(unnamed_3_c_i33_1),
	.b(\+12v ));

  c page3_i33  (.\1 (unnamed_3_c_i33_1),
	.\2 (glbl.gndd));

  c page3_i34  (.\1 (\+12v ),
	.\2 (glbl.gndd));

  cp page3_i35  (.\1 (\+12v ),
	.\2 (glbl.gndd));

  r page3_i37  (.a(glbl.gndd),
	.b(unnamed_3_r_i25_a));

  tps54228 page3_i39  (.en(unnamed_3_r_i40_a),
	.gnd(glbl.gndd),
	.pgnd(glbl.gndd),
	.ss(unnamed_3_c_i44_1),
	.sw(unnamed_3_c_i48_2),
	.vbst(unnamed_3_c_i48_1),
	.vfb(unnamed_3_r_i46_b),
	.vin(\+12v ),
	.vreg5(unnamed_3_c_i45_1));

  r page3_i40  (.a(unnamed_3_r_i40_a),
	.b(\+12v ));

  cp page3_i41  (.\1 (\+12v ),
	.\2 (gndd));

  c page3_i42  (.\1 (\+12v ),
	.\2 (gndd));

  c page3_i44  (.\1 (unnamed_3_c_i44_1),
	.\2 (glbl.gndd));

  c page3_i45  (.\1 (unnamed_3_c_i45_1),
	.\2 (glbl.gndd));

  r page3_i46  (.a(glbl.gndd),
	.b(unnamed_3_r_i46_b));

  r page3_i47  (.a(vcc_1v8),
	.b(unnamed_3_r_i46_b));

  c page3_i48  (.\1 (unnamed_3_c_i48_1),
	.\2 (unnamed_3_c_i48_2));

  l page3_i49  (.a(unnamed_3_c_i48_2),
	.b(vcc_1v8));

  cp page3_i50  (.\1 (vcc_1v8),
	.\2 (glbl.gndd));

  c page3_i51  (.\1 (vcc_1v8),
	.\2 (glbl.gndd));

  c page3_i52  (.\1 (vcc_1v8),
	.\2 (glbl.gndd));

  cp page3_i53  (.\1 (vcc_1v8),
	.\2 (glbl.gndd));

  r page3_i55  (.a(unnamed_3_leds_i56_a),
	.b(p3_3v));

  led_s page3_i56  (.a(unnamed_3_leds_i56_a),
	.b(glbl.gndd));

endmodule // zc702video(sch_1) 
