// generated by newgenasym  Tue May 24 21:42:12 2011


module flcrystal (a1, a3, gnd2, gnd4);
    inout a1;
    inout a3;
    inout gnd2;
    inout gnd4;


    initial
        begin
        end

endmodule
