-- generated by newgenasym Tue May 24 21:42:12 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity flcrystal is
    port (    
	A1:        INOUT  STD_LOGIC;    
	A3:        INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	GND4:      INOUT  STD_LOGIC);
end flcrystal;
