-- generated by newgenasym Tue Sep 13 17:07:04 2022

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity esd_tvs is
    port (    
	GND:       IN     STD_LOGIC;    
	\i/o1\:    INOUT  STD_LOGIC;    
	\i/o2\:    INOUT  STD_LOGIC);
end esd_tvs;
