// generated by newgenasym  Tue Sep 06 14:37:52 2016


module l3gd20h (cap, cs, den, \drdy/int2 , gnd1, gnd2, gnd3, gnd4, gnd5, int1,
        \scl/spc , \sda/sdi/sdo , \sdo/sa0 , vdd1, vdd2, vdd_io);
    inout cap;
    inout cs;
    inout den;
    inout \drdy/int2 ;
    inout gnd1;
    inout gnd2;
    inout gnd3;
    inout gnd4;
    inout gnd5;
    inout int1;
    inout \scl/spc ;
    inout \sda/sdi/sdo ;
    inout \sdo/sa0 ;
    inout vdd1;
    inout vdd2;
    inout vdd_io;


    initial
        begin
        end

endmodule
