-- generated by newgenasym Tue Sep 06 14:37:52 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity l3gd20h is
    port (    
	CAP:       INOUT  STD_LOGIC;    
	CS:        INOUT  STD_LOGIC;    
	DEN:       INOUT  STD_LOGIC;    
	\drdy/int2\: INOUT  STD_LOGIC;    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	GND3:      INOUT  STD_LOGIC;    
	GND4:      INOUT  STD_LOGIC;    
	GND5:      INOUT  STD_LOGIC;    
	INT1:      INOUT  STD_LOGIC;    
	\scl/spc\: INOUT  STD_LOGIC;    
	\sda/sdi/sdo\: INOUT  STD_LOGIC;    
	\sdo/sa0\: INOUT  STD_LOGIC;    
	VDD1:      INOUT  STD_LOGIC;    
	VDD2:      INOUT  STD_LOGIC;    
	VDD_IO:    INOUT  STD_LOGIC);
end l3gd20h;
