// generated by newgenasym  Sat Mar 09 22:34:23 2013


module dac8551 (din, gnd, sclk, \sync* , vdd, vfb, vout, vref);
    input din;
    input gnd;
    input sclk;
    input \sync* ;
    input vdd;
    input vfb;
    output vout;
    input vref;


    initial
        begin
        end

endmodule
