-- generated by newgenasym Sat Mar 09 22:34:23 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity dac8551 is
    port (    
	DIN:       IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	SCLK:      IN     STD_LOGIC;    
	\sync*\:   IN     STD_LOGIC;    
	VDD:       IN     STD_LOGIC;    
	VFB:       IN     STD_LOGIC;    
	VOUT:      OUT    STD_LOGIC;    
	VREF:      IN     STD_LOGIC);
end dac8551;
