// generated by newgenasym  Sat Nov 22 15:58:29 2025


module \ams1117-3.3  (gnd, vin, vout, vout1);
    inout gnd;
    inout vin;
    inout vout;
    inout vout1;


    initial
        begin
        end

endmodule
