`timescale 1 ns/1 ps

module p3_3v (g );
// generated by Concept HDL Direct Version 05.10-p009 (Production) 06-Mar-98
// on Wed Jan 27 10:21:57 1999
// from adsl_lib/p3_3v/sch_1

  parameter size = 1;

  inout [size-1:0] g;


// begin instances 

endmodule // p3_3v(sch_1) 
