

library ieee;
use ieee.std_logic_1164.all;
use work.all;

entity P3_3V is 

-- generated by Concept HDL Direct Version 05.10-p009 (Production) 06-Mar-98
-- on Wed Jan 27 10:21:57 1999
-- from adsl_lib/p3_3v/sch_1 

  generic (SIZE:positive  );
  port (G:inout std_logic_vector (SIZE-1 downto 0)  );
end P3_3V;

-- HDL Direct File Check Sum: 313 2008261177
