-- generated by newgenasym Mon Sep 03 15:00:38 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity w25q128fv is
    port (    
	CLK:       IN     STD_LOGIC;    
	\cs*\:     IN     STD_LOGIC;    
	\di/io0\:  INOUT  STD_LOGIC;    
	\do/io1\:  INOUT  STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	\hold/reset/io3*\: INOUT  STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	\wp/io2*\: INOUT  STD_LOGIC);
end w25q128fv;
