-- generated by newgenasym Wed Nov 26 23:09:52 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity xc6206p182mr is
    port (    
	GND:       INOUT  STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC;    
	VOUT:      INOUT  STD_LOGIC);
end xc6206p182mr;
