// generated by newgenasym  Mon Jan 09 17:10:35 2006


module \74lvc04  (a, gnd, vcc, \y* );
    input a;
    input gnd;
    input vcc;
    output \y* ;


    initial
        begin
        end

endmodule
