-- generated by newgenasym Mon Jan 09 17:10:35 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74lvc04\ is
    port (    
	A:         IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	\y*\:      OUT    STD_LOGIC);
end \74lvc04\;
