-- generated by newgenasym Thu Apr 27 15:11:12 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity crystal is
    port (    
	A1:        IN     STD_LOGIC;    
	A2:        OUT    STD_LOGIC);
end crystal;
