// generated by newgenasym  Fri Oct 11 20:23:01 2019


module acsl6400 (anode1, anode2, anode3, anode4, cathode1, cathode2,
        cathode3, cathode4, gnd1, gnd2, vdd1, vdd2, vo1, vo2, vo3, vo4);
    inout anode1;
    inout anode2;
    inout anode3;
    inout anode4;
    inout cathode1;
    inout cathode2;
    inout cathode3;
    inout cathode4;
    inout gnd1;
    inout gnd2;
    inout vdd1;
    inout vdd2;
    inout vo1;
    inout vo2;
    inout vo3;
    inout vo4;


    initial
        begin
        end

endmodule
