-- generated by newgenasym Fri Oct 11 20:23:01 2019

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity acsl6400 is
    port (    
	ANODE1:    INOUT  STD_LOGIC;    
	ANODE2:    INOUT  STD_LOGIC;    
	ANODE3:    INOUT  STD_LOGIC;    
	ANODE4:    INOUT  STD_LOGIC;    
	CATHODE1:  INOUT  STD_LOGIC;    
	CATHODE2:  INOUT  STD_LOGIC;    
	CATHODE3:  INOUT  STD_LOGIC;    
	CATHODE4:  INOUT  STD_LOGIC;    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	VDD1:      INOUT  STD_LOGIC;    
	VDD2:      INOUT  STD_LOGIC;    
	VO1:       INOUT  STD_LOGIC;    
	VO2:       INOUT  STD_LOGIC;    
	VO3:       INOUT  STD_LOGIC;    
	VO4:       INOUT  STD_LOGIC);
end acsl6400;
