// generated by newgenasym  Thu Nov 12 16:34:22 2020


module micro_usb_smd (\d+ , \d- , gnd, gndd, gndd2, gndd3, gndd4, id, vbus);
    inout \d+ ;
    inout \d- ;
    inout gnd;
    inout gndd;
    inout gndd2;
    inout gndd3;
    inout gndd4;
    inout id;
    inout vbus;


    initial
        begin
        end

endmodule
