-- generated by newgenasym Thu Nov 12 16:34:22 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity micro_usb_smd is
    port (    
	\d+\:      INOUT  STD_LOGIC;    
	\d-\:      INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	GNDD:      INOUT  STD_LOGIC;    
	GNDD2:     INOUT  STD_LOGIC;    
	GNDD3:     INOUT  STD_LOGIC;    
	GNDD4:     INOUT  STD_LOGIC;    
	ID:        INOUT  STD_LOGIC;    
	VBUS:      INOUT  STD_LOGIC);
end micro_usb_smd;
