// generated by newgenasym  Wed May 17 13:49:25 2017


module tps62170 (agnd, en, fb, pg, pgnd, sw, vin, vos);
    inout agnd;
    inout en;
    inout fb;
    inout pg;
    inout pgnd;
    inout sw;
    inout vin;
    inout vos;


    initial
        begin
        end

endmodule
