-- generated by newgenasym Wed May 17 13:49:25 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tps62170 is
    port (    
	AGND:      INOUT  STD_LOGIC;    
	EN:        INOUT  STD_LOGIC;    
	FB:        INOUT  STD_LOGIC;    
	PG:        INOUT  STD_LOGIC;    
	PGND:      INOUT  STD_LOGIC;    
	SW:        INOUT  STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC;    
	VOS:       INOUT  STD_LOGIC);
end tps62170;
