// generated by newgenasym  Sun Dec 01 13:01:57 2013


module sja1000 (ad0, ad1, ad2, ad3, ad4, ad5, ad6, ad7, ale, clkout, \cs* , \int* ,
        mode, \rd* , \rst* , rx0, rx1, tx0, tx1, vdd1, vdd2, vdd3, vss1,
        vss2, vss3, \wr* , xtal1, xtal2);
    inout ad0;
    inout ad1;
    inout ad2;
    inout ad3;
    inout ad4;
    inout ad5;
    inout ad6;
    inout ad7;
    inout ale;
    inout clkout;
    inout \cs* ;
    inout \int* ;
    inout mode;
    inout \rd* ;
    inout \rst* ;
    inout rx0;
    inout rx1;
    inout tx0;
    inout tx1;
    input vdd1;
    input vdd2;
    input vdd3;
    input vss1;
    input vss2;
    input vss3;
    inout \wr* ;
    inout xtal1;
    inout xtal2;


    initial
        begin
        end

endmodule
