-- generated by newgenasym Sun Dec 01 13:01:57 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sja1000 is
    port (    
	AD0:       INOUT  STD_LOGIC;    
	AD1:       INOUT  STD_LOGIC;    
	AD2:       INOUT  STD_LOGIC;    
	AD3:       INOUT  STD_LOGIC;    
	AD4:       INOUT  STD_LOGIC;    
	AD5:       INOUT  STD_LOGIC;    
	AD6:       INOUT  STD_LOGIC;    
	AD7:       INOUT  STD_LOGIC;    
	ALE:       INOUT  STD_LOGIC;    
	CLKOUT:    INOUT  STD_LOGIC;    
	\cs*\:     INOUT  STD_LOGIC;    
	\int*\:    INOUT  STD_LOGIC;    
	MODE:      INOUT  STD_LOGIC;    
	\rd*\:     INOUT  STD_LOGIC;    
	\rst*\:    INOUT  STD_LOGIC;    
	RX0:       INOUT  STD_LOGIC;    
	RX1:       INOUT  STD_LOGIC;    
	TX0:       INOUT  STD_LOGIC;    
	TX1:       INOUT  STD_LOGIC;    
	VDD1:      IN     STD_LOGIC;    
	VDD2:      IN     STD_LOGIC;    
	VDD3:      IN     STD_LOGIC;    
	VSS1:      IN     STD_LOGIC;    
	VSS2:      IN     STD_LOGIC;    
	VSS3:      IN     STD_LOGIC;    
	\wr*\:     INOUT  STD_LOGIC;    
	XTAL1:     INOUT  STD_LOGIC;    
	XTAL2:     INOUT  STD_LOGIC);
end sja1000;
