-- generated by newgenasym Thu Mar 25 15:01:48 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \switch-3pin\ is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC);
end \switch-3pin\;
