// generated by newgenasym  Mon Aug 07 20:54:18 2006


module sn74lvc245apw (a1, a2, a3, a4, a5, a6, a7, a8, b1, b2, b3, b4, b5, b6, b7, b8, dir,
        gnd, \oe* , vcc);
    input a1;
    output a2;
    input a3;
    output a4;
    input a5;
    output a6;
    input a7;
    output a8;
    output b1;
    input b2;
    output b3;
    input b4;
    output b5;
    input b6;
    output b7;
    input b8;
    input dir;
    output gnd;
    input \oe* ;
    output vcc;


    initial
        begin
        end

endmodule
