-- generated by newgenasym Mon Aug 07 20:54:18 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sn74lvc245apw is
    port (    
	A1:        IN     STD_LOGIC;    
	A2:        OUT    STD_LOGIC;    
	A3:        IN     STD_LOGIC;    
	A4:        OUT    STD_LOGIC;    
	A5:        IN     STD_LOGIC;    
	A6:        OUT    STD_LOGIC;    
	A7:        IN     STD_LOGIC;    
	A8:        OUT    STD_LOGIC;    
	B1:        OUT    STD_LOGIC;    
	B2:        IN     STD_LOGIC;    
	B3:        OUT    STD_LOGIC;    
	B4:        IN     STD_LOGIC;    
	B5:        OUT    STD_LOGIC;    
	B6:        IN     STD_LOGIC;    
	B7:        OUT    STD_LOGIC;    
	B8:        IN     STD_LOGIC;    
	DIR:       IN     STD_LOGIC;    
	GND:       OUT    STD_LOGIC;    
	\oe*\:     IN     STD_LOGIC;    
	VCC:       OUT    STD_LOGIC);
end sn74lvc245apw;
