// generated by newgenasym  Mon Jun 20 21:30:19 2005


module \74lvc244  (\1a1 , \1a2 , \1a3 , \1a4 , \1oe* , \1y1 , \1y2 , \1y3 , \1y4 , \2a1 , \2a2 , \2a3 , \2a4 ,
        \2oe* , \2y1 , \2y2 , \2y3 , \2y4 , gnd, vcc);
    input \1a1 ;
    input \1a2 ;
    input \1a3 ;
    input \1a4 ;
    input \1oe* ;
    output \1y1 ;
    output \1y2 ;
    output \1y3 ;
    output \1y4 ;
    input \2a1 ;
    input \2a2 ;
    input \2a3 ;
    input \2a4 ;
    input \2oe* ;
    output \2y1 ;
    output \2y2 ;
    output \2y3 ;
    output \2y4 ;
    output gnd;
    output vcc;


    initial
        begin
        end

endmodule
