-- generated by newgenasym Mon Jun 20 21:30:19 2005

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74lvc244\ is
    port (    
	\1a1\:     IN     STD_LOGIC;    
	\1a2\:     IN     STD_LOGIC;    
	\1a3\:     IN     STD_LOGIC;    
	\1a4\:     IN     STD_LOGIC;    
	\1oe*\:    IN     STD_LOGIC;    
	\1y1\:     OUT    STD_LOGIC;    
	\1y2\:     OUT    STD_LOGIC;    
	\1y3\:     OUT    STD_LOGIC;    
	\1y4\:     OUT    STD_LOGIC;    
	\2a1\:     IN     STD_LOGIC;    
	\2a2\:     IN     STD_LOGIC;    
	\2a3\:     IN     STD_LOGIC;    
	\2a4\:     IN     STD_LOGIC;    
	\2oe*\:    IN     STD_LOGIC;    
	\2y1\:     OUT    STD_LOGIC;    
	\2y2\:     OUT    STD_LOGIC;    
	\2y3\:     OUT    STD_LOGIC;    
	\2y4\:     OUT    STD_LOGIC;    
	GND:       OUT    STD_LOGIC;    
	VCC:       OUT    STD_LOGIC);
end \74lvc244\;
