-- generated by newgenasym Thu Nov 14 15:55:50 2024

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity c is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end c;
