-- generated by newgenasym Mon Feb 22 21:15:41 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity pmosfet is
    port (    
	D:         INOUT  STD_LOGIC;    
	G:         INOUT  STD_LOGIC;    
	S:         INOUT  STD_LOGIC);
end pmosfet;
