// generated by newgenasym  Tue Dec  2 17:27:29 2025


module tpa6120a2dwpr (ep, \lin+ , \lin- , lout, \lvcc+ , \lvcc- , nc, nc1, nc2, nc3, nc4, nc5,
        nc6, nc7, nc8, nc9, \rin+ , \rin- , rout, \rvcc+ , \rvcc- );
    inout ep;
    inout \lin+ ;
    inout \lin- ;
    inout lout;
    inout \lvcc+ ;
    inout \lvcc- ;
    inout nc;
    inout nc1;
    inout nc2;
    inout nc3;
    inout nc4;
    inout nc5;
    inout nc6;
    inout nc7;
    inout nc8;
    inout nc9;
    inout \rin+ ;
    inout \rin- ;
    inout rout;
    inout \rvcc+ ;
    inout \rvcc- ;


    initial
        begin
        end

endmodule
