-- generated by newgenasym Tue Dec  2 17:27:29 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tpa6120a2dwpr is
    port (    
	EP:        INOUT  STD_LOGIC;    
	\lin+\:    INOUT  STD_LOGIC;    
	\lin-\:    INOUT  STD_LOGIC;    
	LOUT:      INOUT  STD_LOGIC;    
	\lvcc+\:   INOUT  STD_LOGIC;    
	\lvcc-\:   INOUT  STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC;    
	NC2:       INOUT  STD_LOGIC;    
	NC3:       INOUT  STD_LOGIC;    
	NC4:       INOUT  STD_LOGIC;    
	NC5:       INOUT  STD_LOGIC;    
	NC6:       INOUT  STD_LOGIC;    
	NC7:       INOUT  STD_LOGIC;    
	NC8:       INOUT  STD_LOGIC;    
	NC9:       INOUT  STD_LOGIC;    
	\rin+\:    INOUT  STD_LOGIC;    
	\rin-\:    INOUT  STD_LOGIC;    
	ROUT:      INOUT  STD_LOGIC;    
	\rvcc+\:   INOUT  STD_LOGIC;    
	\rvcc-\:   INOUT  STD_LOGIC);
end tpa6120a2dwpr;
