// generated by newgenasym  Tue Dec 13 16:38:37 2016


module ad8130a (\+in , \+vs , \-in , \-vs , fb, out, \pd* , ref);
    inout \+in ;
    inout \+vs ;
    inout \-in ;
    inout \-vs ;
    inout fb;
    inout out;
    inout \pd* ;
    inout ref;


    initial
        begin
        end

endmodule
