-- generated by newgenasym Tue Dec 13 16:38:37 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad8130a is
    port (    
	\+in\:     INOUT  STD_LOGIC;    
	\+vs\:     INOUT  STD_LOGIC;    
	\-in\:     INOUT  STD_LOGIC;    
	\-vs\:     INOUT  STD_LOGIC;    
	FB:        INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	\pd*\:     INOUT  STD_LOGIC;    
	REF:       INOUT  STD_LOGIC);
end ad8130a;
