-- generated by newgenasym Mon Dec  1 14:35:15 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ss54_c5200096 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end ss54_c5200096;
