// generated by newgenasym  Wed Jul 19 12:32:19 2023


module fk_oscillator (gnd, \oe/nc , out, vdd);
    input gnd;
    input \oe/nc ;
    output out;
    input vdd;


    initial
        begin
        end

endmodule
