-- generated by newgenasym Wed Jul 19 12:32:19 2023

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity fk_oscillator is
    port (    
	GND:       IN     STD_LOGIC;    
	\oe/nc\:   IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	VDD:       IN     STD_LOGIC);
end fk_oscillator;
