// generated by newgenasym  Sat Nov 24 09:02:45 2012


module pci_lack2pin (\12v+ , \12v- , \3.3v+_1 , \3.3v+_10 , \3.3v+_11 , \3.3v+_12 , \3.3v+_2 ,
        \3.3v+_3 , \3.3v+_4 , \3.3v+_5 , \3.3v+_6 , \3.3v+_7 , \3.3v+_8 ,
        \3.3v+_9 , \5v+_1 , \5v+_2 , \5v+_3 , \5v+_4 , \5v+_5 , \5v+_6 , \5v+_7 ,
        \5v+_8 , \5v+i/0_3 , \5v+i/0_4 , \5v+i/o_1 , \5v+i/o_2 , \5v+i/o_5 ,
        \ack64# , ad00, ad01, ad02, ad03, ad04, ad05, ad06, ad07, ad08,
        ad09, ad10, ad11, ad12, ad13, ad14, ad15, ad16, ad17, ad18,
        ad19, ad20, ad21, ad22, ad23, ad24, ad25, ad26, ad27, ad28,
        ad29, ad30, ad31, \c/be0# , \c/be1# , \c/be2# , \c/be3# , clk,
        \devsel# , \frame# , gnd1, gnd10, gnd11, gnd12, gnd13, gnd14,
        gnd15, gnd16, gnd17, gnd18, gnd19, gnd2, gnd20, gnd21, gnd22,
        gnd3, gnd4, gnd5, gnd6, gnd7, gnd8, gnd9, \gnt# , idsel, inta,
        \intb# , \intc# , \intd# , \lock# , par, \perr# , prsnt2, \prsnt2# , \req# ,
        \req64# , \rst# , rsvd1, rsvd2, rsvd3, rsvd4, rsvd5, rsvd6, \sbo# ,
        sdone, \serr# , \stop# , tck, tdi, tdo, tms, \tr5t# , \trdy#1 , \trdy#2 );
    input \12v+ ;
    input \12v- ;
    input \3.3v+_1 ;
    input \3.3v+_10 ;
    input \3.3v+_11 ;
    input \3.3v+_12 ;
    input \3.3v+_2 ;
    input \3.3v+_3 ;
    input \3.3v+_4 ;
    input \3.3v+_5 ;
    input \3.3v+_6 ;
    input \3.3v+_7 ;
    input \3.3v+_8 ;
    input \3.3v+_9 ;
    input \5v+_1 ;
    input \5v+_2 ;
    input \5v+_3 ;
    input \5v+_4 ;
    input \5v+_5 ;
    input \5v+_6 ;
    input \5v+_7 ;
    input \5v+_8 ;
    inout \5v+i/0_3 ;
    inout \5v+i/0_4 ;
    inout \5v+i/o_1 ;
    inout \5v+i/o_2 ;
    inout \5v+i/o_5 ;
    inout \ack64# ;
    inout ad00;
    inout ad01;
    inout ad02;
    inout ad03;
    inout ad04;
    inout ad05;
    inout ad06;
    inout ad07;
    inout ad08;
    inout ad09;
    inout ad10;
    inout ad11;
    inout ad12;
    inout ad13;
    inout ad14;
    inout ad15;
    inout ad16;
    inout ad17;
    inout ad18;
    inout ad19;
    inout ad20;
    inout ad21;
    inout ad22;
    inout ad23;
    inout ad24;
    inout ad25;
    inout ad26;
    inout ad27;
    inout ad28;
    inout ad29;
    inout ad30;
    inout ad31;
    inout \c/be0# ;
    inout \c/be1# ;
    inout \c/be2# ;
    inout \c/be3# ;
    inout clk;
    inout \devsel# ;
    inout \frame# ;
    input gnd1;
    input gnd10;
    input gnd11;
    input gnd12;
    input gnd13;
    input gnd14;
    input gnd15;
    input gnd16;
    input gnd17;
    input gnd18;
    input gnd19;
    input gnd2;
    input gnd20;
    input gnd21;
    input gnd22;
    input gnd3;
    input gnd4;
    input gnd5;
    input gnd6;
    input gnd7;
    input gnd8;
    input gnd9;
    inout \gnt# ;
    inout idsel;
    inout inta;
    inout \intb# ;
    inout \intc# ;
    inout \intd# ;
    inout \lock# ;
    inout par;
    inout \perr# ;
    inout prsnt2;
    inout \prsnt2# ;
    inout \req# ;
    inout \req64# ;
    inout \rst# ;
    inout rsvd1;
    inout rsvd2;
    inout rsvd3;
    inout rsvd4;
    inout rsvd5;
    inout rsvd6;
    inout \sbo# ;
    inout sdone;
    inout \serr# ;
    inout \stop# ;
    inout tck;
    inout tdi;
    inout tdo;
    inout tms;
    inout \tr5t# ;
    inout \trdy#1 ;
    inout \trdy#2 ;


    initial
        begin
        end

endmodule
