// generated by newgenasym  Tue Sep 06 17:00:27 2016


module \ms5611-01ba  (csb1, csb2, gnd, ps, sclk, \sdi/sda , sdo, vdd);
    inout csb1;
    inout csb2;
    inout gnd;
    inout ps;
    inout sclk;
    inout \sdi/sda ;
    inout sdo;
    inout vdd;


    initial
        begin
        end

endmodule
