-- generated by newgenasym Tue Sep 06 17:00:27 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \ms5611-01ba\ is
    port (    
	CSB1:      INOUT  STD_LOGIC;    
	CSB2:      INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	PS:        INOUT  STD_LOGIC;    
	SCLK:      INOUT  STD_LOGIC;    
	\sdi/sda\: INOUT  STD_LOGIC;    
	SDO:       INOUT  STD_LOGIC;    
	VDD:       INOUT  STD_LOGIC);
end \ms5611-01ba\;
