-- generated by newgenasym Sat Nov 22 16:27:50 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity c0805 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end c0805;
