-- generated by newgenasym Sat Nov 15 22:20:57 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity res0805 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end res0805;
