-- generated by newgenasym Mon Jan 16 15:06:35 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ref102 is
    port (    
	COM:       IN     STD_LOGIC;    
	\noise reduction\: INOUT  STD_LOGIC;    
	TRIM:      INOUT  STD_LOGIC;    
	\v+\:      IN     STD_LOGIC;    
	VOUT:      OUT    STD_LOGIC);
end ref102;
