-- generated by newgenasym Tue Mar 13 22:49:53 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity header26 is
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (26 DOWNTO 1));
end header26;
