// generated by newgenasym  Sun Mar 10 15:57:38 2013


module ads1602 (agnd1, agnd2, agnd3, agnd4, agnd5, agnd6, agnd7, ainn, ainp,
        avdd1, avdd2, avdd3, avdd4, avdd5, clk, dgnd1, dgnd2, dgnd3,
        dgnd4, dgnd5, \dout* , dout1, dvdd1, dvdd2, dvdd3, \fso* , fso1,
        iovdd, nc1, nc2, nc3, nc4, nc5, nc6, otr, \pd* , rbias, \refen* ,
        rpullup, \sclk* , sclk1, sync, vcap, vmid, vrefn, vrefn2,
        vrefp1, vrefp2);
    input agnd1;
    input agnd2;
    input agnd3;
    input agnd4;
    input agnd5;
    input agnd6;
    input agnd7;
    input ainn;
    input ainp;
    input avdd1;
    input avdd2;
    input avdd3;
    input avdd4;
    input avdd5;
    output clk;
    input dgnd1;
    input dgnd2;
    input dgnd3;
    input dgnd4;
    input dgnd5;
    output \dout* ;
    output dout1;
    input dvdd1;
    input dvdd2;
    input dvdd3;
    output \fso* ;
    output fso1;
    inout iovdd;
    inout nc1;
    inout nc2;
    inout nc3;
    inout nc4;
    inout nc5;
    inout nc6;
    output otr;
    input \pd* ;
    inout rbias;
    input \refen* ;
    input rpullup;
    output \sclk* ;
    output sclk1;
    input sync;
    inout vcap;
    inout vmid;
    inout vrefn;
    inout vrefn2;
    inout vrefp1;
    inout vrefp2;


    initial
        begin
        end

endmodule
