// generated by newgenasym  Mon Jan 09 16:42:25 2006


module \74lvc1g32  (a, b, gnd, vcc, y);
    input a;
    input b;
    input gnd;
    input vcc;
    output y;


    initial
        begin
        end

endmodule
