// generated by newgenasym  Tue Sep 05 18:51:58 2017


module adm2682ebriz (a, b, de, gnd1, gnd2, gnd3, gnd4, rxd, txd, vcc, vcc2, visoin,
        visoout, y, z, \|re );
    inout a;
    inout b;
    inout de;
    inout gnd1;
    inout gnd2;
    inout gnd3;
    inout gnd4;
    inout rxd;
    inout txd;
    inout vcc;
    inout vcc2;
    inout visoin;
    inout visoout;
    inout y;
    inout z;
    inout \|re ;


    initial
        begin
        end

endmodule
