-- generated by newgenasym Tue Sep 05 18:51:58 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adm2682ebriz is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC;    
	DE:        INOUT  STD_LOGIC;    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	GND3:      INOUT  STD_LOGIC;    
	GND4:      INOUT  STD_LOGIC;    
	RXD:       INOUT  STD_LOGIC;    
	TXD:       INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC;    
	VCC2:      INOUT  STD_LOGIC;    
	VISOIN:    INOUT  STD_LOGIC;    
	VISOOUT:   INOUT  STD_LOGIC;    
	Y:         INOUT  STD_LOGIC;    
	Z:         INOUT  STD_LOGIC;    
	\|re\:     INOUT  STD_LOGIC);
end adm2682ebriz;
