// generated by newgenasym  Mon Jan 09 16:49:38 2006


module \74lvc16374  (\1clk , \1d1 , \1d2 , \1d3 , \1d4 , \1d5 , \1d6 , \1d7 , \1d8 , \1oe* , \1q1 , \1q2 ,
        \1q3 , \1q4 , \1q5 , \1q6 , \1q7 , \1q8 , \2clk , \2d1 , \2d2 , \2d3 , \2d4 , \2d5 , \2d6 ,
        \2d7 , \2d8 , \2oe* , \2q1 , \2q2 , \2q3 , \2q4 , \2q5 , \2q6 , \2q7 , \2q8 , gnd, vcc);
    input \1clk ;
    input \1d1 ;
    input \1d2 ;
    input \1d3 ;
    input \1d4 ;
    input \1d5 ;
    input \1d6 ;
    input \1d7 ;
    input \1d8 ;
    input \1oe* ;
    output \1q1 ;
    output \1q2 ;
    output \1q3 ;
    output \1q4 ;
    output \1q5 ;
    output \1q6 ;
    output \1q7 ;
    output \1q8 ;
    input \2clk ;
    input \2d1 ;
    input \2d2 ;
    input \2d3 ;
    input \2d4 ;
    input \2d5 ;
    input \2d6 ;
    input \2d7 ;
    input \2d8 ;
    input \2oe* ;
    output \2q1 ;
    output \2q2 ;
    output \2q3 ;
    output \2q4 ;
    output \2q5 ;
    output \2q6 ;
    output \2q7 ;
    output \2q8 ;
    input [7:0] gnd;
    input [3:0] vcc;


    initial
        begin
        end

endmodule
