-- generated by newgenasym Mon Jan 09 16:49:38 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74lvc16374\ is
    port (    
	\1clk\:    IN     STD_LOGIC;    
	\1d1\:     IN     STD_LOGIC;    
	\1d2\:     IN     STD_LOGIC;    
	\1d3\:     IN     STD_LOGIC;    
	\1d4\:     IN     STD_LOGIC;    
	\1d5\:     IN     STD_LOGIC;    
	\1d6\:     IN     STD_LOGIC;    
	\1d7\:     IN     STD_LOGIC;    
	\1d8\:     IN     STD_LOGIC;    
	\1oe*\:    IN     STD_LOGIC;    
	\1q1\:     OUT    STD_LOGIC;    
	\1q2\:     OUT    STD_LOGIC;    
	\1q3\:     OUT    STD_LOGIC;    
	\1q4\:     OUT    STD_LOGIC;    
	\1q5\:     OUT    STD_LOGIC;    
	\1q6\:     OUT    STD_LOGIC;    
	\1q7\:     OUT    STD_LOGIC;    
	\1q8\:     OUT    STD_LOGIC;    
	\2clk\:    IN     STD_LOGIC;    
	\2d1\:     IN     STD_LOGIC;    
	\2d2\:     IN     STD_LOGIC;    
	\2d3\:     IN     STD_LOGIC;    
	\2d4\:     IN     STD_LOGIC;    
	\2d5\:     IN     STD_LOGIC;    
	\2d6\:     IN     STD_LOGIC;    
	\2d7\:     IN     STD_LOGIC;    
	\2d8\:     IN     STD_LOGIC;    
	\2oe*\:    IN     STD_LOGIC;    
	\2q1\:     OUT    STD_LOGIC;    
	\2q2\:     OUT    STD_LOGIC;    
	\2q3\:     OUT    STD_LOGIC;    
	\2q4\:     OUT    STD_LOGIC;    
	\2q5\:     OUT    STD_LOGIC;    
	\2q6\:     OUT    STD_LOGIC;    
	\2q7\:     OUT    STD_LOGIC;    
	\2q8\:     OUT    STD_LOGIC;    
	GND:       IN     STD_LOGIC_VECTOR (7 DOWNTO 0);    
	VCC:       IN     STD_LOGIC_VECTOR (3 DOWNTO 0));
end \74lvc16374\;
