// generated by newgenasym  Tue Dec 20 18:29:43 2016


module isl55110 (gnd, \in-a , \in-b , oa, ob, pd, vdd, vh);
    inout gnd;
    inout \in-a ;
    inout \in-b ;
    inout oa;
    inout ob;
    inout pd;
    inout vdd;
    inout vh;


    initial
        begin
        end

endmodule
