-- generated by newgenasym Tue Dec 20 18:29:43 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity isl55110 is
    port (    
	GND:       INOUT  STD_LOGIC;    
	\in-a\:    INOUT  STD_LOGIC;    
	\in-b\:    INOUT  STD_LOGIC;    
	OA:        INOUT  STD_LOGIC;    
	OB:        INOUT  STD_LOGIC;    
	PD:        INOUT  STD_LOGIC;    
	VDD:       INOUT  STD_LOGIC;    
	VH:        INOUT  STD_LOGIC);
end isl55110;
