// generated by newgenasym  Wed Mar 13 00:39:22 2013


module ad8021 (comp, \disable* , \in+ , \in- , \logic#20ref , vout, \vs+ , \vs- );
    output comp;
    input \disable* ;
    input \in+ ;
    input \in- ;
    input \logic#20ref ;
    output vout;
    input \vs+ ;
    input \vs- ;


    initial
        begin
        end

endmodule
