-- generated by newgenasym Wed Mar 13 00:39:22 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad8021 is
    port (    
	COMP:      OUT    STD_LOGIC;    
	\disable*\: IN     STD_LOGIC;    
	\in+\:     IN     STD_LOGIC;    
	\in-\:     IN     STD_LOGIC;    
	\logic ref\: IN     STD_LOGIC;    
	VOUT:      OUT    STD_LOGIC;    
	\vs+\:     IN     STD_LOGIC;    
	\vs-\:     IN     STD_LOGIC);
end ad8021;
