// generated by newgenasym  Wed May 28 09:57:20 2014


module tps62300 (adj, agnd, avin, en, fb, \mode/sync , pgnd, pt, sw, vin, vout);
    inout adj;
    inout agnd;
    inout avin;
    inout en;
    inout fb;
    inout \mode/sync ;
    inout pgnd;
    inout pt;
    inout sw;
    inout vin;
    inout vout;


    initial
        begin
        end

endmodule
