-- generated by newgenasym Wed May 28 09:57:20 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity TPS62300 is
    port (    
	ADJ:       INOUT  STD_LOGIC;    
	AGND:      INOUT  STD_LOGIC;    
	AVIN:      INOUT  STD_LOGIC;    
	EN:        INOUT  STD_LOGIC;    
	FB:        INOUT  STD_LOGIC;    
	\mode/sync\: INOUT  STD_LOGIC;    
	PGND:      INOUT  STD_LOGIC;    
	PT:        INOUT  STD_LOGIC;    
	SW:        INOUT  STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC;    
	VOUT:      INOUT  STD_LOGIC);
end TPS62300;
