// generated by newgenasym  Mon Jan 09 16:43:19 2006


module \74lvc138  (a, b, c, g1, \g2a* , \g2b* , gnd, vcc, y);
    input a;
    input b;
    input c;
    input g1;
    input \g2a* ;
    input \g2b* ;
    input gnd;
    input vcc;
    output [7:0] y;


    initial
        begin
        end

endmodule
