-- generated by newgenasym Mon Jan 09 16:43:19 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74lvc138\ is
    port (    
	A:         IN     STD_LOGIC;    
	B:         IN     STD_LOGIC;    
	C:         IN     STD_LOGIC;    
	G1:        IN     STD_LOGIC;    
	\g2a*\:    IN     STD_LOGIC;    
	\g2b*\:    IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	Y:         OUT    STD_LOGIC_VECTOR (7 DOWNTO 0));
end \74lvc138\;
