// generated by newgenasym  Sat Oct 27 21:38:03 2012


module dac7311 (\avdd/vref , din, gnd, sclk, \sync* , vout);
    input \avdd/vref ;
    input din;
    input gnd;
    input sclk;
    input \sync* ;
    output vout;


    initial
        begin
        end

endmodule
