-- generated by newgenasym Sat Oct 27 21:38:03 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity dac7311 is
    port (    
	\avdd/vref\: IN     STD_LOGIC;    
	DIN:       IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	SCLK:      IN     STD_LOGIC;    
	\sync*\:   IN     STD_LOGIC;    
	VOUT:      OUT    STD_LOGIC);
end dac7311;
