-- generated by newgenasym Thu Sep 14 14:30:04 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity rj45_led is
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (14 DOWNTO 1));
end rj45_led;
