// generated by newgenasym  Mon Apr 28 10:46:44 2008


module ltc2641 (\clr* , \cs* , din, gnd, ref, sclk, vdd, vout);
    inout \clr* ;
    inout \cs* ;
    inout din;
    inout gnd;
    inout ref;
    inout sclk;
    inout vdd;
    inout vout;


    initial
        begin
        end

endmodule
