-- generated by newgenasym Mon Apr 28 10:46:44 2008

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ltc2641 is
    port (    
	\clr*\:    INOUT  STD_LOGIC;    
	\cs*\:     INOUT  STD_LOGIC;    
	DIN:       INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	REF:       INOUT  STD_LOGIC;    
	SCLK:      INOUT  STD_LOGIC;    
	VDD:       INOUT  STD_LOGIC;    
	VOUT:      INOUT  STD_LOGIC);
end ltc2641;
