// generated by newgenasym  Mon Oct 22 15:55:07 2012


module xrp7664 (bs, comp, en, ep, fb, gnd, in, ss, sw);
    input bs;
    output comp;
    input en;
    input ep;
    input fb;
    input gnd;
    input in;
    input ss;
    output sw;


    initial
        begin
        end

endmodule
