-- generated by newgenasym Mon Oct 22 15:55:07 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity xrp7664 is
    port (    
	BS:        IN     STD_LOGIC;    
	COMP:      OUT    STD_LOGIC;    
	EN:        IN     STD_LOGIC;    
	EP:        IN     STD_LOGIC;    
	FB:        IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	\in\:      IN     STD_LOGIC;    
	SS:        IN     STD_LOGIC;    
	SW:        OUT    STD_LOGIC);
end xrp7664;
