// generated by newgenasym  Sat Oct 27 21:10:25 2012


module ads7883 (\cs* , gnd, sclk, sdo, vdd, vin);
    input \cs* ;
    input gnd;
    input sclk;
    output sdo;
    input vdd;
    input vin;


    initial
        begin
        end

endmodule
