-- generated by newgenasym Sat Oct 27 21:10:25 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ads7883 is
    port (    
	\cs*\:     IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	SCLK:      IN     STD_LOGIC;    
	SDO:       OUT    STD_LOGIC;    
	VDD:       IN     STD_LOGIC;    
	VIN:       IN     STD_LOGIC);
end ads7883;
