// generated by newgenasym  Fri Mar 26 15:10:14 2021


module lmr14020sddar (boot, en, fb, gnd, pad, \rt/sync , ss, sw, vin);
    inout boot;
    inout en;
    inout fb;
    inout gnd;
    inout pad;
    inout \rt/sync ;
    inout ss;
    inout sw;
    inout vin;


    initial
        begin
        end

endmodule
