-- generated by newgenasym Fri Mar 26 15:10:14 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lmr14020sddar is
    port (    
	BOOT:      INOUT  STD_LOGIC;    
	EN:        INOUT  STD_LOGIC;    
	FB:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	PAD:       INOUT  STD_LOGIC;    
	\rt/sync\: INOUT  STD_LOGIC;    
	SS:        INOUT  STD_LOGIC;    
	SW:        INOUT  STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC);
end lmr14020sddar;
