// generated by newgenasym  Thu Nov 13 16:32:11 2014


module lmt043 (b0, b1, b2, b3, b4, b5, b6, b7, dclk, de, disp, g0, g1, g2, g3, g4,
        g5, g6, g7, gnd1, gnd2, gnd3, hsync, \n/c1 , \n/c2 , nc1, r0, r1, r2,
        r3, r4, r5, r6, r7, vdd1, \vled+ , \vled- , vsync, xl, xr, yd, yu);
    inout b0;
    inout b1;
    inout b2;
    inout b3;
    inout b4;
    inout b5;
    inout b6;
    inout b7;
    inout dclk;
    inout de;
    inout disp;
    inout g0;
    inout g1;
    inout g2;
    inout g3;
    inout g4;
    inout g5;
    inout g6;
    inout g7;
    inout gnd1;
    inout gnd2;
    inout gnd3;
    inout hsync;
    inout \n/c1 ;
    inout \n/c2 ;
    inout nc1;
    inout r0;
    inout r1;
    inout r2;
    inout r3;
    inout r4;
    inout r5;
    inout r6;
    inout r7;
    inout vdd1;
    inout \vled+ ;
    inout \vled- ;
    inout vsync;
    inout xl;
    inout xr;
    inout yd;
    inout yu;


    initial
        begin
        end

endmodule
