// generated by newgenasym  Tue Dec 13 15:10:42 2016


module lm324 (\1in+ , \1in- , \1out , \2in+ , \2in- , \2out , \3in+ , \3in- , \3out , \4in+ ,
        \4in- , \4out , gnd, vcc);
    inout \1in+ ;
    inout \1in- ;
    inout \1out ;
    inout \2in+ ;
    inout \2in- ;
    inout \2out ;
    inout \3in+ ;
    inout \3in- ;
    inout \3out ;
    inout \4in+ ;
    inout \4in- ;
    inout \4out ;
    input gnd;
    input vcc;


    initial
        begin
        end

endmodule
