-- generated by newgenasym Tue Dec 13 15:10:42 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lm324 is
    port (    
	\1in+\:    INOUT  STD_LOGIC;    
	\1in-\:    INOUT  STD_LOGIC;    
	\1out\:    INOUT  STD_LOGIC;    
	\2in+\:    INOUT  STD_LOGIC;    
	\2in-\:    INOUT  STD_LOGIC;    
	\2out\:    INOUT  STD_LOGIC;    
	\3in+\:    INOUT  STD_LOGIC;    
	\3in-\:    INOUT  STD_LOGIC;    
	\3out\:    INOUT  STD_LOGIC;    
	\4in+\:    INOUT  STD_LOGIC;    
	\4in-\:    INOUT  STD_LOGIC;    
	\4out\:    INOUT  STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end lm324;
