// generated by newgenasym  Tue Aug 09 20:18:52 2016


module fm25v01a (cs, hold, sck, si, so, vdd, vss, wp);
    inout cs;
    inout hold;
    inout sck;
    inout si;
    inout so;
    inout vdd;
    inout vss;
    inout wp;


    initial
        begin
        end

endmodule
