-- generated by newgenasym Tue Aug 09 20:18:52 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity fm25v01a is
    port (    
	CS:        INOUT  STD_LOGIC;    
	HOLD:      INOUT  STD_LOGIC;    
	SCK:       INOUT  STD_LOGIC;    
	SI:        INOUT  STD_LOGIC;    
	SO:        INOUT  STD_LOGIC;    
	VDD:       INOUT  STD_LOGIC;    
	VSS:       INOUT  STD_LOGIC;    
	WP:        INOUT  STD_LOGIC);
end fm25v01a;
