// generated by newgenasym  Mon Sep 17 15:09:58 2012


module \tpl0202-10mrter  (\cs* , din, gnd, ha, hb, la, lb, nc1, nc2, nc3, nc4, nc5, sclk, tap,
        vcc, wa, wb);
    input \cs* ;
    input din;
    input gnd;
    input ha;
    input hb;
    input la;
    input lb;
    inout nc1;
    inout nc2;
    inout nc3;
    inout nc4;
    inout nc5;
    input sclk;
    input tap;
    input vcc;
    output wa;
    output wb;


    initial
        begin
        end

endmodule
