-- generated by newgenasym Mon Sep 17 15:09:58 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \tpl0202-10mrter\ is
    port (    
	\cs*\:     IN     STD_LOGIC;    
	DIN:       IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	HA:        IN     STD_LOGIC;    
	HB:        IN     STD_LOGIC;    
	LA:        IN     STD_LOGIC;    
	LB:        IN     STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC;    
	NC2:       INOUT  STD_LOGIC;    
	NC3:       INOUT  STD_LOGIC;    
	NC4:       INOUT  STD_LOGIC;    
	NC5:       INOUT  STD_LOGIC;    
	SCLK:      IN     STD_LOGIC;    
	TAP:       IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	WA:        OUT    STD_LOGIC;    
	WB:        OUT    STD_LOGIC);
end \tpl0202-10mrter\;
