// generated by newgenasym  Mon Jan 16 15:06:35 2012


module ref102 (com, \noise#20reduction , trim, \v+ , vout);
    input com;
    inout \noise#20reduction ;
    inout trim;
    input \v+ ;
    output vout;


    initial
        begin
        end

endmodule
