// generated by newgenasym  Thu Sep 13 16:50:06 2012


module xr21v1410 (\cd/gpio1* , \cts/gpio4* , \d+ , \d- , \dsr/gpio2* , \dtr/gpio3* ,
        gnd1, gnd2, gnd3, lowpower, \ri/gpio0* , \rts/gpio5* , rx, scl,
        sda, tx, vdd);
    inout \cd/gpio1* ;
    inout \cts/gpio4* ;
    inout \d+ ;
    inout \d- ;
    inout \dsr/gpio2* ;
    inout \dtr/gpio3* ;
    input gnd1;
    input gnd2;
    input gnd3;
    input lowpower;
    inout \ri/gpio0* ;
    inout \rts/gpio5* ;
    input rx;
    inout scl;
    inout sda;
    output tx;
    input vdd;


    initial
        begin
        end

endmodule
