-- generated by newgenasym Thu Sep 13 16:50:06 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity xr21v1410 is
    port (    
	\cd/gpio1*\: INOUT  STD_LOGIC;    
	\cts/gpio4*\: INOUT  STD_LOGIC;    
	\d+\:      INOUT  STD_LOGIC;    
	\d-\:      INOUT  STD_LOGIC;    
	\dsr/gpio2*\: INOUT  STD_LOGIC;    
	\dtr/gpio3*\: INOUT  STD_LOGIC;    
	GND1:      IN     STD_LOGIC;    
	GND2:      IN     STD_LOGIC;    
	GND3:      IN     STD_LOGIC;    
	LOWPOWER:  IN     STD_LOGIC;    
	\ri/gpio0*\: INOUT  STD_LOGIC;    
	\rts/gpio5*\: INOUT  STD_LOGIC;    
	RX:        IN     STD_LOGIC;    
	SCL:       INOUT  STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC;    
	TX:        OUT    STD_LOGIC;    
	VDD:       IN     STD_LOGIC);
end xr21v1410;
