-- generated by newgenasym Mon Apr 14 19:58:28 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity head2x3 is
    port (    
	A1:        INOUT  STD_LOGIC;    
	A2:        INOUT  STD_LOGIC;    
	A3:        INOUT  STD_LOGIC;    
	B1:        INOUT  STD_LOGIC;    
	B2:        INOUT  STD_LOGIC;    
	B3:        INOUT  STD_LOGIC);
end head2x3;
