// generated by newgenasym  Thu Oct 10 21:24:52 2019


module ads1675 (agnd1, agnd2, agnd3, agnd4, agnd5, agnd6, agnd7, agnd8, ainn,
        ainp, avdd1, avdd2, avdd3, avdd4, avdd5, avdd6, cap1, cap2,
        clk, \cs* , dgnd1, dgnd10, dgnd11, dgnd12, dgnd13, dgnd2, dgnd3,
        dgnd4, dgnd5, dgnd6, dgnd7, dgnd8, dgnd9, dout, \dout* , drate0,
        drate1, drate2, drdy, \drdy* , dvdd1, dvdd2, dvdd3, dvdd4,
        dvdd5, dvdd6, fpath, ll_cfg, \lvds* , otra, otrd, \pdwn* , rbias,
        rsv1, rsv2, sclk, \sclk* , sclk_sel, start, vcm, vrefn1, vrefn2,
        vrefp1, vrefp2);
    inout agnd1;
    inout agnd2;
    inout agnd3;
    inout agnd4;
    inout agnd5;
    inout agnd6;
    inout agnd7;
    inout agnd8;
    inout ainn;
    inout ainp;
    inout avdd1;
    inout avdd2;
    inout avdd3;
    inout avdd4;
    inout avdd5;
    inout avdd6;
    inout cap1;
    inout cap2;
    inout clk;
    inout \cs* ;
    inout dgnd1;
    inout dgnd10;
    inout dgnd11;
    inout dgnd12;
    inout dgnd13;
    inout dgnd2;
    inout dgnd3;
    inout dgnd4;
    inout dgnd5;
    inout dgnd6;
    inout dgnd7;
    inout dgnd8;
    inout dgnd9;
    inout dout;
    inout \dout* ;
    inout drate0;
    inout drate1;
    inout drate2;
    inout drdy;
    inout \drdy* ;
    inout dvdd1;
    inout dvdd2;
    inout dvdd3;
    inout dvdd4;
    inout dvdd5;
    inout dvdd6;
    inout fpath;
    inout ll_cfg;
    inout \lvds* ;
    inout otra;
    inout otrd;
    inout \pdwn* ;
    inout rbias;
    inout rsv1;
    inout rsv2;
    inout sclk;
    inout \sclk* ;
    inout sclk_sel;
    inout start;
    inout vcm;
    inout vrefn1;
    inout vrefn2;
    inout vrefp1;
    inout vrefp2;


    initial
        begin
        end

endmodule
