// generated by newgenasym  Sun Sep 22 23:08:12 2013


module tps76201 (\en* , fb, gnd, in, out);
    inout \en* ;
    inout fb;
    inout gnd;
    inout in;
    inout out;


    initial
        begin
        end

endmodule
