-- generated by newgenasym Sun Sep 22 23:08:12 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity TPS76201 is
    port (    
	\en*\:     INOUT  STD_LOGIC;    
	FB:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	\in\:      INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC);
end TPS76201;
