// generated by newgenasym  Thu Mar 11 16:09:01 2021


module \type-c  (\1 , \2 , \3 , \4 , \5 , \6 , a1, a10, a11, a12, a2, a3, a4, a5, a6, a7, a8, a9,
        b1, b10, b11, b12, b2, b3, b4, b5, b6, b7, b8, b9);
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;
    inout \6 ;
    inout a1;
    inout a10;
    inout a11;
    inout a12;
    inout a2;
    inout a3;
    inout a4;
    inout a5;
    inout a6;
    inout a7;
    inout a8;
    inout a9;
    inout b1;
    inout b10;
    inout b11;
    inout b12;
    inout b2;
    inout b3;
    inout b4;
    inout b5;
    inout b6;
    inout b7;
    inout b8;
    inout b9;


    initial
        begin
        end

endmodule
