-- generated by newgenasym Mon Dec  1 15:20:46 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ma35v470m10x13 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end ma35v470m10x13;
