-- generated by newgenasym Mon Apr 11 11:35:33 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity nmos_e is
    port (    
	DRAIN:     INOUT  STD_LOGIC;    
	GATE:      INOUT  STD_LOGIC;    
	SOURCE:    INOUT  STD_LOGIC);
end nmos_e;
