// generated by newgenasym  Wed Nov 05 10:59:34 2014


module adv7611 (ap, cec, cvdd1, cvdd2, ddca_scl, ddca_sda, de, dvdd1, dvdd2,
        dvdd3, dvdd4, dvddio1, dvddio2, dvddio3, gnd, \hpa_a/int2 , hs,
        int1, llc, lrclk, \mclk/int2 , p0, p1, p10, p11, p12, p13, p14,
        p15, p16, p17, p18, p19, p2, p20, p21, p22, p23, p3, p4, p5, p6, p7,
        p8, p9, pvdd, reset, \rxa_0+ , \rxa_0- , \rxa_1+ , \rxa_1- , \rxa_2+ ,
        \rxa_2- , rxa_5v, \rxa_c+ , \rxa_c- , scl, \sclk/int2 , sda, tvdd1,
        tvdd2, tvdd3, \vs/field/alsb , xtaln, xtalp);
    inout ap;
    inout cec;
    inout cvdd1;
    inout cvdd2;
    inout ddca_scl;
    inout ddca_sda;
    inout de;
    inout dvdd1;
    inout dvdd2;
    inout dvdd3;
    inout dvdd4;
    inout dvddio1;
    inout dvddio2;
    inout dvddio3;
    inout gnd;
    inout \hpa_a/int2 ;
    inout hs;
    inout int1;
    inout llc;
    inout lrclk;
    inout \mclk/int2 ;
    inout p0;
    inout p1;
    inout p10;
    inout p11;
    inout p12;
    inout p13;
    inout p14;
    inout p15;
    inout p16;
    inout p17;
    inout p18;
    inout p19;
    inout p2;
    inout p20;
    inout p21;
    inout p22;
    inout p23;
    inout p3;
    inout p4;
    inout p5;
    inout p6;
    inout p7;
    inout p8;
    inout p9;
    inout pvdd;
    inout reset;
    inout \rxa_0+ ;
    inout \rxa_0- ;
    inout \rxa_1+ ;
    inout \rxa_1- ;
    inout \rxa_2+ ;
    inout \rxa_2- ;
    inout rxa_5v;
    inout \rxa_c+ ;
    inout \rxa_c- ;
    inout scl;
    inout \sclk/int2 ;
    inout sda;
    inout tvdd1;
    inout tvdd2;
    inout tvdd3;
    inout \vs/field/alsb ;
    inout xtaln;
    inout xtalp;


    initial
        begin
        end

endmodule
