-- generated by newgenasym Wed Sep 06 16:15:28 2023

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity w25q128jvsiq is
    port (    
	CLK:       IN     STD_LOGIC;    
	\cs#\:     IN     STD_LOGIC;    
	\di(io0)\: INOUT  STD_LOGIC;    
	\do(io1)\: INOUT  STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	\hold#reset#(io3)\: INOUT  STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	\wp#(io2)\: INOUT  STD_LOGIC);
end w25q128jvsiq;
