// generated by newgenasym  Tue Nov 18 10:43:41 2014


module cp2103 (cts, \d+ , \d- , dcd, dsr, dtr, gnd, gpio0, gpio1, gpio2, gpio3,
        nc1, nc2, nc3, nc4, nc5, nc6, regin, ri, rst, rts, rxd, sgnd1,
        sgnd2, suspend1, suspend2, txd, vbus, vdd, vio);
    inout cts;
    inout \d+ ;
    inout \d- ;
    inout dcd;
    inout dsr;
    inout dtr;
    inout gnd;
    inout gpio0;
    inout gpio1;
    inout gpio2;
    inout gpio3;
    inout nc1;
    inout nc2;
    inout nc3;
    inout nc4;
    inout nc5;
    inout nc6;
    inout regin;
    inout ri;
    inout rst;
    inout rts;
    inout rxd;
    inout sgnd1;
    inout sgnd2;
    inout suspend1;
    inout suspend2;
    inout txd;
    inout vbus;
    inout vdd;
    inout vio;


    initial
        begin
        end

endmodule
