-- generated by newgenasym Tue Nov 18 10:43:41 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity cp2103 is
    port (    
	CTS:       INOUT  STD_LOGIC;    
	\d+\:      INOUT  STD_LOGIC;    
	\d-\:      INOUT  STD_LOGIC;    
	DCD:       INOUT  STD_LOGIC;    
	DSR:       INOUT  STD_LOGIC;    
	DTR:       INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	GPIO0:     INOUT  STD_LOGIC;    
	GPIO1:     INOUT  STD_LOGIC;    
	GPIO2:     INOUT  STD_LOGIC;    
	GPIO3:     INOUT  STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC;    
	NC2:       INOUT  STD_LOGIC;    
	NC3:       INOUT  STD_LOGIC;    
	NC4:       INOUT  STD_LOGIC;    
	NC5:       INOUT  STD_LOGIC;    
	NC6:       INOUT  STD_LOGIC;    
	REGIN:     INOUT  STD_LOGIC;    
	RI:        INOUT  STD_LOGIC;    
	RST:       INOUT  STD_LOGIC;    
	RTS:       INOUT  STD_LOGIC;    
	RXD:       INOUT  STD_LOGIC;    
	SGND1:     INOUT  STD_LOGIC;    
	SGND2:     INOUT  STD_LOGIC;    
	SUSPEND1:  INOUT  STD_LOGIC;    
	SUSPEND2:  INOUT  STD_LOGIC;    
	TXD:       INOUT  STD_LOGIC;    
	VBUS:      INOUT  STD_LOGIC;    
	VDD:       INOUT  STD_LOGIC;    
	VIO:       INOUT  STD_LOGIC);
end cp2103;
