// generated by newgenasym  Mon Jun 20 16:51:30 2005


module \74hc05  (a, gnd, vcc, y);
    inout [6:1] a;
    input gnd;
    input vcc;
    inout [6:1] y;


    initial
        begin
        end

endmodule
