-- generated by newgenasym Mon Jun 20 16:51:31 2005

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74hc05\ is
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (6 DOWNTO 1);    
	GND:       IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	Y:         INOUT  STD_LOGIC_VECTOR (6 DOWNTO 1));
end \74hc05\;
