// generated by newgenasym  Fri Sep 28 12:43:28 2018


module h5004enl (mct1, mct2, mct3, mct4, \mx1* , mx1_p, \mx2* , mx2_p, \mx3* , mx3_p,
        \mx4* , mx4_p, tct1, tct2, tct3, tct4, \td1* , td1_p, \td2* , td2_p,
        \td3* , td3_p, \td4* , td4_p);
    inout mct1;
    inout mct2;
    inout mct3;
    inout mct4;
    inout \mx1* ;
    inout mx1_p;
    inout \mx2* ;
    inout mx2_p;
    inout \mx3* ;
    inout mx3_p;
    inout \mx4* ;
    inout mx4_p;
    inout tct1;
    inout tct2;
    inout tct3;
    inout tct4;
    inout \td1* ;
    inout td1_p;
    inout \td2* ;
    inout td2_p;
    inout \td3* ;
    inout td3_p;
    inout \td4* ;
    inout td4_p;


    initial
        begin
        end

endmodule
