-- generated by newgenasym Fri Sep 28 12:43:28 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity h5004enl is
    port (    
	MCT1:      INOUT  STD_LOGIC;    
	MCT2:      INOUT  STD_LOGIC;    
	MCT3:      INOUT  STD_LOGIC;    
	MCT4:      INOUT  STD_LOGIC;    
	\mx1*\:    INOUT  STD_LOGIC;    
	MX1_P:     INOUT  STD_LOGIC;    
	\mx2*\:    INOUT  STD_LOGIC;    
	MX2_P:     INOUT  STD_LOGIC;    
	\mx3*\:    INOUT  STD_LOGIC;    
	MX3_P:     INOUT  STD_LOGIC;    
	\mx4*\:    INOUT  STD_LOGIC;    
	MX4_P:     INOUT  STD_LOGIC;    
	TCT1:      INOUT  STD_LOGIC;    
	TCT2:      INOUT  STD_LOGIC;    
	TCT3:      INOUT  STD_LOGIC;    
	TCT4:      INOUT  STD_LOGIC;    
	\td1*\:    INOUT  STD_LOGIC;    
	TD1_P:     INOUT  STD_LOGIC;    
	\td2*\:    INOUT  STD_LOGIC;    
	TD2_P:     INOUT  STD_LOGIC;    
	\td3*\:    INOUT  STD_LOGIC;    
	TD3_P:     INOUT  STD_LOGIC;    
	\td4*\:    INOUT  STD_LOGIC;    
	TD4_P:     INOUT  STD_LOGIC);
end h5004enl;
