// generated by newgenasym  Fri Nov 21 11:11:29 2014


module rj45 (gnd, gnd1, gnd2, \md1+ , \md1- , \md2+ , \md2- , \md3+ , \md3- , \md4+ ,
        \md4- , vcc);
    inout gnd;
    inout gnd1;
    inout gnd2;
    inout \md1+ ;
    inout \md1- ;
    inout \md2+ ;
    inout \md2- ;
    inout \md3+ ;
    inout \md3- ;
    inout \md4+ ;
    inout \md4- ;
    inout vcc;


    initial
        begin
        end

endmodule
