-- generated by newgenasym Fri Nov 21 11:11:29 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity rj45 is
    port (    
	GND:       INOUT  STD_LOGIC;    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	\md1+\:    INOUT  STD_LOGIC;    
	\md1-\:    INOUT  STD_LOGIC;    
	\md2+\:    INOUT  STD_LOGIC;    
	\md2-\:    INOUT  STD_LOGIC;    
	\md3+\:    INOUT  STD_LOGIC;    
	\md3-\:    INOUT  STD_LOGIC;    
	\md4+\:    INOUT  STD_LOGIC;    
	\md4-\:    INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC);
end rj45;
