// generated by newgenasym  Wed Apr 10 21:51:25 2013


module ad5660 (din, gnd, sclk, \sync* , vdd, vfb, vout, vrefout);
    input din;
    input gnd;
    input sclk;
    input \sync* ;
    input vdd;
    input vfb;
    output vout;
    input vrefout;


    initial
        begin
        end

endmodule
