-- generated by newgenasym Wed Apr 10 21:51:25 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad5660 is
    port (    
	DIN:       IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	SCLK:      IN     STD_LOGIC;    
	\sync*\:   IN     STD_LOGIC;    
	VDD:       IN     STD_LOGIC;    
	VFB:       IN     STD_LOGIC;    
	VOUT:      OUT    STD_LOGIC;    
	VREFOUT:   IN     STD_LOGIC);
end ad5660;
