-- generated by newgenasym Wed Dec 24 10:23:15 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity c3216x7r1c106kt000n is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end c3216x7r1c106kt000n;
