-- generated by newgenasym Tue Mar 26 16:36:04 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \bav-99\ is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC);
end \bav-99\;
