// generated by newgenasym  Sat Oct 15 18:33:40 2005


module \71v30  (a_l, a_r, \busy_l* , \busy_r* , \ce_l* , \ce_r* , gnd, \i/o_l , \i/o_r ,
        \int_l* , \int_r* , \oe_l* , \oe_r* , \r/w_l* , \r/w_r* , vcc);
    input [9:0] a_l;
    input [9:0] a_r;
    output \busy_l* ;
    output \busy_r* ;
    input \ce_l* ;
    input \ce_r* ;
    input [1:0] gnd;
    inout [7:0] \i/o_l ;
    inout [7:0] \i/o_r ;
    output \int_l* ;
    output \int_r* ;
    input \oe_l* ;
    input \oe_r* ;
    input \r/w_l* ;
    input \r/w_r* ;
    input [1:0] vcc;


    initial
        begin
        end

endmodule
