-- generated by newgenasym Sat Oct 15 18:33:40 2005

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \71v30\ is
    port (    
	A_L:       IN     STD_LOGIC_VECTOR (9 DOWNTO 0);    
	A_R:       IN     STD_LOGIC_VECTOR (9 DOWNTO 0);    
	\busy_l*\: OUT    STD_LOGIC;    
	\busy_r*\: OUT    STD_LOGIC;    
	\ce_l*\:   IN     STD_LOGIC;    
	\ce_r*\:   IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC_VECTOR (1 DOWNTO 0);    
	\i/o_l\:   INOUT  STD_LOGIC_VECTOR (7 DOWNTO 0);    
	\i/o_r\:   INOUT  STD_LOGIC_VECTOR (7 DOWNTO 0);    
	\int_l*\:  OUT    STD_LOGIC;    
	\int_r*\:  OUT    STD_LOGIC;    
	\oe_l*\:   IN     STD_LOGIC;    
	\oe_r*\:   IN     STD_LOGIC;    
	\r/w_l*\:  IN     STD_LOGIC;    
	\r/w_r*\:  IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC_VECTOR (1 DOWNTO 0));
end \71v30\;
