// generated by newgenasym  Tue Nov 07 13:45:34 2023


module \at24c256c-sshl-t  (a0, a1, a2, gnd, scl, sda, vcc, wp);
    inout a0;
    inout a1;
    inout a2;
    inout gnd;
    inout scl;
    inout sda;
    inout vcc;
    inout wp;


    initial
        begin
        end

endmodule
