-- generated by newgenasym Tue Nov 07 13:45:34 2023

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \at24c256c-sshl-t\ is
    port (    
	A0:        INOUT  STD_LOGIC;    
	A1:        INOUT  STD_LOGIC;    
	A2:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	SCL:       INOUT  STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC;    
	WP:        INOUT  STD_LOGIC);
end \at24c256c-sshl-t\;
