// generated by newgenasym  Mon Jan 09 16:46:16 2006


module \74lvc16245  (\1a0 , \1a1 , \1a2 , \1a3 , \1a4 , \1a5 , \1a6 , \1a7 , \1b0 , \1b1 , \1b2 , \1b3 , \1b4 ,
        \1b5 , \1b6 , \1b7 , \1dir , \1oe* , \2a0 , \2a1 , \2a2 , \2a3 , \2a4 , \2a5 , \2a6 , \2a7 ,
        \2b0 , \2b1 , \2b2 , \2b3 , \2b4 , \2b5 , \2b6 , \2b7 , \2dir , \2oe* , gnd, vcc);
    input \1a0 ;
    input \1a1 ;
    input \1a2 ;
    input \1a3 ;
    input \1a4 ;
    input \1a5 ;
    input \1a6 ;
    input \1a7 ;
    inout \1b0 ;
    inout \1b1 ;
    inout \1b2 ;
    inout \1b3 ;
    inout \1b4 ;
    inout \1b5 ;
    inout \1b6 ;
    inout \1b7 ;
    input \1dir ;
    input \1oe* ;
    input \2a0 ;
    input \2a1 ;
    input \2a2 ;
    input \2a3 ;
    input \2a4 ;
    input \2a5 ;
    input \2a6 ;
    input \2a7 ;
    inout \2b0 ;
    inout \2b1 ;
    inout \2b2 ;
    inout \2b3 ;
    inout \2b4 ;
    inout \2b5 ;
    inout \2b6 ;
    inout \2b7 ;
    input \2dir ;
    input \2oe* ;
    input [7:0] gnd;
    input [3:0] vcc;


    initial
        begin
        end

endmodule
