-- generated by newgenasym Mon Jan 09 16:46:16 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74lvc16245\ is
    port (    
	\1a0\:     IN     STD_LOGIC;    
	\1a1\:     IN     STD_LOGIC;    
	\1a2\:     IN     STD_LOGIC;    
	\1a3\:     IN     STD_LOGIC;    
	\1a4\:     IN     STD_LOGIC;    
	\1a5\:     IN     STD_LOGIC;    
	\1a6\:     IN     STD_LOGIC;    
	\1a7\:     IN     STD_LOGIC;    
	\1b0\:     INOUT  STD_LOGIC;    
	\1b1\:     INOUT  STD_LOGIC;    
	\1b2\:     INOUT  STD_LOGIC;    
	\1b3\:     INOUT  STD_LOGIC;    
	\1b4\:     INOUT  STD_LOGIC;    
	\1b5\:     INOUT  STD_LOGIC;    
	\1b6\:     INOUT  STD_LOGIC;    
	\1b7\:     INOUT  STD_LOGIC;    
	\1dir\:    IN     STD_LOGIC;    
	\1oe*\:    IN     STD_LOGIC;    
	\2a0\:     IN     STD_LOGIC;    
	\2a1\:     IN     STD_LOGIC;    
	\2a2\:     IN     STD_LOGIC;    
	\2a3\:     IN     STD_LOGIC;    
	\2a4\:     IN     STD_LOGIC;    
	\2a5\:     IN     STD_LOGIC;    
	\2a6\:     IN     STD_LOGIC;    
	\2a7\:     IN     STD_LOGIC;    
	\2b0\:     INOUT  STD_LOGIC;    
	\2b1\:     INOUT  STD_LOGIC;    
	\2b2\:     INOUT  STD_LOGIC;    
	\2b3\:     INOUT  STD_LOGIC;    
	\2b4\:     INOUT  STD_LOGIC;    
	\2b5\:     INOUT  STD_LOGIC;    
	\2b6\:     INOUT  STD_LOGIC;    
	\2b7\:     INOUT  STD_LOGIC;    
	\2dir\:    IN     STD_LOGIC;    
	\2oe*\:    IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC_VECTOR (7 DOWNTO 0);    
	VCC:       IN     STD_LOGIC_VECTOR (3 DOWNTO 0));
end \74lvc16245\;
