// generated by newgenasym  Tue Oct 15 09:58:41 2019


module opa211aidgk (\in+ , \in- , nc1, nc2, out, shut, \v+ , \v- );
    inout \in+ ;
    inout \in- ;
    inout nc1;
    inout nc2;
    inout out;
    inout shut;
    inout \v+ ;
    inout \v- ;


    initial
        begin
        end

endmodule
