-- generated by newgenasym Tue Oct 15 09:58:41 2019

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity opa211aidgk is
    port (    
	\in+\:     INOUT  STD_LOGIC;    
	\in-\:     INOUT  STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC;    
	NC2:       INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	SHUT:      INOUT  STD_LOGIC;    
	\v+\:      INOUT  STD_LOGIC;    
	\v-\:      INOUT  STD_LOGIC);
end opa211aidgk;
