

library ieee;
use ieee.std_logic_1164.all;
use work.all;

entity P5V is 

-- generated by Concept HDL Direct Version 05.10-p009 (Production) 06-Mar-98
-- on Wed Jan 27 10:31:04 1999
-- from adsl_lib/p5v/sch_1 

  generic (SIZE:positive  );
  port (G:inout std_logic_vector (SIZE-1 downto 0)  );
end P5V;

-- HDL Direct File Check Sum: 307 1005823362
