// generated by newgenasym  Sun Nov 16 15:23:48 2014


module txs02612 (clka, clkb0, clkb1, cmda, cmdb0, cmdb1, dat0a, dat0b0,
        dat0b1, dat1a, dat1b0, dat1b1, dat2a, dat2b0, dat2b1, dat3a,
        dat3b0, dat3b1, gnd1, gnd2, gnd3, sel, vcca, vccb0, vccb1);
    inout clka;
    inout clkb0;
    inout clkb1;
    inout cmda;
    inout cmdb0;
    inout cmdb1;
    inout dat0a;
    inout dat0b0;
    inout dat0b1;
    inout dat1a;
    inout dat1b0;
    inout dat1b1;
    inout dat2a;
    inout dat2b0;
    inout dat2b1;
    inout dat3a;
    inout dat3b0;
    inout dat3b1;
    inout gnd1;
    inout gnd2;
    inout gnd3;
    inout sel;
    inout vcca;
    inout vccb0;
    inout vccb1;


    initial
        begin
        end

endmodule
