-- generated by newgenasym Sun Nov 16 15:23:48 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity txs02612 is
    port (    
	CLKA:      INOUT  STD_LOGIC;    
	CLKB0:     INOUT  STD_LOGIC;    
	CLKB1:     INOUT  STD_LOGIC;    
	CMDA:      INOUT  STD_LOGIC;    
	CMDB0:     INOUT  STD_LOGIC;    
	CMDB1:     INOUT  STD_LOGIC;    
	DAT0A:     INOUT  STD_LOGIC;    
	DAT0B0:    INOUT  STD_LOGIC;    
	DAT0B1:    INOUT  STD_LOGIC;    
	DAT1A:     INOUT  STD_LOGIC;    
	DAT1B0:    INOUT  STD_LOGIC;    
	DAT1B1:    INOUT  STD_LOGIC;    
	DAT2A:     INOUT  STD_LOGIC;    
	DAT2B0:    INOUT  STD_LOGIC;    
	DAT2B1:    INOUT  STD_LOGIC;    
	DAT3A:     INOUT  STD_LOGIC;    
	DAT3B0:    INOUT  STD_LOGIC;    
	DAT3B1:    INOUT  STD_LOGIC;    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	GND3:      INOUT  STD_LOGIC;    
	SEL:       INOUT  STD_LOGIC;    
	VCCA:      INOUT  STD_LOGIC;    
	VCCB0:     INOUT  STD_LOGIC;    
	VCCB1:     INOUT  STD_LOGIC);
end txs02612;
