// generated by newgenasym  Wed Dec 07 19:53:10 2016


module tps73130 (en, gnd, in, nr, out);
    inout en;
    input gnd;
    input in;
    inout nr;
    output out;


    initial
        begin
        end

endmodule
