-- generated by newgenasym Wed Dec 07 19:53:10 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tps73130 is
    port (    
	EN:        INOUT  STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	\in\:      IN     STD_LOGIC;    
	NR:        INOUT  STD_LOGIC;    
	\out\:     OUT    STD_LOGIC);
end tps73130;
