// generated by newgenasym  Thu Oct 30 14:42:17 2014


module ads7881 (\+in , \+va , \+va1 , \+va2 , \+va3 , \+va4 , \+va5 , \+vbd , \+vbd1 , \-in ,
        \a_pwd* , agnd, agnd1, agnd2, agnd3, agnd4, agnd5, agnd6, agnd7,
        bgnd, bgnd1, busy, byte, \convst* , \cs* , db0, db1, db11, db1o,
        db2, db3, db4, db5, db6, db7, db8, db9, nc, nc1, nc2, nc3, nc4,
        \pwd/rst* , \rd* , refin, refm1, refm2, refout);
    inout \+in ;
    input \+va ;
    input \+va1 ;
    input \+va2 ;
    input \+va3 ;
    input \+va4 ;
    input \+va5 ;
    input \+vbd ;
    input \+vbd1 ;
    inout \-in ;
    inout \a_pwd* ;
    input agnd;
    input agnd1;
    input agnd2;
    input agnd3;
    input agnd4;
    input agnd5;
    input agnd6;
    input agnd7;
    input bgnd;
    input bgnd1;
    inout busy;
    inout byte;
    inout \convst* ;
    inout \cs* ;
    inout db0;
    inout db1;
    inout db11;
    inout db1o;
    inout db2;
    inout db3;
    inout db4;
    inout db5;
    inout db6;
    inout db7;
    inout db8;
    inout db9;
    inout nc;
    inout nc1;
    inout nc2;
    inout nc3;
    inout nc4;
    inout \pwd/rst* ;
    inout \rd* ;
    inout refin;
    inout refm1;
    inout refm2;
    inout refout;


    initial
        begin
        end

endmodule
