// generated by newgenasym  Wed Dec 11 10:07:03 2019


module ada4841 (\int1+ , \int1- , \int2+ , \int2- , out1, out2, \vs+ , \vs- );
    inout \int1+ ;
    inout \int1- ;
    inout \int2+ ;
    inout \int2- ;
    inout out1;
    inout out2;
    inout \vs+ ;
    inout \vs- ;


    initial
        begin
        end

endmodule
