-- generated by newgenasym Wed Dec 11 10:07:03 2019

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ada4841 is
    port (    
	\int1+\:   INOUT  STD_LOGIC;    
	\int1-\:   INOUT  STD_LOGIC;    
	\int2+\:   INOUT  STD_LOGIC;    
	\int2-\:   INOUT  STD_LOGIC;    
	OUT1:      INOUT  STD_LOGIC;    
	OUT2:      INOUT  STD_LOGIC;    
	\vs+\:     INOUT  STD_LOGIC;    
	\vs-\:     INOUT  STD_LOGIC);
end ada4841;
