-- generated by newgenasym Sun Nov 30 02:03:16 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \dc-005-5a\ is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC);
end \dc-005-5a\;
