// generated by newgenasym  Thu Mar 20 11:21:11 2008


module ad7982 (cnv, gnd, \in+ , \in- , ref, sck, sdi, sdo, vdd, vio);
    inout cnv;
    inout gnd;
    inout \in+ ;
    inout \in- ;
    inout ref;
    inout sck;
    inout sdi;
    inout sdo;
    inout vdd;
    inout vio;


    initial
        begin
        end

endmodule
