-- generated by newgenasym Thu Mar 20 11:21:11 2008

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad7982 is
    port (    
	CNV:       INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	\in+\:     INOUT  STD_LOGIC;    
	\in-\:     INOUT  STD_LOGIC;    
	REF:       INOUT  STD_LOGIC;    
	SCK:       INOUT  STD_LOGIC;    
	SDI:       INOUT  STD_LOGIC;    
	SDO:       INOUT  STD_LOGIC;    
	VDD:       INOUT  STD_LOGIC;    
	VIO:       INOUT  STD_LOGIC);
end ad7982;
