// generated by newgenasym  Fri Aug 04 21:46:35 2006


module \rtl8201bl#20lqfp48  (agnd0, agnd1, ane, avdd33, col, crs, dgnd0, dgnd1, dgnd2,
        duplex, dvdd33_0, dvdd33_1, isolate, ldps, \led0/phyad0 ,
        \led1/phyad1 , \led2/phyad2 , \led3/phyad3 , \led4/phyad4 , mdc,
        mdio, \mii/snib/rtt3 , pwfbin, pwfbout, resetb, rptr, rtset,
        rxc, rxd, rxdv, \rxer/fxen , speed, \tprx+ , \tprx- , \tptx+ , \tptx- ,
        txc, txd, txen, x1, x2);
    input agnd0;
    input agnd1;
    input ane;
    input avdd33;
    input col;
    input crs;
    input dgnd0;
    input dgnd1;
    input dgnd2;
    input duplex;
    input dvdd33_0;
    input dvdd33_1;
    input isolate;
    input ldps;
    input \led0/phyad0 ;
    input \led1/phyad1 ;
    input \led2/phyad2 ;
    input \led3/phyad3 ;
    input \led4/phyad4 ;
    input mdc;
    input mdio;
    input \mii/snib/rtt3 ;
    input pwfbin;
    input pwfbout;
    input resetb;
    input rptr;
    input rtset;
    input rxc;
    input [3:0] rxd;
    input rxdv;
    input \rxer/fxen ;
    input speed;
    input \tprx+ ;
    input \tprx- ;
    input \tptx+ ;
    input \tptx- ;
    input txc;
    input [3:0] txd;
    input txen;
    input x1;
    input x2;


    initial
        begin
        end

endmodule
