-- generated by newgenasym Fri Aug 04 21:46:35 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \rtl8201bl lqfp48\ is
    port (    
	AGND0:     IN     STD_LOGIC;    
	AGND1:     IN     STD_LOGIC;    
	ANE:       IN     STD_LOGIC;    
	AVDD33:    IN     STD_LOGIC;    
	COL:       IN     STD_LOGIC;    
	CRS:       IN     STD_LOGIC;    
	DGND0:     IN     STD_LOGIC;    
	DGND1:     IN     STD_LOGIC;    
	DGND2:     IN     STD_LOGIC;    
	DUPLEX:    IN     STD_LOGIC;    
	DVDD33_0:  IN     STD_LOGIC;    
	DVDD33_1:  IN     STD_LOGIC;    
	ISOLATE:   IN     STD_LOGIC;    
	LDPS:      IN     STD_LOGIC;    
	\led0/phyad0\: IN     STD_LOGIC;    
	\led1/phyad1\: IN     STD_LOGIC;    
	\led2/phyad2\: IN     STD_LOGIC;    
	\led3/phyad3\: IN     STD_LOGIC;    
	\led4/phyad4\: IN     STD_LOGIC;    
	MDC:       IN     STD_LOGIC;    
	MDIO:      IN     STD_LOGIC;    
	\mii/snib/rtt3\: IN     STD_LOGIC;    
	PWFBIN:    IN     STD_LOGIC;    
	PWFBOUT:   IN     STD_LOGIC;    
	RESETB:    IN     STD_LOGIC;    
	RPTR:      IN     STD_LOGIC;    
	RTSET:     IN     STD_LOGIC;    
	RXC:       IN     STD_LOGIC;    
	RXD:       IN     STD_LOGIC_VECTOR (3 DOWNTO 0);    
	RXDV:      IN     STD_LOGIC;    
	\rxer/fxen\: IN     STD_LOGIC;    
	SPEED:     IN     STD_LOGIC;    
	\tprx+\:   IN     STD_LOGIC;    
	\tprx-\:   IN     STD_LOGIC;    
	\tptx+\:   IN     STD_LOGIC;    
	\tptx-\:   IN     STD_LOGIC;    
	TXC:       IN     STD_LOGIC;    
	TXD:       IN     STD_LOGIC_VECTOR (3 DOWNTO 0);    
	TXEN:      IN     STD_LOGIC;    
	X1:        IN     STD_LOGIC;    
	X2:        IN     STD_LOGIC);
end \rtl8201bl lqfp48\;
