-- generated by newgenasym Fri Dec 18 18:20:20 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity fuse is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end fuse;
