// generated by newgenasym  Thu Dec 15 21:08:52 2016


module lsf0204pwr (a1, a2, a3, a4, b1, b2, b3, b4, en, gnd, nc, vref_a, vref_b);
    inout a1;
    inout a2;
    inout a3;
    inout a4;
    inout b1;
    inout b2;
    inout b3;
    inout b4;
    inout en;
    inout gnd;
    inout [2:1] nc;
    inout vref_a;
    inout vref_b;


    initial
        begin
        end

endmodule
