-- generated by newgenasym Thu Dec 15 21:08:52 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lsf0204pwr is
    port (    
	A1:        INOUT  STD_LOGIC;    
	A2:        INOUT  STD_LOGIC;    
	A3:        INOUT  STD_LOGIC;    
	A4:        INOUT  STD_LOGIC;    
	B1:        INOUT  STD_LOGIC;    
	B2:        INOUT  STD_LOGIC;    
	B3:        INOUT  STD_LOGIC;    
	B4:        INOUT  STD_LOGIC;    
	EN:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	NC:        INOUT  STD_LOGIC_VECTOR (2 DOWNTO 1);    
	VREF_A:    INOUT  STD_LOGIC;    
	VREF_B:    INOUT  STD_LOGIC);
end lsf0204pwr;
