// generated by newgenasym  Thu Apr 07 22:41:31 2011


module cy22394fc (agnd, avdd, clka, clkb, clkc, gnd, \p_clk* , p_clk_p,
        \s2/suspend , sclk_s1, sdat_s0, \shutdown_m/oe , vdd, xbuf,
        xtalin, xtalout);
    input agnd;
    input avdd;
    output clka;
    output clkb;
    output clkc;
    input gnd;
    output \p_clk* ;
    output p_clk_p;
    input \s2/suspend ;
    input sclk_s1;
    input sdat_s0;
    input \shutdown_m/oe ;
    input vdd;
    output xbuf;
    input xtalin;
    output xtalout;


    initial
        begin
        end

endmodule
