-- generated by newgenasym Thu Apr 07 22:41:31 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity cy22394fc is
    port (    
	AGND:      IN     STD_LOGIC;    
	AVDD:      IN     STD_LOGIC;    
	CLKA:      OUT    STD_LOGIC;    
	CLKB:      OUT    STD_LOGIC;    
	CLKC:      OUT    STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	\p_clk*\:  OUT    STD_LOGIC;    
	P_CLK_P:   OUT    STD_LOGIC;    
	\s2/suspend\: IN     STD_LOGIC;    
	SCLK_S1:   IN     STD_LOGIC;    
	SDAT_S0:   IN     STD_LOGIC;    
	\shutdown_m/oe\: IN     STD_LOGIC;    
	VDD:       IN     STD_LOGIC;    
	XBUF:      OUT    STD_LOGIC;    
	XTALIN:    IN     STD_LOGIC;    
	XTALOUT:   OUT    STD_LOGIC);
end cy22394fc;
