// generated by newgenasym  Fri May 05 14:28:42 2017


module \mc20901-4  (bta, \d-phy-a-n , \d-phy-a-p , \d-phy-b-n , \d-phy-b-p ,
        \d-phy-c-n , \d-phy-c-p , \d-phy-d-n , \d-phy-d-p , \d-phy-e-n ,
        \d-phy-e-p , gnd, \gpio-0 , \gpio-1 , \hs-a-n , \hs-a-p , \hs-b-n ,
        \hs-b-p , \hs-c-n , \hs-c-p , \hs-d-n , \hs-d-p , \hs-e-n , \hs-e-p ,
        \lp-a-n , \lp-a-p , \lp-b-n , \lp-b-p , \lp-c-n , \lp-c-p , \lp-d-n ,
        \lp-d-p , \lp-e-n , \lp-e-p , \n.c , pinswap, vdd, vddio);
    inout bta;
    inout \d-phy-a-n ;
    inout \d-phy-a-p ;
    inout \d-phy-b-n ;
    inout \d-phy-b-p ;
    inout \d-phy-c-n ;
    inout \d-phy-c-p ;
    inout \d-phy-d-n ;
    inout \d-phy-d-p ;
    inout \d-phy-e-n ;
    inout \d-phy-e-p ;
    inout [5:1] gnd;
    inout \gpio-0 ;
    inout \gpio-1 ;
    inout \hs-a-n ;
    inout \hs-a-p ;
    inout \hs-b-n ;
    inout \hs-b-p ;
    inout \hs-c-n ;
    inout \hs-c-p ;
    inout \hs-d-n ;
    inout \hs-d-p ;
    inout \hs-e-n ;
    inout \hs-e-p ;
    inout \lp-a-n ;
    inout \lp-a-p ;
    inout \lp-b-n ;
    inout \lp-b-p ;
    inout \lp-c-n ;
    inout \lp-c-p ;
    inout \lp-d-n ;
    inout \lp-d-p ;
    inout \lp-e-n ;
    inout \lp-e-p ;
    inout [6:1] \n.c ;
    inout pinswap;
    inout vdd;
    inout [2:1] vddio;


    initial
        begin
        end

endmodule
