-- generated by newgenasym Fri May 05 14:28:42 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \mc20901-4\ is
    port (    
	BTA:       INOUT  STD_LOGIC;    
	\d-phy-a-n\: INOUT  STD_LOGIC;    
	\d-phy-a-p\: INOUT  STD_LOGIC;    
	\d-phy-b-n\: INOUT  STD_LOGIC;    
	\d-phy-b-p\: INOUT  STD_LOGIC;    
	\d-phy-c-n\: INOUT  STD_LOGIC;    
	\d-phy-c-p\: INOUT  STD_LOGIC;    
	\d-phy-d-n\: INOUT  STD_LOGIC;    
	\d-phy-d-p\: INOUT  STD_LOGIC;    
	\d-phy-e-n\: INOUT  STD_LOGIC;    
	\d-phy-e-p\: INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC_VECTOR (5 DOWNTO 1);    
	\gpio-0\:  INOUT  STD_LOGIC;    
	\gpio-1\:  INOUT  STD_LOGIC;    
	\hs-a-n\:  INOUT  STD_LOGIC;    
	\hs-a-p\:  INOUT  STD_LOGIC;    
	\hs-b-n\:  INOUT  STD_LOGIC;    
	\hs-b-p\:  INOUT  STD_LOGIC;    
	\hs-c-n\:  INOUT  STD_LOGIC;    
	\hs-c-p\:  INOUT  STD_LOGIC;    
	\hs-d-n\:  INOUT  STD_LOGIC;    
	\hs-d-p\:  INOUT  STD_LOGIC;    
	\hs-e-n\:  INOUT  STD_LOGIC;    
	\hs-e-p\:  INOUT  STD_LOGIC;    
	\lp-a-n\:  INOUT  STD_LOGIC;    
	\lp-a-p\:  INOUT  STD_LOGIC;    
	\lp-b-n\:  INOUT  STD_LOGIC;    
	\lp-b-p\:  INOUT  STD_LOGIC;    
	\lp-c-n\:  INOUT  STD_LOGIC;    
	\lp-c-p\:  INOUT  STD_LOGIC;    
	\lp-d-n\:  INOUT  STD_LOGIC;    
	\lp-d-p\:  INOUT  STD_LOGIC;    
	\lp-e-n\:  INOUT  STD_LOGIC;    
	\lp-e-p\:  INOUT  STD_LOGIC;    
	\n.c\:     INOUT  STD_LOGIC_VECTOR (6 DOWNTO 1);    
	PINSWAP:   INOUT  STD_LOGIC;    
	VDD:       INOUT  STD_LOGIC;    
	VDDIO:     INOUT  STD_LOGIC_VECTOR (2 DOWNTO 1));
end \mc20901-4\;
