// generated by newgenasym  Mon Nov 24 10:41:00 2025


module \at24c64d-sshm-t  (a0, a1, a2, gnd, scl, sda, vcc, wp);
    inout a0;
    inout a1;
    inout a2;
    inout gnd;
    inout scl;
    inout sda;
    inout vcc;
    inout wp;


    initial
        begin
        end

endmodule
