// generated by newgenasym  Sat Oct 12 11:14:50 2019


module idt74fct3807aqi (gnd1, gnd2, gnd3, gnd4, gnd5, in, o1, o10, o2, o3, o4, o5, o6, o7,
        o8, o9, vcc1, vcc2, vcc3, vcc4);
    inout gnd1;
    inout gnd2;
    inout gnd3;
    inout gnd4;
    inout gnd5;
    inout in;
    inout o1;
    inout o10;
    inout o2;
    inout o3;
    inout o4;
    inout o5;
    inout o6;
    inout o7;
    inout o8;
    inout o9;
    inout vcc1;
    inout vcc2;
    inout vcc3;
    inout vcc4;


    initial
        begin
        end

endmodule
