-- generated by newgenasym Sat Oct 12 11:14:50 2019

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity idt74fct3807aqi is
    port (    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	GND3:      INOUT  STD_LOGIC;    
	GND4:      INOUT  STD_LOGIC;    
	GND5:      INOUT  STD_LOGIC;    
	\in\:      INOUT  STD_LOGIC;    
	O1:        INOUT  STD_LOGIC;    
	O10:       INOUT  STD_LOGIC;    
	O2:        INOUT  STD_LOGIC;    
	O3:        INOUT  STD_LOGIC;    
	O4:        INOUT  STD_LOGIC;    
	O5:        INOUT  STD_LOGIC;    
	O6:        INOUT  STD_LOGIC;    
	O7:        INOUT  STD_LOGIC;    
	O8:        INOUT  STD_LOGIC;    
	O9:        INOUT  STD_LOGIC;    
	VCC1:      INOUT  STD_LOGIC;    
	VCC2:      INOUT  STD_LOGIC;    
	VCC3:      INOUT  STD_LOGIC;    
	VCC4:      INOUT  STD_LOGIC);
end idt74fct3807aqi;
