// generated by newgenasym  Tue Jul 19 10:23:04 2016


module ksz8895mqi (fxsd4, gnda, gndd, in_pwr_sel, \intr* , iset, ldo_o, led1_0,
        led1_1, led1_2, led2_0, led2_1, led2_2, led3_0, led3_1,
        led3_2, led4_0, led4_1, led4_2, led5_0, led5_1, led5_2, mdc,
        mdio, mdixdis, nc, \nc/fxsd3 , pcol, pcrs, pmrxc, pmrxd0,
        pmrxd1, pmrxd2, pmrxd3, \pmrxdv/pmcrsdv , pmrxer,
        \pmtxc/pmrefclk , pmtxd0, pmtxd1, pmtxd2, pmtxd3, pmtxen,
        pmtxer, ps0, ps1, \pwrdn* , \rst* , rxm1, rxm2, rxm3, rxm4, rxm5,
        rxp1, rxp2, rxp3, rxp4, rxp5, scanen, scol, sconf0, sconf1,
        scrs, smrxc, smrxd0, smrxd1, smrxd2, smrxd3, \smrxdv/smcrsdv ,
        \smtxc/smrefclk , smtxd0, smtxd1, smtxd2, smtxd3, smtxen,
        smtxer, \spic/scl , spiq, \spis* , \sspid/sda , test2, testen,
        txm1, txm2, txm3, txm4, txm5, txp1, txp2, txp3, txp4, txp5,
        vddar, vddat, vddc, vddio, x1, x2);
    inout fxsd4;
    inout [9:1] gnda;
    inout [6:1] gndd;
    inout in_pwr_sel;
    inout \intr* ;
    inout iset;
    inout ldo_o;
    inout led1_0;
    inout led1_1;
    inout led1_2;
    inout led2_0;
    inout led2_1;
    inout led2_2;
    inout led3_0;
    inout led3_1;
    inout led3_2;
    inout led4_0;
    inout led4_1;
    inout led4_2;
    inout led5_0;
    inout led5_1;
    inout led5_2;
    inout mdc;
    inout mdio;
    inout mdixdis;
    inout [10:1] nc;
    inout \nc/fxsd3 ;
    inout pcol;
    inout pcrs;
    inout pmrxc;
    inout pmrxd0;
    inout pmrxd1;
    inout pmrxd2;
    inout pmrxd3;
    inout \pmrxdv/pmcrsdv ;
    inout pmrxer;
    inout \pmtxc/pmrefclk ;
    inout pmtxd0;
    inout pmtxd1;
    inout pmtxd2;
    inout pmtxd3;
    inout pmtxen;
    inout pmtxer;
    inout ps0;
    inout ps1;
    inout \pwrdn* ;
    inout \rst* ;
    inout rxm1;
    inout rxm2;
    inout rxm3;
    inout rxm4;
    inout rxm5;
    inout rxp1;
    inout rxp2;
    inout rxp3;
    inout rxp4;
    inout rxp5;
    inout scanen;
    inout scol;
    inout sconf0;
    inout sconf1;
    inout scrs;
    inout smrxc;
    inout smrxd0;
    inout smrxd1;
    inout smrxd2;
    inout smrxd3;
    inout \smrxdv/smcrsdv ;
    inout \smtxc/smrefclk ;
    inout smtxd0;
    inout smtxd1;
    inout smtxd2;
    inout smtxd3;
    inout smtxen;
    inout smtxer;
    inout \spic/scl ;
    inout spiq;
    inout \spis* ;
    inout \sspid/sda ;
    inout test2;
    inout testen;
    inout txm1;
    inout txm2;
    inout txm3;
    inout txm4;
    inout txm5;
    inout txp1;
    inout txp2;
    inout txp3;
    inout txp4;
    inout txp5;
    inout [3:1] vddar;
    inout [4:1] vddat;
    inout [3:1] vddc;
    inout [3:1] vddio;
    inout x1;
    inout x2;


    initial
        begin
        end

endmodule
