-- generated by newgenasym Wed Nov 18 21:48:56 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \5557-2p\ is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end \5557-2p\;
