// generated by newgenasym  Wed May 28 14:57:55 2014


module tps51200 (en, gnd, pgnd, pgood, refin, refout, tp, vin, vldoin, vo,
        vosns);
    inout en;
    inout gnd;
    inout pgnd;
    inout pgood;
    inout refin;
    inout refout;
    inout tp;
    inout vin;
    inout vldoin;
    inout vo;
    inout vosns;


    initial
        begin
        end

endmodule
