-- generated by newgenasym Wed May 28 14:57:55 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity TPS51200 is
    port (    
	EN:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	PGND:      INOUT  STD_LOGIC;    
	PGOOD:     INOUT  STD_LOGIC;    
	REFIN:     INOUT  STD_LOGIC;    
	REFOUT:    INOUT  STD_LOGIC;    
	TP:        INOUT  STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC;    
	VLDOIN:    INOUT  STD_LOGIC;    
	VO:        INOUT  STD_LOGIC;    
	VOSNS:     INOUT  STD_LOGIC);
end TPS51200;
