// generated by newgenasym  Wed Mar 11 10:45:39 2015


module tps61041 (en, fb, gnd, sw, vin);
    inout en;
    inout fb;
    inout gnd;
    inout sw;
    inout vin;


    initial
        begin
        end

endmodule
