-- generated by newgenasym Wed Mar 11 10:45:39 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tps61041 is
    port (    
	EN:        INOUT  STD_LOGIC;    
	FB:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	SW:        INOUT  STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC);
end tps61041;
