-- generated by newgenasym Fri Dec 12 16:27:05 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \5_8_zsgt\ is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC);
end \5_8_zsgt\;
