// generated by newgenasym  Fri Oct 26 21:49:25 2012


module ad9834 (agnd, avdd, \cap/2.5v , comp, dgnd, dvdd, fsadjust, fselect,
        fsync, iout, ioutb, mclk, pselect, refout, reset, sclk, sdata,
        \sign#20bit#20out , sleep, vin);
    input agnd;
    input avdd;
    inout \cap/2.5v ;
    inout comp;
    input dgnd;
    input dvdd;
    inout fsadjust;
    input fselect;
    input fsync;
    output iout;
    output ioutb;
    input mclk;
    input pselect;
    output refout;
    input reset;
    input sclk;
    input sdata;
    output \sign#20bit#20out ;
    input sleep;
    input vin;


    initial
        begin
        end

endmodule
