-- generated by newgenasym Fri Oct 26 21:49:25 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad9834 is
    port (    
	AGND:      IN     STD_LOGIC;    
	AVDD:      IN     STD_LOGIC;    
	\cap/2.5v\: INOUT  STD_LOGIC;    
	COMP:      INOUT  STD_LOGIC;    
	DGND:      IN     STD_LOGIC;    
	DVDD:      IN     STD_LOGIC;    
	FSADJUST:  INOUT  STD_LOGIC;    
	FSELECT:   IN     STD_LOGIC;    
	FSYNC:     IN     STD_LOGIC;    
	IOUT:      OUT    STD_LOGIC;    
	IOUTB:     OUT    STD_LOGIC;    
	MCLK:      IN     STD_LOGIC;    
	PSELECT:   IN     STD_LOGIC;    
	REFOUT:    OUT    STD_LOGIC;    
	RESET:     IN     STD_LOGIC;    
	SCLK:      IN     STD_LOGIC;    
	SDATA:     IN     STD_LOGIC;    
	\sign bit out\: OUT    STD_LOGIC;    
	SLEEP:     IN     STD_LOGIC;    
	VIN:       IN     STD_LOGIC);
end ad9834;
