// generated by newgenasym  Mon Apr 14 20:20:23 2014


module head2x11 (a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20,
        a21, a22, a3, a4, a5, a6, a7, a8, a9);
    inout a1;
    inout a10;
    inout a11;
    inout a12;
    inout a13;
    inout a14;
    inout a15;
    inout a16;
    inout a17;
    inout a18;
    inout a19;
    inout a2;
    inout a20;
    inout a21;
    inout a22;
    inout a3;
    inout a4;
    inout a5;
    inout a6;
    inout a7;
    inout a8;
    inout a9;


    initial
        begin
        end

endmodule
