-- generated by newgenasym Fri Jun 24 15:52:30 2005

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity led_s is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC);
end led_s;
