// generated by newgenasym  Fri Sep 07 16:04:36 2012


module opa4348aid (\+in , \-in , out, \v+ , \v- );
    input \+in ;
    input \-in ;
    output out;
    input \v+ ;
    input \v- ;


    initial
        begin
        end

endmodule
