-- generated by newgenasym Fri Sep 07 16:04:36 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity opa4348aid is
    port (    
	\+in\:     IN     STD_LOGIC;    
	\-in\:     IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	\v+\:      IN     STD_LOGIC;    
	\v-\:      IN     STD_LOGIC);
end opa4348aid;
