// generated by newgenasym  Wed Dec 14 11:47:49 2016


module ds90lv019 (de, din, \do+ , \do- , gnd, nc, re, \ri+ , \ri- , rout, vcc);
    inout de;
    inout din;
    inout \do+ ;
    inout \do- ;
    inout gnd;
    inout [4:1] nc;
    inout re;
    inout \ri+ ;
    inout \ri- ;
    inout rout;
    inout vcc;


    initial
        begin
        end

endmodule
