-- generated by newgenasym Wed Dec 14 11:47:49 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ds90lv019 is
    port (    
	DE:        INOUT  STD_LOGIC;    
	DIN:       INOUT  STD_LOGIC;    
	\do+\:     INOUT  STD_LOGIC;    
	\do-\:     INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	NC:        INOUT  STD_LOGIC_VECTOR (4 DOWNTO 1);    
	RE:        INOUT  STD_LOGIC;    
	\ri+\:     INOUT  STD_LOGIC;    
	\ri-\:     INOUT  STD_LOGIC;    
	ROUT:      INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC);
end ds90lv019;
