// generated by newgenasym  Thu Jun 23 14:58:33 2005


module \74hc00  (a, b, gnd, vcc, \y* );
    input a;
    input b;
    input gnd;
    input vcc;
    output \y* ;


    initial
        begin
        end

endmodule
