-- generated by newgenasym Thu Jun 23 14:58:33 2005

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74hc00\ is
    port (    
	A:         IN     STD_LOGIC;    
	B:         IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	\y*\:      OUT    STD_LOGIC);
end \74hc00\;
