-- generated by newgenasym Tue Jan 10 15:37:17 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity head2x4 is
    port (    
	P1:        INOUT  STD_LOGIC;    
	P2:        INOUT  STD_LOGIC;    
	P3:        INOUT  STD_LOGIC;    
	P4:        INOUT  STD_LOGIC;    
	P5:        INOUT  STD_LOGIC;    
	P6:        INOUT  STD_LOGIC;    
	P7:        INOUT  STD_LOGIC;    
	P8:        INOUT  STD_LOGIC);
end head2x4;
