// generated by newgenasym  Fri Dec 21 12:59:37 2012


module ref5050 (dnc1, dnc2, gnd, nc, temp, \trim/nr , vin, vout);
    inout dnc1;
    inout dnc2;
    inout gnd;
    inout nc;
    inout temp;
    inout \trim/nr ;
    input vin;
    inout vout;


    initial
        begin
        end

endmodule
