-- generated by newgenasym Fri Dec 21 12:59:37 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ref5050 is
    port (    
	DNC1:      INOUT  STD_LOGIC;    
	DNC2:      INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	TEMP:      INOUT  STD_LOGIC;    
	\trim/nr\: INOUT  STD_LOGIC;    
	VIN:       IN     STD_LOGIC;    
	VOUT:      INOUT  STD_LOGIC);
end ref5050;
