// generated by newgenasym  Tue Oct 16 18:59:59 2007


module at24c32a (a0, a1, a2, gnd, scl, sda, vcc, wp);
    input a0;
    input a1;
    input a2;
    input gnd;
    input scl;
    input sda;
    input vcc;
    inout wp;


    initial
        begin
        end

endmodule
