-- generated by newgenasym Tue Oct 16 18:59:59 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity AT24C32A is
    port (    
	A0:        IN     STD_LOGIC;    
	A1:        IN     STD_LOGIC;    
	A2:        IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	SCL:       IN     STD_LOGIC;    
	SDA:       IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	WP:        INOUT  STD_LOGIC);
end AT24C32A;
