// generated by newgenasym  Wed Jun 10 20:44:31 2020


module \5557_4pin  (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
