-- generated by newgenasym Wed Jun 10 20:44:31 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \5557_4pin\ is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC);
end \5557_4pin\;
