-- generated by newgenasym Fri Aug 19 20:06:41 2005

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity bat is
    port (    
	GND:       IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end bat;
