-- generated by newgenasym Thu Sep 20 10:22:28 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \4pin\ is
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (4 DOWNTO 1));
end \4pin\;
