// generated by newgenasym  Wed Feb 26 20:29:10 2014


module xc7k160tffg676 (cclk_0, cfgbvs_0, done_0, dxn_0, dxp_0, gnd_10, gnd_a1,
        gnd_a16, gnd_a2, gnd_a26, gnd_a5, gnd_a6, gnd_a7, gnd_aa16,
        gnd_aa26, gnd_aa6, gnd_ab13, gnd_ab23, gnd_ab3, gnd_ac10,
        gnd_ac20, gnd_ad17, gnd_ad7, gnd_ae14, gnd_ae24, gnd_ae4,
        gnd_af1, gnd_af11, gnd_af21, gnd_b13, gnd_b23, gnd_b4,
        gnd_b7, gnd_c1, gnd_c10, gnd_c20, gnd_c5, gnd_c7, gnd_d17,
        gnd_d4, gnd_d7, gnd_e1, gnd_e14, gnd_e2, gnd_e24, gnd_e5,
        gnd_e7, gnd_f11, gnd_f21, gnd_f3, gnd_f4, gnd_f7, gnd_g1,
        gnd_g18, gnd_g5, gnd_g8, gnd_h15, gnd_h25, gnd_h4, gnd_h7,
        gnd_j1, gnd_j12, gnd_j2, gnd_j22, gnd_j5, gnd_k11, gnd_k13,
        gnd_k19, gnd_k3, gnd_k4, gnd_k7, gnd_k9, gnd_l1, gnd_l12,
        gnd_l14, gnd_l16, gnd_l26, gnd_l5, gnd_m13, gnd_m15,
        gnd_m23, gnd_m4, gnd_m7, gnd_m9, gnd_n1, gnd_n10, gnd_n14,
        gnd_n2, gnd_n20, gnd_n5, gnd_n7, gnd_p13, gnd_p15, gnd_p17,
        gnd_p3, gnd_p4, gnd_p9, gnd_r1, gnd_r10, gnd_r14, gnd_r2,
        gnd_r24, gnd_r5, gnd_r8, gnd_t1, gnd_t11, gnd_t13, gnd_t15,
        gnd_t21, gnd_t3, gnd_t4, gnd_t9, gnd_u10, gnd_u12, gnd_u14,
        gnd_u18, gnd_u8, gnd_v15, gnd_v25, gnd_v5, gnd_w12, gnd_w2,
        gnd_w22, gnd_y19, gnd_y9, gndadc_0, init_b_0, io_0_12,
        io_0_13, io_0_14, io_0_15, io_0_16, io_0_vrn_32,
        io_0_vrn_33, io_0_vrn_34, io_25_12, io_25_13, io_25_14,
        io_25_15, io_25_16, io_25_vrp_32, io_25_vrp_33,
        io_25_vrp_34, io_l10n_t1_12, io_l10n_t1_13,
        io_l10n_t1_16, io_l10n_t1_32, io_l10n_t1_33,
        io_l10n_t1_34, io_l10n_t1_ad4n_15, io_l10n_t1_d15_14,
        io_l10p_t1_12, io_l10p_t1_13, io_l10p_t1_16,
        io_l10p_t1_32, io_l10p_t1_33, io_l10p_t1_34,
        io_l10p_t1_ad4p_15, io_l10p_t1_d14_14,
        io_l11n_t1_srcc_12, io_l11n_t1_srcc_13,
        io_l11n_t1_srcc_14, io_l11n_t1_srcc_16,
        io_l11n_t1_srcc_32, io_l11n_t1_srcc_33,
        io_l11n_t1_srcc_34, io_l11n_t1_srcc_ad12n_15,
        io_l11p_t1_srcc_12, io_l11p_t1_srcc_13,
        io_l11p_t1_srcc_14, io_l11p_t1_srcc_16,
        io_l11p_t1_srcc_32, io_l11p_t1_srcc_33,
        io_l11p_t1_srcc_34, io_l11p_t1_srcc_ad12p_15,
        io_l12n_t1_mrcc_12, io_l12n_t1_mrcc_13,
        io_l12n_t1_mrcc_14, io_l12n_t1_mrcc_16,
        io_l12n_t1_mrcc_32, io_l12n_t1_mrcc_33,
        io_l12n_t1_mrcc_34, io_l12n_t1_mrcc_ad5n_15,
        io_l12p_t1_mrcc_12, io_l12p_t1_mrcc_13,
        io_l12p_t1_mrcc_14, io_l12p_t1_mrcc_16,
        io_l12p_t1_mrcc_32, io_l12p_t1_mrcc_33,
        io_l12p_t1_mrcc_34, io_l12p_t1_mrcc_ad5p_15,
        io_l13n_t2_mrcc_12, io_l13n_t2_mrcc_13,
        io_l13n_t2_mrcc_14, io_l13n_t2_mrcc_15,
        io_l13n_t2_mrcc_16, io_l13n_t2_mrcc_32,
        io_l13n_t2_mrcc_33, io_l13n_t2_mrcc_34,
        io_l13p_t2_mrcc_12, io_l13p_t2_mrcc_13,
        io_l13p_t2_mrcc_14, io_l13p_t2_mrcc_15,
        io_l13p_t2_mrcc_16, io_l13p_t2_mrcc_32,
        io_l13p_t2_mrcc_33, io_l13p_t2_mrcc_34,
        io_l14n_t2_srcc_12, io_l14n_t2_srcc_13,
        io_l14n_t2_srcc_14, io_l14n_t2_srcc_15,
        io_l14n_t2_srcc_16, io_l14n_t2_srcc_32,
        io_l14n_t2_srcc_33, io_l14n_t2_srcc_34,
        io_l14p_t2_srcc_12, io_l14p_t2_srcc_13,
        io_l14p_t2_srcc_14, io_l14p_t2_srcc_15,
        io_l14p_t2_srcc_16, io_l14p_t2_srcc_32,
        io_l14p_t2_srcc_33, io_l14p_t2_srcc_34,
        io_l15n_t2_dqs_12, io_l15n_t2_dqs_13, io_l15n_t2_dqs_16,
        io_l15n_t2_dqs_32, io_l15n_t2_dqs_33, io_l15n_t2_dqs_34,
        io_l15n_t2_dqs_adv_b_15, io_l15n_t2_dqs_dout_cso_b_14,
        io_l15p_t2_dqs_12, io_l15p_t2_dqs_13, io_l15p_t2_dqs_15,
        io_l15p_t2_dqs_16, io_l15p_t2_dqs_32, io_l15p_t2_dqs_33,
        io_l15p_t2_dqs_34, io_l15p_t2_dqs_rdwr_b_14,
        io_l16n_t2_12, io_l16n_t2_13, io_l16n_t2_16,
        io_l16n_t2_32, io_l16n_t2_33, io_l16n_t2_34,
        io_l16n_t2_a15_d31_14, io_l16n_t2_a27_15, io_l16p_t2_12,
        io_l16p_t2_13, io_l16p_t2_16, io_l16p_t2_32,
        io_l16p_t2_33, io_l16p_t2_34, io_l16p_t2_a28_15,
        io_l16p_t2_csi_b_14, io_l17n_t2_12, io_l17n_t2_13,
        io_l17n_t2_16, io_l17n_t2_32, io_l17n_t2_33,
        io_l17n_t2_34, io_l17n_t2_a13_d29_14, io_l17n_t2_a25_15,
        io_l17p_t2_12, io_l17p_t2_13, io_l17p_t2_16,
        io_l17p_t2_32, io_l17p_t2_33, io_l17p_t2_34,
        io_l17p_t2_a14_d30_14, io_l17p_t2_a26_15, io_l18n_t2_12,
        io_l18n_t2_13, io_l18n_t2_16, io_l18n_t2_32,
        io_l18n_t2_33, io_l18n_t2_34, io_l18n_t2_a11_d27_14,
        io_l18n_t2_a23_15, io_l18p_t2_12, io_l18p_t2_13,
        io_l18p_t2_16, io_l18p_t2_32, io_l18p_t2_33,
        io_l18p_t2_34, io_l18p_t2_a12_d28_14, io_l18p_t2_a24_15,
        io_l19n_t3_a09_d25_vref_14, io_l19n_t3_a21_vref_15,
        io_l19n_t3_vref_12, io_l19n_t3_vref_13,
        io_l19n_t3_vref_16, io_l19n_t3_vref_32,
        io_l19n_t3_vref_33, io_l19n_t3_vref_34, io_l19p_t3_12,
        io_l19p_t3_13, io_l19p_t3_16, io_l19p_t3_32,
        io_l19p_t3_33, io_l19p_t3_34, io_l19p_t3_a10_d26_14,
        io_l19p_t3_a22_15, io_l1n_t0_12, io_l1n_t0_13,
        io_l1n_t0_16, io_l1n_t0_32, io_l1n_t0_33, io_l1n_t0_34,
        io_l1n_t0_ad0n_15, io_l1n_t0_d01_din_14, io_l1p_t0_12,
        io_l1p_t0_13, io_l1p_t0_16, io_l1p_t0_32, io_l1p_t0_33,
        io_l1p_t0_34, io_l1p_t0_ad0p_15, io_l1p_t0_d00_mosi_14,
        io_l20n_t3_12, io_l20n_t3_13, io_l20n_t3_16,
        io_l20n_t3_32, io_l20n_t3_33, io_l20n_t3_34,
        io_l20n_t3_a07_d23_14, io_l20n_t3_a19_15, io_l20p_t3_12,
        io_l20p_t3_13, io_l20p_t3_16, io_l20p_t3_32,
        io_l20p_t3_33, io_l20p_t3_34, io_l20p_t3_a08_d24_14,
        io_l20p_t3_a20_15, io_l21n_t3_dqs_12, io_l21n_t3_dqs_13,
        io_l21n_t3_dqs_16, io_l21n_t3_dqs_32, io_l21n_t3_dqs_33,
        io_l21n_t3_dqs_34, io_l21n_t3_dqs_a06_d22_14,
        io_l21n_t3_dqs_a18_15, io_l21p_t3_dqs_12,
        io_l21p_t3_dqs_13, io_l21p_t3_dqs_14, io_l21p_t3_dqs_15,
        io_l21p_t3_dqs_16, io_l21p_t3_dqs_32, io_l21p_t3_dqs_33,
        io_l21p_t3_dqs_34, io_l22n_t3_12, io_l22n_t3_13,
        io_l22n_t3_16, io_l22n_t3_32, io_l22n_t3_33,
        io_l22n_t3_34, io_l22n_t3_a04_d20_14, io_l22n_t3_a16_15,
        io_l22p_t3_12, io_l22p_t3_13, io_l22p_t3_16,
        io_l22p_t3_32, io_l22p_t3_33, io_l22p_t3_34,
        io_l22p_t3_a05_d21_14, io_l22p_t3_a17_15, io_l23n_t3_12,
        io_l23n_t3_13, io_l23n_t3_16, io_l23n_t3_32,
        io_l23n_t3_33, io_l23n_t3_34, io_l23n_t3_a02_d18_14,
        io_l23n_t3_fwe_b_15, io_l23p_t3_12, io_l23p_t3_13,
        io_l23p_t3_16, io_l23p_t3_32, io_l23p_t3_33,
        io_l23p_t3_34, io_l23p_t3_a03_d19_14,
        io_l23p_t3_foe_b_15, io_l24n_t3_12, io_l24n_t3_13,
        io_l24n_t3_16, io_l24n_t3_32, io_l24n_t3_33,
        io_l24n_t3_34, io_l24n_t3_a00_d16_14, io_l24n_t3_rs0_15,
        io_l24p_t3_12, io_l24p_t3_13, io_l24p_t3_16,
        io_l24p_t3_32, io_l24p_t3_33, io_l24p_t3_34,
        io_l24p_t3_a01_d17_14, io_l24p_t3_rs1_15, io_l2n_t0_12,
        io_l2n_t0_13, io_l2n_t0_16, io_l2n_t0_32, io_l2n_t0_33,
        io_l2n_t0_34, io_l2n_t0_ad8n_15, io_l2n_t0_d03_14,
        io_l2p_t0_12, io_l2p_t0_13, io_l2p_t0_16, io_l2p_t0_32,
        io_l2p_t0_33, io_l2p_t0_34, io_l2p_t0_ad8p_15,
        io_l2p_t0_d02_14, io_l3n_t0_dqs_12, io_l3n_t0_dqs_13,
        io_l3n_t0_dqs_16, io_l3n_t0_dqs_32, io_l3n_t0_dqs_33,
        io_l3n_t0_dqs_34, io_l3n_t0_dqs_ad1n_15,
        io_l3n_t0_dqs_emcclk_14, io_l3p_t0_dqs_12,
        io_l3p_t0_dqs_13, io_l3p_t0_dqs_16, io_l3p_t0_dqs_32,
        io_l3p_t0_dqs_33, io_l3p_t0_dqs_34,
        io_l3p_t0_dqs_ad1p_15, io_l3p_t0_dqs_pudc_b_14,
        io_l4n_t0_12, io_l4n_t0_13, io_l4n_t0_16, io_l4n_t0_32,
        io_l4n_t0_33, io_l4n_t0_34, io_l4n_t0_ad9n_15,
        io_l4n_t0_d05_14, io_l4p_t0_12, io_l4p_t0_13,
        io_l4p_t0_16, io_l4p_t0_32, io_l4p_t0_33, io_l4p_t0_34,
        io_l4p_t0_ad9p_15, io_l4p_t0_d04_14, io_l5n_t0_12,
        io_l5n_t0_13, io_l5n_t0_16, io_l5n_t0_32, io_l5n_t0_33,
        io_l5n_t0_34, io_l5n_t0_ad2n_15, io_l5n_t0_d07_14,
        io_l5p_t0_12, io_l5p_t0_13, io_l5p_t0_16, io_l5p_t0_32,
        io_l5p_t0_33, io_l5p_t0_34, io_l5p_t0_ad2p_15,
        io_l5p_t0_d06_14, io_l6n_t0_d08_vref_14,
        io_l6n_t0_vref_12, io_l6n_t0_vref_13, io_l6n_t0_vref_15,
        io_l6n_t0_vref_16, io_l6n_t0_vref_32, io_l6n_t0_vref_33,
        io_l6n_t0_vref_34, io_l6p_t0_12, io_l6p_t0_13,
        io_l6p_t0_15, io_l6p_t0_16, io_l6p_t0_32, io_l6p_t0_33,
        io_l6p_t0_34, io_l6p_t0_fcs_b_14, io_l7n_t1_12,
        io_l7n_t1_13, io_l7n_t1_16, io_l7n_t1_32, io_l7n_t1_33,
        io_l7n_t1_34, io_l7n_t1_ad10n_15, io_l7n_t1_d10_14,
        io_l7p_t1_12, io_l7p_t1_13, io_l7p_t1_16, io_l7p_t1_32,
        io_l7p_t1_33, io_l7p_t1_34, io_l7p_t1_ad10p_15,
        io_l7p_t1_d09_14, io_l8n_t1_12, io_l8n_t1_13,
        io_l8n_t1_16, io_l8n_t1_32, io_l8n_t1_33, io_l8n_t1_34,
        io_l8n_t1_ad3n_15, io_l8n_t1_d12_14, io_l8p_t1_12,
        io_l8p_t1_13, io_l8p_t1_16, io_l8p_t1_32, io_l8p_t1_33,
        io_l8p_t1_34, io_l8p_t1_ad3p_15, io_l8p_t1_d11_14,
        io_l9n_t1_dqs_12, io_l9n_t1_dqs_13, io_l9n_t1_dqs_16,
        io_l9n_t1_dqs_32, io_l9n_t1_dqs_33, io_l9n_t1_dqs_34,
        io_l9n_t1_dqs_ad11n_15, io_l9n_t1_dqs_d13_14,
        io_l9p_t1_dqs_12, io_l9p_t1_dqs_13, io_l9p_t1_dqs_14,
        io_l9p_t1_dqs_16, io_l9p_t1_dqs_32, io_l9p_t1_dqs_33,
        io_l9p_t1_dqs_34, io_l9p_t1_dqs_ad11p_15, m0_0, m1_0,
        m2_0, mgtavcc_c6, mgtavcc_e6, mgtavcc_g6, mgtavcc_j6,
        mgtavcc_l6, mgtavtt_b3, mgtavtt_c2, mgtavtt_d3,
        mgtavtt_g2, mgtavtt_h3, mgtavtt_l2, mgtavtt_m3,
        mgtavttrcal_115, mgtrefclk0n_115, mgtrefclk0n_116,
        mgtrefclk0p_115, mgtrefclk0p_116, mgtrefclk1n_115,
        mgtrefclk1n_116, mgtrefclk1p_115, mgtrefclk1p_116,
        mgtrref_115, mgtvccaux, mgtxrxn0_115, mgtxrxn0_116,
        mgtxrxn1_115, mgtxrxn1_116, mgtxrxn2_115, mgtxrxn2_116,
        mgtxrxn3_115, mgtxrxn3_116, mgtxrxp0_115, mgtxrxp0_116,
        mgtxrxp1_115, mgtxrxp1_116, mgtxrxp2_115, mgtxrxp2_116,
        mgtxrxp3_115, mgtxrxp3_116, mgtxtxn0_115, mgtxtxn0_116,
        mgtxtxn1_115, mgtxtxn1_116, mgtxtxn2_115, mgtxtxn2_116,
        mgtxtxn3_115, mgtxtxn3_116, mgtxtxp0_115, mgtxtxp0_116,
        mgtxtxp1_115, mgtxtxp1_116, mgtxtxp2_115, mgtxtxp2_116,
        mgtxtxp3_115, mgtxtxp3_116, program_b_0, tck_0, tdi_0,
        tdo_0, tms_0, vccadc_0, vccaux_io_g0_p8, vccaux_io_g0_r9,
        vccaux_io_g0_t8, vccaux_l11, vccaux_m10, vccaux_p10,
        vccaux_t10, vccaux_u11, vccbatt_0, vccbram_n13,
        vccbram_r13, vccbram_t12, vccbram_u13, vccint_j9,
        vccint_k10, vccint_k12, vccint_k14, vccint_k8, vccint_l13,
        vccint_l15, vccint_l9, vccint_m14, vccint_m8, vccint_n15,
        vccint_n9, vccint_p14, vccint_r15, vccint_t14, vccint_u15,
        vcco_0_l7, vcco_0_t6, vcco_12_aa21, vcco_12_ac25,
        vcco_12_ad22, vcco_12_af26, vcco_12_u23, vcco_12_v20,
        vcco_12_y24, vcco_13_k24, vcco_13_n25, vcco_13_p22,
        vcco_13_r19, vcco_13_t16, vcco_13_t26, vcco_14_a21,
        vcco_14_c25, vcco_14_d22, vcco_14_f26, vcco_14_g23,
        vcco_14_l21, vcco_15_b18, vcco_15_e19, vcco_15_f16,
        vcco_15_h20, vcco_15_j17, vcco_15_m18, vcco_16_a11,
        vcco_16_b8, vcco_16_c15, vcco_16_d12, vcco_16_e9,
        vcco_16_g13, vcco_16_h10, vcco_32_ab18, vcco_32_ac15,
        vcco_32_ae19, vcco_32_af16, vcco_32_w17, vcco_32_y14,
        vcco_33_aa11, vcco_33_ab8, vcco_33_ad12, vcco_33_ae9,
        vcco_33_v10, vcco_33_w7, vcco_34_aa1, vcco_34_ac5,
        vcco_34_ad2, vcco_34_af6, vcco_34_u3, vcco_34_y4, vn_0,
        vp_0, vrefn_0, vrefp_0);
    inout cclk_0;
    inout cfgbvs_0;
    inout done_0;
    inout dxn_0;
    inout dxp_0;
    input gnd_10;
    input gnd_a1;
    input gnd_a16;
    input gnd_a2;
    input gnd_a26;
    input gnd_a5;
    input gnd_a6;
    input gnd_a7;
    input gnd_aa16;
    input gnd_aa26;
    input gnd_aa6;
    input gnd_ab13;
    input gnd_ab23;
    input gnd_ab3;
    input gnd_ac10;
    input gnd_ac20;
    input gnd_ad17;
    input gnd_ad7;
    input gnd_ae14;
    input gnd_ae24;
    input gnd_ae4;
    input gnd_af1;
    input gnd_af11;
    input gnd_af21;
    input gnd_b13;
    input gnd_b23;
    input gnd_b4;
    input gnd_b7;
    input gnd_c1;
    input gnd_c10;
    input gnd_c20;
    input gnd_c5;
    input gnd_c7;
    input gnd_d17;
    input gnd_d4;
    input gnd_d7;
    input gnd_e1;
    input gnd_e14;
    input gnd_e2;
    input gnd_e24;
    input gnd_e5;
    input gnd_e7;
    input gnd_f11;
    input gnd_f21;
    input gnd_f3;
    input gnd_f4;
    input gnd_f7;
    input gnd_g1;
    input gnd_g18;
    input gnd_g5;
    input gnd_g8;
    input gnd_h15;
    input gnd_h25;
    input gnd_h4;
    input gnd_h7;
    input gnd_j1;
    input gnd_j12;
    input gnd_j2;
    input gnd_j22;
    input gnd_j5;
    input gnd_k11;
    input gnd_k13;
    input gnd_k19;
    input gnd_k3;
    input gnd_k4;
    input gnd_k7;
    input gnd_k9;
    input gnd_l1;
    input gnd_l12;
    input gnd_l14;
    input gnd_l16;
    input gnd_l26;
    input gnd_l5;
    input gnd_m13;
    input gnd_m15;
    input gnd_m23;
    input gnd_m4;
    input gnd_m7;
    input gnd_m9;
    input gnd_n1;
    input gnd_n10;
    input gnd_n14;
    input gnd_n2;
    input gnd_n20;
    input gnd_n5;
    input gnd_n7;
    input gnd_p13;
    input gnd_p15;
    input gnd_p17;
    input gnd_p3;
    input gnd_p4;
    input gnd_p9;
    input gnd_r1;
    input gnd_r10;
    input gnd_r14;
    input gnd_r2;
    input gnd_r24;
    input gnd_r5;
    input gnd_r8;
    input gnd_t1;
    input gnd_t11;
    input gnd_t13;
    input gnd_t15;
    input gnd_t21;
    input gnd_t3;
    input gnd_t4;
    input gnd_t9;
    input gnd_u10;
    input gnd_u12;
    input gnd_u14;
    input gnd_u18;
    input gnd_u8;
    input gnd_v15;
    input gnd_v25;
    input gnd_v5;
    input gnd_w12;
    input gnd_w2;
    input gnd_w22;
    input gnd_y19;
    input gnd_y9;
    inout gndadc_0;
    inout init_b_0;
    inout io_0_12;
    inout io_0_13;
    inout io_0_14;
    inout io_0_15;
    inout io_0_16;
    inout io_0_vrn_32;
    inout io_0_vrn_33;
    inout io_0_vrn_34;
    inout io_25_12;
    inout io_25_13;
    inout io_25_14;
    inout io_25_15;
    inout io_25_16;
    inout io_25_vrp_32;
    inout io_25_vrp_33;
    inout io_25_vrp_34;
    inout io_l10n_t1_12;
    inout io_l10n_t1_13;
    inout io_l10n_t1_16;
    inout io_l10n_t1_32;
    inout io_l10n_t1_33;
    inout io_l10n_t1_34;
    inout io_l10n_t1_ad4n_15;
    inout io_l10n_t1_d15_14;
    inout io_l10p_t1_12;
    inout io_l10p_t1_13;
    inout io_l10p_t1_16;
    inout io_l10p_t1_32;
    inout io_l10p_t1_33;
    inout io_l10p_t1_34;
    inout io_l10p_t1_ad4p_15;
    inout io_l10p_t1_d14_14;
    inout io_l11n_t1_srcc_12;
    inout io_l11n_t1_srcc_13;
    inout io_l11n_t1_srcc_14;
    inout io_l11n_t1_srcc_16;
    inout io_l11n_t1_srcc_32;
    inout io_l11n_t1_srcc_33;
    inout io_l11n_t1_srcc_34;
    inout io_l11n_t1_srcc_ad12n_15;
    inout io_l11p_t1_srcc_12;
    inout io_l11p_t1_srcc_13;
    inout io_l11p_t1_srcc_14;
    inout io_l11p_t1_srcc_16;
    inout io_l11p_t1_srcc_32;
    inout io_l11p_t1_srcc_33;
    inout io_l11p_t1_srcc_34;
    inout io_l11p_t1_srcc_ad12p_15;
    inout io_l12n_t1_mrcc_12;
    inout io_l12n_t1_mrcc_13;
    inout io_l12n_t1_mrcc_14;
    inout io_l12n_t1_mrcc_16;
    inout io_l12n_t1_mrcc_32;
    inout io_l12n_t1_mrcc_33;
    inout io_l12n_t1_mrcc_34;
    inout io_l12n_t1_mrcc_ad5n_15;
    inout io_l12p_t1_mrcc_12;
    inout io_l12p_t1_mrcc_13;
    inout io_l12p_t1_mrcc_14;
    inout io_l12p_t1_mrcc_16;
    inout io_l12p_t1_mrcc_32;
    inout io_l12p_t1_mrcc_33;
    inout io_l12p_t1_mrcc_34;
    inout io_l12p_t1_mrcc_ad5p_15;
    inout io_l13n_t2_mrcc_12;
    inout io_l13n_t2_mrcc_13;
    inout io_l13n_t2_mrcc_14;
    inout io_l13n_t2_mrcc_15;
    inout io_l13n_t2_mrcc_16;
    inout io_l13n_t2_mrcc_32;
    inout io_l13n_t2_mrcc_33;
    inout io_l13n_t2_mrcc_34;
    inout io_l13p_t2_mrcc_12;
    inout io_l13p_t2_mrcc_13;
    inout io_l13p_t2_mrcc_14;
    inout io_l13p_t2_mrcc_15;
    inout io_l13p_t2_mrcc_16;
    inout io_l13p_t2_mrcc_32;
    inout io_l13p_t2_mrcc_33;
    inout io_l13p_t2_mrcc_34;
    inout io_l14n_t2_srcc_12;
    inout io_l14n_t2_srcc_13;
    inout io_l14n_t2_srcc_14;
    inout io_l14n_t2_srcc_15;
    inout io_l14n_t2_srcc_16;
    inout io_l14n_t2_srcc_32;
    inout io_l14n_t2_srcc_33;
    inout io_l14n_t2_srcc_34;
    inout io_l14p_t2_srcc_12;
    inout io_l14p_t2_srcc_13;
    inout io_l14p_t2_srcc_14;
    inout io_l14p_t2_srcc_15;
    inout io_l14p_t2_srcc_16;
    inout io_l14p_t2_srcc_32;
    inout io_l14p_t2_srcc_33;
    inout io_l14p_t2_srcc_34;
    inout io_l15n_t2_dqs_12;
    inout io_l15n_t2_dqs_13;
    inout io_l15n_t2_dqs_16;
    inout io_l15n_t2_dqs_32;
    inout io_l15n_t2_dqs_33;
    inout io_l15n_t2_dqs_34;
    inout io_l15n_t2_dqs_adv_b_15;
    inout io_l15n_t2_dqs_dout_cso_b_14;
    inout io_l15p_t2_dqs_12;
    inout io_l15p_t2_dqs_13;
    inout io_l15p_t2_dqs_15;
    inout io_l15p_t2_dqs_16;
    inout io_l15p_t2_dqs_32;
    inout io_l15p_t2_dqs_33;
    inout io_l15p_t2_dqs_34;
    inout io_l15p_t2_dqs_rdwr_b_14;
    inout io_l16n_t2_12;
    inout io_l16n_t2_13;
    inout io_l16n_t2_16;
    inout io_l16n_t2_32;
    inout io_l16n_t2_33;
    inout io_l16n_t2_34;
    inout io_l16n_t2_a15_d31_14;
    inout io_l16n_t2_a27_15;
    inout io_l16p_t2_12;
    inout io_l16p_t2_13;
    inout io_l16p_t2_16;
    inout io_l16p_t2_32;
    inout io_l16p_t2_33;
    inout io_l16p_t2_34;
    inout io_l16p_t2_a28_15;
    inout io_l16p_t2_csi_b_14;
    inout io_l17n_t2_12;
    inout io_l17n_t2_13;
    inout io_l17n_t2_16;
    inout io_l17n_t2_32;
    inout io_l17n_t2_33;
    inout io_l17n_t2_34;
    inout io_l17n_t2_a13_d29_14;
    inout io_l17n_t2_a25_15;
    inout io_l17p_t2_12;
    inout io_l17p_t2_13;
    inout io_l17p_t2_16;
    inout io_l17p_t2_32;
    inout io_l17p_t2_33;
    inout io_l17p_t2_34;
    inout io_l17p_t2_a14_d30_14;
    inout io_l17p_t2_a26_15;
    inout io_l18n_t2_12;
    inout io_l18n_t2_13;
    inout io_l18n_t2_16;
    inout io_l18n_t2_32;
    inout io_l18n_t2_33;
    inout io_l18n_t2_34;
    inout io_l18n_t2_a11_d27_14;
    inout io_l18n_t2_a23_15;
    inout io_l18p_t2_12;
    inout io_l18p_t2_13;
    inout io_l18p_t2_16;
    inout io_l18p_t2_32;
    inout io_l18p_t2_33;
    inout io_l18p_t2_34;
    inout io_l18p_t2_a12_d28_14;
    inout io_l18p_t2_a24_15;
    inout io_l19n_t3_a09_d25_vref_14;
    inout io_l19n_t3_a21_vref_15;
    inout io_l19n_t3_vref_12;
    inout io_l19n_t3_vref_13;
    inout io_l19n_t3_vref_16;
    inout io_l19n_t3_vref_32;
    inout io_l19n_t3_vref_33;
    inout io_l19n_t3_vref_34;
    inout io_l19p_t3_12;
    inout io_l19p_t3_13;
    inout io_l19p_t3_16;
    inout io_l19p_t3_32;
    inout io_l19p_t3_33;
    inout io_l19p_t3_34;
    inout io_l19p_t3_a10_d26_14;
    inout io_l19p_t3_a22_15;
    inout io_l1n_t0_12;
    inout io_l1n_t0_13;
    inout io_l1n_t0_16;
    inout io_l1n_t0_32;
    inout io_l1n_t0_33;
    inout io_l1n_t0_34;
    inout io_l1n_t0_ad0n_15;
    inout io_l1n_t0_d01_din_14;
    inout io_l1p_t0_12;
    inout io_l1p_t0_13;
    inout io_l1p_t0_16;
    inout io_l1p_t0_32;
    inout io_l1p_t0_33;
    inout io_l1p_t0_34;
    inout io_l1p_t0_ad0p_15;
    inout io_l1p_t0_d00_mosi_14;
    inout io_l20n_t3_12;
    inout io_l20n_t3_13;
    inout io_l20n_t3_16;
    inout io_l20n_t3_32;
    inout io_l20n_t3_33;
    inout io_l20n_t3_34;
    inout io_l20n_t3_a07_d23_14;
    inout io_l20n_t3_a19_15;
    inout io_l20p_t3_12;
    inout io_l20p_t3_13;
    inout io_l20p_t3_16;
    inout io_l20p_t3_32;
    inout io_l20p_t3_33;
    inout io_l20p_t3_34;
    inout io_l20p_t3_a08_d24_14;
    inout io_l20p_t3_a20_15;
    inout io_l21n_t3_dqs_12;
    inout io_l21n_t3_dqs_13;
    inout io_l21n_t3_dqs_16;
    inout io_l21n_t3_dqs_32;
    inout io_l21n_t3_dqs_33;
    inout io_l21n_t3_dqs_34;
    inout io_l21n_t3_dqs_a06_d22_14;
    inout io_l21n_t3_dqs_a18_15;
    inout io_l21p_t3_dqs_12;
    inout io_l21p_t3_dqs_13;
    inout io_l21p_t3_dqs_14;
    inout io_l21p_t3_dqs_15;
    inout io_l21p_t3_dqs_16;
    inout io_l21p_t3_dqs_32;
    inout io_l21p_t3_dqs_33;
    inout io_l21p_t3_dqs_34;
    inout io_l22n_t3_12;
    inout io_l22n_t3_13;
    inout io_l22n_t3_16;
    inout io_l22n_t3_32;
    inout io_l22n_t3_33;
    inout io_l22n_t3_34;
    inout io_l22n_t3_a04_d20_14;
    inout io_l22n_t3_a16_15;
    inout io_l22p_t3_12;
    inout io_l22p_t3_13;
    inout io_l22p_t3_16;
    inout io_l22p_t3_32;
    inout io_l22p_t3_33;
    inout io_l22p_t3_34;
    inout io_l22p_t3_a05_d21_14;
    inout io_l22p_t3_a17_15;
    inout io_l23n_t3_12;
    inout io_l23n_t3_13;
    inout io_l23n_t3_16;
    inout io_l23n_t3_32;
    inout io_l23n_t3_33;
    inout io_l23n_t3_34;
    inout io_l23n_t3_a02_d18_14;
    inout io_l23n_t3_fwe_b_15;
    inout io_l23p_t3_12;
    inout io_l23p_t3_13;
    inout io_l23p_t3_16;
    inout io_l23p_t3_32;
    inout io_l23p_t3_33;
    inout io_l23p_t3_34;
    inout io_l23p_t3_a03_d19_14;
    inout io_l23p_t3_foe_b_15;
    inout io_l24n_t3_12;
    inout io_l24n_t3_13;
    inout io_l24n_t3_16;
    inout io_l24n_t3_32;
    inout io_l24n_t3_33;
    inout io_l24n_t3_34;
    inout io_l24n_t3_a00_d16_14;
    inout io_l24n_t3_rs0_15;
    inout io_l24p_t3_12;
    inout io_l24p_t3_13;
    inout io_l24p_t3_16;
    inout io_l24p_t3_32;
    inout io_l24p_t3_33;
    inout io_l24p_t3_34;
    inout io_l24p_t3_a01_d17_14;
    inout io_l24p_t3_rs1_15;
    inout io_l2n_t0_12;
    inout io_l2n_t0_13;
    inout io_l2n_t0_16;
    inout io_l2n_t0_32;
    inout io_l2n_t0_33;
    inout io_l2n_t0_34;
    inout io_l2n_t0_ad8n_15;
    inout io_l2n_t0_d03_14;
    inout io_l2p_t0_12;
    inout io_l2p_t0_13;
    inout io_l2p_t0_16;
    inout io_l2p_t0_32;
    inout io_l2p_t0_33;
    inout io_l2p_t0_34;
    inout io_l2p_t0_ad8p_15;
    inout io_l2p_t0_d02_14;
    inout io_l3n_t0_dqs_12;
    inout io_l3n_t0_dqs_13;
    inout io_l3n_t0_dqs_16;
    inout io_l3n_t0_dqs_32;
    inout io_l3n_t0_dqs_33;
    inout io_l3n_t0_dqs_34;
    inout io_l3n_t0_dqs_ad1n_15;
    inout io_l3n_t0_dqs_emcclk_14;
    inout io_l3p_t0_dqs_12;
    inout io_l3p_t0_dqs_13;
    inout io_l3p_t0_dqs_16;
    inout io_l3p_t0_dqs_32;
    inout io_l3p_t0_dqs_33;
    inout io_l3p_t0_dqs_34;
    inout io_l3p_t0_dqs_ad1p_15;
    inout io_l3p_t0_dqs_pudc_b_14;
    inout io_l4n_t0_12;
    inout io_l4n_t0_13;
    inout io_l4n_t0_16;
    inout io_l4n_t0_32;
    inout io_l4n_t0_33;
    inout io_l4n_t0_34;
    inout io_l4n_t0_ad9n_15;
    inout io_l4n_t0_d05_14;
    inout io_l4p_t0_12;
    inout io_l4p_t0_13;
    inout io_l4p_t0_16;
    inout io_l4p_t0_32;
    inout io_l4p_t0_33;
    inout io_l4p_t0_34;
    inout io_l4p_t0_ad9p_15;
    inout io_l4p_t0_d04_14;
    inout io_l5n_t0_12;
    inout io_l5n_t0_13;
    inout io_l5n_t0_16;
    inout io_l5n_t0_32;
    inout io_l5n_t0_33;
    inout io_l5n_t0_34;
    inout io_l5n_t0_ad2n_15;
    inout io_l5n_t0_d07_14;
    inout io_l5p_t0_12;
    inout io_l5p_t0_13;
    inout io_l5p_t0_16;
    inout io_l5p_t0_32;
    inout io_l5p_t0_33;
    inout io_l5p_t0_34;
    inout io_l5p_t0_ad2p_15;
    inout io_l5p_t0_d06_14;
    inout io_l6n_t0_d08_vref_14;
    inout io_l6n_t0_vref_12;
    inout io_l6n_t0_vref_13;
    inout io_l6n_t0_vref_15;
    inout io_l6n_t0_vref_16;
    inout io_l6n_t0_vref_32;
    inout io_l6n_t0_vref_33;
    inout io_l6n_t0_vref_34;
    inout io_l6p_t0_12;
    inout io_l6p_t0_13;
    inout io_l6p_t0_15;
    inout io_l6p_t0_16;
    inout io_l6p_t0_32;
    inout io_l6p_t0_33;
    inout io_l6p_t0_34;
    inout io_l6p_t0_fcs_b_14;
    inout io_l7n_t1_12;
    inout io_l7n_t1_13;
    inout io_l7n_t1_16;
    inout io_l7n_t1_32;
    inout io_l7n_t1_33;
    inout io_l7n_t1_34;
    inout io_l7n_t1_ad10n_15;
    inout io_l7n_t1_d10_14;
    inout io_l7p_t1_12;
    inout io_l7p_t1_13;
    inout io_l7p_t1_16;
    inout io_l7p_t1_32;
    inout io_l7p_t1_33;
    inout io_l7p_t1_34;
    inout io_l7p_t1_ad10p_15;
    inout io_l7p_t1_d09_14;
    inout io_l8n_t1_12;
    inout io_l8n_t1_13;
    inout io_l8n_t1_16;
    inout io_l8n_t1_32;
    inout io_l8n_t1_33;
    inout io_l8n_t1_34;
    inout io_l8n_t1_ad3n_15;
    inout io_l8n_t1_d12_14;
    inout io_l8p_t1_12;
    inout io_l8p_t1_13;
    inout io_l8p_t1_16;
    inout io_l8p_t1_32;
    inout io_l8p_t1_33;
    inout io_l8p_t1_34;
    inout io_l8p_t1_ad3p_15;
    inout io_l8p_t1_d11_14;
    inout io_l9n_t1_dqs_12;
    inout io_l9n_t1_dqs_13;
    inout io_l9n_t1_dqs_16;
    inout io_l9n_t1_dqs_32;
    inout io_l9n_t1_dqs_33;
    inout io_l9n_t1_dqs_34;
    inout io_l9n_t1_dqs_ad11n_15;
    inout io_l9n_t1_dqs_d13_14;
    inout io_l9p_t1_dqs_12;
    inout io_l9p_t1_dqs_13;
    inout io_l9p_t1_dqs_14;
    inout io_l9p_t1_dqs_16;
    inout io_l9p_t1_dqs_32;
    inout io_l9p_t1_dqs_33;
    inout io_l9p_t1_dqs_34;
    inout io_l9p_t1_dqs_ad11p_15;
    inout m0_0;
    inout m1_0;
    inout m2_0;
    inout mgtavcc_c6;
    inout mgtavcc_e6;
    inout mgtavcc_g6;
    inout mgtavcc_j6;
    inout mgtavcc_l6;
    inout mgtavtt_b3;
    inout mgtavtt_c2;
    inout mgtavtt_d3;
    inout mgtavtt_g2;
    inout mgtavtt_h3;
    inout mgtavtt_l2;
    inout mgtavtt_m3;
    inout mgtavttrcal_115;
    inout mgtrefclk0n_115;
    inout mgtrefclk0n_116;
    inout mgtrefclk0p_115;
    inout mgtrefclk0p_116;
    inout mgtrefclk1n_115;
    inout mgtrefclk1n_116;
    inout mgtrefclk1p_115;
    inout mgtrefclk1p_116;
    inout mgtrref_115;
    inout mgtvccaux;
    inout mgtxrxn0_115;
    inout mgtxrxn0_116;
    inout mgtxrxn1_115;
    inout mgtxrxn1_116;
    inout mgtxrxn2_115;
    inout mgtxrxn2_116;
    inout mgtxrxn3_115;
    inout mgtxrxn3_116;
    inout mgtxrxp0_115;
    inout mgtxrxp0_116;
    inout mgtxrxp1_115;
    inout mgtxrxp1_116;
    inout mgtxrxp2_115;
    inout mgtxrxp2_116;
    inout mgtxrxp3_115;
    inout mgtxrxp3_116;
    inout mgtxtxn0_115;
    inout mgtxtxn0_116;
    inout mgtxtxn1_115;
    inout mgtxtxn1_116;
    inout mgtxtxn2_115;
    inout mgtxtxn2_116;
    inout mgtxtxn3_115;
    inout mgtxtxn3_116;
    inout mgtxtxp0_115;
    inout mgtxtxp0_116;
    inout mgtxtxp1_115;
    inout mgtxtxp1_116;
    inout mgtxtxp2_115;
    inout mgtxtxp2_116;
    inout mgtxtxp3_115;
    inout mgtxtxp3_116;
    inout program_b_0;
    inout tck_0;
    inout tdi_0;
    inout tdo_0;
    inout tms_0;
    inout vccadc_0;
    input vccaux_io_g0_p8;
    input vccaux_io_g0_r9;
    input vccaux_io_g0_t8;
    input vccaux_l11;
    input vccaux_m10;
    input vccaux_p10;
    input vccaux_t10;
    input vccaux_u11;
    inout vccbatt_0;
    inout vccbram_n13;
    inout vccbram_r13;
    inout vccbram_t12;
    inout vccbram_u13;
    input vccint_j9;
    input vccint_k10;
    input vccint_k12;
    input vccint_k14;
    input vccint_k8;
    input vccint_l13;
    input vccint_l15;
    input vccint_l9;
    input vccint_m14;
    input vccint_m8;
    input vccint_n15;
    input vccint_n9;
    input vccint_p14;
    input vccint_r15;
    input vccint_t14;
    input vccint_u15;
    input vcco_0_l7;
    input vcco_0_t6;
    input vcco_12_aa21;
    input vcco_12_ac25;
    input vcco_12_ad22;
    input vcco_12_af26;
    input vcco_12_u23;
    input vcco_12_v20;
    input vcco_12_y24;
    input vcco_13_k24;
    input vcco_13_n25;
    input vcco_13_p22;
    input vcco_13_r19;
    input vcco_13_t16;
    input vcco_13_t26;
    input vcco_14_a21;
    input vcco_14_c25;
    input vcco_14_d22;
    input vcco_14_f26;
    input vcco_14_g23;
    input vcco_14_l21;
    input vcco_15_b18;
    input vcco_15_e19;
    input vcco_15_f16;
    input vcco_15_h20;
    input vcco_15_j17;
    input vcco_15_m18;
    input vcco_16_a11;
    input vcco_16_b8;
    input vcco_16_c15;
    input vcco_16_d12;
    input vcco_16_e9;
    input vcco_16_g13;
    input vcco_16_h10;
    input vcco_32_ab18;
    input vcco_32_ac15;
    input vcco_32_ae19;
    input vcco_32_af16;
    input vcco_32_w17;
    input vcco_32_y14;
    input vcco_33_aa11;
    input vcco_33_ab8;
    input vcco_33_ad12;
    input vcco_33_ae9;
    input vcco_33_v10;
    input vcco_33_w7;
    input vcco_34_aa1;
    input vcco_34_ac5;
    input vcco_34_ad2;
    input vcco_34_af6;
    input vcco_34_u3;
    input vcco_34_y4;
    inout vn_0;
    inout vp_0;
    inout vrefn_0;
    inout vrefp_0;


    initial
        begin
        end

endmodule
