-- generated by newgenasym Thu Oct 30 19:04:38 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \earphone-jk325\ is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC);
end \earphone-jk325\;
