// generated by newgenasym  Tue Mar 25 17:37:19 2014


module \osc-6  (gnd, nc, \oe/st# , \out+ , \out- , vdd);
    inout gnd;
    inout nc;
    inout \oe/st# ;
    inout \out+ ;
    inout \out- ;
    inout vdd;


    initial
        begin
        end

endmodule
