-- generated by newgenasym Tue Mar 25 17:37:19 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \osc-6\ is
    port (    
	GND:       INOUT  STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	\oe/st#\:  INOUT  STD_LOGIC;    
	\out+\:    INOUT  STD_LOGIC;    
	\out-\:    INOUT  STD_LOGIC;    
	VDD:       INOUT  STD_LOGIC);
end \osc-6\;
