-- generated by newgenasym Fri Nov 06 19:49:44 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity esd9b is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end esd9b;
