// generated by newgenasym  Fri Nov 28 19:59:34 2025


module ne5532dr (\in1+ , \in1- , \in2+ , \in2- , out1, out2, \vcc+ , \vcc-/gnd );
    inout \in1+ ;
    inout \in1- ;
    inout \in2+ ;
    inout \in2- ;
    inout out1;
    inout out2;
    inout \vcc+ ;
    inout \vcc-/gnd ;


    initial
        begin
        end

endmodule
