// generated by newgenasym  Wed Apr 09 16:20:07 2014


module max3160e (\a/r2in , \b/r1in , \c1+ , \c1- , \c2+ , \c2- , \de485/t2in , \di/t1in ,
        fast, gnd, hdplx, r1out, \ro/r2out , \rs485/rs232 , \shdn* , \v+ , \v- ,
        vcc, \y/a/t2out , \z/b/t1out );
    inout \a/r2in ;
    inout \b/r1in ;
    inout \c1+ ;
    inout \c1- ;
    inout \c2+ ;
    inout \c2- ;
    inout \de485/t2in ;
    inout \di/t1in ;
    inout fast;
    inout gnd;
    inout hdplx;
    inout r1out;
    inout \ro/r2out ;
    inout \rs485/rs232 ;
    inout \shdn* ;
    inout \v+ ;
    inout \v- ;
    inout vcc;
    inout \y/a/t2out ;
    inout \z/b/t1out ;


    initial
        begin
        end

endmodule
