-- generated by newgenasym Wed Apr 09 16:20:07 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max3160e is
    port (    
	\a/r2in\:  INOUT  STD_LOGIC;    
	\b/r1in\:  INOUT  STD_LOGIC;    
	\c1+\:     INOUT  STD_LOGIC;    
	\c1-\:     INOUT  STD_LOGIC;    
	\c2+\:     INOUT  STD_LOGIC;    
	\c2-\:     INOUT  STD_LOGIC;    
	\de485/t2in\: INOUT  STD_LOGIC;    
	\di/t1in\: INOUT  STD_LOGIC;    
	FAST:      INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	HDPLX:     INOUT  STD_LOGIC;    
	R1OUT:     INOUT  STD_LOGIC;    
	\ro/r2out\: INOUT  STD_LOGIC;    
	\rs485/rs232\: INOUT  STD_LOGIC;    
	\shdn*\:   INOUT  STD_LOGIC;    
	\v+\:      INOUT  STD_LOGIC;    
	\v-\:      INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC;    
	\y/a/t2out\: INOUT  STD_LOGIC;    
	\z/b/t1out\: INOUT  STD_LOGIC);
end max3160e;
