// generated by newgenasym  Tue Sep 01 11:06:47 2009


module \ada4941-1  (dis, fb, in, \out+ , \out- , ref, \v+ , \v- );
    input dis;
    input fb;
    input in;
    output \out+ ;
    output \out- ;
    input ref;
    input \v+ ;
    input \v- ;


    initial
        begin
        end

endmodule
