-- generated by newgenasym Tue Sep 01 11:06:47 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \ada4941-1\ is
    port (    
	DIS:       IN     STD_LOGIC;    
	FB:        IN     STD_LOGIC;    
	\in\:      IN     STD_LOGIC;    
	\out+\:    OUT    STD_LOGIC;    
	\out-\:    OUT    STD_LOGIC;    
	REF:       IN     STD_LOGIC;    
	\v+\:      IN     STD_LOGIC;    
	\v-\:      IN     STD_LOGIC);
end \ada4941-1\;
