-- generated by newgenasym Tue Apr 05 10:56:40 2005

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity cp is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end cp;
