// generated by newgenasym  Wed Dec 14 12:12:36 2016


module ds90cr287 (gnd, \lvds#20gnd , \lvds#20vcc , \pll#20gnd , \pll#20vcc , \pwr#20dwn ,
        \txclk#20in , \txclkout+ , \txclkout- , txin0, txin1, txin10,
        txin11, txin12, txin13, txin14, txin15, txin16, txin17,
        txin18, txin19, txin2, txin20, txin21, txin22, txin23,
        txin24, txin25, txin26, txin27, txin3, txin4, txin5, txin6,
        txin7, txin8, txin9, \txout0+ , \txout0- , \txout1+ , \txout1- ,
        \txout2+ , \txout2- , \txout3+ , \txout3- , vcc);
    inout [5:1] gnd;
    inout [3:1] \lvds#20gnd ;
    inout \lvds#20vcc ;
    inout [2:1] \pll#20gnd ;
    inout \pll#20vcc ;
    inout \pwr#20dwn ;
    inout \txclk#20in ;
    inout \txclkout+ ;
    inout \txclkout- ;
    inout txin0;
    inout txin1;
    inout txin10;
    inout txin11;
    inout txin12;
    inout txin13;
    inout txin14;
    inout txin15;
    inout txin16;
    inout txin17;
    inout txin18;
    inout txin19;
    inout txin2;
    inout txin20;
    inout txin21;
    inout txin22;
    inout txin23;
    inout txin24;
    inout txin25;
    inout txin26;
    inout txin27;
    inout txin3;
    inout txin4;
    inout txin5;
    inout txin6;
    inout txin7;
    inout txin8;
    inout txin9;
    inout \txout0+ ;
    inout \txout0- ;
    inout \txout1+ ;
    inout \txout1- ;
    inout \txout2+ ;
    inout \txout2- ;
    inout \txout3+ ;
    inout \txout3- ;
    inout [4:1] vcc;


    initial
        begin
        end

endmodule
