// generated by newgenasym  Thu Jan 19 14:03:07 2012


module opa211 (\in+ , \in- , out, \v+ , \v- );
    input \in+ ;
    input \in- ;
    output out;
    input \v+ ;
    input \v- ;


    initial
        begin
        end

endmodule
