-- generated by newgenasym Thu Jan 19 14:03:07 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity opa211 is
    port (    
	\in+\:     IN     STD_LOGIC;    
	\in-\:     IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	\v+\:      IN     STD_LOGIC;    
	\v-\:      IN     STD_LOGIC);
end opa211;
