-- generated by newgenasym Sun May 11 16:28:51 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity head2x12 is
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (24 DOWNTO 1));
end head2x12;
