-- generated by newgenasym Fri Nov 16 10:37:20 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \3pin\ is
    port (    
	A1:        INOUT  STD_LOGIC;    
	A2:        INOUT  STD_LOGIC;    
	A3:        INOUT  STD_LOGIC);
end \3pin\;
