// generated by newgenasym  Tue Jan 10 11:05:19 2012


module sn75lvde83a (clkin, clkoutm, clkoutp, clksel, d0, d1, d10, d11, d12, d13,
        d14, d15, d16, d17, d18, d19, d2, d20, d21, d22, d23, d24, d25,
        d26, d27, d3, d4, d5, d6, d7, d8, d9, gnd1, gnd10, gnd2, gnd3,
        gnd4, gnd5, gnd6, gnd7, gnd8, gnd9, lvdsvcc, pllvcc, \shtdn* ,
        vcc1, vcc2, vcc3, y0m, y0p, y1m, y1p, y2m, y2p, y3m, y3p);
    input clkin;
    output clkoutm;
    output clkoutp;
    input clksel;
    input d0;
    input d1;
    input d10;
    input d11;
    input d12;
    input d13;
    input d14;
    input d15;
    input d16;
    input d17;
    input d18;
    input d19;
    input d2;
    input d20;
    input d21;
    input d22;
    input d23;
    input d24;
    input d25;
    input d26;
    input d27;
    input d3;
    input d4;
    input d5;
    input d6;
    input d7;
    input d8;
    input d9;
    input gnd1;
    input gnd10;
    input gnd2;
    input gnd3;
    input gnd4;
    input gnd5;
    input gnd6;
    input gnd7;
    input gnd8;
    input gnd9;
    input lvdsvcc;
    input pllvcc;
    input \shtdn* ;
    input vcc1;
    input vcc2;
    input vcc3;
    output y0m;
    output y0p;
    output y1m;
    output y1p;
    output y2m;
    output y2p;
    output y3m;
    output y3p;


    initial
        begin
        end

endmodule
