-- generated by newgenasym Thu Nov 20 20:06:32 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity blm18pg121sn1d_c14709 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end blm18pg121sn1d_c14709;
