-- generated by newgenasym Wed Sep 01 15:39:34 2010

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity NMOSFET is
    port (    
	D:         INOUT  STD_LOGIC;    
	G:         INOUT  STD_LOGIC;    
	S:         INOUT  STD_LOGIC);
end NMOSFET;
