// generated by newgenasym  Mon Aug 07 20:50:58 2006


module ds1339 (gnd, scl, sda, \sqw/int , vbkp, vcc, x1, x2);
    input gnd;
    input scl;
    inout sda;
    output \sqw/int ;
    input vbkp;
    input vcc;
    input x1;
    input x2;


    initial
        begin
        end

endmodule
