-- generated by newgenasym Mon Aug 07 20:50:58 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ds1339 is
    port (    
	GND:       IN     STD_LOGIC;    
	SCL:       IN     STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC;    
	\sqw/int\: OUT    STD_LOGIC;    
	VBKP:      IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	X1:        IN     STD_LOGIC;    
	X2:        IN     STD_LOGIC);
end ds1339;
