// generated by newgenasym  Wed May 28 19:21:12 2014


module tps54228 (en, gnd, pgnd, ss, sw, vbst, vfb, vin, vreg5);
    inout en;
    inout gnd;
    inout pgnd;
    inout ss;
    inout sw;
    inout vbst;
    inout vfb;
    inout vin;
    inout vreg5;


    initial
        begin
        end

endmodule
