-- generated by newgenasym Wed May 28 19:21:12 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tps54228 is
    port (    
	EN:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	PGND:      INOUT  STD_LOGIC;    
	SS:        INOUT  STD_LOGIC;    
	SW:        INOUT  STD_LOGIC;    
	VBST:      INOUT  STD_LOGIC;    
	VFB:       INOUT  STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC;    
	VREG5:     INOUT  STD_LOGIC);
end tps54228;
