// generated by newgenasym  Tue Apr 10 11:12:41 2007


module \74f175sc  (cp, d, gnd, \mr* , q, \q* , vcc);
    input cp;
    input [3:0] d;
    input gnd;
    input \mr* ;
    output [3:0] q;
    output [3:0] \q* ;
    input vcc;


    initial
        begin
        end

endmodule
