-- generated by newgenasym Tue Apr 10 11:12:41 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74f175sc\ is
    port (    
	CP:        IN     STD_LOGIC;    
	D:         IN     STD_LOGIC_VECTOR (3 DOWNTO 0);    
	GND:       IN     STD_LOGIC;    
	\mr*\:     IN     STD_LOGIC;    
	Q:         OUT    STD_LOGIC_VECTOR (3 DOWNTO 0);    
	\q*\:      OUT    STD_LOGIC_VECTOR (3 DOWNTO 0);    
	VCC:       IN     STD_LOGIC);
end \74f175sc\;
