// generated by newgenasym  Fri Jul 20 10:31:17 2012


module sd_new_3 (cd, cd_com, clk, cmd, data0, data1, data2, data3, gnd1, gnd2,
        gnd_sh1, gnd_sh2, vcc, \wp* );
    inout cd;
    inout cd_com;
    input clk;
    input cmd;
    inout data0;
    inout data1;
    inout data2;
    inout data3;
    input gnd1;
    input gnd2;
    input gnd_sh1;
    input gnd_sh2;
    input vcc;
    inout \wp* ;


    initial
        begin
        end

endmodule
