-- generated by newgenasym Fri Jul 20 10:31:17 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sd_new_3 is
    port (    
	CD:        INOUT  STD_LOGIC;    
	CD_COM:    INOUT  STD_LOGIC;    
	CLK:       IN     STD_LOGIC;    
	CMD:       IN     STD_LOGIC;    
	DATA0:     INOUT  STD_LOGIC;    
	DATA1:     INOUT  STD_LOGIC;    
	DATA2:     INOUT  STD_LOGIC;    
	DATA3:     INOUT  STD_LOGIC;    
	GND1:      IN     STD_LOGIC;    
	GND2:      IN     STD_LOGIC;    
	GND_SH1:   IN     STD_LOGIC;    
	GND_SH2:   IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	\wp*\:     INOUT  STD_LOGIC);
end sd_new_3;
