// generated by newgenasym  Wed Sep 07 13:00:06 2016


module bq24315 (ce, ep, fault, ilim, in, nc, out, vbat, vss);
    inout ce;
    inout ep;
    inout fault;
    inout ilim;
    inout in;
    inout nc;
    inout out;
    inout vbat;
    inout vss;


    initial
        begin
        end

endmodule
