-- generated by newgenasym Wed Sep 07 13:00:06 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity bq24315 is
    port (    
	CE:        INOUT  STD_LOGIC;    
	EP:        INOUT  STD_LOGIC;    
	FAULT:     INOUT  STD_LOGIC;    
	ILIM:      INOUT  STD_LOGIC;    
	\in\:      INOUT  STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	VBAT:      INOUT  STD_LOGIC;    
	VSS:       INOUT  STD_LOGIC);
end bq24315;
