// generated by newgenasym  Wed Jul 12 13:59:20 2023


module op27gs (\+in , \-in , nc, out, \v+ , \v- , vos1, vos2);
    inout \+in ;
    inout \-in ;
    inout nc;
    inout out;
    inout \v+ ;
    inout \v- ;
    inout vos1;
    inout vos2;


    initial
        begin
        end

endmodule
