-- generated by newgenasym Wed Jul 12 13:59:20 2023

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity op27gs is
    port (    
	\+in\:     INOUT  STD_LOGIC;    
	\-in\:     INOUT  STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	\v+\:      INOUT  STD_LOGIC;    
	\v-\:      INOUT  STD_LOGIC;    
	VOS1:      INOUT  STD_LOGIC;    
	VOS2:      INOUT  STD_LOGIC);
end op27gs;
