// generated by newgenasym  Mon Nov 17 10:15:27 2014


module adau17621 (\adc_sdata/gpio1 , \addr0/clatch , \addr1/cdata , agnd1, agnd2,
        avdd1, avdd2, \bclk/gpio2 , cm, \dac_sdata/gpio0 , dgnd,
        dvddout, \exposed#20pad , iovdd, \jackdet/micin , laux, lhp, linn,
        linp, loutn, loutp, \lrclk/gpio3 , mclk, micbias, monoout,
        raux, rhp, rinn, rinp, routn, routp, \scl/cclk , \sda/cout );
    inout \adc_sdata/gpio1 ;
    inout \addr0/clatch ;
    inout \addr1/cdata ;
    inout agnd1;
    inout agnd2;
    inout avdd1;
    inout avdd2;
    inout \bclk/gpio2 ;
    inout cm;
    inout \dac_sdata/gpio0 ;
    inout dgnd;
    inout dvddout;
    inout \exposed#20pad ;
    inout iovdd;
    inout \jackdet/micin ;
    inout laux;
    inout lhp;
    inout linn;
    inout linp;
    inout loutn;
    inout loutp;
    inout \lrclk/gpio3 ;
    inout mclk;
    inout micbias;
    inout monoout;
    inout raux;
    inout rhp;
    inout rinn;
    inout rinp;
    inout routn;
    inout routp;
    inout \scl/cclk ;
    inout \sda/cout ;


    initial
        begin
        end

endmodule
