-- generated by newgenasym Mon Nov 17 10:15:27 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adau17621 is
    port (    
	\adc_sdata/gpio1\: INOUT  STD_LOGIC;    
	\addr0/clatch\: INOUT  STD_LOGIC;    
	\addr1/cdata\: INOUT  STD_LOGIC;    
	AGND1:     INOUT  STD_LOGIC;    
	AGND2:     INOUT  STD_LOGIC;    
	AVDD1:     INOUT  STD_LOGIC;    
	AVDD2:     INOUT  STD_LOGIC;    
	\bclk/gpio2\: INOUT  STD_LOGIC;    
	CM:        INOUT  STD_LOGIC;    
	\dac_sdata/gpio0\: INOUT  STD_LOGIC;    
	DGND:      INOUT  STD_LOGIC;    
	DVDDOUT:   INOUT  STD_LOGIC;    
	\exposed pad\: INOUT  STD_LOGIC;    
	IOVDD:     INOUT  STD_LOGIC;    
	\jackdet/micin\: INOUT  STD_LOGIC;    
	LAUX:      INOUT  STD_LOGIC;    
	LHP:       INOUT  STD_LOGIC;    
	LINN:      INOUT  STD_LOGIC;    
	LINP:      INOUT  STD_LOGIC;    
	LOUTN:     INOUT  STD_LOGIC;    
	LOUTP:     INOUT  STD_LOGIC;    
	\lrclk/gpio3\: INOUT  STD_LOGIC;    
	MCLK:      INOUT  STD_LOGIC;    
	MICBIAS:   INOUT  STD_LOGIC;    
	MONOOUT:   INOUT  STD_LOGIC;    
	RAUX:      INOUT  STD_LOGIC;    
	RHP:       INOUT  STD_LOGIC;    
	RINN:      INOUT  STD_LOGIC;    
	RINP:      INOUT  STD_LOGIC;    
	ROUTN:     INOUT  STD_LOGIC;    
	ROUTP:     INOUT  STD_LOGIC;    
	\scl/cclk\: INOUT  STD_LOGIC;    
	\sda/cout\: INOUT  STD_LOGIC);
end adau17621;
