// generated by newgenasym  Mon Dec 25 15:08:35 2023


module tps7a54 (bias, en, fb, gnd0, gnd1, gnd2, in0, in1, nrss, out0, out1, pg);
    input bias;
    input en;
    inout fb;
    input gnd0;
    input gnd1;
    input gnd2;
    input in0;
    input in1;
    input nrss;
    input out0;
    input out1;
    inout pg;


    initial
        begin
        end

endmodule
