-- generated by newgenasym Mon Dec 25 15:08:35 2023

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tps7a54 is
    port (    
	BIAS:      IN     STD_LOGIC;    
	EN:        IN     STD_LOGIC;    
	FB:        INOUT  STD_LOGIC;    
	GND0:      IN     STD_LOGIC;    
	GND1:      IN     STD_LOGIC;    
	GND2:      IN     STD_LOGIC;    
	IN0:       IN     STD_LOGIC;    
	IN1:       IN     STD_LOGIC;    
	NRSS:      IN     STD_LOGIC;    
	OUT0:      IN     STD_LOGIC;    
	OUT1:      IN     STD_LOGIC;    
	PG:        INOUT  STD_LOGIC);
end tps7a54;
