// generated by newgenasym  Mon Jan 06 11:48:40 2003


module \74ahc125  (\1a , \1oe* , \1y , \2a , \2oe* , \2y , \3a , \3oe* , \3y , \4a , \4oe* , \4y , gnd, vcc);
    input \1a ;
    input \4a ;
    input \1oe* ;
    input \4oe* ;
    input \2a ;
    input \3a ;
    input \2oe* ;
    output \1y ;
    output \4y ;
    output \2y ;
    output \3y ;
    output \3oe* ;
    inout gnd;
    inout vcc;


    initial
        begin
        end

endmodule
