-- generated by newgenasym Mon Jan 06 11:48:40 2003

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74ahc125\ is
    port (    
	\1a\:      IN     STD_LOGIC;    
	\1oe*\:    IN     STD_LOGIC;    
	\1y\:      OUT    STD_LOGIC;    
	\2a\:      IN     STD_LOGIC;    
	\2oe*\:    IN     STD_LOGIC;    
	\2y\:      OUT    STD_LOGIC;    
	\3a\:      IN     STD_LOGIC;    
	\3oe*\:    OUT    STD_LOGIC;    
	\3y\:      OUT    STD_LOGIC;    
	\4a\:      IN     STD_LOGIC;    
	\4oe*\:    IN     STD_LOGIC;    
	\4y\:      OUT    STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC);
end \74ahc125\;
