// generated by newgenasym  Tue Nov 14 16:38:38 2023


module nca9555 (a0, a1, a2, \int* , io0_0, io0_1, io0_2, io0_3, io0_4, io0_5,
        io0_6, io0_7, io1_0, io1_1, io1_2, io1_3, io1_4, io1_5, io1_6,
        io1_7, scl, sda, vdd, vss);
    inout a0;
    inout a1;
    inout a2;
    inout \int* ;
    inout io0_0;
    inout io0_1;
    inout io0_2;
    inout io0_3;
    inout io0_4;
    inout io0_5;
    inout io0_6;
    inout io0_7;
    inout io1_0;
    inout io1_1;
    inout io1_2;
    inout io1_3;
    inout io1_4;
    inout io1_5;
    inout io1_6;
    inout io1_7;
    inout scl;
    inout sda;
    inout vdd;
    inout vss;


    initial
        begin
        end

endmodule
