-- generated by newgenasym Tue Nov 14 16:38:38 2023

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity nca9555 is
    port (    
	A0:        INOUT  STD_LOGIC;    
	A1:        INOUT  STD_LOGIC;    
	A2:        INOUT  STD_LOGIC;    
	\int*\:    INOUT  STD_LOGIC;    
	IO0_0:     INOUT  STD_LOGIC;    
	IO0_1:     INOUT  STD_LOGIC;    
	IO0_2:     INOUT  STD_LOGIC;    
	IO0_3:     INOUT  STD_LOGIC;    
	IO0_4:     INOUT  STD_LOGIC;    
	IO0_5:     INOUT  STD_LOGIC;    
	IO0_6:     INOUT  STD_LOGIC;    
	IO0_7:     INOUT  STD_LOGIC;    
	IO1_0:     INOUT  STD_LOGIC;    
	IO1_1:     INOUT  STD_LOGIC;    
	IO1_2:     INOUT  STD_LOGIC;    
	IO1_3:     INOUT  STD_LOGIC;    
	IO1_4:     INOUT  STD_LOGIC;    
	IO1_5:     INOUT  STD_LOGIC;    
	IO1_6:     INOUT  STD_LOGIC;    
	IO1_7:     INOUT  STD_LOGIC;    
	SCL:       INOUT  STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC;    
	VDD:       INOUT  STD_LOGIC;    
	VSS:       INOUT  STD_LOGIC);
end nca9555;
