`timescale 1 ns/1 ps

module p5v (g );
// generated by Concept HDL Direct Version 05.10-p009 (Production) 06-Mar-98
// on Wed Jan 27 10:31:04 1999
// from adsl_lib/p5v/sch_1

  parameter size = 1;

  inout [size-1:0] g;
  // global signal glbl.p5v;



  `ifdef VAN

  wire [size-1:0] page1_g;
  wire  p5v;
  wire  page1_p5v;

  assign page1_g = g;
  assign p5v = glbl.p5v;
  assign page1_p5v = p5v;

  `endif


  `ifdef VAN

  assign g [size-1:0] = {};

  `else
  alias_vector alias_inst1 (g[size-1:0], {});
	  defparam alias_inst1.size = (1 + (SIZE-1) - (0));

  `endif

// begin instances 

endmodule // p5v(sch_1) 
