// generated by newgenasym  Wed Aug 27 18:10:33 2014


module micro_usb (\d+ , \d- , g, id, s1, s2, s3, s4, v);
    inout \d+ ;
    inout \d- ;
    inout g;
    inout id;
    inout s1;
    inout s2;
    inout s3;
    inout s4;
    inout v;


    initial
        begin
        end

endmodule
