-- generated by newgenasym Wed Aug 27 18:10:33 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity micro_usb is
    port (    
	\d+\:      INOUT  STD_LOGIC;    
	\d-\:      INOUT  STD_LOGIC;    
	G:         INOUT  STD_LOGIC;    
	ID:        INOUT  STD_LOGIC;    
	S1:        INOUT  STD_LOGIC;    
	S2:        INOUT  STD_LOGIC;    
	S3:        INOUT  STD_LOGIC;    
	S4:        INOUT  STD_LOGIC;    
	V:         INOUT  STD_LOGIC);
end micro_usb;
