-- generated by newgenasym Fri Apr 06 11:49:01 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tvs_diode is
    port (    
	\1\:       IN     STD_LOGIC;    
	\2\:       OUT    STD_LOGIC);
end tvs_diode;
