// generated by newgenasym  Tue Dec 13 13:34:26 2016


module \il-p3-b  (cr1, cr2, crlast, nc, os, pr, rst, tck, vbb, vdd, vhigh, vlow,
        vls, vod, vpr, vset, vss, vstor);
    inout [2:1] cr1;
    inout [2:1] cr2;
    inout crlast;
    inout [3:1] nc;
    inout os;
    inout pr;
    inout rst;
    inout [2:1] tck;
    inout vbb;
    inout vdd;
    inout vhigh;
    inout vlow;
    inout [2:1] vls;
    inout vod;
    inout vpr;
    inout vset;
    inout vss;
    inout vstor;


    initial
        begin
        end

endmodule
