-- generated by newgenasym Tue Dec 13 13:34:26 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \il-p3-b\ is
    port (    
	CR1:       INOUT  STD_LOGIC_VECTOR (2 DOWNTO 1);    
	CR2:       INOUT  STD_LOGIC_VECTOR (2 DOWNTO 1);    
	CRLAST:    INOUT  STD_LOGIC;    
	NC:        INOUT  STD_LOGIC_VECTOR (3 DOWNTO 1);    
	OS:        INOUT  STD_LOGIC;    
	PR:        INOUT  STD_LOGIC;    
	RST:       INOUT  STD_LOGIC;    
	TCK:       INOUT  STD_LOGIC_VECTOR (2 DOWNTO 1);    
	VBB:       INOUT  STD_LOGIC;    
	VDD:       INOUT  STD_LOGIC;    
	VHIGH:     INOUT  STD_LOGIC;    
	VLOW:      INOUT  STD_LOGIC;    
	VLS:       INOUT  STD_LOGIC_VECTOR (2 DOWNTO 1);    
	VOD:       INOUT  STD_LOGIC;    
	VPR:       INOUT  STD_LOGIC;    
	VSET:      INOUT  STD_LOGIC;    
	VSS:       INOUT  STD_LOGIC;    
	VSTOR:     INOUT  STD_LOGIC);
end \il-p3-b\;
