// generated by newgenasym  Tue Mar 26 15:44:07 2013


module mp3202 (en, fb, gnd, in, ov, sw);
    inout en;
    inout fb;
    inout gnd;
    inout in;
    inout ov;
    inout sw;


    initial
        begin
        end

endmodule
