-- generated by newgenasym Tue Mar 26 15:44:07 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mp3202 is
    port (    
	EN:        INOUT  STD_LOGIC;    
	FB:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	\in\:      INOUT  STD_LOGIC;    
	OV:        INOUT  STD_LOGIC;    
	SW:        INOUT  STD_LOGIC);
end mp3202;
