// generated by newgenasym  Thu May 25 18:14:03 2017


module ad9826 (adcclk, avdd, avss, capb, capt, cdsclk1, cdsclk2, cml, d0, d1,
        d2, d3, d4, d5, d6, d7, drvdd, drvss, oeb, offset, sclk, sdata,
        sload, vinb, ving, vinr);
    inout adcclk;
    input [2:1] avdd;
    input [2:1] avss;
    inout capb;
    inout capt;
    inout cdsclk1;
    inout cdsclk2;
    inout cml;
    inout d0;
    inout d1;
    inout d2;
    inout d3;
    inout d4;
    inout d5;
    inout d6;
    inout d7;
    inout drvdd;
    inout drvss;
    inout oeb;
    inout offset;
    inout sclk;
    inout sdata;
    inout sload;
    inout vinb;
    inout ving;
    inout vinr;


    initial
        begin
        end

endmodule
