-- generated by newgenasym Thu May 25 18:14:03 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad9826 is
    port (    
	ADCCLK:    INOUT  STD_LOGIC;    
	AVDD:      IN     STD_LOGIC_VECTOR (2 DOWNTO 1);    
	AVSS:      IN     STD_LOGIC_VECTOR (2 DOWNTO 1);    
	CAPB:      INOUT  STD_LOGIC;    
	CAPT:      INOUT  STD_LOGIC;    
	CDSCLK1:   INOUT  STD_LOGIC;    
	CDSCLK2:   INOUT  STD_LOGIC;    
	CML:       INOUT  STD_LOGIC;    
	D0:        INOUT  STD_LOGIC;    
	D1:        INOUT  STD_LOGIC;    
	D2:        INOUT  STD_LOGIC;    
	D3:        INOUT  STD_LOGIC;    
	D4:        INOUT  STD_LOGIC;    
	D5:        INOUT  STD_LOGIC;    
	D6:        INOUT  STD_LOGIC;    
	D7:        INOUT  STD_LOGIC;    
	DRVDD:     INOUT  STD_LOGIC;    
	DRVSS:     INOUT  STD_LOGIC;    
	OEB:       INOUT  STD_LOGIC;    
	OFFSET:    INOUT  STD_LOGIC;    
	SCLK:      INOUT  STD_LOGIC;    
	SDATA:     INOUT  STD_LOGIC;    
	SLOAD:     INOUT  STD_LOGIC;    
	VINB:      INOUT  STD_LOGIC;    
	VING:      INOUT  STD_LOGIC;    
	VINR:      INOUT  STD_LOGIC);
end ad9826;
