// generated by newgenasym  Thu Oct 13 11:15:16 2005


module \74lvc1g08  (a, b, gnd, vcc, y);
    input a;
    input b;
    input gnd;
    input vcc;
    output y;


    initial
        begin
        end

endmodule
