// generated by newgenasym  Wed Nov 20 19:22:36 2019


module ad8338 (agnd, comm, deto, fbkm, fbkp, gain, inmd, inmr, inpd, inpr,
        mode, ofsn, outm, outp, vagc, vbat, vref);
    inout agnd;
    inout comm;
    inout deto;
    inout fbkm;
    inout fbkp;
    inout gain;
    inout inmd;
    inout inmr;
    inout inpd;
    inout inpr;
    inout mode;
    inout ofsn;
    inout outm;
    inout outp;
    inout vagc;
    inout vbat;
    inout vref;


    initial
        begin
        end

endmodule
