-- generated by newgenasym Wed Nov 20 19:22:36 2019

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad8338 is
    port (    
	AGND:      INOUT  STD_LOGIC;    
	COMM:      INOUT  STD_LOGIC;    
	DETO:      INOUT  STD_LOGIC;    
	FBKM:      INOUT  STD_LOGIC;    
	FBKP:      INOUT  STD_LOGIC;    
	GAIN:      INOUT  STD_LOGIC;    
	INMD:      INOUT  STD_LOGIC;    
	INMR:      INOUT  STD_LOGIC;    
	INPD:      INOUT  STD_LOGIC;    
	INPR:      INOUT  STD_LOGIC;    
	MODE:      INOUT  STD_LOGIC;    
	OFSN:      INOUT  STD_LOGIC;    
	OUTM:      INOUT  STD_LOGIC;    
	OUTP:      INOUT  STD_LOGIC;    
	VAGC:      INOUT  STD_LOGIC;    
	VBAT:      INOUT  STD_LOGIC;    
	VREF:      INOUT  STD_LOGIC);
end ad8338;
