// generated by newgenasym  Sun May 27 15:59:59 2012


module tps61080 (en, fb, fsw, gnd, l, out, pgnd, ss, sw, thermal_pad, vin);
    input en;
    input fb;
    input fsw;
    input gnd;
    input l;
    output out;
    input pgnd;
    input ss;
    input sw;
    input thermal_pad;
    input vin;


    initial
        begin
        end

endmodule
