-- generated by newgenasym Sun May 27 15:59:59 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity TPS61080 is
    port (    
	EN:        IN     STD_LOGIC;    
	FB:        IN     STD_LOGIC;    
	FSW:       IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	L:         IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	PGND:      IN     STD_LOGIC;    
	SS:        IN     STD_LOGIC;    
	SW:        IN     STD_LOGIC;    
	THERMAL_PAD: IN     STD_LOGIC;    
	VIN:       IN     STD_LOGIC);
end TPS61080;
