-- generated by newgenasym Mon Apr 09 11:20:05 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity head2x8 is
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (16 DOWNTO 1));
end head2x8;
