// generated by newgenasym  Tue Nov 25 08:42:29 2025


module ams1117_1_8v (gnd, vin, vout, vout1);
    inout gnd;
    inout vin;
    inout vout;
    inout vout1;


    initial
        begin
        end

endmodule
