// generated by newgenasym  Sat Dec 31 14:09:41 2011


module head2x15 (a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20,
        a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a4, a5, a6,
        a7, a8, a9);
    inout a1;
    inout a10;
    inout a11;
    inout a12;
    inout a13;
    inout a14;
    inout a15;
    inout a16;
    inout a17;
    inout a18;
    inout a19;
    inout a2;
    inout a20;
    inout a21;
    inout a22;
    inout a23;
    inout a24;
    inout a25;
    inout a26;
    inout a27;
    inout a28;
    inout a29;
    inout a3;
    inout a30;
    inout a4;
    inout a5;
    inout a6;
    inout a7;
    inout a8;
    inout a9;


    initial
        begin
        end

endmodule
