// generated by newgenasym  Wed Feb 26 15:46:04 2014


module ov7620_pin (fodd, gnd, href, pclk, rst, scl, sda, vcc, vsync, vto, y0, y1,
        y2, y3, y4, y5, y6, y7);
    inout fodd;
    inout gnd;
    inout href;
    inout pclk;
    inout rst;
    inout scl;
    inout sda;
    inout vcc;
    inout vsync;
    inout vto;
    inout y0;
    inout y1;
    inout y2;
    inout y3;
    inout y4;
    inout y5;
    inout y6;
    inout y7;


    initial
        begin
        end

endmodule
