-- generated by newgenasym Wed Feb 26 15:46:04 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ov7620_pin is
    port (    
	FODD:      INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	HREF:      INOUT  STD_LOGIC;    
	PCLK:      INOUT  STD_LOGIC;    
	RST:       INOUT  STD_LOGIC;    
	SCL:       INOUT  STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC;    
	VSYNC:     INOUT  STD_LOGIC;    
	VTO:       INOUT  STD_LOGIC;    
	Y0:        INOUT  STD_LOGIC;    
	Y1:        INOUT  STD_LOGIC;    
	Y2:        INOUT  STD_LOGIC;    
	Y3:        INOUT  STD_LOGIC;    
	Y4:        INOUT  STD_LOGIC;    
	Y5:        INOUT  STD_LOGIC;    
	Y6:        INOUT  STD_LOGIC;    
	Y7:        INOUT  STD_LOGIC);
end ov7620_pin;
