// generated by newgenasym  Thu Jul 31 11:33:02 2008


module tps3808g09dbvr (ct, gnd, \mr# , \reset# , sense, vdd);
    input ct;
    input gnd;
    input \mr# ;
    output \reset# ;
    input sense;
    input vdd;


    initial
        begin
        end

endmodule
