-- generated by newgenasym Thu Jul 31 11:33:02 2008

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity TPS3808G09DBVR is
    port (    
	CT:        IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	\mr#\:     IN     STD_LOGIC;    
	\reset#\:  OUT    STD_LOGIC;    
	SENSE:     IN     STD_LOGIC;    
	VDD:       IN     STD_LOGIC);
end TPS3808G09DBVR;
