-- generated by newgenasym Sat Nov 29 16:14:54 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity rk09712200my is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC);
end rk09712200my;
