// generated by newgenasym  Mon Sep 03 09:22:57 2007


module hdmi_recp (cec, clk_sheild, d0_sheild, d1_sheild, d2_sheild, ddc_clk,
        ddc_data, gnd, hpd, nc, pwr_5v, \tmds_clk+ , \tmds_clk- ,
        \tmds_d0+ , \tmds_d0- , \tmds_d1+ , \tmds_d1- , \tmds_d2+ , \tmds_d2- );
    input cec;
    input clk_sheild;
    input d0_sheild;
    input d1_sheild;
    input d2_sheild;
    output ddc_clk;
    output ddc_data;
    input gnd;
    output hpd;
    inout nc;
    input pwr_5v;
    input \tmds_clk+ ;
    input \tmds_clk- ;
    input \tmds_d0+ ;
    input \tmds_d0- ;
    input \tmds_d1+ ;
    input \tmds_d1- ;
    input \tmds_d2+ ;
    input \tmds_d2- ;


    initial
        begin
        end

endmodule
