-- generated by newgenasym Mon Sep 03 09:22:57 2007

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity hdmi_recp is
    port (    
	CEC:       IN     STD_LOGIC;    
	CLK_SHEILD: IN     STD_LOGIC;    
	D0_SHEILD: IN     STD_LOGIC;    
	D1_SHEILD: IN     STD_LOGIC;    
	D2_SHEILD: IN     STD_LOGIC;    
	DDC_CLK:   OUT    STD_LOGIC;    
	DDC_DATA:  OUT    STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	HPD:       OUT    STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	PWR_5V:    IN     STD_LOGIC;    
	\tmds_clk+\: IN     STD_LOGIC;    
	\tmds_clk-\: IN     STD_LOGIC;    
	\tmds_d0+\: IN     STD_LOGIC;    
	\tmds_d0-\: IN     STD_LOGIC;    
	\tmds_d1+\: IN     STD_LOGIC;    
	\tmds_d1-\: IN     STD_LOGIC;    
	\tmds_d2+\: IN     STD_LOGIC;    
	\tmds_d2-\: IN     STD_LOGIC);
end hdmi_recp;
