// generated by newgenasym  Wed Dec 07 19:06:29 2016


module ad9945 (avdd, avss, ccdin, clpob, d0, d1, d10, d11, d2, d3, d4, d5, d6,
        d7, d8, d9, dataclk, drvdd, drvss, dvdd, dvss, nc, nc1, nc2, pad,
        pblk, refb, reft, sck, sdata, shd, shp, sl);
    inout avdd;
    inout avss;
    inout ccdin;
    inout clpob;
    inout d0;
    inout d1;
    inout d10;
    inout d11;
    inout d2;
    inout d3;
    inout d4;
    inout d5;
    inout d6;
    inout d7;
    inout d8;
    inout d9;
    inout dataclk;
    input drvdd;
    input drvss;
    input dvdd;
    inout dvss;
    inout nc;
    inout nc1;
    inout nc2;
    input pad;
    inout pblk;
    inout refb;
    inout reft;
    inout sck;
    inout sdata;
    inout shd;
    inout shp;
    inout sl;


    initial
        begin
        end

endmodule
