-- generated by newgenasym Wed Dec 07 19:06:29 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad9945 is
    port (    
	AVDD:      INOUT  STD_LOGIC;    
	AVSS:      INOUT  STD_LOGIC;    
	CCDIN:     INOUT  STD_LOGIC;    
	CLPOB:     INOUT  STD_LOGIC;    
	D0:        INOUT  STD_LOGIC;    
	D1:        INOUT  STD_LOGIC;    
	D10:       INOUT  STD_LOGIC;    
	D11:       INOUT  STD_LOGIC;    
	D2:        INOUT  STD_LOGIC;    
	D3:        INOUT  STD_LOGIC;    
	D4:        INOUT  STD_LOGIC;    
	D5:        INOUT  STD_LOGIC;    
	D6:        INOUT  STD_LOGIC;    
	D7:        INOUT  STD_LOGIC;    
	D8:        INOUT  STD_LOGIC;    
	D9:        INOUT  STD_LOGIC;    
	DATACLK:   INOUT  STD_LOGIC;    
	DRVDD:     IN     STD_LOGIC;    
	DRVSS:     IN     STD_LOGIC;    
	DVDD:      IN     STD_LOGIC;    
	DVSS:      INOUT  STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC;    
	NC2:       INOUT  STD_LOGIC;    
	PAD:       IN     STD_LOGIC;    
	PBLK:      INOUT  STD_LOGIC;    
	REFB:      INOUT  STD_LOGIC;    
	REFT:      INOUT  STD_LOGIC;    
	SCK:       INOUT  STD_LOGIC;    
	SDATA:     INOUT  STD_LOGIC;    
	SHD:       INOUT  STD_LOGIC;    
	SHP:       INOUT  STD_LOGIC;    
	SL:        INOUT  STD_LOGIC);
end ad9945;
