-- generated by newgenasym Thu Jun 05 18:17:12 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity swith is
    port (    
	\in\:      INOUT  STD_LOGIC;    
	OFF:       INOUT  STD_LOGIC;    
	\on\:      INOUT  STD_LOGIC);
end swith;
