-- generated by newgenasym Tue Jun 28 14:19:08 2005

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity resetkey is
    port (    
	A1:        IN     STD_LOGIC;    
	A2:        OUT    STD_LOGIC;    
	B1:        IN     STD_LOGIC;    
	B2:        OUT    STD_LOGIC);
end resetkey;
