// generated by newgenasym  Tue Sep 06 15:24:02 2016


module lsm303d (c1, cs, gnd1, gnd2, gnd3, gnd4, int1, int2, reserved, \scl/spc ,
        \sda/sdi/sdo , \sdo/sa0 , setc, setp, vdd, vdd_io);
    inout c1;
    inout cs;
    inout gnd1;
    inout gnd2;
    inout gnd3;
    inout gnd4;
    inout int1;
    inout int2;
    inout reserved;
    inout \scl/spc ;
    inout \sda/sdi/sdo ;
    inout \sdo/sa0 ;
    inout setc;
    inout setp;
    inout vdd;
    inout vdd_io;


    initial
        begin
        end

endmodule
