-- generated by newgenasym Tue Sep 06 15:24:02 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lsm303d is
    port (    
	C1:        INOUT  STD_LOGIC;    
	CS:        INOUT  STD_LOGIC;    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	GND3:      INOUT  STD_LOGIC;    
	GND4:      INOUT  STD_LOGIC;    
	INT1:      INOUT  STD_LOGIC;    
	INT2:      INOUT  STD_LOGIC;    
	RESERVED:  INOUT  STD_LOGIC;    
	\scl/spc\: INOUT  STD_LOGIC;    
	\sda/sdi/sdo\: INOUT  STD_LOGIC;    
	\sdo/sa0\: INOUT  STD_LOGIC;    
	SETC:      INOUT  STD_LOGIC;    
	SETP:      INOUT  STD_LOGIC;    
	VDD:       INOUT  STD_LOGIC;    
	VDD_IO:    INOUT  STD_LOGIC);
end lsm303d;
