// generated by newgenasym  Thu Dec 16 21:32:25 2010


module omap138_con (\5v , aclkr, aclkx, afsr, afsx, ahclkr, ahclkx, amute, axr15,
        axr7, clkout, clkr1, clks1, clkx1, \cs0* , \cs2* , \cs4* , \cs5* , dr1,
        dx1, ema_a0, ema_a1, ema_a10, ema_a11, ema_a12, ema_a13,
        ema_a14, ema_a15, ema_a16, ema_a17, ema_a18, ema_a19,
        ema_a2, ema_a20, ema_a21, ema_a22, ema_a23, ema_a3, ema_a4,
        ema_a5, ema_a6, ema_a7, ema_a8, ema_a9, ema_a_rw, ema_ba0,
        ema_ba1, \ema_cas* , ema_clk, ema_d0, ema_d1, ema_d10,
        ema_d11, ema_d12, ema_d13, ema_d14, ema_d15, ema_d2, ema_d3,
        ema_d4, ema_d5, ema_d6, ema_d7, ema_d8, ema_d9, \ema_dqm0* ,
        \ema_dqm1* , \ema_oe* , \ema_ras* , ema_sdcke, ema_wait0,
        ema_wait1, \ema_we* , fsr1, fsx1, gnd, gp6_12, gp6_13, gp8_10,
        i2c0_scl, i2c0_sda, lcd_d0, lcd_d1, lcd_d10, lcd_d11,
        lcd_d12, lcd_d13, lcd_d14, lcd_d15, lcd_d2, lcd_d3, lcd_d4,
        lcd_d5, lcd_d6, lcd_d7, lcd_d8, lcd_d9, \lcd_enb* , lcd_hsync,
        lcd_pclk, lcd_vsync, \ledl- , \ledr- , \nmi* , \resetout* , \rst* ,
        rtc_alarm, \rx+ , \rx- , sata_rxn, sata_rxp, sata_txn, sata_txp,
        spi1_clk, spi1_ena, \spi1_scs0* , \spi1_scs1* , spi1_simo,
        spi1_somi, \tx+ , \tx- , uart1_rxd, uart1_txd, uart2_rxd,
        uart2_txd, upp_ch0_clk, upp_ch0_enable, upp_ch0_start,
        upp_ch0_wait, upp_ch1_clk, upp_ch1_enable, upp_ch1_start,
        upp_ch1_wait, usb0_dm, usb0_dp, usb0_drvbus, usb0_id,
        usb0_vbus, usb1_dm, usb1_dp, vbat, vpif_clkin0,
        vpif_clkin1, vpif_clkin2, vpif_clkin3, vpif_clkout2,
        vpif_clkout3, vpif_d0, vpif_d1, vpif_d10, vpif_d11,
        vpif_d12, vpif_d13, vpif_d14, vpif_d15, vpif_d2, vpif_d3,
        vpif_d4, vpif_d5, vpif_d6, vpif_d7, vpif_d8, vpif_d9);
    input [6:1] \5v ;
    inout aclkr;
    input aclkx;
    inout afsr;
    inout afsx;
    inout ahclkr;
    inout ahclkx;
    inout amute;
    inout axr15;
    inout axr7;
    output clkout;
    input clkr1;
    input clks1;
    input clkx1;
    input \cs0* ;
    input \cs2* ;
    input \cs4* ;
    input \cs5* ;
    inout dr1;
    inout dx1;
    output ema_a0;
    output ema_a1;
    output ema_a10;
    output ema_a11;
    output ema_a12;
    output ema_a13;
    output ema_a14;
    output ema_a15;
    output ema_a16;
    output ema_a17;
    output ema_a18;
    output ema_a19;
    output ema_a2;
    output ema_a20;
    output ema_a21;
    output ema_a22;
    output ema_a23;
    output ema_a3;
    output ema_a4;
    output ema_a5;
    output ema_a6;
    output ema_a7;
    output ema_a8;
    output ema_a9;
    inout ema_a_rw;
    input ema_ba0;
    input ema_ba1;
    input \ema_cas* ;
    input ema_clk;
    inout ema_d0;
    inout ema_d1;
    inout ema_d10;
    inout ema_d11;
    inout ema_d12;
    inout ema_d13;
    inout ema_d14;
    inout ema_d15;
    inout ema_d2;
    inout ema_d3;
    inout ema_d4;
    inout ema_d5;
    inout ema_d6;
    inout ema_d7;
    inout ema_d8;
    inout ema_d9;
    input \ema_dqm0* ;
    input \ema_dqm1* ;
    input \ema_oe* ;
    input \ema_ras* ;
    inout ema_sdcke;
    input ema_wait0;
    input ema_wait1;
    input \ema_we* ;
    inout fsr1;
    inout fsx1;
    input [18:1] gnd;
    inout gp6_12;
    inout gp6_13;
    inout gp8_10;
    input i2c0_scl;
    inout i2c0_sda;
    inout lcd_d0;
    inout lcd_d1;
    inout lcd_d10;
    inout lcd_d11;
    inout lcd_d12;
    inout lcd_d13;
    inout lcd_d14;
    inout lcd_d15;
    inout lcd_d2;
    inout lcd_d3;
    inout lcd_d4;
    inout lcd_d5;
    inout lcd_d6;
    inout lcd_d7;
    inout lcd_d8;
    inout lcd_d9;
    input \lcd_enb* ;
    inout lcd_hsync;
    inout lcd_pclk;
    inout lcd_vsync;
    inout \ledl- ;
    inout \ledr- ;
    input \nmi* ;
    input \resetout* ;
    input \rst* ;
    inout rtc_alarm;
    input \rx+ ;
    input \rx- ;
    inout sata_rxn;
    inout sata_rxp;
    inout sata_txn;
    inout sata_txp;
    input spi1_clk;
    input spi1_ena;
    input \spi1_scs0* ;
    input \spi1_scs1* ;
    output spi1_simo;
    input spi1_somi;
    output \tx+ ;
    output \tx- ;
    input uart1_rxd;
    output uart1_txd;
    input uart2_rxd;
    output uart2_txd;
    input upp_ch0_clk;
    input upp_ch0_enable;
    input upp_ch0_start;
    inout upp_ch0_wait;
    input upp_ch1_clk;
    input upp_ch1_enable;
    input upp_ch1_start;
    input upp_ch1_wait;
    input usb0_dm;
    input usb0_dp;
    inout usb0_drvbus;
    inout usb0_id;
    input usb0_vbus;
    input usb1_dm;
    input usb1_dp;
    input [2:1] vbat;
    input vpif_clkin0;
    input vpif_clkin1;
    input vpif_clkin2;
    input vpif_clkin3;
    output vpif_clkout2;
    output vpif_clkout3;
    inout vpif_d0;
    inout vpif_d1;
    inout vpif_d10;
    inout vpif_d11;
    inout vpif_d12;
    inout vpif_d13;
    inout vpif_d14;
    inout vpif_d15;
    inout vpif_d2;
    inout vpif_d3;
    inout vpif_d4;
    inout vpif_d5;
    inout vpif_d6;
    inout vpif_d7;
    inout vpif_d8;
    inout vpif_d9;


    initial
        begin
        end

endmodule
