// generated by newgenasym  Sat Mar 27 09:57:19 2021


module w25q256 (clk, cs, \di(io0) , gnd, gndd, \hold(io3) , \so(io1) , vcc,
        \wp(io2) );
    inout clk;
    inout cs;
    inout \di(io0) ;
    inout gnd;
    inout gndd;
    inout \hold(io3) ;
    inout \so(io1) ;
    inout vcc;
    inout \wp(io2) ;


    initial
        begin
        end

endmodule
