-- generated by newgenasym Sat Mar 27 09:57:19 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity w25q256 is
    port (    
	CLK:       INOUT  STD_LOGIC;    
	CS:        INOUT  STD_LOGIC;    
	\di(io0)\: INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	GNDD:      INOUT  STD_LOGIC;    
	\hold(io3)\: INOUT  STD_LOGIC;    
	\so(io1)\: INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC;    
	\wp(io2)\: INOUT  STD_LOGIC);
end w25q256;
