// generated by newgenasym  Thu Sep 22 01:41:45 2016


module nuf2042xv6 (d1i, d1o, d2i, d2o, gnd, vbus);
    inout d1i;
    inout d1o;
    inout d2i;
    inout d2o;
    inout gnd;
    inout vbus;


    initial
        begin
        end

endmodule
