-- generated by newgenasym Thu Sep 22 01:41:45 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity nuf2042xv6 is
    port (    
	D1I:       INOUT  STD_LOGIC;    
	D1O:       INOUT  STD_LOGIC;    
	D2I:       INOUT  STD_LOGIC;    
	D2O:       INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	VBUS:      INOUT  STD_LOGIC);
end nuf2042xv6;
