// generated by newgenasym  Tue Sep 01 15:54:14 2009


module sn74lvc1t45 (a, b, dir, gnd, vcca, vccb);
    inout a;
    inout b;
    inout dir;
    inout gnd;
    inout vcca;
    inout vccb;


    initial
        begin
        end

endmodule
