-- generated by newgenasym Tue Sep 01 15:54:14 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sn74lvc1t45 is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC;    
	DIR:       INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	VCCA:      INOUT  STD_LOGIC;    
	VCCB:      INOUT  STD_LOGIC);
end sn74lvc1t45;
