// generated by newgenasym  Thu Nov 06 21:39:46 2014


module tusb1210 (cfg, clock, cpen, cs, data0, data1, data2, data3, data4,
        data5, data6, data7, dir, dm, dp, gnd1, id, \n/c , \n/c1 , \n/c2 ,
        \n/c3 , \n/c4 , nxt, refclk, resetn, stp, vbat, vbus, vdd15,
        vdd18_1, vdd18_2, vdd33, vddio);
    inout cfg;
    inout clock;
    inout cpen;
    inout cs;
    inout data0;
    inout data1;
    inout data2;
    inout data3;
    inout data4;
    inout data5;
    inout data6;
    inout data7;
    inout dir;
    inout dm;
    inout dp;
    inout gnd1;
    inout id;
    inout \n/c ;
    inout \n/c1 ;
    inout \n/c2 ;
    inout \n/c3 ;
    inout \n/c4 ;
    inout nxt;
    inout refclk;
    inout resetn;
    inout stp;
    inout vbat;
    inout vbus;
    inout vdd15;
    inout vdd18_1;
    inout vdd18_2;
    inout vdd33;
    inout vddio;


    initial
        begin
        end

endmodule
