-- generated by newgenasym Thu Nov 06 21:39:46 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tusb1210 is
    port (    
	CFG:       INOUT  STD_LOGIC;    
	CLOCK:     INOUT  STD_LOGIC;    
	CPEN:      INOUT  STD_LOGIC;    
	CS:        INOUT  STD_LOGIC;    
	DATA0:     INOUT  STD_LOGIC;    
	DATA1:     INOUT  STD_LOGIC;    
	DATA2:     INOUT  STD_LOGIC;    
	DATA3:     INOUT  STD_LOGIC;    
	DATA4:     INOUT  STD_LOGIC;    
	DATA5:     INOUT  STD_LOGIC;    
	DATA6:     INOUT  STD_LOGIC;    
	DATA7:     INOUT  STD_LOGIC;    
	DIR:       INOUT  STD_LOGIC;    
	DM:        INOUT  STD_LOGIC;    
	DP:        INOUT  STD_LOGIC;    
	GND1:      INOUT  STD_LOGIC;    
	ID:        INOUT  STD_LOGIC;    
	\n/c\:     INOUT  STD_LOGIC;    
	\n/c1\:    INOUT  STD_LOGIC;    
	\n/c2\:    INOUT  STD_LOGIC;    
	\n/c3\:    INOUT  STD_LOGIC;    
	\n/c4\:    INOUT  STD_LOGIC;    
	NXT:       INOUT  STD_LOGIC;    
	REFCLK:    INOUT  STD_LOGIC;    
	RESETN:    INOUT  STD_LOGIC;    
	STP:       INOUT  STD_LOGIC;    
	VBAT:      INOUT  STD_LOGIC;    
	VBUS:      INOUT  STD_LOGIC;    
	VDD15:     INOUT  STD_LOGIC;    
	VDD18_1:   INOUT  STD_LOGIC;    
	VDD18_2:   INOUT  STD_LOGIC;    
	VDD33:     INOUT  STD_LOGIC;    
	VDDIO:     INOUT  STD_LOGIC);
end tusb1210;
