// generated by newgenasym  Mon Jan 09 16:59:32 2006


module \74lvc374  (clk, d, gnd, \oe* , q, vcc);
    input clk;
    input [8:1] d;
    input gnd;
    input \oe* ;
    output [8:1] q;
    input vcc;


    initial
        begin
        end

endmodule
