-- generated by newgenasym Mon Jan 09 16:59:32 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74lvc374\ is
    port (    
	CLK:       IN     STD_LOGIC;    
	D:         IN     STD_LOGIC_VECTOR (8 DOWNTO 1);    
	GND:       IN     STD_LOGIC;    
	\oe*\:     IN     STD_LOGIC;    
	Q:         OUT    STD_LOGIC_VECTOR (8 DOWNTO 1);    
	VCC:       IN     STD_LOGIC);
end \74lvc374\;
