// generated by newgenasym  Tue Apr 11 15:44:01 2017


module idt49fct805apyg (gnda, gndb, ina, inb, mon, nc, oa1, oa2, oa3, oa4, oa5, ob1, ob2,
        ob3, ob4, ob5, \oea* , \oeb* , vcc, vcca);
    input gnda;
    input gndb;
    inout ina;
    inout inb;
    inout mon;
    inout nc;
    inout oa1;
    inout oa2;
    inout oa3;
    inout oa4;
    inout oa5;
    inout ob1;
    inout ob2;
    inout ob3;
    inout ob4;
    inout ob5;
    inout \oea* ;
    inout \oeb* ;
    input vcc;
    input vcca;


    initial
        begin
        end

endmodule
