-- generated by newgenasym Tue Apr 11 15:44:01 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity idt49fct805apyg is
    port (    
	GNDA:      IN     STD_LOGIC;    
	GNDB:      IN     STD_LOGIC;    
	INA:       INOUT  STD_LOGIC;    
	INB:       INOUT  STD_LOGIC;    
	MON:       INOUT  STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	OA1:       INOUT  STD_LOGIC;    
	OA2:       INOUT  STD_LOGIC;    
	OA3:       INOUT  STD_LOGIC;    
	OA4:       INOUT  STD_LOGIC;    
	OA5:       INOUT  STD_LOGIC;    
	OB1:       INOUT  STD_LOGIC;    
	OB2:       INOUT  STD_LOGIC;    
	OB3:       INOUT  STD_LOGIC;    
	OB4:       INOUT  STD_LOGIC;    
	OB5:       INOUT  STD_LOGIC;    
	\oea*\:    INOUT  STD_LOGIC;    
	\oeb*\:    INOUT  STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	VCCA:      IN     STD_LOGIC);
end idt49fct805apyg;
