// generated by newgenasym  Sat Jun 18 16:44:51 2005


module \74hc4316  (\1ctl , \1i/o , \1o/i , \2ctl , \2i/o , \2o/i , \3ctl , \3i/o , \3o/i , \4ctl ,
        \4i/o , \4o/i , \en* , gnd, vcc, vee);
    input \1ctl ;
    inout \1i/o ;
    inout \1o/i ;
    input \2ctl ;
    inout \2i/o ;
    inout \2o/i ;
    input \3ctl ;
    inout \3i/o ;
    inout \3o/i ;
    input \4ctl ;
    inout \4i/o ;
    inout \4o/i ;
    input \en* ;
    input gnd;
    input vcc;
    input vee;


    initial
        begin
        end

endmodule
