-- generated by newgenasym Sat Jun 18 16:44:51 2005

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74hc4316\ is
    port (    
	\1ctl\:    IN     STD_LOGIC;    
	\1i/o\:    INOUT  STD_LOGIC;    
	\1o/i\:    INOUT  STD_LOGIC;    
	\2ctl\:    IN     STD_LOGIC;    
	\2i/o\:    INOUT  STD_LOGIC;    
	\2o/i\:    INOUT  STD_LOGIC;    
	\3ctl\:    IN     STD_LOGIC;    
	\3i/o\:    INOUT  STD_LOGIC;    
	\3o/i\:    INOUT  STD_LOGIC;    
	\4ctl\:    IN     STD_LOGIC;    
	\4i/o\:    INOUT  STD_LOGIC;    
	\4o/i\:    INOUT  STD_LOGIC;    
	\en*\:     IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	VEE:       IN     STD_LOGIC);
end \74hc4316\;
