// generated by newgenasym  Mon Jun 03 09:40:15 2013


module tps22929 (gnd1, gnd2, on, vin1, vin2, vout);
    inout gnd1;
    inout gnd2;
    inout on;
    inout vin1;
    inout vin2;
    inout vout;


    initial
        begin
        end

endmodule
