-- generated by newgenasym Mon Jun 03 09:40:15 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity TPS22929 is
    port (    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	\on\:      INOUT  STD_LOGIC;    
	VIN1:      INOUT  STD_LOGIC;    
	VIN2:      INOUT  STD_LOGIC;    
	VOUT:      INOUT  STD_LOGIC);
end TPS22929;
