// generated by newgenasym  Wed Apr 10 22:26:26 2013


module ad7683 (\cs* , dclock, dout, gnd, \in+ , \in- , ref, vdd);
    inout \cs* ;
    inout dclock;
    inout dout;
    inout gnd;
    inout \in+ ;
    inout \in- ;
    inout ref;
    inout vdd;


    initial
        begin
        end

endmodule
