-- generated by newgenasym Wed Apr 10 22:26:26 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad7683 is
    port (    
	\cs*\:     INOUT  STD_LOGIC;    
	DCLOCK:    INOUT  STD_LOGIC;    
	DOUT:      INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	\in+\:     INOUT  STD_LOGIC;    
	\in-\:     INOUT  STD_LOGIC;    
	REF:       INOUT  STD_LOGIC;    
	VDD:       INOUT  STD_LOGIC);
end ad7683;
