// generated by newgenasym  Fri Dec 07 10:21:07 2012


module hy5ps121621bfp (a0, a1, a10, a11, a12, a2, a3, a4, a5, a6, a7, a8, a9, ba0, ba1,
        ba2, \cas* , ck, \ck* , cke, \cs* , dq0, dq1, dq10, dq11, dq12, dq13,
        dq14, dq15, dq2, dq3, dq4, dq5, dq6, dq7, dq8, dq9, ldm, ldqs,
        \ldqs* , odt, \ras* , udm, udqs, \udqs* , vdd, vddl, vddq, vref, vss,
        vssdl, vssq, \we* );
    input a0;
    input a1;
    input a10;
    input a11;
    input a12;
    input a2;
    input a3;
    input a4;
    input a5;
    input a6;
    input a7;
    input a8;
    input a9;
    input ba0;
    input ba1;
    input ba2;
    input \cas* ;
    input ck;
    input \ck* ;
    input cke;
    input \cs* ;
    inout dq0;
    inout dq1;
    inout dq10;
    inout dq11;
    inout dq12;
    inout dq13;
    inout dq14;
    inout dq15;
    inout dq2;
    inout dq3;
    inout dq4;
    inout dq5;
    inout dq6;
    inout dq7;
    inout dq8;
    inout dq9;
    input ldm;
    inout ldqs;
    inout \ldqs* ;
    input odt;
    input \ras* ;
    input udm;
    inout udqs;
    inout \udqs* ;
    input [4:0] vdd;
    input vddl;
    input [9:0] vddq;
    input vref;
    input [4:0] vss;
    input vssdl;
    input [9:0] vssq;
    input \we* ;


    initial
        begin
        end

endmodule
