// generated by newgenasym  Thu Sep 08 17:54:06 2016


module tca62724fmg (gnd, out0, out1, out2, reset, rext, scl, sda, shdn, vin);
    inout gnd;
    inout out0;
    inout out1;
    inout out2;
    inout reset;
    inout rext;
    inout scl;
    inout sda;
    inout shdn;
    inout vin;


    initial
        begin
        end

endmodule
