-- generated by newgenasym Thu Sep 08 17:54:06 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tca62724fmg is
    port (    
	GND:       INOUT  STD_LOGIC;    
	OUT0:      INOUT  STD_LOGIC;    
	OUT1:      INOUT  STD_LOGIC;    
	OUT2:      INOUT  STD_LOGIC;    
	RESET:     INOUT  STD_LOGIC;    
	REXT:      INOUT  STD_LOGIC;    
	SCL:       INOUT  STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC;    
	SHDN:      INOUT  STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC);
end tca62724fmg;
