// generated by newgenasym  Sun Jun 14 17:24:12 2020


module head1x4 (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
