-- generated by newgenasym Sun Jun 14 17:24:12 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity head1x4 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC);
end head1x4;
