// generated by newgenasym  Mon Mar 03 19:18:20 2014


module w25q128bvsfig (clk, \cs* , \di/io0 , \do/io1 , gnd, \hold#/io3 , nc1, nc2, nc3, nc4,
        nc5, nc6, nc7, nc8, vcc, \wp#/io2 );
    input clk;
    input \cs* ;
    inout \di/io0 ;
    inout \do/io1 ;
    input gnd;
    inout \hold#/io3 ;
    inout nc1;
    inout nc2;
    inout nc3;
    inout nc4;
    inout nc5;
    inout nc6;
    inout nc7;
    inout nc8;
    input vcc;
    inout \wp#/io2 ;


    initial
        begin
        end

endmodule
