-- generated by newgenasym Mon Mar 03 19:18:20 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity w25q128bvsfig is
    port (    
	CLK:       IN     STD_LOGIC;    
	\cs*\:     IN     STD_LOGIC;    
	\di/io0\:  INOUT  STD_LOGIC;    
	\do/io1\:  INOUT  STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	\hold#/io3\: INOUT  STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC;    
	NC2:       INOUT  STD_LOGIC;    
	NC3:       INOUT  STD_LOGIC;    
	NC4:       INOUT  STD_LOGIC;    
	NC5:       INOUT  STD_LOGIC;    
	NC6:       INOUT  STD_LOGIC;    
	NC7:       INOUT  STD_LOGIC;    
	NC8:       INOUT  STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	\wp#/io2\: INOUT  STD_LOGIC);
end w25q128bvsfig;
