// generated by newgenasym  Tue Dec 20 15:06:51 2016


module lmc7101 (\input+ , \input- , \output , \v+ , \v- );
    inout \input+ ;
    inout \input- ;
    inout \output ;
    inout \v+ ;
    inout \v- ;


    initial
        begin
        end

endmodule
