-- generated by newgenasym Tue Dec 20 15:06:51 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lmc7101 is
    port (    
	\input+\:  INOUT  STD_LOGIC;    
	\input-\:  INOUT  STD_LOGIC;    
	OUTPUT:    INOUT  STD_LOGIC;    
	\v+\:      INOUT  STD_LOGIC;    
	\v-\:      INOUT  STD_LOGIC);
end lmc7101;
