-- generated by newgenasym Thu May 29 19:51:17 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lsf0108 is
    port (    
	A1:        INOUT  STD_LOGIC;    
	A2:        INOUT  STD_LOGIC;    
	A3:        INOUT  STD_LOGIC;    
	A4:        INOUT  STD_LOGIC;    
	A5:        INOUT  STD_LOGIC;    
	A6:        INOUT  STD_LOGIC;    
	A7:        INOUT  STD_LOGIC;    
	A8:        INOUT  STD_LOGIC;    
	B1:        INOUT  STD_LOGIC;    
	B2:        INOUT  STD_LOGIC;    
	B3:        INOUT  STD_LOGIC;    
	B4:        INOUT  STD_LOGIC;    
	B5:        INOUT  STD_LOGIC;    
	B6:        INOUT  STD_LOGIC;    
	B7:        INOUT  STD_LOGIC;    
	B8:        INOUT  STD_LOGIC;    
	EN:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	VREF_A:    INOUT  STD_LOGIC;    
	VREF_B:    INOUT  STD_LOGIC);
end lsf0108;
