// generated by newgenasym  Thu Nov 10 16:44:25 2016


module lp5907 (en, gnd, in, \n/c , out);
    inout en;
    inout gnd;
    inout in;
    inout \n/c ;
    inout out;


    initial
        begin
        end

endmodule
