-- generated by newgenasym Thu Nov 10 16:44:25 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lp5907 is
    port (    
	EN:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	\in\:      INOUT  STD_LOGIC;    
	\n/c\:     INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC);
end lp5907;
