// generated by newgenasym  Sun Jan 20 14:57:49 2008


module tps5430 (boot, ena, gnd, nc1, nc2, ph, powerpad, vin, vsense);
    inout boot;
    inout ena;
    inout gnd;
    inout nc1;
    inout nc2;
    inout ph;
    inout powerpad;
    inout vin;
    inout vsense;


    initial
        begin
        end

endmodule
