-- generated by newgenasym Sun Jan 20 14:57:49 2008

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tps5430 is
    port (    
	BOOT:      INOUT  STD_LOGIC;    
	ENA:       INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC;    
	NC2:       INOUT  STD_LOGIC;    
	PH:        INOUT  STD_LOGIC;    
	POWERPAD:  INOUT  STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC;    
	VSENSE:    INOUT  STD_LOGIC);
end tps5430;
