// generated by newgenasym  Wed May 07 14:14:21 2014


module sn74lvc1t45 (a, b, dir, gnd, vcca, vccb);
    inout a;
    inout b;
    inout dir;
    inout gnd;
    inout vcca;
    inout vccb;


    initial
        begin
        end

endmodule
