// generated by newgenasym  Mon Oct 24 09:34:01 2011


module b3fs_1012 (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
