-- generated by newgenasym Mon Oct 24 09:34:01 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity b3fs_1012 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC);
end b3fs_1012;
