// generated by newgenasym  Wed Mar 16 12:55:52 2011


module \5pin  (pin1, pin2, pin3, pin4, pin5);
    inout pin1;
    inout pin2;
    inout pin3;
    inout pin4;
    inout pin5;


    initial
        begin
        end

endmodule
