-- generated by newgenasym Wed Mar 16 12:55:52 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \5pin\ is
    port (    
	PIN1:      INOUT  STD_LOGIC;    
	PIN2:      INOUT  STD_LOGIC;    
	PIN3:      INOUT  STD_LOGIC;    
	PIN4:      INOUT  STD_LOGIC;    
	PIN5:      INOUT  STD_LOGIC);
end \5pin\;
