// generated by newgenasym  Thu Mar 09 16:05:17 2023


module tmuxhs4212 (a0n, a0p, a1n, a1p, b0n, b0p, b1n, b1p, c0n, c0p, c1n, c1p,
        gnd_1, gnd_2, gnd_3, oen, rsvd1, rsvd2, sel, sink, vcc1);
    inout a0n;
    inout a0p;
    inout a1n;
    inout a1p;
    inout b0n;
    inout b0p;
    inout b1n;
    inout b1p;
    inout c0n;
    inout c0p;
    inout c1n;
    inout c1p;
    inout gnd_1;
    inout gnd_2;
    inout gnd_3;
    inout oen;
    inout rsvd1;
    inout rsvd2;
    inout sel;
    inout sink;
    inout vcc1;


    initial
        begin
        end

endmodule
