-- generated by newgenasym Thu Mar 09 16:05:17 2023

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tmuxhs4212 is
    port (    
	A0N:       INOUT  STD_LOGIC;    
	A0P:       INOUT  STD_LOGIC;    
	A1N:       INOUT  STD_LOGIC;    
	A1P:       INOUT  STD_LOGIC;    
	B0N:       INOUT  STD_LOGIC;    
	B0P:       INOUT  STD_LOGIC;    
	B1N:       INOUT  STD_LOGIC;    
	B1P:       INOUT  STD_LOGIC;    
	C0N:       INOUT  STD_LOGIC;    
	C0P:       INOUT  STD_LOGIC;    
	C1N:       INOUT  STD_LOGIC;    
	C1P:       INOUT  STD_LOGIC;    
	GND_1:     INOUT  STD_LOGIC;    
	GND_2:     INOUT  STD_LOGIC;    
	GND_3:     INOUT  STD_LOGIC;    
	OEN:       INOUT  STD_LOGIC;    
	RSVD1:     INOUT  STD_LOGIC;    
	RSVD2:     INOUT  STD_LOGIC;    
	SEL:       INOUT  STD_LOGIC;    
	SINK:      INOUT  STD_LOGIC;    
	VCC1:      INOUT  STD_LOGIC);
end tmuxhs4212;
