// generated by newgenasym  Thu Sep 27 10:32:51 2012


module \mt47h32m16hr-37e  (a0, a1, a10, a11, a12, a2, a3, a4, a5, a6, a7, a8, a9, ba0, ba1,
        \cas# , ck, \ck# , cke, \cs# , dq0, dq1, dq10, dq11, dq12, dq13, dq14,
        dq15, dq2, dq3, dq4, dq5, dq6, dq7, dq8, dq9, ldm, ldqs,
        \ldqs#/nu , nc_a2, nc_e2, odt, \ras# , rfu_l1, rfu_r3, rfu_r7,
        rfu_r8, udm, udqs, \udqs#/nu , vdd_a1, vdd_e1, vdd_j9, vdd_m9,
        vdd_r1, vddl_j1, vddq_a9, vddq_c1, vddq_c3, vddq_c7,
        vddq_c9, vddq_e9, vddq_g1, vddq_g3, vddq_g7, vddq_g9,
        vref_j2, vss_a3, vss_e3, vss_j3, vss_n1, vss_p9, vssdl_j7,
        vssq_a7, vssq_b2, vssq_b8, vssq_d2, vssq_d8, vssq_e7,
        vssq_f2, vssq_f8, vssq_h2, vssq_h8, \we# );
    input a0;
    input a1;
    input a10;
    input a11;
    input a12;
    input a2;
    input a3;
    input a4;
    input a5;
    input a6;
    input a7;
    input a8;
    input a9;
    input ba0;
    input ba1;
    input \cas# ;
    input ck;
    input \ck# ;
    input cke;
    input \cs# ;
    inout dq0;
    inout dq1;
    inout dq10;
    inout dq11;
    inout dq12;
    inout dq13;
    inout dq14;
    inout dq15;
    inout dq2;
    inout dq3;
    inout dq4;
    inout dq5;
    inout dq6;
    inout dq7;
    inout dq8;
    inout dq9;
    input ldm;
    inout ldqs;
    inout \ldqs#/nu ;
    input nc_a2;
    input nc_e2;
    input odt;
    input \ras# ;
    input rfu_l1;
    input rfu_r3;
    input rfu_r7;
    input rfu_r8;
    input udm;
    inout udqs;
    inout \udqs#/nu ;
    input vdd_a1;
    input vdd_e1;
    input vdd_j9;
    input vdd_m9;
    input vdd_r1;
    input vddl_j1;
    input vddq_a9;
    input vddq_c1;
    input vddq_c3;
    input vddq_c7;
    input vddq_c9;
    input vddq_e9;
    input vddq_g1;
    input vddq_g3;
    input vddq_g7;
    input vddq_g9;
    input vref_j2;
    input vss_a3;
    input vss_e3;
    input vss_j3;
    input vss_n1;
    input vss_p9;
    input vssdl_j7;
    input vssq_a7;
    input vssq_b2;
    input vssq_b8;
    input vssq_d2;
    input vssq_d8;
    input vssq_e7;
    input vssq_f2;
    input vssq_f8;
    input vssq_h2;
    input vssq_h8;
    input \we# ;


    initial
        begin
        end

endmodule
