// generated by newgenasym  Thu Jan 19 14:39:28 2012


module opa2211 (ex, \in+ , \in- , out, \v+ , \v- );
    input ex;
    input \in+ ;
    input \in- ;
    output out;
    input \v+ ;
    input \v- ;


    initial
        begin
        end

endmodule
