-- generated by newgenasym Thu Jan 19 14:39:28 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity opa2211 is
    port (    
	EX:        IN     STD_LOGIC;    
	\in+\:     IN     STD_LOGIC;    
	\in-\:     IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC;    
	\v+\:      IN     STD_LOGIC;    
	\v-\:      IN     STD_LOGIC);
end opa2211;
