// generated by newgenasym  Thu Mar 29 14:14:30 2018


module \rj45-jk-jxk  (\21 , \22 , \23 , \24 , ledg, \ledg+ , \ledg- , ledy, \md1+ , \md1- , \md2+ ,
        \md2- , \md3+ , \md3- , \md4+ , \md4- , mdct1, mdct2, mdct3, mdct4,
        \vdc1+ , \vdc1- , \vdc2+ , \vdc2- );
    inout \21 ;
    inout \22 ;
    inout \23 ;
    inout \24 ;
    inout ledg;
    inout \ledg+ ;
    inout \ledg- ;
    inout ledy;
    inout \md1+ ;
    inout \md1- ;
    inout \md2+ ;
    inout \md2- ;
    inout \md3+ ;
    inout \md3- ;
    inout \md4+ ;
    inout \md4- ;
    inout mdct1;
    inout mdct2;
    inout mdct3;
    inout mdct4;
    inout \vdc1+ ;
    inout \vdc1- ;
    inout \vdc2+ ;
    inout \vdc2- ;


    initial
        begin
        end

endmodule
