-- generated by newgenasym Thu Mar 29 14:14:30 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \rj45-jk-jxk\ is
    port (    
	\21\:      INOUT  STD_LOGIC;    
	\22\:      INOUT  STD_LOGIC;    
	\23\:      INOUT  STD_LOGIC;    
	\24\:      INOUT  STD_LOGIC;    
	LEDG:      INOUT  STD_LOGIC;    
	\ledg+\:   INOUT  STD_LOGIC;    
	\ledg-\:   INOUT  STD_LOGIC;    
	LEDY:      INOUT  STD_LOGIC;    
	\md1+\:    INOUT  STD_LOGIC;    
	\md1-\:    INOUT  STD_LOGIC;    
	\md2+\:    INOUT  STD_LOGIC;    
	\md2-\:    INOUT  STD_LOGIC;    
	\md3+\:    INOUT  STD_LOGIC;    
	\md3-\:    INOUT  STD_LOGIC;    
	\md4+\:    INOUT  STD_LOGIC;    
	\md4-\:    INOUT  STD_LOGIC;    
	MDCT1:     INOUT  STD_LOGIC;    
	MDCT2:     INOUT  STD_LOGIC;    
	MDCT3:     INOUT  STD_LOGIC;    
	MDCT4:     INOUT  STD_LOGIC;    
	\vdc1+\:   INOUT  STD_LOGIC;    
	\vdc1-\:   INOUT  STD_LOGIC;    
	\vdc2+\:   INOUT  STD_LOGIC;    
	\vdc2-\:   INOUT  STD_LOGIC);
end \rj45-jk-jxk\;
