// generated by newgenasym  Wed Dec 14 12:12:27 2016


module ds90lv048a (en, \en* , gnd, \rin1+ , \rin1- , \rin2+ , \rin2- , \rin3+ , \rin3- , \rin4+ ,
        \rin4- , rout1, rout2, rout3, rout4, vcc);
    inout en;
    inout \en* ;
    inout gnd;
    inout \rin1+ ;
    inout \rin1- ;
    inout \rin2+ ;
    inout \rin2- ;
    inout \rin3+ ;
    inout \rin3- ;
    inout \rin4+ ;
    inout \rin4- ;
    inout rout1;
    inout rout2;
    inout rout3;
    inout rout4;
    inout vcc;


    initial
        begin
        end

endmodule
