-- generated by newgenasym Wed Dec 14 12:12:27 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ds90lv048a is
    port (    
	EN:        INOUT  STD_LOGIC;    
	\en*\:     INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	\rin1+\:   INOUT  STD_LOGIC;    
	\rin1-\:   INOUT  STD_LOGIC;    
	\rin2+\:   INOUT  STD_LOGIC;    
	\rin2-\:   INOUT  STD_LOGIC;    
	\rin3+\:   INOUT  STD_LOGIC;    
	\rin3-\:   INOUT  STD_LOGIC;    
	\rin4+\:   INOUT  STD_LOGIC;    
	\rin4-\:   INOUT  STD_LOGIC;    
	ROUT1:     INOUT  STD_LOGIC;    
	ROUT2:     INOUT  STD_LOGIC;    
	ROUT3:     INOUT  STD_LOGIC;    
	ROUT4:     INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC);
end ds90lv048a;
