-- generated by newgenasym Mon Nov 24 10:41:00 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \at24c64d-sshm-t\ is
    port (    
	A0:        INOUT  STD_LOGIC;    
	A1:        INOUT  STD_LOGIC;    
	A2:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	SCL:       INOUT  STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC;    
	WP:        INOUT  STD_LOGIC);
end \at24c64d-sshm-t\;
