// generated by newgenasym  Thu Oct 30 14:52:04 2014


module tpa6204a1drbr (bypass, ep, gnd, \in+ , \in- , \shouendown* , vcc, \vo+ , \vo- );
    inout bypass;
    input ep;
    input gnd;
    inout \in+ ;
    inout \in- ;
    input \shouendown* ;
    input vcc;
    output \vo+ ;
    output \vo- ;


    initial
        begin
        end

endmodule
