-- generated by newgenasym Thu Oct 30 14:52:04 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tpa6204a1drbr is
    port (    
	BYPASS:    INOUT  STD_LOGIC;    
	EP:        IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	\in+\:     INOUT  STD_LOGIC;    
	\in-\:     INOUT  STD_LOGIC;    
	\shouendown*\: IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	\vo+\:     OUT    STD_LOGIC;    
	\vo-\:     OUT    STD_LOGIC);
end tpa6204a1drbr;
