// generated by newgenasym  Tue Feb 26 12:56:44 2013


module \xrp6272idbtr-f  (adj, bp, en, ep, gnd1, gnd2, pgood, vin, vout);
    input adj;
    inout bp;
    input en;
    input ep;
    input gnd1;
    input gnd2;
    output pgood;
    input vin;
    input vout;


    initial
        begin
        end

endmodule
