-- generated by newgenasym Tue Feb 26 12:56:44 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \xrp6272idbtr-f\ is
    port (    
	ADJ:       IN     STD_LOGIC;    
	BP:        INOUT  STD_LOGIC;    
	EN:        IN     STD_LOGIC;    
	EP:        IN     STD_LOGIC;    
	GND1:      IN     STD_LOGIC;    
	GND2:      IN     STD_LOGIC;    
	PGOOD:     OUT    STD_LOGIC;    
	VIN:       IN     STD_LOGIC;    
	VOUT:      IN     STD_LOGIC);
end \xrp6272idbtr-f\;
