-- generated by newgenasym Tue Nov 28 16:29:48 2023

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity diode is
    port (    
	A:         INOUT  STD_LOGIC;    
	K:         INOUT  STD_LOGIC);
end diode;
