// generated by newgenasym  Wed May 24 21:04:19 2017


module \s11156-2048-02  (ard, arg, ig1h, ig2h, ish, nc1, nc2, nc3, od, og, os, p1h, p2h,
        rd, rd2, regh, regl, rg, sg, ss, stg1, stg2, tg, vret);
    inout ard;
    inout arg;
    inout ig1h;
    inout ig2h;
    inout ish;
    inout nc1;
    inout nc2;
    inout nc3;
    inout od;
    inout og;
    inout os;
    inout p1h;
    inout p2h;
    inout rd;
    inout rd2;
    inout regh;
    inout regl;
    inout rg;
    inout sg;
    inout ss;
    inout stg1;
    inout stg2;
    inout tg;
    inout vret;


    initial
        begin
        end

endmodule
