-- generated by newgenasym Wed May 24 21:04:19 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \s11156-2048-02\ is
    port (    
	ARD:       INOUT  STD_LOGIC;    
	ARG:       INOUT  STD_LOGIC;    
	IG1H:      INOUT  STD_LOGIC;    
	IG2H:      INOUT  STD_LOGIC;    
	ISH:       INOUT  STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC;    
	NC2:       INOUT  STD_LOGIC;    
	NC3:       INOUT  STD_LOGIC;    
	OD:        INOUT  STD_LOGIC;    
	OG:        INOUT  STD_LOGIC;    
	OS:        INOUT  STD_LOGIC;    
	P1H:       INOUT  STD_LOGIC;    
	P2H:       INOUT  STD_LOGIC;    
	RD:        INOUT  STD_LOGIC;    
	RD2:       INOUT  STD_LOGIC;    
	REGH:      INOUT  STD_LOGIC;    
	REGL:      INOUT  STD_LOGIC;    
	RG:        INOUT  STD_LOGIC;    
	SG:        INOUT  STD_LOGIC;    
	SS:        INOUT  STD_LOGIC;    
	STG1:      INOUT  STD_LOGIC;    
	STG2:      INOUT  STD_LOGIC;    
	TG:        INOUT  STD_LOGIC;    
	VRET:      INOUT  STD_LOGIC);
end \s11156-2048-02\;
