// generated by newgenasym  Mon Jan 09 16:51:00 2006


module \74lvc16244  (\1a1 , \1a2 , \1a3 , \1a4 , \1oe* , \1y1 , \1y2 , \1y3 , \1y4 , \2a1 , \2a2 , \2a3 , \2a4 ,
        \2oe* , \2y1 , \2y2 , \2y3 , \2y4 , \3a1 , \3a2 , \3a3 , \3a4 , \3oe* , \3y1 , \3y2 , \3y3 ,
        \3y4 , \4a1 , \4a2 , \4a3 , \4a4 , \4oe* , \4y1 , \4y2 , \4y3 , \4y4 , gnd, vcc);
    input \1a1 ;
    input \1a2 ;
    input \1a3 ;
    input \1a4 ;
    input \1oe* ;
    input \1y1 ;
    output \1y2 ;
    output \1y3 ;
    output \1y4 ;
    input \2a1 ;
    input \2a2 ;
    input \2a3 ;
    input \2a4 ;
    input \2oe* ;
    output \2y1 ;
    output \2y2 ;
    output \2y3 ;
    output \2y4 ;
    input \3a1 ;
    input \3a2 ;
    input \3a3 ;
    input \3a4 ;
    input \3oe* ;
    output \3y1 ;
    output \3y2 ;
    output \3y3 ;
    output \3y4 ;
    input \4a1 ;
    input \4a2 ;
    input \4a3 ;
    input \4a4 ;
    input \4oe* ;
    output \4y1 ;
    output \4y2 ;
    output \4y3 ;
    output \4y4 ;
    input [7:0] gnd;
    input [3:0] vcc;


    initial
        begin
        end

endmodule
