-- generated by newgenasym Mon Jan 09 16:51:00 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74lvc16244\ is
    port (    
	\1a1\:     IN     STD_LOGIC;    
	\1a2\:     IN     STD_LOGIC;    
	\1a3\:     IN     STD_LOGIC;    
	\1a4\:     IN     STD_LOGIC;    
	\1oe*\:    IN     STD_LOGIC;    
	\1y1\:     IN     STD_LOGIC;    
	\1y2\:     OUT    STD_LOGIC;    
	\1y3\:     OUT    STD_LOGIC;    
	\1y4\:     OUT    STD_LOGIC;    
	\2a1\:     IN     STD_LOGIC;    
	\2a2\:     IN     STD_LOGIC;    
	\2a3\:     IN     STD_LOGIC;    
	\2a4\:     IN     STD_LOGIC;    
	\2oe*\:    IN     STD_LOGIC;    
	\2y1\:     OUT    STD_LOGIC;    
	\2y2\:     OUT    STD_LOGIC;    
	\2y3\:     OUT    STD_LOGIC;    
	\2y4\:     OUT    STD_LOGIC;    
	\3a1\:     IN     STD_LOGIC;    
	\3a2\:     IN     STD_LOGIC;    
	\3a3\:     IN     STD_LOGIC;    
	\3a4\:     IN     STD_LOGIC;    
	\3oe*\:    IN     STD_LOGIC;    
	\3y1\:     OUT    STD_LOGIC;    
	\3y2\:     OUT    STD_LOGIC;    
	\3y3\:     OUT    STD_LOGIC;    
	\3y4\:     OUT    STD_LOGIC;    
	\4a1\:     IN     STD_LOGIC;    
	\4a2\:     IN     STD_LOGIC;    
	\4a3\:     IN     STD_LOGIC;    
	\4a4\:     IN     STD_LOGIC;    
	\4oe*\:    IN     STD_LOGIC;    
	\4y1\:     OUT    STD_LOGIC;    
	\4y2\:     OUT    STD_LOGIC;    
	\4y3\:     OUT    STD_LOGIC;    
	\4y4\:     OUT    STD_LOGIC;    
	GND:       IN     STD_LOGIC_VECTOR (7 DOWNTO 0);    
	VCC:       IN     STD_LOGIC_VECTOR (3 DOWNTO 0));
end \74lvc16244\;
