-- generated by newgenasym Sun Nov 16 15:48:51 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity c3216 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end c3216;
