-- generated by newgenasym Mon Jan 09 17:53:18 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74lvc08\ is
    port (    
	A:         IN     STD_LOGIC;    
	B:         IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	Y:         OUT    STD_LOGIC);
end \74lvc08\;
