// generated by newgenasym  Thu Sep 27 07:33:47 2018


module adg3304bruz (a1, a2, a3, a4, en, gnd, nc, nc1, vcca, vccy, y1, y2, y3, y4);
    inout a1;
    inout a2;
    inout a3;
    inout a4;
    inout en;
    inout gnd;
    inout nc;
    inout nc1;
    inout vcca;
    inout vccy;
    inout y1;
    inout y2;
    inout y3;
    inout y4;


    initial
        begin
        end

endmodule
