-- generated by newgenasym Thu Sep 27 07:33:47 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adg3304bruz is
    port (    
	A1:        INOUT  STD_LOGIC;    
	A2:        INOUT  STD_LOGIC;    
	A3:        INOUT  STD_LOGIC;    
	A4:        INOUT  STD_LOGIC;    
	EN:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC;    
	VCCA:      INOUT  STD_LOGIC;    
	VCCY:      INOUT  STD_LOGIC;    
	Y1:        INOUT  STD_LOGIC;    
	Y2:        INOUT  STD_LOGIC;    
	Y3:        INOUT  STD_LOGIC;    
	Y4:        INOUT  STD_LOGIC);
end adg3304bruz;
