// generated by newgenasym  Tue Jan 14 19:52:37 2014


module msp430f5438aipz (avcc, avss, dvcc1, dvcc2, dvcc3, dvcc4, dvss1, dvss2, dvss3,
        dvss4, \p1.0/ta0clk/aclk , \p1.1/ta0.0 , \p1.2/ta0.1 ,
        \p1.3/ta0.2 , \p1.4/ta0.3 , \p1.5/ta0.4 , \p1.6/smclk , \p1.7 ,
        \p10.0/ucb3ste/uca3clk , \p10.1/ucb3simo/ucb3sda ,
        \p10.2/ucb3somi/ucb3scl , \p10.3/ucb3clk/uca3ste ,
        \p10.4/uca3txd/uca3simo , \p10.5/uca3rxd/uca3somi , \p10.6 ,
        \p10.7 , \p11.0/aclk , \p11.1/mclk , \p11.2/smclk ,
        \p2.0/ta1clk/mclk , \p2.1/ta1.0 , \p2.2/ta1.1 , \p2.3/ta1.2 ,
        \p2.4/rtcclk , \p2.5 , \p2.6/aclk , \p2.7/adc12clk/dmae0 ,
        \p3.0/ucb0ste/uca0clk , \p3.1/ucb0simo/ucb0sda ,
        \p3.2/ucb0somi/ucb0scl , \p3.3/ucb0clk/uca0ste ,
        \p3.4/uca0txd/uca0simo , \p3.5/uca0rxd/uca0somi ,
        \p3.6/ucb1ste/uca1clk , \p3.7/ucb1simo/ucb1sda , \p4.0/tb0 ,
        \p4.1/tb1 , \p4.2/tb2 , \p4.3/tb3 , \p4.4/tb4 , \p4.5/tb5 , \p4.6/tb6 ,
        \p4.7/tbclk/smclk , \p5.0/vref+/veref+ , \p5.1/vref-/veref- ,
        \p5.2/xt2in , \p5.3/xt2out , \p5.4/ucb1somi/ucb1scl ,
        \p5.5/ucb1clk/uca1ste , \p5.6/uca1txd/uca1simo ,
        \p5.7/uca1rxd/uca1somi , \p6.0/a0 , \p6.1/a1 , \p6.2/a2 , \p6.3/a3 ,
        \p6.4/a4 , \p6.5/a5 , \p6.6/a6 , \p6.7/a7 , \p7.0/xin , \p7.1/xout ,
        \p7.2/tbouth/svmout , \p7.3/ta1.2 , \p7.4/a12 , \p7.5/a13 ,
        \p7.6/a14 , \p7.7/a15 , \p8.0/ta0.0 , \p8.1/ta0.1 , \p8.2/ta0.2 ,
        \p8.3/ta0.3 , \p8.4/ta0.4 , \p8.5/ta1.0 , \p8.6/ta1.1 , \p8.7 ,
        \p9.0/ucb2ste/uca2clk , \p9.1/ucb2simo/ucb2sda ,
        \p9.2/ucb2somi/ucb2scl , \p9.3/ucb2sclk/uca2ste ,
        \p9.4/uca2txd/uca2simo , \p9.5/uca2rxd/uca2somi , \p9.6 , \p9.7 ,
        \pj.0/tdo , \pj.1/tdi/tclk , \pj.2/tms , \pj.3/tck ,
        \rst_n/nmi/sbwtdio , \test/sbwtclk , vcore);
    inout avcc;
    inout avss;
    inout dvcc1;
    inout dvcc2;
    inout dvcc3;
    inout dvcc4;
    inout dvss1;
    inout dvss2;
    inout dvss3;
    inout dvss4;
    inout \p1.0/ta0clk/aclk ;
    inout \p1.1/ta0.0 ;
    inout \p1.2/ta0.1 ;
    inout \p1.3/ta0.2 ;
    inout \p1.4/ta0.3 ;
    inout \p1.5/ta0.4 ;
    inout \p1.6/smclk ;
    inout \p1.7 ;
    inout \p10.0/ucb3ste/uca3clk ;
    inout \p10.1/ucb3simo/ucb3sda ;
    inout \p10.2/ucb3somi/ucb3scl ;
    inout \p10.3/ucb3clk/uca3ste ;
    inout \p10.4/uca3txd/uca3simo ;
    inout \p10.5/uca3rxd/uca3somi ;
    inout \p10.6 ;
    inout \p10.7 ;
    inout \p11.0/aclk ;
    inout \p11.1/mclk ;
    inout \p11.2/smclk ;
    inout \p2.0/ta1clk/mclk ;
    inout \p2.1/ta1.0 ;
    inout \p2.2/ta1.1 ;
    inout \p2.3/ta1.2 ;
    inout \p2.4/rtcclk ;
    inout \p2.5 ;
    inout \p2.6/aclk ;
    inout \p2.7/adc12clk/dmae0 ;
    inout \p3.0/ucb0ste/uca0clk ;
    inout \p3.1/ucb0simo/ucb0sda ;
    inout \p3.2/ucb0somi/ucb0scl ;
    inout \p3.3/ucb0clk/uca0ste ;
    inout \p3.4/uca0txd/uca0simo ;
    inout \p3.5/uca0rxd/uca0somi ;
    inout \p3.6/ucb1ste/uca1clk ;
    inout \p3.7/ucb1simo/ucb1sda ;
    inout \p4.0/tb0 ;
    inout \p4.1/tb1 ;
    inout \p4.2/tb2 ;
    inout \p4.3/tb3 ;
    inout \p4.4/tb4 ;
    inout \p4.5/tb5 ;
    inout \p4.6/tb6 ;
    inout \p4.7/tbclk/smclk ;
    inout \p5.0/vref+/veref+ ;
    inout \p5.1/vref-/veref- ;
    inout \p5.2/xt2in ;
    inout \p5.3/xt2out ;
    inout \p5.4/ucb1somi/ucb1scl ;
    inout \p5.5/ucb1clk/uca1ste ;
    inout \p5.6/uca1txd/uca1simo ;
    inout \p5.7/uca1rxd/uca1somi ;
    inout \p6.0/a0 ;
    inout \p6.1/a1 ;
    inout \p6.2/a2 ;
    inout \p6.3/a3 ;
    inout \p6.4/a4 ;
    inout \p6.5/a5 ;
    inout \p6.6/a6 ;
    inout \p6.7/a7 ;
    inout \p7.0/xin ;
    inout \p7.1/xout ;
    inout \p7.2/tbouth/svmout ;
    inout \p7.3/ta1.2 ;
    inout \p7.4/a12 ;
    inout \p7.5/a13 ;
    inout \p7.6/a14 ;
    inout \p7.7/a15 ;
    inout \p8.0/ta0.0 ;
    inout \p8.1/ta0.1 ;
    inout \p8.2/ta0.2 ;
    inout \p8.3/ta0.3 ;
    inout \p8.4/ta0.4 ;
    inout \p8.5/ta1.0 ;
    inout \p8.6/ta1.1 ;
    inout \p8.7 ;
    inout \p9.0/ucb2ste/uca2clk ;
    inout \p9.1/ucb2simo/ucb2sda ;
    inout \p9.2/ucb2somi/ucb2scl ;
    inout \p9.3/ucb2sclk/uca2ste ;
    inout \p9.4/uca2txd/uca2simo ;
    inout \p9.5/uca2rxd/uca2somi ;
    inout \p9.6 ;
    inout \p9.7 ;
    inout \pj.0/tdo ;
    inout \pj.1/tdi/tclk ;
    inout \pj.2/tms ;
    inout \pj.3/tck ;
    inout \rst_n/nmi/sbwtdio ;
    inout \test/sbwtclk ;
    inout vcore;


    initial
        begin
        end

endmodule
