// generated by newgenasym  Mon Aug 21 11:51:33 2006


module rs232 (a1, a2, a3, a4, a5, a6, a7, a8, a9, gnd1, gnd2);
    input a1;
    input a2;
    input a3;
    input a4;
    input a5;
    input a6;
    input a7;
    input a8;
    input a9;
    input gnd1;
    input gnd2;


    initial
        begin
        end

endmodule
