-- generated by newgenasym Wed Dec 24 22:50:23 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \fxl0630-100-m\ is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end \fxl0630-100-m\;
