// generated by newgenasym  Mon Oct 22 18:14:05 2012


module sn75lbc172dw (\1a , \1y , \1z , \2a , \2y , \2z , \3a , \3y , \3z , \4a , \4y , \4z , g, \g* , gnd, nc1, nc2,
        nc3, nc4, vcc);
    input \1a ;
    output \1y ;
    output \1z ;
    input \2a ;
    output \2y ;
    output \2z ;
    input \3a ;
    output \3y ;
    output \3z ;
    input \4a ;
    output \4y ;
    output \4z ;
    input g;
    input \g* ;
    input gnd;
    inout nc1;
    inout nc2;
    inout nc3;
    inout nc4;
    input vcc;


    initial
        begin
        end

endmodule
