-- generated by newgenasym Mon Oct 22 18:14:05 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sn75lbc172dw is
    port (    
	\1a\:      IN     STD_LOGIC;    
	\1y\:      OUT    STD_LOGIC;    
	\1z\:      OUT    STD_LOGIC;    
	\2a\:      IN     STD_LOGIC;    
	\2y\:      OUT    STD_LOGIC;    
	\2z\:      OUT    STD_LOGIC;    
	\3a\:      IN     STD_LOGIC;    
	\3y\:      OUT    STD_LOGIC;    
	\3z\:      OUT    STD_LOGIC;    
	\4a\:      IN     STD_LOGIC;    
	\4y\:      OUT    STD_LOGIC;    
	\4z\:      OUT    STD_LOGIC;    
	G:         IN     STD_LOGIC;    
	\g*\:      IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC;    
	NC2:       INOUT  STD_LOGIC;    
	NC3:       INOUT  STD_LOGIC;    
	NC4:       INOUT  STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end sn75lbc172dw;
