// generated by newgenasym  Sat Nov 17 12:51:14 2012


module pci (\12v+ , \12v- , \3.3v+_1 , \3.3v+_10 , \3.3v+_11 , \3.3v+_12 , \3.3v+_2 ,
        \3.3v+_3 , \3.3v+_4 , \3.3v+_5 , \3.3v+_6 , \3.3v+_7 , \3.3v+_8 ,
        \3.3v+_9 , \5v+_1 , \5v+_2 , \5v+_3 , \5v+_4 , \5v+_5 , \5v+_6 , \5v+_7 ,
        \5v+_8 , \5v+i/0_3 , \5v+i/0_4 , \5v+i/o_1 , \5v+i/o_2 , \5v+i/o_5 ,
        \ack64# , \ad[00] , \ad[01] , \ad[02] , \ad[03] , \ad[04] , \ad[05] ,
        \ad[06] , \ad[07] , \ad[08] , \ad[09] , \ad[10] , \ad[11] , \ad[12] ,
        \ad[13] , \ad[14] , \ad[15] , \ad[16] , \ad[17] , \ad[18] , \ad[19] ,
        \ad[20] , \ad[21] , \ad[22] , \ad[23] , \ad[24] , \ad[25] , \ad[26] ,
        \ad[27] , \ad[28] , \ad[29] , \ad[30] , \ad[31] , \c/be[0]# , \c/be[1]# ,
        \c/be[2]# , \c/be[3]# , clk, \devsel# , \frame# , gnd1, gnd10, gnd11,
        gnd12, gnd13, gnd14, gnd15, gnd16, gnd17, gnd18, gnd19, gnd2,
        gnd20, gnd21, gnd22, gnd3, gnd4, gnd5, gnd6, gnd7, gnd8, gnd9,
        \gnt# , idsel, inta, \intb# , \intc# , \intd# , key1, key2, key3, key4,
        \lock# , par, \perr# , prsnt2, \prsnt2# , \req# , \req64# , \rst# , rsvd1,
        rsvd2, rsvd3, rsvd4, rsvd5, rsvd6, \sbo# , sdone, \serr# , \stop# ,
        tck, tdi, tdo, tms, \tr5t# , \trdy#1 , \trdy#2 );
    input \12v+ ;
    input \12v- ;
    input \3.3v+_1 ;
    input \3.3v+_10 ;
    input \3.3v+_11 ;
    input \3.3v+_12 ;
    input \3.3v+_2 ;
    input \3.3v+_3 ;
    input \3.3v+_4 ;
    input \3.3v+_5 ;
    input \3.3v+_6 ;
    input \3.3v+_7 ;
    input \3.3v+_8 ;
    input \3.3v+_9 ;
    input \5v+_1 ;
    input \5v+_2 ;
    input \5v+_3 ;
    input \5v+_4 ;
    input \5v+_5 ;
    input \5v+_6 ;
    input \5v+_7 ;
    input \5v+_8 ;
    inout \5v+i/0_3 ;
    inout \5v+i/0_4 ;
    inout \5v+i/o_1 ;
    inout \5v+i/o_2 ;
    inout \5v+i/o_5 ;
    inout \ack64# ;
    inout \ad[00] ;
    inout \ad[01] ;
    inout \ad[02] ;
    inout \ad[03] ;
    inout \ad[04] ;
    inout \ad[05] ;
    inout \ad[06] ;
    inout \ad[07] ;
    inout \ad[08] ;
    inout \ad[09] ;
    inout \ad[10] ;
    inout \ad[11] ;
    inout \ad[12] ;
    inout \ad[13] ;
    inout \ad[14] ;
    inout \ad[15] ;
    inout \ad[16] ;
    inout \ad[17] ;
    inout \ad[18] ;
    inout \ad[19] ;
    inout \ad[20] ;
    inout \ad[21] ;
    inout \ad[22] ;
    inout \ad[23] ;
    inout \ad[24] ;
    inout \ad[25] ;
    inout \ad[26] ;
    inout \ad[27] ;
    inout \ad[28] ;
    inout \ad[29] ;
    inout \ad[30] ;
    inout \ad[31] ;
    inout \c/be[0]# ;
    inout \c/be[1]# ;
    inout \c/be[2]# ;
    inout \c/be[3]# ;
    inout clk;
    inout \devsel# ;
    inout \frame# ;
    input gnd1;
    input gnd10;
    input gnd11;
    input gnd12;
    input gnd13;
    input gnd14;
    input gnd15;
    input gnd16;
    input gnd17;
    input gnd18;
    input gnd19;
    input gnd2;
    input gnd20;
    input gnd21;
    input gnd22;
    input gnd3;
    input gnd4;
    input gnd5;
    input gnd6;
    input gnd7;
    input gnd8;
    input gnd9;
    inout \gnt# ;
    inout idsel;
    inout inta;
    inout \intb# ;
    inout \intc# ;
    inout \intd# ;
    inout key1;
    inout key2;
    inout key3;
    inout key4;
    inout \lock# ;
    inout par;
    inout \perr# ;
    inout prsnt2;
    inout \prsnt2# ;
    inout \req# ;
    inout \req64# ;
    inout \rst# ;
    inout rsvd1;
    inout rsvd2;
    inout rsvd3;
    inout rsvd4;
    inout rsvd5;
    inout rsvd6;
    inout \sbo# ;
    inout sdone;
    inout \serr# ;
    inout \stop# ;
    inout tck;
    inout tdi;
    inout tdo;
    inout tms;
    inout \tr5t# ;
    inout \trdy#1 ;
    inout \trdy#2 ;


    initial
        begin
        end

endmodule
