// generated by newgenasym  Tue Dec 19 18:18:55 2017


module tf (\cd/data3 , clk, cmd, data0, data1, data2, gnd1, gnd2, gnd3,
        gnd4, sd, vdd, vss);
    inout \cd/data3 ;
    inout clk;
    inout cmd;
    inout data0;
    inout data1;
    inout data2;
    input gnd1;
    inout gnd2;
    inout gnd3;
    inout gnd4;
    inout sd;
    input vdd;
    input vss;


    initial
        begin
        end

endmodule
