-- generated by newgenasym Tue Dec 19 18:18:55 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tf is
    port (    
	\cd/data3\: INOUT  STD_LOGIC;    
	CLK:       INOUT  STD_LOGIC;    
	CMD:       INOUT  STD_LOGIC;    
	DATA0:     INOUT  STD_LOGIC;    
	DATA1:     INOUT  STD_LOGIC;    
	DATA2:     INOUT  STD_LOGIC;    
	GND1:      IN     STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	GND3:      INOUT  STD_LOGIC;    
	GND4:      INOUT  STD_LOGIC;    
	SD:        INOUT  STD_LOGIC;    
	VDD:       IN     STD_LOGIC;    
	VSS:       IN     STD_LOGIC);
end tf;
