// generated by newgenasym  Wed Nov 26 23:34:11 2025


module stm32f103c8t6 (boot0, nrst, \pa0-wkup , pa1, pa10, pa11, pa12, pa13, pa14,
        pa15, pa2, pa3, pa4, pa5, pa6, pa7, pa8, pa9, pb0, pb1, pb10,
        pb11, pb12, pb13, pb14, pb15, pb2, pb3, pb4, pb5, pb6, pb7, pb8,
        pb9, \pc13-tamper-rtc , \pc14-osc32_in , \pc15-osc32_out ,
        \pd0-osc_in , \pd1-osc_out , vbat, vdd_1, vdd_2, vdd_3, vdda,
        vss_1, vss_2, vss_3, vssa);
    inout boot0;
    inout nrst;
    inout \pa0-wkup ;
    inout pa1;
    inout pa10;
    inout pa11;
    inout pa12;
    inout pa13;
    inout pa14;
    inout pa15;
    inout pa2;
    inout pa3;
    inout pa4;
    inout pa5;
    inout pa6;
    inout pa7;
    inout pa8;
    inout pa9;
    inout pb0;
    inout pb1;
    inout pb10;
    inout pb11;
    inout pb12;
    inout pb13;
    inout pb14;
    inout pb15;
    inout pb2;
    inout pb3;
    inout pb4;
    inout pb5;
    inout pb6;
    inout pb7;
    inout pb8;
    inout pb9;
    inout \pc13-tamper-rtc ;
    inout \pc14-osc32_in ;
    inout \pc15-osc32_out ;
    inout \pd0-osc_in ;
    inout \pd1-osc_out ;
    inout vbat;
    inout vdd_1;
    inout vdd_2;
    inout vdd_3;
    inout vdda;
    inout vss_1;
    inout vss_2;
    inout vss_3;
    inout vssa;


    initial
        begin
        end

endmodule
