// generated by newgenasym  Tue Mar 07 17:25:35 2023


module \rclamp0544m-ms  (\d1+ , \d1- , \d2+ , \d2- , gnd_1, gnd_2, nc_10, nc_6, nc_7, nc_9);
    inout \d1+ ;
    inout \d1- ;
    inout \d2+ ;
    inout \d2- ;
    inout gnd_1;
    inout gnd_2;
    inout nc_10;
    inout nc_6;
    inout nc_7;
    inout nc_9;


    initial
        begin
        end

endmodule
