-- generated by newgenasym Tue Mar 07 17:25:35 2023

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \rclamp0544m-ms\ is
    port (    
	\d1+\:     INOUT  STD_LOGIC;    
	\d1-\:     INOUT  STD_LOGIC;    
	\d2+\:     INOUT  STD_LOGIC;    
	\d2-\:     INOUT  STD_LOGIC;    
	GND_1:     INOUT  STD_LOGIC;    
	GND_2:     INOUT  STD_LOGIC;    
	NC_10:     INOUT  STD_LOGIC;    
	NC_6:      INOUT  STD_LOGIC;    
	NC_7:      INOUT  STD_LOGIC;    
	NC_9:      INOUT  STD_LOGIC);
end \rclamp0544m-ms\;
