// generated by newgenasym  Wed Sep 23 14:50:25 2015


module \12mhz  (\1 , \2 , \3 , \4 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;


    initial
        begin
        end

endmodule
