-- generated by newgenasym Wed Sep 23 14:50:25 2015

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \12mhz\ is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC);
end \12mhz\;
