// generated by newgenasym  Wed Sep 07 12:20:24 2016


module mic5332 (cset2, en1, en2, ep, gnd, por2, vin, vout1, vout2);
    inout cset2;
    inout en1;
    inout en2;
    inout ep;
    inout gnd;
    inout por2;
    inout vin;
    inout vout1;
    inout vout2;


    initial
        begin
        end

endmodule
