-- generated by newgenasym Wed Sep 07 12:20:24 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity mic5332 is
    port (    
	CSET2:     INOUT  STD_LOGIC;    
	EN1:       INOUT  STD_LOGIC;    
	EN2:       INOUT  STD_LOGIC;    
	EP:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	POR2:      INOUT  STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC;    
	VOUT1:     INOUT  STD_LOGIC;    
	VOUT2:     INOUT  STD_LOGIC);
end mic5332;
