-- generated by newgenasym Tue May 30 11:30:33 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity head1x2_s is
    port (    
	P1:        INOUT  STD_LOGIC;    
	P2:        INOUT  STD_LOGIC);
end head1x2_s;
