// generated by newgenasym  Sun Dec 01 20:09:44 2013


module aha4524 (acptpolarity, agnd, c_acpt, c_clk, c_data0, c_data1,
        c_data2, c_data3, c_fs, d_clk, d_cs_n, d_data, d_fs, d_gout,
        d_mode, d_rdy, dparinput, e_clk, e_cs_n, e_data, e_fs,
        e_gout, e_mode, e_rdy, gnd1, gnd10, gnd2, gnd3, gnd4, gnd5,
        gnd6, gnd7, gnd8, gnd9, gndio1, gndio2, gndio3, gndio4,
        pll_bypass, rdypolarity, reset_n, scanmode, sysclk,
        testmode, tristate_n, u_acpt, u_clk, u_data, u_fs, vad, vdd1,
        vdd10, vdd2, vdd3, vdd4, vdd5, vdd6, vdd7, vdd8, vdd9, vddio1,
        vddio2, vddio3, vddio4);
    inout acptpolarity;
    input agnd;
    inout c_acpt;
    inout c_clk;
    inout c_data0;
    inout c_data1;
    inout c_data2;
    inout c_data3;
    inout c_fs;
    inout d_clk;
    inout d_cs_n;
    inout d_data;
    inout d_fs;
    inout d_gout;
    inout d_mode;
    inout d_rdy;
    inout dparinput;
    inout e_clk;
    inout e_cs_n;
    inout e_data;
    inout e_fs;
    inout e_gout;
    inout e_mode;
    inout e_rdy;
    input gnd1;
    input gnd10;
    input gnd2;
    input gnd3;
    input gnd4;
    input gnd5;
    input gnd6;
    input gnd7;
    input gnd8;
    input gnd9;
    input gndio1;
    input gndio2;
    input gndio3;
    input gndio4;
    inout pll_bypass;
    inout rdypolarity;
    inout reset_n;
    inout scanmode;
    inout sysclk;
    inout testmode;
    inout tristate_n;
    inout u_acpt;
    inout u_clk;
    inout u_data;
    inout u_fs;
    input vad;
    input vdd1;
    input vdd10;
    input vdd2;
    input vdd3;
    input vdd4;
    input vdd5;
    input vdd6;
    input vdd7;
    input vdd8;
    input vdd9;
    input vddio1;
    input vddio2;
    input vddio3;
    input vddio4;


    initial
        begin
        end

endmodule
