// generated by newgenasym  Wed Apr 19 14:42:38 2017


module imx290 (\a1/n.c , \a11/n.c , \a3/vloadlm , \a4/vddhan , \a5/vrlfr ,
        \a6/vddhpx , \a7/vddhcp , \a8/vddhpx , \a9/vddhan , \b3/vsshpx ,
        \b4/vsshan , \b5/vrlst , \b6/vsshpx , \b7/vsshcp , \b8/vsshpx ,
        \b9/vsshan , \c1/dloma , \c10/tamon , \c11/vbgr , \c2/dlopa ,
        \c3/vssmif , \c4/n.c , \c5/n.c , \c6/n.c , \c7/n.c , \c8/n.c , \c9/n.c ,
        \d1/dlomb , \d10/vsslcn , \d11/vddlcn , \d2/dlopb , \d3/vssmif ,
        \d4/vsslsc , \d5/n.c , \d6/n.c , \d7/n.c , \d8/vsslsc , \d9/n.c ,
        \e1/dlomc , \e10/vsslsc , \e11/tenable , \e2/dlopc , \e3/vssmif ,
        \e4/vddlsc , \e5/n.c , \e6/n.c , \e7/n.c , \e8/vddlsc , \e9/n.c ,
        \f1/dlomd , \f10/sod , \f11/xmaster , \f2/dlopd , \g1/dlckm ,
        \g10/sck , \g11/xce , \g2/dlckp , \h1/dlome , \h10/sdi , \h11/xvs ,
        h2dlope, \j1/dlomf , \j10/omode , \j11/tout , \j2/dlopf , \k1/dlomg ,
        \k10/xclr , \k11/xtrig , \k2/dlopg , \k3/vssmif , \k4/n.c ,
        \k5/vddlsc , \k6/vddlif , \k7/vddlif , \k8/vddlsc , \k9/n.c ,
        \l1/dlomh , \l10/xhs , \l11/vsslsc , \l2/dloph , \l3/vssmif , \l4/n.c ,
        \l5/vsslsc , \l6/vsslif , \l7/vsslif , \l8/vsslsc , \l9/n.c ,
        \m1/vddmif , \m10/vsslcn , \m11/vddlcn , \m2/vssmif , \m3/vssmif ,
        \m4/n.c , \m5/vsslif , \m6/vsslif , \m7/vsslif , \m8/vsslif ,
        \m9/vsslif , \n3/vsslsc , \n4/n.c , \n5/dmo3p , \n6/dmo1p , \n7/dmckp ,
        \n8/dmo2p , \n9/dmo4p , \p1/n.c , \p11/n.c , \p3/inck , \p4/n.c ,
        \p5/dmo3n , \p6/dmo1n , \p7/dmokn , \p8/dmo2n , \p9/dmo4n );
    inout \a1/n.c ;
    inout \a11/n.c ;
    inout \a3/vloadlm ;
    inout \a4/vddhan ;
    inout \a5/vrlfr ;
    inout \a6/vddhpx ;
    inout \a7/vddhcp ;
    inout \a8/vddhpx ;
    inout \a9/vddhan ;
    inout \b3/vsshpx ;
    inout \b4/vsshan ;
    inout \b5/vrlst ;
    inout \b6/vsshpx ;
    inout \b7/vsshcp ;
    inout \b8/vsshpx ;
    inout \b9/vsshan ;
    inout \c1/dloma ;
    inout \c10/tamon ;
    inout \c11/vbgr ;
    inout \c2/dlopa ;
    inout \c3/vssmif ;
    inout \c4/n.c ;
    inout \c5/n.c ;
    inout \c6/n.c ;
    inout \c7/n.c ;
    inout \c8/n.c ;
    inout \c9/n.c ;
    inout \d1/dlomb ;
    inout \d10/vsslcn ;
    inout \d11/vddlcn ;
    inout \d2/dlopb ;
    inout \d3/vssmif ;
    inout \d4/vsslsc ;
    inout \d5/n.c ;
    inout \d6/n.c ;
    inout \d7/n.c ;
    inout \d8/vsslsc ;
    inout \d9/n.c ;
    inout \e1/dlomc ;
    inout \e10/vsslsc ;
    inout \e11/tenable ;
    inout \e2/dlopc ;
    inout \e3/vssmif ;
    inout \e4/vddlsc ;
    inout \e5/n.c ;
    inout \e6/n.c ;
    inout \e7/n.c ;
    inout \e8/vddlsc ;
    inout \e9/n.c ;
    inout \f1/dlomd ;
    inout \f10/sod ;
    inout \f11/xmaster ;
    inout \f2/dlopd ;
    inout \g1/dlckm ;
    inout \g10/sck ;
    inout \g11/xce ;
    inout \g2/dlckp ;
    inout \h1/dlome ;
    inout \h10/sdi ;
    inout \h11/xvs ;
    inout h2dlope;
    inout \j1/dlomf ;
    inout \j10/omode ;
    inout \j11/tout ;
    inout \j2/dlopf ;
    inout \k1/dlomg ;
    inout \k10/xclr ;
    inout \k11/xtrig ;
    inout \k2/dlopg ;
    inout \k3/vssmif ;
    inout \k4/n.c ;
    inout \k5/vddlsc ;
    inout \k6/vddlif ;
    inout \k7/vddlif ;
    inout \k8/vddlsc ;
    inout \k9/n.c ;
    inout \l1/dlomh ;
    inout \l10/xhs ;
    inout \l11/vsslsc ;
    inout \l2/dloph ;
    inout \l3/vssmif ;
    inout \l4/n.c ;
    inout \l5/vsslsc ;
    inout \l6/vsslif ;
    inout \l7/vsslif ;
    inout \l8/vsslsc ;
    inout \l9/n.c ;
    inout \m1/vddmif ;
    inout \m10/vsslcn ;
    inout \m11/vddlcn ;
    inout \m2/vssmif ;
    inout \m3/vssmif ;
    inout \m4/n.c ;
    inout \m5/vsslif ;
    inout \m6/vsslif ;
    inout \m7/vsslif ;
    inout \m8/vsslif ;
    inout \m9/vsslif ;
    inout \n3/vsslsc ;
    inout \n4/n.c ;
    inout \n5/dmo3p ;
    inout \n6/dmo1p ;
    inout \n7/dmckp ;
    inout \n8/dmo2p ;
    inout \n9/dmo4p ;
    inout \p1/n.c ;
    inout \p11/n.c ;
    inout \p3/inck ;
    inout \p4/n.c ;
    inout \p5/dmo3n ;
    inout \p6/dmo1n ;
    inout \p7/dmokn ;
    inout \p8/dmo2n ;
    inout \p9/dmo4n ;


    initial
        begin
        end

endmodule
