-- generated by newgenasym Wed Apr 26 21:48:48 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity head1x3_s is
    port (    
	A1:        INOUT  STD_LOGIC;    
	A2:        INOUT  STD_LOGIC;    
	A3:        INOUT  STD_LOGIC);
end head1x3_s;
