// generated by newgenasym  Thu Mar 09 10:25:20 2023


module stef12s (\dv/dt , \en/fault , gnd, ilimit, \nc/vg , \source/vout1 ,
        \source/vout2 , \source/vout3 , \source/vout4 , \source/vout5 ,
        vcc);
    inout \dv/dt ;
    inout \en/fault ;
    inout gnd;
    inout ilimit;
    inout \nc/vg ;
    inout \source/vout1 ;
    inout \source/vout2 ;
    inout \source/vout3 ;
    inout \source/vout4 ;
    inout \source/vout5 ;
    inout vcc;


    initial
        begin
        end

endmodule
