-- generated by newgenasym Thu Mar 09 10:25:20 2023

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity stef12s is
    port (    
	\dv/dt\:   INOUT  STD_LOGIC;    
	\en/fault\: INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	ILIMIT:    INOUT  STD_LOGIC;    
	\nc/vg\:   INOUT  STD_LOGIC;    
	\source/vout1\: INOUT  STD_LOGIC;    
	\source/vout2\: INOUT  STD_LOGIC;    
	\source/vout3\: INOUT  STD_LOGIC;    
	\source/vout4\: INOUT  STD_LOGIC;    
	\source/vout5\: INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC);
end stef12s;
