-- generated by newgenasym Wed Nov 19 11:30:03 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity res0603 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end res0603;
