// generated by newgenasym  Fri Mar 10 16:05:52 2023


module ch340n (gnd, \rts# , rxd, txd, \ud+ , \ud- , v3, vcc);
    inout gnd;
    inout \rts# ;
    inout rxd;
    inout txd;
    inout \ud+ ;
    inout \ud- ;
    inout v3;
    inout vcc;


    initial
        begin
        end

endmodule
