-- generated by newgenasym Fri Mar 10 16:05:52 2023

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ch340n is
    port (    
	GND:       INOUT  STD_LOGIC;    
	\rts#\:    INOUT  STD_LOGIC;    
	RXD:       INOUT  STD_LOGIC;    
	TXD:       INOUT  STD_LOGIC;    
	\ud+\:     INOUT  STD_LOGIC;    
	\ud-\:     INOUT  STD_LOGIC;    
	V3:        INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC);
end ch340n;
