// generated by newgenasym  Thu Sep 22 18:29:51 2016


module knh16c104dasts (a1, a2, a3, a4);
    inout a1;
    inout a2;
    inout a3;
    inout a4;


    initial
        begin
        end

endmodule
