-- generated by newgenasym Thu Sep 22 18:29:51 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity knh16c104dasts is
    port (    
	A1:        INOUT  STD_LOGIC;    
	A2:        INOUT  STD_LOGIC;    
	A3:        INOUT  STD_LOGIC;    
	A4:        INOUT  STD_LOGIC);
end knh16c104dasts;
