// generated by newgenasym  Tue Mar 18 10:49:12 2008


module ltc1019 (dnc, gnd, \input , \output , temp, trim);
    inout [3:1] dnc;
    inout gnd;
    inout \input ;
    inout \output ;
    inout temp;
    inout trim;


    initial
        begin
        end

endmodule
