-- generated by newgenasym Tue Mar 18 10:49:12 2008

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ltc1019 is
    port (    
	DNC:       INOUT  STD_LOGIC_VECTOR (3 DOWNTO 1);    
	GND:       INOUT  STD_LOGIC;    
	INPUT:     INOUT  STD_LOGIC;    
	OUTPUT:    INOUT  STD_LOGIC;    
	TEMP:      INOUT  STD_LOGIC;    
	TRIM:      INOUT  STD_LOGIC);
end ltc1019;
