// generated by newgenasym  Mon Sep 26 14:30:20 2005


module \74alvc08  (a, b, gnd, vcc, y);
    input a;
    input b;
    input gnd;
    input vcc;
    output y;


    initial
        begin
        end

endmodule
