-- generated by newgenasym Mon Sep 26 14:30:20 2005

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74alvc08\ is
    port (    
	A:         IN     STD_LOGIC;    
	B:         IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	Y:         OUT    STD_LOGIC);
end \74alvc08\;
