-- generated by newgenasym Wed Dec 24 15:51:04 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ma35v220m8x8 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end ma35v220m8x8;
