-- generated by newgenasym Tue Nov 25 08:41:29 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity c0805 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end c0805;
