-- generated by newgenasym Mon Dec 22 14:59:07 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity c0805 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end c0805;
