// generated by newgenasym  Thu Jun 23 11:49:12 2011


module tps79901 (en, fb, gnd, in, out);
    input en;
    input fb;
    input gnd;
    input in;
    output out;


    initial
        begin
        end

endmodule
