-- generated by newgenasym Thu Jun 23 11:49:12 2011

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tps79901 is
    port (    
	EN:        IN     STD_LOGIC;    
	FB:        IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	\in\:      IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC);
end tps79901;
