// generated by newgenasym  Fri Apr 28 14:02:45 2006


module ide_con_40 (a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a3,
        a4, a5, a6, a7, a8, a9, b1, b10, b11, b12, b13, b14, b15, b16, b17,
        b18, b19, b2, b20, b3, b4, b5, b6, b7, b8, b9);
    inout a1;
    inout a10;
    inout a11;
    inout a12;
    inout a13;
    inout a14;
    inout a15;
    inout a16;
    inout a17;
    inout a18;
    inout a19;
    inout a2;
    inout a20;
    inout a3;
    inout a4;
    inout a5;
    inout a6;
    inout a7;
    inout a8;
    inout a9;
    inout b1;
    inout b10;
    inout b11;
    inout b12;
    inout b13;
    inout b14;
    inout b15;
    inout b16;
    inout b17;
    inout b18;
    inout b19;
    inout b2;
    inout b20;
    inout b3;
    inout b4;
    inout b5;
    inout b6;
    inout b7;
    inout b8;
    inout b9;


    initial
        begin
        end

endmodule
