// generated by newgenasym  Mon Sep 05 21:28:27 2016


module max3051 (canh, canl, gnd, rs, rxd, shdn, txd, vcc);
    inout canh;
    inout canl;
    inout gnd;
    inout rs;
    inout rxd;
    inout shdn;
    inout txd;
    inout vcc;


    initial
        begin
        end

endmodule
