-- generated by newgenasym Mon Sep 05 21:28:27 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity max3051 is
    port (    
	CANH:      INOUT  STD_LOGIC;    
	CANL:      INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	RS:        INOUT  STD_LOGIC;    
	RXD:       INOUT  STD_LOGIC;    
	SHDN:      INOUT  STD_LOGIC;    
	TXD:       INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC);
end max3051;
