// generated by newgenasym  Mon Dec  1 16:28:14 2025


module ltc3260 (\adj+ , \adj- , \byp+ , \byp- , \c+ , \c- , \en+ , \en- , ep, \ldo+ , \ldo- , mode,
        nc, nc1, rt, vin, vout);
    inout \adj+ ;
    inout \adj- ;
    inout \byp+ ;
    inout \byp- ;
    inout \c+ ;
    inout \c- ;
    inout \en+ ;
    inout \en- ;
    inout ep;
    inout \ldo+ ;
    inout \ldo- ;
    inout mode;
    inout nc;
    inout nc1;
    inout rt;
    inout vin;
    inout vout;


    initial
        begin
        end

endmodule
