-- generated by newgenasym Mon Dec  1 16:28:14 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ltc3260 is
    port (    
	\adj+\:    INOUT  STD_LOGIC;    
	\adj-\:    INOUT  STD_LOGIC;    
	\byp+\:    INOUT  STD_LOGIC;    
	\byp-\:    INOUT  STD_LOGIC;    
	\c+\:      INOUT  STD_LOGIC;    
	\c-\:      INOUT  STD_LOGIC;    
	\en+\:     INOUT  STD_LOGIC;    
	\en-\:     INOUT  STD_LOGIC;    
	EP:        INOUT  STD_LOGIC;    
	\ldo+\:    INOUT  STD_LOGIC;    
	\ldo-\:    INOUT  STD_LOGIC;    
	MODE:      INOUT  STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC;    
	RT:        INOUT  STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC;    
	VOUT:      INOUT  STD_LOGIC);
end ltc3260;
