// generated by newgenasym  Tue Sep 06 16:46:01 2016


module \mpu-6000  (\ad0/sdo , aux_cl, aux_da, clkin, clkout, cpout, cs, fsync,
        gnd, int, nc1, nc2, nc3, nc4, nc5, nc6, nc7, nc8, regout, resv1,
        resv2, \scl/sclk , \sda/sdi , vdd);
    inout \ad0/sdo ;
    inout aux_cl;
    inout aux_da;
    inout clkin;
    inout clkout;
    inout cpout;
    inout cs;
    inout fsync;
    inout gnd;
    inout int;
    inout nc1;
    inout nc2;
    inout nc3;
    inout nc4;
    inout nc5;
    inout nc6;
    inout nc7;
    inout nc8;
    inout regout;
    inout resv1;
    inout resv2;
    inout \scl/sclk ;
    inout \sda/sdi ;
    inout vdd;


    initial
        begin
        end

endmodule
