-- generated by newgenasym Tue Sep 06 16:46:01 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \mpu-6000\ is
    port (    
	\ad0/sdo\: INOUT  STD_LOGIC;    
	AUX_CL:    INOUT  STD_LOGIC;    
	AUX_DA:    INOUT  STD_LOGIC;    
	CLKIN:     INOUT  STD_LOGIC;    
	CLKOUT:    INOUT  STD_LOGIC;    
	CPOUT:     INOUT  STD_LOGIC;    
	CS:        INOUT  STD_LOGIC;    
	FSYNC:     INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	INT:       INOUT  STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC;    
	NC2:       INOUT  STD_LOGIC;    
	NC3:       INOUT  STD_LOGIC;    
	NC4:       INOUT  STD_LOGIC;    
	NC5:       INOUT  STD_LOGIC;    
	NC6:       INOUT  STD_LOGIC;    
	NC7:       INOUT  STD_LOGIC;    
	NC8:       INOUT  STD_LOGIC;    
	REGOUT:    INOUT  STD_LOGIC;    
	RESV1:     INOUT  STD_LOGIC;    
	RESV2:     INOUT  STD_LOGIC;    
	\scl/sclk\: INOUT  STD_LOGIC;    
	\sda/sdi\: INOUT  STD_LOGIC;    
	VDD:       INOUT  STD_LOGIC);
end \mpu-6000\;
