-- generated by newgenasym Thu Nov 20 20:08:25 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity esd05 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC);
end esd05;
