-- generated by newgenasym Sat Jul 09 19:00:47 2005

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity dcjack is
    port (    
	GND:       INOUT  STD_LOGIC;    
	NOC:       INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC);
end dcjack;
