// generated by newgenasym  Fri Oct 11 12:48:34 2019


module ref5025 (dnc1, dnc2, gnd, nc, temp, \trim/nr , vin, vout);
    inout dnc1;
    inout dnc2;
    inout gnd;
    inout nc;
    inout temp;
    inout \trim/nr ;
    input vin;
    inout vout;


    initial
        begin
        end

endmodule
