// generated by newgenasym  Sun Mar 20 13:48:25 2016


module tl101wxh13 (\clkin+ , \clkin- , dvdd, gnd, led_en, nc, pwm, \rin0+ , \rin0- ,
        \rin1+ , \rin1- , \rin2+ , \rin2- , scl, sda, vdd, vled);
    inout \clkin+ ;
    inout \clkin- ;
    inout dvdd;
    inout [10:1] gnd;
    inout led_en;
    inout [14:1] nc;
    inout pwm;
    inout \rin0+ ;
    inout \rin0- ;
    inout \rin1+ ;
    inout \rin1- ;
    inout \rin2+ ;
    inout \rin2- ;
    inout scl;
    inout sda;
    inout [2:1] vdd;
    inout [3:1] vled;


    initial
        begin
        end

endmodule
