-- generated by newgenasym Sun Mar 20 13:48:25 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity TL101WXH13 is
    port (    
	\clkin+\:  INOUT  STD_LOGIC;    
	\clkin-\:  INOUT  STD_LOGIC;    
	DVDD:      INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC_VECTOR (10 DOWNTO 1);    
	LED_EN:    INOUT  STD_LOGIC;    
	NC:        INOUT  STD_LOGIC_VECTOR (14 DOWNTO 1);    
	PWM:       INOUT  STD_LOGIC;    
	\rin0+\:   INOUT  STD_LOGIC;    
	\rin0-\:   INOUT  STD_LOGIC;    
	\rin1+\:   INOUT  STD_LOGIC;    
	\rin1-\:   INOUT  STD_LOGIC;    
	\rin2+\:   INOUT  STD_LOGIC;    
	\rin2-\:   INOUT  STD_LOGIC;    
	SCL:       INOUT  STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC;    
	VDD:       INOUT  STD_LOGIC_VECTOR (2 DOWNTO 1);    
	VLED:      INOUT  STD_LOGIC_VECTOR (3 DOWNTO 1));
end TL101WXH13;
