// generated by newgenasym  Thu Oct 30 14:53:26 2014


module tsc2046ipwr (\+vcc , aux, busy, \cs* , dclk, din, dout, gnd, iovdd, \penirq* ,
        vbat, vref, \x+ , \x- , \y+ , \y- );
    input \+vcc ;
    input aux;
    output busy;
    input \cs* ;
    input dclk;
    input din;
    output dout;
    input gnd;
    input iovdd;
    output \penirq* ;
    input vbat;
    input vref;
    output \x+ ;
    output \x- ;
    output \y+ ;
    output \y- ;


    initial
        begin
        end

endmodule
