-- generated by newgenasym Thu Oct 30 14:53:26 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tsc2046ipwr is
    port (    
	\+vcc\:    IN     STD_LOGIC;    
	AUX:       IN     STD_LOGIC;    
	BUSY:      OUT    STD_LOGIC;    
	\cs*\:     IN     STD_LOGIC;    
	DCLK:      IN     STD_LOGIC;    
	DIN:       IN     STD_LOGIC;    
	DOUT:      OUT    STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	IOVDD:     IN     STD_LOGIC;    
	\penirq*\: OUT    STD_LOGIC;    
	VBAT:      IN     STD_LOGIC;    
	VREF:      IN     STD_LOGIC;    
	\x+\:      OUT    STD_LOGIC;    
	\x-\:      OUT    STD_LOGIC;    
	\y+\:      OUT    STD_LOGIC;    
	\y-\:      OUT    STD_LOGIC);
end tsc2046ipwr;
