// generated by newgenasym  Wed Jan 23 21:33:49 2008


module \6pin  (pin1, pin2, pin3, pin4, pin5, pin6);
    inout pin1;
    inout pin2;
    inout pin3;
    inout pin4;
    inout pin5;
    inout pin6;


    initial
        begin
        end

endmodule
