-- generated by newgenasym Wed Jan 23 21:33:49 2008

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \6pin\ is
    port (    
	PIN1:      INOUT  STD_LOGIC;    
	PIN2:      INOUT  STD_LOGIC;    
	PIN3:      INOUT  STD_LOGIC;    
	PIN4:      INOUT  STD_LOGIC;    
	PIN5:      INOUT  STD_LOGIC;    
	PIN6:      INOUT  STD_LOGIC);
end \6pin\;
