// generated by newgenasym  Wed Nov 19 15:30:30 2014


module \88e1518  (avdd18_1, avdd18_2, avdd18_out, avdd33_1, avdd33_2,
        avddc18, clk125, config, dvdd1, dvdd2, dvdd_out, hsdacn,
        hsdacp, led0, led1, \led2/int_n* , mdc, mdin0, mdin1, mdin2,
        mdin3, mdio, mdip0, mdip1, mdip2, mdip3, reg_in, regcap1,
        regcap2, \resetn* , rset, rx_clk, rx_ctrl, rxd0, rxd1, rxd2,
        rxd3, tx_clk, tx_ctrl, txd0, txd1, txd2, txd3, vddo1, vddo2,
        vddo3, vss, xtal_in, xtal_out);
    inout avdd18_1;
    inout avdd18_2;
    inout avdd18_out;
    inout avdd33_1;
    inout avdd33_2;
    inout avddc18;
    inout clk125;
    inout config;
    inout dvdd1;
    inout dvdd2;
    inout dvdd_out;
    inout hsdacn;
    inout hsdacp;
    inout led0;
    inout led1;
    output \led2/int_n* ;
    inout mdc;
    inout mdin0;
    inout mdin1;
    inout mdin2;
    inout mdin3;
    inout mdio;
    inout mdip0;
    inout mdip1;
    inout mdip2;
    inout mdip3;
    inout reg_in;
    inout regcap1;
    inout regcap2;
    inout \resetn* ;
    inout rset;
    inout rx_clk;
    inout rx_ctrl;
    inout rxd0;
    inout rxd1;
    inout rxd2;
    inout rxd3;
    inout tx_clk;
    inout tx_ctrl;
    inout txd0;
    inout txd1;
    inout txd2;
    inout txd3;
    inout vddo1;
    inout vddo2;
    inout vddo3;
    inout vss;
    inout xtal_in;
    inout xtal_out;


    initial
        begin
        end

endmodule
