-- generated by newgenasym Wed Apr 17 21:35:56 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity head2x5 is
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (10 DOWNTO 1));
end head2x5;
