// generated by newgenasym  Sun Sep 16 20:28:53 2012


module tvp5158pnpr (ain_1, ain_2, ain_3, ain_4, bclk_ci, bclk_r, dvo_a_, dvo_b_,
        dvo_c_, dvo_d_, i2ca0, i2ca1, i2ca2, intreq, lrclk_ci,
        lrclk_r, nc, \oclk_n/clkin , oclk_p, osc_out, resetb, rext_2k,
        scl, sd_ci, sd_co, sd_m, sd_r, sda, t1, t2, t3, t4, t5, tap,
        vdd_1v1_1, vdd_1v1_10, vdd_1v1_11, vdd_1v1_2, vdd_1v1_3,
        vdd_1v1_4, vdd_1v1_5, vdd_1v1_6, vdd_1v1_7, vdd_1v1_8,
        vdd_1v1_9, vdd_3v3_1, vdda_1v1_1, vdda_1v1_2, vdda_1v1_3,
        vdda_1v8_1, vdda_1v8_2, vdda_1v8_3, vdda_1v8_4,
        vdda_1v8_5, vdda_1v8_6, vdda_1v8_7, vdda_3v3, \vin_1* ,
        vin_1_p, \vin_2* , vin_2_p, \vin_3* , vin_3_p, \vin_4* , vin_4_p,
        vss_1, vss_10, vss_11, vss_12, vss_13, vss_14, vss_15,
        vss_16, vss_17, vss_18, vss_2, vss_3, vss_4, vss_5, vss_6,
        vss_7, vss_8, vss_9, vssa_1, vssa_10, vssa_2, vssa_3, vssa_4,
        vssa_5, vssa_6, vssa_7, vssa_8, vssa_9, xtal_in, xtal_out,
        xtal_ref);
    input ain_1;
    input ain_2;
    input ain_3;
    input ain_4;
    input bclk_ci;
    inout bclk_r;
    output [7:0] dvo_a_;
    output [7:0] dvo_b_;
    inout [7:0] dvo_c_;
    inout [7:0] dvo_d_;
    input i2ca0;
    input i2ca1;
    input i2ca2;
    output intreq;
    input lrclk_ci;
    inout lrclk_r;
    inout nc;
    inout \oclk_n/clkin ;
    output oclk_p;
    output osc_out;
    input resetb;
    input rext_2k;
    inout scl;
    input sd_ci;
    output sd_co;
    output sd_m;
    output sd_r;
    inout sda;
    inout t1;
    inout t2;
    inout t3;
    inout t4;
    inout t5;
    input tap;
    input vdd_1v1_1;
    input vdd_1v1_10;
    input vdd_1v1_11;
    input vdd_1v1_2;
    input vdd_1v1_3;
    input vdd_1v1_4;
    input vdd_1v1_5;
    input vdd_1v1_6;
    input vdd_1v1_7;
    input vdd_1v1_8;
    input vdd_1v1_9;
    input [6:1] vdd_3v3_1;
    input vdda_1v1_1;
    input vdda_1v1_2;
    input vdda_1v1_3;
    input vdda_1v8_1;
    input vdda_1v8_2;
    input vdda_1v8_3;
    input vdda_1v8_4;
    input vdda_1v8_5;
    input vdda_1v8_6;
    input vdda_1v8_7;
    input vdda_3v3;
    input \vin_1* ;
    input vin_1_p;
    input \vin_2* ;
    input vin_2_p;
    input \vin_3* ;
    input vin_3_p;
    input \vin_4* ;
    input vin_4_p;
    input vss_1;
    input vss_10;
    input vss_11;
    input vss_12;
    input vss_13;
    input vss_14;
    input vss_15;
    input vss_16;
    input vss_17;
    input vss_18;
    input vss_2;
    input vss_3;
    input vss_4;
    input vss_5;
    input vss_6;
    input vss_7;
    input vss_8;
    input vss_9;
    input vssa_1;
    input vssa_10;
    input vssa_2;
    input vssa_3;
    input vssa_4;
    input vssa_5;
    input vssa_6;
    input vssa_7;
    input vssa_8;
    input vssa_9;
    input xtal_in;
    output xtal_out;
    input xtal_ref;


    initial
        begin
        end

endmodule
