// generated by newgenasym  Tue Dec 11 20:23:41 2012


module tmds141rhar (gnd1, gnd2, gnd3, gnd4, gnd5, gnd6, gnd7, gnd8, i2cen, \oe* ,
        ovs, pre, rscl, rsda, rx0, \rx0* , rx1, \rx1* , rx2, \rx2* , rxc, \rxc* ,
        tscl, tsda, tx0, \tx0* , tx1, \tx1* , tx2, \tx2* , txc, \txc* , vcc1,
        vcc2, vcc3, vcc4, vcc5, vcc6, vcc7, vsadj);
    input gnd1;
    input gnd2;
    input gnd3;
    input gnd4;
    input gnd5;
    input gnd6;
    input gnd7;
    input gnd8;
    input i2cen;
    input \oe* ;
    inout ovs;
    inout pre;
    inout rscl;
    inout rsda;
    inout rx0;
    inout \rx0* ;
    inout rx1;
    inout \rx1* ;
    inout rx2;
    inout \rx2* ;
    inout rxc;
    inout \rxc* ;
    inout tscl;
    inout tsda;
    inout tx0;
    inout \tx0* ;
    inout tx1;
    inout \tx1* ;
    inout tx2;
    inout \tx2* ;
    inout txc;
    inout \txc* ;
    input vcc1;
    input vcc2;
    input vcc3;
    input vcc4;
    input vcc5;
    input vcc6;
    input vcc7;
    inout vsadj;


    initial
        begin
        end

endmodule
