-- generated by newgenasym Tue Dec 11 20:23:41 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tmds141rhar is
    port (    
	GND1:      IN     STD_LOGIC;    
	GND2:      IN     STD_LOGIC;    
	GND3:      IN     STD_LOGIC;    
	GND4:      IN     STD_LOGIC;    
	GND5:      IN     STD_LOGIC;    
	GND6:      IN     STD_LOGIC;    
	GND7:      IN     STD_LOGIC;    
	GND8:      IN     STD_LOGIC;    
	I2CEN:     IN     STD_LOGIC;    
	\oe*\:     IN     STD_LOGIC;    
	OVS:       INOUT  STD_LOGIC;    
	PRE:       INOUT  STD_LOGIC;    
	RSCL:      INOUT  STD_LOGIC;    
	RSDA:      INOUT  STD_LOGIC;    
	RX0:       INOUT  STD_LOGIC;    
	\rx0*\:    INOUT  STD_LOGIC;    
	RX1:       INOUT  STD_LOGIC;    
	\rx1*\:    INOUT  STD_LOGIC;    
	RX2:       INOUT  STD_LOGIC;    
	\rx2*\:    INOUT  STD_LOGIC;    
	RXC:       INOUT  STD_LOGIC;    
	\rxc*\:    INOUT  STD_LOGIC;    
	TSCL:      INOUT  STD_LOGIC;    
	TSDA:      INOUT  STD_LOGIC;    
	TX0:       INOUT  STD_LOGIC;    
	\tx0*\:    INOUT  STD_LOGIC;    
	TX1:       INOUT  STD_LOGIC;    
	\tx1*\:    INOUT  STD_LOGIC;    
	TX2:       INOUT  STD_LOGIC;    
	\tx2*\:    INOUT  STD_LOGIC;    
	TXC:       INOUT  STD_LOGIC;    
	\txc*\:    INOUT  STD_LOGIC;    
	VCC1:      IN     STD_LOGIC;    
	VCC2:      IN     STD_LOGIC;    
	VCC3:      IN     STD_LOGIC;    
	VCC4:      IN     STD_LOGIC;    
	VCC5:      IN     STD_LOGIC;    
	VCC6:      IN     STD_LOGIC;    
	VCC7:      IN     STD_LOGIC;    
	VSADJ:     INOUT  STD_LOGIC);
end tmds141rhar;
