// generated by newgenasym  Mon Oct 14 19:10:17 2019


module ths4503 (\pd* , \vin+ , \vin- , vocm, \vout+ , \vout- , \vs+ , \vs- );
    inout \pd* ;
    inout \vin+ ;
    inout \vin- ;
    inout vocm;
    inout \vout+ ;
    inout \vout- ;
    inout \vs+ ;
    inout \vs- ;


    initial
        begin
        end

endmodule
