-- generated by newgenasym Mon Oct 14 19:10:17 2019

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ths4503 is
    port (    
	\pd*\:     INOUT  STD_LOGIC;    
	\vin+\:    INOUT  STD_LOGIC;    
	\vin-\:    INOUT  STD_LOGIC;    
	VOCM:      INOUT  STD_LOGIC;    
	\vout+\:   INOUT  STD_LOGIC;    
	\vout-\:   INOUT  STD_LOGIC;    
	\vs+\:     INOUT  STD_LOGIC;    
	\vs-\:     INOUT  STD_LOGIC);
end ths4503;
