// generated by newgenasym  Mon Oct 22 14:48:29 2012


module ads7841e (busy, ch0, ch1, ch2, ch3, com, \cs* , dclk, din, dout, gnd, mode,
        \shdn* , vcc1, vcc2, vref);
    output busy;
    input ch0;
    input ch1;
    input ch2;
    input ch3;
    input com;
    input \cs* ;
    input dclk;
    input din;
    output dout;
    input gnd;
    input mode;
    input \shdn* ;
    input vcc1;
    input vcc2;
    input vref;


    initial
        begin
        end

endmodule
