-- generated by newgenasym Mon Oct 22 14:48:29 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ads7841e is
    port (    
	BUSY:      OUT    STD_LOGIC;    
	CH0:       IN     STD_LOGIC;    
	CH1:       IN     STD_LOGIC;    
	CH2:       IN     STD_LOGIC;    
	CH3:       IN     STD_LOGIC;    
	COM:       IN     STD_LOGIC;    
	\cs*\:     IN     STD_LOGIC;    
	DCLK:      IN     STD_LOGIC;    
	DIN:       IN     STD_LOGIC;    
	DOUT:      OUT    STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	MODE:      IN     STD_LOGIC;    
	\shdn*\:   IN     STD_LOGIC;    
	VCC1:      IN     STD_LOGIC;    
	VCC2:      IN     STD_LOGIC;    
	VREF:      IN     STD_LOGIC);
end ads7841e;
