// generated by newgenasym  Fri Oct 11 16:00:22 2019


module op284 (\+ina , \+inb , \-ina , \-inb , outa, outb, \v+ , \v- );
    inout \+ina ;
    inout \+inb ;
    inout \-ina ;
    inout \-inb ;
    inout outa;
    inout outb;
    inout \v+ ;
    inout \v- ;


    initial
        begin
        end

endmodule
