-- generated by newgenasym Fri Oct 11 16:00:22 2019

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity op284 is
    port (    
	\+ina\:    INOUT  STD_LOGIC;    
	\+inb\:    INOUT  STD_LOGIC;    
	\-ina\:    INOUT  STD_LOGIC;    
	\-inb\:    INOUT  STD_LOGIC;    
	OUTA:      INOUT  STD_LOGIC;    
	OUTB:      INOUT  STD_LOGIC;    
	\v+\:      INOUT  STD_LOGIC;    
	\v-\:      INOUT  STD_LOGIC);
end op284;
