// generated by newgenasym  Fri May 25 12:42:10 2018


module ksz9896 (avddh1, avddh2, avddh3, avddh4, avddh5, avddh6, avddh7,
        avddl1, avddl2, avddl3, avddl4, avddl5, avddl6, avddl7,
        avddl8, avddl9, clko_25_125, col6, crs6, dvddl1, dvddl2,
        dvddl3, dvddl4, dvddl5, dvddl6, dvddl7, dvddl8, dvddl9, gnd1,
        gnd2, gnd3, gnd4, gnd5, gnd6, gnd7, gnd8, gnd9, \intrp* , iset,
        led1_0, led1_1, led2_0, led2_1, led3_0, led3_1, led4_0,
        led4_1, led5_0, led5_1, nc, \pme* , \reset* , rx_clk6, rx_dv6,
        \rx_er6/rx_clk6 , rxd6_0, rxd6_1, rxd6_2, rxd6_3, rxd6_4,
        rxd6_5, rxd6_6, rxd6_7, \scl/mdc , \scs* , \sdi/sda/mdio , sdo,
        \tx_clk6/refclki6 , \tx_en6/tx_ctl6 , tx_er6, txd6_0, txd6_1,
        txd6_2, txd6_3, txd6_4, txd6_5, txd6_6, txd6_7, txrx1m_a,
        txrx1m_b, txrx1m_c, txrx1m_d, txrx1p_a, txrx1p_b, txrx1p_c,
        txrx1p_d, txrx2m_a, txrx2m_b, txrx2m_c, txrx2m_d, txrx2p_a,
        txrx2p_b, txrx2p_c, txrx2p_d, txrx3m_a, txrx3m_b, txrx3m_c,
        txrx3m_d, txrx3p_a, txrx3p_b, txrx3p_c, txrx3p_d, txrx4m_a,
        txrx4m_b, txrx4m_c, txrx4m_d, txrx4p_a, txrx4p_b, txrx4p_c,
        txrx4p_d, txrx5m_a, txrx5m_b, txrx5m_c, txrx5m_d, txrx5p_a,
        txrx5p_b, txrx5p_c, txrx5p_d, vddio1, vddio2, vddio3,
        vddio4, xi, xo);
    inout avddh1;
    inout avddh2;
    inout avddh3;
    inout avddh4;
    inout avddh5;
    inout avddh6;
    inout avddh7;
    inout avddl1;
    inout avddl2;
    inout avddl3;
    inout avddl4;
    inout avddl5;
    inout avddl6;
    inout avddl7;
    inout avddl8;
    inout avddl9;
    inout clko_25_125;
    inout col6;
    inout crs6;
    inout dvddl1;
    inout dvddl2;
    inout dvddl3;
    inout dvddl4;
    inout dvddl5;
    inout dvddl6;
    inout dvddl7;
    inout dvddl8;
    inout dvddl9;
    inout gnd1;
    inout gnd2;
    inout gnd3;
    inout gnd4;
    inout gnd5;
    inout gnd6;
    inout gnd7;
    inout gnd8;
    inout gnd9;
    inout \intrp* ;
    inout iset;
    inout led1_0;
    inout led1_1;
    inout led2_0;
    inout led2_1;
    inout led3_0;
    inout led3_1;
    inout led4_0;
    inout led4_1;
    inout led5_0;
    inout led5_1;
    inout [6:1] nc;
    inout \pme* ;
    inout \reset* ;
    inout rx_clk6;
    inout rx_dv6;
    inout \rx_er6/rx_clk6 ;
    inout rxd6_0;
    inout rxd6_1;
    inout rxd6_2;
    inout rxd6_3;
    inout rxd6_4;
    inout rxd6_5;
    inout rxd6_6;
    inout rxd6_7;
    inout \scl/mdc ;
    inout \scs* ;
    inout \sdi/sda/mdio ;
    inout sdo;
    inout \tx_clk6/refclki6 ;
    inout \tx_en6/tx_ctl6 ;
    inout tx_er6;
    inout txd6_0;
    inout txd6_1;
    inout txd6_2;
    inout txd6_3;
    inout txd6_4;
    inout txd6_5;
    inout txd6_6;
    inout txd6_7;
    inout txrx1m_a;
    inout txrx1m_b;
    inout txrx1m_c;
    inout txrx1m_d;
    inout txrx1p_a;
    inout txrx1p_b;
    inout txrx1p_c;
    inout txrx1p_d;
    inout txrx2m_a;
    inout txrx2m_b;
    inout txrx2m_c;
    inout txrx2m_d;
    inout txrx2p_a;
    inout txrx2p_b;
    inout txrx2p_c;
    inout txrx2p_d;
    inout txrx3m_a;
    inout txrx3m_b;
    inout txrx3m_c;
    inout txrx3m_d;
    inout txrx3p_a;
    inout txrx3p_b;
    inout txrx3p_c;
    inout txrx3p_d;
    inout txrx4m_a;
    inout txrx4m_b;
    inout txrx4m_c;
    inout txrx4m_d;
    inout txrx4p_a;
    inout txrx4p_b;
    inout txrx4p_c;
    inout txrx4p_d;
    inout txrx5m_a;
    inout txrx5m_b;
    inout txrx5m_c;
    inout txrx5m_d;
    inout txrx5p_a;
    inout txrx5p_b;
    inout txrx5p_c;
    inout txrx5p_d;
    inout vddio1;
    inout vddio2;
    inout vddio3;
    inout vddio4;
    inout xi;
    inout xo;


    initial
        begin
        end

endmodule
