// generated by newgenasym  Tue Jun 28 14:10:32 2005


module \osc-4  (gnd, nnc, out, vdd);
    input gnd;
    input nnc;
    output out;
    input vdd;


    initial
        begin
        end

endmodule
