-- generated by newgenasym Mon Aug 12 13:55:38 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ref3030 is
    port (    
	GND:       INOUT  STD_LOGIC;    
	\in\:      IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC);
end ref3030;
