// generated by newgenasym  Sat Jun 01 19:12:02 2013


module tps22913 (gnd, on, vin, vout);
    inout gnd;
    inout on;
    inout vin;
    inout vout;


    initial
        begin
        end

endmodule
