-- generated by newgenasym Sat Jun 01 19:12:02 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tps22913 is
    port (    
	GND:       INOUT  STD_LOGIC;    
	\on\:      INOUT  STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC;    
	VOUT:      INOUT  STD_LOGIC);
end tps22913;
