// generated by newgenasym  Fri Feb 14 15:33:18 2014


module xc6slx45fgg484 (cmpcs_b_2, done_2, gnd_a1, gnd_a22, gnd_aa13, gnd_aa17,
        gnd_aa5, gnd_aa9, gnd_ab1, gnd_ab22, gnd_b13, gnd_b17,
        gnd_b5, gnd_b9, gnd_d18, gnd_d4, gnd_e11, gnd_e15, gnd_e2,
        gnd_e21, gnd_e7, gnd_g18, gnd_g5, gnd_h7, gnd_j11, gnd_j13,
        gnd_j15, gnd_j2, gnd_j21, gnd_j9, gnd_k10, gnd_k12, gnd_k14,
        gnd_l11, gnd_l13, gnd_l18, gnd_l5, gnd_l9, gnd_m10, gnd_m12,
        gnd_m14, gnd_n11, gnd_n13, gnd_n17, gnd_n2, gnd_n21, gnd_n9,
        gnd_p10, gnd_p12, gnd_p14, gnd_r18, gnd_r5, gnd_u2, gnd_u21,
        gnd_u7, gnd_v10, gnd_v14, gnd_v4, gnd_w16, gnd_w19, gnd_w7,
        io_l10n_1, io_l10n_2, io_l10n_3, io_l10p_1, io_l10p_2,
        io_l10p_3, io_l11n_2, io_l11n_3, io_l11p_2, io_l11p_3,
        io_l12n_d2_miso3_2, io_l12p_d1_miso2_2, io_l13n_d10_2,
        io_l13p_m1_2, io_l14n_d12_2, io_l14p_d11_2, io_l15n_2,
        io_l15p_2, io_l16n_vref_2, io_l16p_2, io_l17n_2,
        io_l17p_2, io_l18n_2, io_l18p_2, io_l19n_1, io_l19n_2,
        io_l19p_1, io_l19p_2, io_l1n_a24_vref_1,
        io_l1n_m0_cmpmiso_2, io_l1n_vref_0, io_l1n_vref_3,
        io_l1p_3, io_l1p_a25_1, io_l1p_cclk_2, io_l1p_hswapen_0,
        io_l20n_1, io_l20n_2, io_l20p_1, io_l20p_2, io_l21n_1,
        io_l21n_2, io_l21p_1, io_l21p_2, io_l22n_2, io_l22p_2,
        io_l23n_2, io_l23n_3, io_l23p_2, io_l23p_3, io_l24n_3,
        io_l24p_3, io_l25n_3, io_l25p_3, io_l26n_3, io_l26p_3,
        io_l28n_vref_1, io_l28p_1, io_l29n_a22_m1a14_1,
        io_l29n_gclk2_2, io_l29p_a23_m1a13_1, io_l29p_gclk3_2,
        io_l2n_0, io_l2n_3, io_l2n_cmpmosi_2, io_l2p_0, io_l2p_3,
        io_l2p_cmpclk_2, io_l30n_a20_m1a11_1,
        io_l30n_gclk0_usercclk_2, io_l30p_a21_m1reset_1,
        io_l30p_gclk1_d13_2, io_l31n_a18_m1a12_1,
        io_l31n_gclk30_d15_2, io_l31n_vref_3, io_l31p_3,
        io_l31p_a19_m1cke_1, io_l31p_gclk31_d14_2, io_l32n_0,
        io_l32n_a16_m1a9_1, io_l32n_gclk28_2, io_l32n_m3dq15_3,
        io_l32p_0, io_l32p_a17_m1a8_1, io_l32p_gclk29_2,
        io_l32p_m3dq14_3, io_l33n_0, io_l33n_a14_m1a4_1,
        io_l33n_m3dq13_3, io_l33p_0, io_l33p_a15_m1a10_1,
        io_l33p_m3dq12_3, io_l34n_a12_m1ba2_1, io_l34n_gclk18_0,
        io_l34n_m3udqsn_3, io_l34p_a13_m1we_1, io_l34p_gclk19_0,
        io_l34p_m3udqs_3, io_l35n_a10_m1a2_1, io_l35n_gclk16_0,
        io_l35n_m3dq11_3, io_l35p_a11_m1a7_1, io_l35p_gclk17_0,
        io_l35p_m3dq10_3, io_l36n_a8_m1ba1_1, io_l36n_gclk14_0,
        io_l36n_m3dq9_3, io_l36p_a9_m1ba0_1, io_l36p_gclk15_0,
        io_l36p_m3dq8_3, io_l37n_a6_m1a1_1, io_l37n_gclk12_0,
        io_l37n_m3dq1_3, io_l37p_a7_m1a0_1, io_l37p_gclk13_0,
        io_l37p_m3dq0_3, io_l38n_a4_m1clkn_1, io_l38n_m3dq3_3,
        io_l38n_vref_0, io_l38p_0, io_l38p_a5_m1clk_1,
        io_l38p_m3dq2_3, io_l39n_m1odt_1, io_l39n_m3ldqsn_3,
        io_l39p_m1a3_1, io_l39p_m3ldqs_3, io_l3n_0,
        io_l3n_mosi_csi_b_miso0_2, io_l3p_0,
        io_l3p_d0_din_miso_miso1_2, io_l40n_2,
        io_l40n_gclk10_m1a6_1, io_l40n_m3dq7_3, io_l40p_2,
        io_l40p_gclk11_m1a5_1, io_l40p_m3dq6_3,
        io_l41n_gclk26_m3dq5_3, io_l41n_gclk8_m1casn_1,
        io_l41n_vref_2, io_l41p_2, io_l41p_gclk27_m3dq4_3,
        io_l41p_gclk9_irdy1_m1rasn_1, io_l42n_2,
        io_l42n_gclk24_m3ldm_3, io_l42n_gclk6_trdy1_m1ldm_1,
        io_l42p_2, io_l42p_gclk25_trdy2_m3udm_3,
        io_l42p_gclk7_m1udm_1, io_l43n_2,
        io_l43n_gclk22_irdy2_m3casn_3, io_l43n_gclk4_m1dq5_1,
        io_l43p_2, io_l43p_gclk23_m3rasn_3,
        io_l43p_gclk5_m1dq4_1, io_l44n_2, io_l44n_a2_m1dq7_1,
        io_l44n_gclk20_m3a6_3, io_l44p_2, io_l44p_a3_m1dq6_1,
        io_l44p_gclk21_m3a5_3, io_l45n_2, io_l45n_a0_m1ldqsn_1,
        io_l45n_m3odt_3, io_l45p_2, io_l45p_a1_m1ldqs_1,
        io_l45p_m3a3_3, io_l46n_2, io_l46n_foe_b_m1dq3_1,
        io_l46n_m3clkn_3, io_l46p_2, io_l46p_fcs_b_m1dq2_1,
        io_l46p_m3clk_3, io_l47n_2, io_l47n_ldc_m1dq1_1,
        io_l47n_m3a1_3, io_l47p_2, io_l47p_fwe_b_m1dq0_1,
        io_l47p_m3a0_3, io_l48n_m1dq9_1, io_l48n_m3ba1_3,
        io_l48n_rdwr_b_vref_2, io_l48p_d7_2,
        io_l48p_hdc_m1dq8_1, io_l48p_m3ba0_3, io_l49n_0,
        io_l49n_d4_2, io_l49n_m1dq11_1, io_l49n_m3a2_3,
        io_l49p_0, io_l49p_d3_2, io_l49p_m1dq10_1,
        io_l49p_m3a7_3, io_l4n_0, io_l4n_vref_2, io_l4p_0,
        io_l4p_2, io_l50n_0, io_l50n_2, io_l50n_m1udqsn_1,
        io_l50n_m3ba2_3, io_l50p_0, io_l50p_2, io_l50p_m1udqs_1,
        io_l50p_m3we_3, io_l51n_0, io_l51n_2, io_l51n_m1dq13_1,
        io_l51n_m3a4_3, io_l51p_0, io_l51p_2, io_l51p_m1dq12_1,
        io_l51p_m3a10_3, io_l52n_2, io_l52n_m1dq15_1,
        io_l52n_m3a9_3, io_l52p_2, io_l52p_m1dq14_1,
        io_l52p_m3a8_3, io_l53n_2, io_l53n_m3a12_3,
        io_l53n_vref_1, io_l53p_1, io_l53p_2, io_l53p_m3cke_3,
        io_l54n_2, io_l54n_m3a11_3, io_l54p_2, io_l54p_m3reset_3,
        io_l55n_m3a14_3, io_l55p_m3a13_3, io_l57n_2,
        io_l57n_vref_3, io_l57p_2, io_l57p_3, io_l58n_1,
        io_l58n_2, io_l58n_3, io_l58p_1, io_l58p_2, io_l58p_3,
        io_l59n_1, io_l59n_2, io_l59n_3, io_l59p_1, io_l59p_2,
        io_l59p_3, io_l5n_0, io_l5n_2, io_l5p_0, io_l5p_2,
        io_l60n_1, io_l60n_2, io_l60n_3, io_l60p_1, io_l60p_2,
        io_l60p_3, io_l61n_1, io_l61p_1, io_l62n_d6_2,
        io_l62n_vref_0, io_l62p_0, io_l62p_d5_2, io_l63n_2,
        io_l63n_scp6_0, io_l63p_2, io_l63p_scp7_0, io_l64n_d9_2,
        io_l64n_scp4_0, io_l64p_d8_2, io_l64p_scp5_0,
        io_l65n_cso_b_2, io_l65n_scp2_0, io_l65p_init_b_2,
        io_l65p_scp3_0, io_l66n_scp0_0, io_l66p_scp1_0, io_l6n_0,
        io_l6n_2, io_l6p_0, io_l6p_2, io_l70n_1, io_l70p_1,
        io_l71n_1, io_l71p_1, io_l72n_1, io_l72p_1, io_l73n_1,
        io_l73p_1, io_l74n_dout_busy_1, io_l74p_awake_1,
        io_l7n_0, io_l7n_2, io_l7n_3, io_l7p_0, io_l7p_2, io_l7p_3,
        io_l80n_3, io_l80p_3, io_l81n_3, io_l81p_3, io_l82n_3,
        io_l82p_3, io_l83n_vref_3, io_l83p_3, io_l8n_2, io_l8n_3,
        io_l8n_vref_0, io_l8p_0, io_l8p_2, io_l8p_3, io_l9n_1,
        io_l9n_2, io_l9n_3, io_l9p_1, io_l9p_2, io_l9p_3, nc,
        program_b_2, suspend, tck, tdi, tdo, tms, vccaux_d16,
        vccaux_f11, vccaux_g12, vccaux_h15, vccaux_h9, vccaux_k15,
        vccaux_l8, vccaux_m15, vccaux_n8, vccaux_r10, vccaux_r12,
        vccaux_r6, vccaux_u11, vccaux_v6, vccint_j10, vccint_j12,
        vccint_j14, vccint_j8, vccint_k11, vccint_k13, vccint_k9,
        vccint_l10, vccint_l12, vccint_l14, vccint_m11,
        vccint_m13, vccint_m9, vccint_n10, vccint_n12, vccint_n14,
        vccint_p11, vccint_p13, vccint_p9, vccint_r14, vcco_0_b11,
        vcco_0_b15, vcco_0_b19, vcco_0_b4, vcco_0_b7, vcco_0_e13,
        vcco_0_e17, vcco_0_e9, vcco_0_g10, vcco_0_g14, vcco_1_c21,
        vcco_1_e19, vcco_1_g21, vcco_1_j18, vcco_1_l16,
        vcco_1_l21, vcco_1_n18, vcco_1_r21, vcco_1_u18,
        vcco_1_w21, vcco_2_aa11, vcco_2_aa15, vcco_2_aa19,
        vcco_2_aa3, vcco_2_aa7, vcco_2_t13, vcco_2_t9, vcco_2_v12,
        vcco_2_v16, vcco_2_v8, vcco_2_w5, vcco_3_c2, vcco_3_f4,
        vcco_3_f6, vcco_3_g2, vcco_3_j5, vcco_3_l2, vcco_3_l7,
        vcco_3_n5, vcco_3_r2, vcco_3_u5, vcco_3_w2);
    input cmpcs_b_2;
    inout done_2;
    input gnd_a1;
    input gnd_a22;
    input gnd_aa13;
    input gnd_aa17;
    input gnd_aa5;
    input gnd_aa9;
    input gnd_ab1;
    input gnd_ab22;
    input gnd_b13;
    input gnd_b17;
    input gnd_b5;
    input gnd_b9;
    input gnd_d18;
    input gnd_d4;
    input gnd_e11;
    input gnd_e15;
    input gnd_e2;
    input gnd_e21;
    input gnd_e7;
    input gnd_g18;
    input gnd_g5;
    input gnd_h7;
    input gnd_j11;
    input gnd_j13;
    input gnd_j15;
    input gnd_j2;
    input gnd_j21;
    input gnd_j9;
    input gnd_k10;
    input gnd_k12;
    input gnd_k14;
    input gnd_l11;
    input gnd_l13;
    input gnd_l18;
    input gnd_l5;
    input gnd_l9;
    input gnd_m10;
    input gnd_m12;
    input gnd_m14;
    input gnd_n11;
    input gnd_n13;
    input gnd_n17;
    input gnd_n2;
    input gnd_n21;
    input gnd_n9;
    input gnd_p10;
    input gnd_p12;
    input gnd_p14;
    input gnd_r18;
    input gnd_r5;
    input gnd_u2;
    input gnd_u21;
    input gnd_u7;
    input gnd_v10;
    input gnd_v14;
    input gnd_v4;
    input gnd_w16;
    input gnd_w19;
    input gnd_w7;
    inout io_l10n_1;
    inout io_l10n_2;
    inout io_l10n_3;
    inout io_l10p_1;
    inout io_l10p_2;
    inout io_l10p_3;
    inout io_l11n_2;
    inout io_l11n_3;
    inout io_l11p_2;
    inout io_l11p_3;
    inout io_l12n_d2_miso3_2;
    inout io_l12p_d1_miso2_2;
    inout io_l13n_d10_2;
    inout io_l13p_m1_2;
    inout io_l14n_d12_2;
    inout io_l14p_d11_2;
    inout io_l15n_2;
    inout io_l15p_2;
    inout io_l16n_vref_2;
    inout io_l16p_2;
    inout io_l17n_2;
    inout io_l17p_2;
    inout io_l18n_2;
    inout io_l18p_2;
    inout io_l19n_1;
    inout io_l19n_2;
    inout io_l19p_1;
    inout io_l19p_2;
    inout io_l1n_a24_vref_1;
    inout io_l1n_m0_cmpmiso_2;
    inout io_l1n_vref_0;
    inout io_l1n_vref_3;
    inout io_l1p_3;
    inout io_l1p_a25_1;
    inout io_l1p_cclk_2;
    inout io_l1p_hswapen_0;
    inout io_l20n_1;
    inout io_l20n_2;
    inout io_l20p_1;
    inout io_l20p_2;
    inout io_l21n_1;
    inout io_l21n_2;
    inout io_l21p_1;
    inout io_l21p_2;
    inout io_l22n_2;
    inout io_l22p_2;
    inout io_l23n_2;
    inout io_l23n_3;
    inout io_l23p_2;
    inout io_l23p_3;
    inout io_l24n_3;
    inout io_l24p_3;
    inout io_l25n_3;
    inout io_l25p_3;
    inout io_l26n_3;
    inout io_l26p_3;
    inout io_l28n_vref_1;
    inout io_l28p_1;
    inout io_l29n_a22_m1a14_1;
    inout io_l29n_gclk2_2;
    inout io_l29p_a23_m1a13_1;
    inout io_l29p_gclk3_2;
    inout io_l2n_0;
    inout io_l2n_3;
    inout io_l2n_cmpmosi_2;
    inout io_l2p_0;
    inout io_l2p_3;
    inout io_l2p_cmpclk_2;
    inout io_l30n_a20_m1a11_1;
    inout io_l30n_gclk0_usercclk_2;
    inout io_l30p_a21_m1reset_1;
    inout io_l30p_gclk1_d13_2;
    inout io_l31n_a18_m1a12_1;
    inout io_l31n_gclk30_d15_2;
    inout io_l31n_vref_3;
    inout io_l31p_3;
    inout io_l31p_a19_m1cke_1;
    inout io_l31p_gclk31_d14_2;
    inout io_l32n_0;
    inout io_l32n_a16_m1a9_1;
    inout io_l32n_gclk28_2;
    inout io_l32n_m3dq15_3;
    inout io_l32p_0;
    inout io_l32p_a17_m1a8_1;
    inout io_l32p_gclk29_2;
    inout io_l32p_m3dq14_3;
    inout io_l33n_0;
    inout io_l33n_a14_m1a4_1;
    inout io_l33n_m3dq13_3;
    inout io_l33p_0;
    inout io_l33p_a15_m1a10_1;
    inout io_l33p_m3dq12_3;
    inout io_l34n_a12_m1ba2_1;
    inout io_l34n_gclk18_0;
    inout io_l34n_m3udqsn_3;
    inout io_l34p_a13_m1we_1;
    inout io_l34p_gclk19_0;
    inout io_l34p_m3udqs_3;
    inout io_l35n_a10_m1a2_1;
    inout io_l35n_gclk16_0;
    inout io_l35n_m3dq11_3;
    inout io_l35p_a11_m1a7_1;
    inout io_l35p_gclk17_0;
    inout io_l35p_m3dq10_3;
    inout io_l36n_a8_m1ba1_1;
    inout io_l36n_gclk14_0;
    inout io_l36n_m3dq9_3;
    inout io_l36p_a9_m1ba0_1;
    inout io_l36p_gclk15_0;
    inout io_l36p_m3dq8_3;
    inout io_l37n_a6_m1a1_1;
    inout io_l37n_gclk12_0;
    inout io_l37n_m3dq1_3;
    inout io_l37p_a7_m1a0_1;
    inout io_l37p_gclk13_0;
    inout io_l37p_m3dq0_3;
    inout io_l38n_a4_m1clkn_1;
    inout io_l38n_m3dq3_3;
    inout io_l38n_vref_0;
    inout io_l38p_0;
    inout io_l38p_a5_m1clk_1;
    inout io_l38p_m3dq2_3;
    inout io_l39n_m1odt_1;
    inout io_l39n_m3ldqsn_3;
    inout io_l39p_m1a3_1;
    inout io_l39p_m3ldqs_3;
    inout io_l3n_0;
    inout io_l3n_mosi_csi_b_miso0_2;
    inout io_l3p_0;
    inout io_l3p_d0_din_miso_miso1_2;
    inout io_l40n_2;
    inout io_l40n_gclk10_m1a6_1;
    inout io_l40n_m3dq7_3;
    inout io_l40p_2;
    inout io_l40p_gclk11_m1a5_1;
    inout io_l40p_m3dq6_3;
    inout io_l41n_gclk26_m3dq5_3;
    inout io_l41n_gclk8_m1casn_1;
    inout io_l41n_vref_2;
    inout io_l41p_2;
    inout io_l41p_gclk27_m3dq4_3;
    inout io_l41p_gclk9_irdy1_m1rasn_1;
    inout io_l42n_2;
    inout io_l42n_gclk24_m3ldm_3;
    inout io_l42n_gclk6_trdy1_m1ldm_1;
    inout io_l42p_2;
    inout io_l42p_gclk25_trdy2_m3udm_3;
    inout io_l42p_gclk7_m1udm_1;
    inout io_l43n_2;
    inout io_l43n_gclk22_irdy2_m3casn_3;
    inout io_l43n_gclk4_m1dq5_1;
    inout io_l43p_2;
    inout io_l43p_gclk23_m3rasn_3;
    inout io_l43p_gclk5_m1dq4_1;
    inout io_l44n_2;
    inout io_l44n_a2_m1dq7_1;
    inout io_l44n_gclk20_m3a6_3;
    inout io_l44p_2;
    inout io_l44p_a3_m1dq6_1;
    inout io_l44p_gclk21_m3a5_3;
    inout io_l45n_2;
    inout io_l45n_a0_m1ldqsn_1;
    inout io_l45n_m3odt_3;
    inout io_l45p_2;
    inout io_l45p_a1_m1ldqs_1;
    inout io_l45p_m3a3_3;
    inout io_l46n_2;
    inout io_l46n_foe_b_m1dq3_1;
    inout io_l46n_m3clkn_3;
    inout io_l46p_2;
    inout io_l46p_fcs_b_m1dq2_1;
    inout io_l46p_m3clk_3;
    inout io_l47n_2;
    inout io_l47n_ldc_m1dq1_1;
    inout io_l47n_m3a1_3;
    inout io_l47p_2;
    inout io_l47p_fwe_b_m1dq0_1;
    inout io_l47p_m3a0_3;
    inout io_l48n_m1dq9_1;
    inout io_l48n_m3ba1_3;
    inout io_l48n_rdwr_b_vref_2;
    inout io_l48p_d7_2;
    inout io_l48p_hdc_m1dq8_1;
    inout io_l48p_m3ba0_3;
    inout io_l49n_0;
    inout io_l49n_d4_2;
    inout io_l49n_m1dq11_1;
    inout io_l49n_m3a2_3;
    inout io_l49p_0;
    inout io_l49p_d3_2;
    inout io_l49p_m1dq10_1;
    inout io_l49p_m3a7_3;
    inout io_l4n_0;
    inout io_l4n_vref_2;
    inout io_l4p_0;
    inout io_l4p_2;
    inout io_l50n_0;
    inout io_l50n_2;
    inout io_l50n_m1udqsn_1;
    inout io_l50n_m3ba2_3;
    inout io_l50p_0;
    inout io_l50p_2;
    inout io_l50p_m1udqs_1;
    inout io_l50p_m3we_3;
    inout io_l51n_0;
    inout io_l51n_2;
    inout io_l51n_m1dq13_1;
    inout io_l51n_m3a4_3;
    inout io_l51p_0;
    inout io_l51p_2;
    inout io_l51p_m1dq12_1;
    inout io_l51p_m3a10_3;
    inout io_l52n_2;
    inout io_l52n_m1dq15_1;
    inout io_l52n_m3a9_3;
    inout io_l52p_2;
    inout io_l52p_m1dq14_1;
    inout io_l52p_m3a8_3;
    inout io_l53n_2;
    inout io_l53n_m3a12_3;
    inout io_l53n_vref_1;
    inout io_l53p_1;
    inout io_l53p_2;
    inout io_l53p_m3cke_3;
    inout io_l54n_2;
    inout io_l54n_m3a11_3;
    inout io_l54p_2;
    inout io_l54p_m3reset_3;
    inout io_l55n_m3a14_3;
    inout io_l55p_m3a13_3;
    inout io_l57n_2;
    inout io_l57n_vref_3;
    inout io_l57p_2;
    inout io_l57p_3;
    inout io_l58n_1;
    inout io_l58n_2;
    inout io_l58n_3;
    inout io_l58p_1;
    inout io_l58p_2;
    inout io_l58p_3;
    inout io_l59n_1;
    inout io_l59n_2;
    inout io_l59n_3;
    inout io_l59p_1;
    inout io_l59p_2;
    inout io_l59p_3;
    inout io_l5n_0;
    inout io_l5n_2;
    inout io_l5p_0;
    inout io_l5p_2;
    inout io_l60n_1;
    inout io_l60n_2;
    inout io_l60n_3;
    inout io_l60p_1;
    inout io_l60p_2;
    inout io_l60p_3;
    inout io_l61n_1;
    inout io_l61p_1;
    inout io_l62n_d6_2;
    inout io_l62n_vref_0;
    inout io_l62p_0;
    inout io_l62p_d5_2;
    inout io_l63n_2;
    inout io_l63n_scp6_0;
    inout io_l63p_2;
    inout io_l63p_scp7_0;
    inout io_l64n_d9_2;
    inout io_l64n_scp4_0;
    inout io_l64p_d8_2;
    inout io_l64p_scp5_0;
    inout io_l65n_cso_b_2;
    inout io_l65n_scp2_0;
    inout io_l65p_init_b_2;
    inout io_l65p_scp3_0;
    inout io_l66n_scp0_0;
    inout io_l66p_scp1_0;
    inout io_l6n_0;
    inout io_l6n_2;
    inout io_l6p_0;
    inout io_l6p_2;
    inout io_l70n_1;
    inout io_l70p_1;
    inout io_l71n_1;
    inout io_l71p_1;
    inout io_l72n_1;
    inout io_l72p_1;
    inout io_l73n_1;
    inout io_l73p_1;
    inout io_l74n_dout_busy_1;
    inout io_l74p_awake_1;
    inout io_l7n_0;
    inout io_l7n_2;
    inout io_l7n_3;
    inout io_l7p_0;
    inout io_l7p_2;
    inout io_l7p_3;
    inout io_l80n_3;
    inout io_l80p_3;
    inout io_l81n_3;
    inout io_l81p_3;
    inout io_l82n_3;
    inout io_l82p_3;
    inout io_l83n_vref_3;
    inout io_l83p_3;
    inout io_l8n_2;
    inout io_l8n_3;
    inout io_l8n_vref_0;
    inout io_l8p_0;
    inout io_l8p_2;
    inout io_l8p_3;
    inout io_l9n_1;
    inout io_l9n_2;
    inout io_l9n_3;
    inout io_l9p_1;
    inout io_l9p_2;
    inout io_l9p_3;
    input [25:1] nc;
    input program_b_2;
    input suspend;
    input tck;
    input tdi;
    output tdo;
    input tms;
    input vccaux_d16;
    input vccaux_f11;
    input vccaux_g12;
    input vccaux_h15;
    input vccaux_h9;
    input vccaux_k15;
    input vccaux_l8;
    input vccaux_m15;
    input vccaux_n8;
    input vccaux_r10;
    input vccaux_r12;
    input vccaux_r6;
    input vccaux_u11;
    input vccaux_v6;
    input vccint_j10;
    input vccint_j12;
    input vccint_j14;
    input vccint_j8;
    input vccint_k11;
    input vccint_k13;
    input vccint_k9;
    input vccint_l10;
    input vccint_l12;
    input vccint_l14;
    input vccint_m11;
    input vccint_m13;
    input vccint_m9;
    input vccint_n10;
    input vccint_n12;
    input vccint_n14;
    input vccint_p11;
    input vccint_p13;
    input vccint_p9;
    input vccint_r14;
    input vcco_0_b11;
    input vcco_0_b15;
    input vcco_0_b19;
    input vcco_0_b4;
    input vcco_0_b7;
    input vcco_0_e13;
    input vcco_0_e17;
    input vcco_0_e9;
    input vcco_0_g10;
    input vcco_0_g14;
    input vcco_1_c21;
    input vcco_1_e19;
    input vcco_1_g21;
    input vcco_1_j18;
    input vcco_1_l16;
    input vcco_1_l21;
    input vcco_1_n18;
    input vcco_1_r21;
    input vcco_1_u18;
    input vcco_1_w21;
    input vcco_2_aa11;
    input vcco_2_aa15;
    input vcco_2_aa19;
    input vcco_2_aa3;
    input vcco_2_aa7;
    input vcco_2_t13;
    input vcco_2_t9;
    input vcco_2_v12;
    input vcco_2_v16;
    input vcco_2_v8;
    input vcco_2_w5;
    input vcco_3_c2;
    input vcco_3_f4;
    input vcco_3_f6;
    input vcco_3_g2;
    input vcco_3_j5;
    input vcco_3_l2;
    input vcco_3_l7;
    input vcco_3_n5;
    input vcco_3_r2;
    input vcco_3_u5;
    input vcco_3_w2;


    initial
        begin
        end

endmodule
