// generated by newgenasym  Thu Oct 10 22:15:21 2019


module sn74ahc1g32drl (a, b, gnd, vcc, y);
    inout a;
    input b;
    input gnd;
    input vcc;
    output y;


    initial
        begin
        end

endmodule
