-- generated by newgenasym Thu Oct 10 22:15:21 2019

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sn74ahc1g32drl is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	Y:         OUT    STD_LOGIC);
end sn74ahc1g32drl;
