-- generated by newgenasym Wed Jun 22 20:16:10 2005

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity head2x7 is
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (13 DOWNTO 0));
end head2x7;
