// generated by newgenasym  Mon Jan 09 16:59:44 2006


module adm3202 (\c1+ , \c1- , \c2+ , \c2- , gnd, r1in, r1out, r2in, r2out, t1in, t1out,
        t2in, t2out, \v+ , \v- , vcc);
    input \c1+ ;
    input \c1- ;
    input \c2+ ;
    input \c2- ;
    input gnd;
    output r1in;
    input r1out;
    output r2in;
    input r2out;
    input t1in;
    output t1out;
    input t2in;
    output t2out;
    input \v+ ;
    input \v- ;
    input vcc;


    initial
        begin
        end

endmodule
