-- generated by newgenasym Mon Jan 09 16:59:44 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity adm3202 is
    port (    
	\c1+\:     IN     STD_LOGIC;    
	\c1-\:     IN     STD_LOGIC;    
	\c2+\:     IN     STD_LOGIC;    
	\c2-\:     IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	R1IN:      OUT    STD_LOGIC;    
	R1OUT:     IN     STD_LOGIC;    
	R2IN:      OUT    STD_LOGIC;    
	R2OUT:     IN     STD_LOGIC;    
	T1IN:      IN     STD_LOGIC;    
	T1OUT:     OUT    STD_LOGIC;    
	T2IN:      IN     STD_LOGIC;    
	T2OUT:     OUT    STD_LOGIC;    
	\v+\:      IN     STD_LOGIC;    
	\v-\:      IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end adm3202;
