// generated by newgenasym  Tue Sep 13 16:27:14 2016


module ltc4417 (cas, en, ep, g1, g2, g3, gnd, hys, ov1, ov2, ov3, shdn, uv1, uv2,
        uv3, v0ut, v1, v2, v3, valid1, valid2, valid3, vs1, vs2, vs3);
    inout cas;
    inout en;
    inout ep;
    inout g1;
    inout g2;
    inout g3;
    inout gnd;
    inout hys;
    inout ov1;
    inout ov2;
    inout ov3;
    inout shdn;
    inout uv1;
    inout uv2;
    inout uv3;
    inout v0ut;
    inout v1;
    inout v2;
    inout v3;
    inout valid1;
    inout valid2;
    inout valid3;
    inout vs1;
    inout vs2;
    inout vs3;


    initial
        begin
        end

endmodule
