-- generated by newgenasym Tue Sep 13 16:27:14 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ltc4417 is
    port (    
	CAS:       INOUT  STD_LOGIC;    
	EN:        INOUT  STD_LOGIC;    
	EP:        INOUT  STD_LOGIC;    
	G1:        INOUT  STD_LOGIC;    
	G2:        INOUT  STD_LOGIC;    
	G3:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	HYS:       INOUT  STD_LOGIC;    
	OV1:       INOUT  STD_LOGIC;    
	OV2:       INOUT  STD_LOGIC;    
	OV3:       INOUT  STD_LOGIC;    
	SHDN:      INOUT  STD_LOGIC;    
	UV1:       INOUT  STD_LOGIC;    
	UV2:       INOUT  STD_LOGIC;    
	UV3:       INOUT  STD_LOGIC;    
	V0UT:      INOUT  STD_LOGIC;    
	V1:        INOUT  STD_LOGIC;    
	V2:        INOUT  STD_LOGIC;    
	V3:        INOUT  STD_LOGIC;    
	VALID1:    INOUT  STD_LOGIC;    
	VALID2:    INOUT  STD_LOGIC;    
	VALID3:    INOUT  STD_LOGIC;    
	VS1:       INOUT  STD_LOGIC;    
	VS2:       INOUT  STD_LOGIC;    
	VS3:       INOUT  STD_LOGIC);
end ltc4417;
