// generated by newgenasym  Wed May 28 19:30:43 2014


module lm2660 (\cap+ , \cap- , fc, gnd, lv, osc, out, \v+ );
    inout \cap+ ;
    inout \cap- ;
    inout fc;
    inout gnd;
    inout lv;
    inout osc;
    inout out;
    inout \v+ ;


    initial
        begin
        end

endmodule
