-- generated by newgenasym Wed May 28 19:30:43 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lm2660 is
    port (    
	\cap+\:    INOUT  STD_LOGIC;    
	\cap-\:    INOUT  STD_LOGIC;    
	FC:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	LV:        INOUT  STD_LOGIC;    
	OSC:       INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	\v+\:      INOUT  STD_LOGIC);
end lm2660;
