-- generated by newgenasym Sun Nov 16 16:06:46 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity l0805 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end l0805;
