// generated by newgenasym  Wed Nov 02 15:42:59 2005


module \dcdc-4dip  (\vin+ , \vin- , \vout+ , \vout- );
    input \vin+ ;
    input \vin- ;
    output \vout+ ;
    output \vout- ;


    initial
        begin
        end

endmodule
