-- generated by newgenasym Wed Nov 02 15:42:59 2005

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \dcdc-4dip\ is
    port (    
	\vin+\:    IN     STD_LOGIC;    
	\vin-\:    IN     STD_LOGIC;    
	\vout+\:   OUT    STD_LOGIC;    
	\vout-\:   OUT    STD_LOGIC);
end \dcdc-4dip\;
