// generated by newgenasym  Wed Jun 17 20:37:00 2020


module rj45_1000m_180 (\11 , \12 , \13 , \14 , \5 , \6 , \d1+ , \d1- , \d2+ , \d2- , \d3+ , \d3- , \d4+ , \d4- );
    inout \11 ;
    inout \12 ;
    inout \13 ;
    inout \14 ;
    inout \5 ;
    inout \6 ;
    inout \d1+ ;
    inout \d1- ;
    inout \d2+ ;
    inout \d2- ;
    inout \d3+ ;
    inout \d3- ;
    inout \d4+ ;
    inout \d4- ;


    initial
        begin
        end

endmodule
