-- generated by newgenasym Wed Jun 17 20:37:00 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity rj45_1000m_180 is
    port (    
	\11\:      INOUT  STD_LOGIC;    
	\12\:      INOUT  STD_LOGIC;    
	\13\:      INOUT  STD_LOGIC;    
	\14\:      INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC;    
	\d1+\:     INOUT  STD_LOGIC;    
	\d1-\:     INOUT  STD_LOGIC;    
	\d2+\:     INOUT  STD_LOGIC;    
	\d2-\:     INOUT  STD_LOGIC;    
	\d3+\:     INOUT  STD_LOGIC;    
	\d3-\:     INOUT  STD_LOGIC;    
	\d4+\:     INOUT  STD_LOGIC;    
	\d4-\:     INOUT  STD_LOGIC);
end rj45_1000m_180;
