// generated by newgenasym  Thu Sep 08 22:30:58 2016


module lt3469 (\+in , \-in , fb, gnd, out, sw, vcc, vin);
    inout \+in ;
    inout \-in ;
    inout fb;
    inout gnd;
    inout out;
    inout sw;
    inout vcc;
    inout vin;


    initial
        begin
        end

endmodule
