-- generated by newgenasym Thu Sep 08 22:30:58 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lt3469 is
    port (    
	\+in\:     INOUT  STD_LOGIC;    
	\-in\:     INOUT  STD_LOGIC;    
	FB:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	SW:        INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC);
end lt3469;
