// generated by newgenasym  Mon Sep 12 12:42:06 2016


module stm32f100cbt6 (boot0, nrst, \pa0-wkup/usart2_cts/adc1_in0 ,
        \pa1/usart2_rts/adc1_in1 , \pa10/usart1_rx/tim1_ch3 ,
        \pa11/usart1_cts/tim1_ch4 , \pa12/usart1_rts/tim1_etr ,
        \pa13jtms/swdio , \pa14/jtck/swclk , \pa15/jtdi ,
        \pa2/usart2_tx/adc1_in2 , \pa3/usart2_rx/adc1_in3 ,
        \pa4/spi1_nss//adc1_in4/usart2_ck ,
        \pa5/spi1_sck/adc1_in5 , \pa6/spi1_miso/adc1_in6 ,
        \pa7/spi1_mosi/adc1_in7 , \pa8/usart1_ck/mco/tim1_ch1 ,
        \pa9/usart1_tx/tim1_ch2 , \pb0/adc1_in8 , \pb1/adc1_in9 ,
        \pb10/i2c2_scl/usart3_tx , \pb11/i2c2_sda/usart3_rx ,
        \pb12/spi2_nss/i2c2_smba/usart3_ck ,
        \pb13/spi2_sck/usart3_cts , \pb14/spi2_miso/usart3_rts ,
        \pb15/spi2_mosi , \pb2/boot1 , \pb3/jtdo , \pb4/njtrst ,
        \pb5/i2c1_smba , \pb6/i2c1_scl , \pb7/i2c1_sda , pb8, pb9,
        \pc13/tamper-rtc , \pc14/osc32_in , \pc15/osc32_out ,
        \pd0/osc_in , \pd1/osc_out , vbat, vdd_1, vdd_2, vdd_3, vdda,
        vss_1, vss_2, vss_3, vssa);
    inout boot0;
    inout nrst;
    inout \pa0-wkup/usart2_cts/adc1_in0 ;
    inout \pa1/usart2_rts/adc1_in1 ;
    inout \pa10/usart1_rx/tim1_ch3 ;
    inout \pa11/usart1_cts/tim1_ch4 ;
    inout \pa12/usart1_rts/tim1_etr ;
    inout \pa13jtms/swdio ;
    inout \pa14/jtck/swclk ;
    inout \pa15/jtdi ;
    inout \pa2/usart2_tx/adc1_in2 ;
    inout \pa3/usart2_rx/adc1_in3 ;
    inout \pa4/spi1_nss//adc1_in4/usart2_ck ;
    inout \pa5/spi1_sck/adc1_in5 ;
    inout \pa6/spi1_miso/adc1_in6 ;
    inout \pa7/spi1_mosi/adc1_in7 ;
    inout \pa8/usart1_ck/mco/tim1_ch1 ;
    inout \pa9/usart1_tx/tim1_ch2 ;
    inout \pb0/adc1_in8 ;
    inout \pb1/adc1_in9 ;
    inout \pb10/i2c2_scl/usart3_tx ;
    inout \pb11/i2c2_sda/usart3_rx ;
    inout \pb12/spi2_nss/i2c2_smba/usart3_ck ;
    inout \pb13/spi2_sck/usart3_cts ;
    inout \pb14/spi2_miso/usart3_rts ;
    inout \pb15/spi2_mosi ;
    inout \pb2/boot1 ;
    inout \pb3/jtdo ;
    inout \pb4/njtrst ;
    inout \pb5/i2c1_smba ;
    inout \pb6/i2c1_scl ;
    inout \pb7/i2c1_sda ;
    inout pb8;
    inout pb9;
    inout \pc13/tamper-rtc ;
    inout \pc14/osc32_in ;
    inout \pc15/osc32_out ;
    inout \pd0/osc_in ;
    inout \pd1/osc_out ;
    input vbat;
    input vdd_1;
    input vdd_2;
    input vdd_3;
    input vdda;
    input vss_1;
    input vss_2;
    input vss_3;
    input vssa;


    initial
        begin
        end

endmodule
