-- generated by newgenasym Mon Dec  1 14:12:35 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \bsmd2920-300-33v\ is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end \bsmd2920-300-33v\;
