-- generated by newgenasym Tue Nov 25 08:38:00 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \acm2012-2-900\ is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC);
end \acm2012-2-900\;
