// generated by newgenasym  Thu May 22 21:11:56 2008


module ds1388 (gnd, \rst* , scl, sda, vbat, vcc, x1, x2);
    input gnd;
    input \rst* ;
    input scl;
    inout sda;
    input vbat;
    input vcc;
    input x1;
    output x2;


    initial
        begin
        end

endmodule
