-- generated by newgenasym Thu May 22 21:11:56 2008

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity DS1388 is
    port (    
	GND:       IN     STD_LOGIC;    
	\rst*\:    IN     STD_LOGIC;    
	SCL:       IN     STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC;    
	VBAT:      IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	X1:        IN     STD_LOGIC;    
	X2:        OUT    STD_LOGIC);
end DS1388;
