// generated by newgenasym  Fri Sep 28 19:31:19 2018


module l6232d1v2 (adj, en, gnd1, gnd2, gnd3, gnd4, in, out);
    inout adj;
    inout en;
    inout gnd1;
    inout gnd2;
    inout gnd3;
    inout gnd4;
    inout in;
    inout out;


    initial
        begin
        end

endmodule
