-- generated by newgenasym Fri Sep 28 19:31:19 2018

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity l6232d1v2 is
    port (    
	ADJ:       INOUT  STD_LOGIC;    
	EN:        INOUT  STD_LOGIC;    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	GND3:      INOUT  STD_LOGIC;    
	GND4:      INOUT  STD_LOGIC;    
	\in\:      INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC);
end l6232d1v2;
