// generated by newgenasym  Thu Jul 11 16:32:00 2013


module sn74lvc2t45 (a1, a2, b1, b2, dir, gnd, vcca, vccb);
    inout a1;
    inout a2;
    inout b1;
    inout b2;
    inout dir;
    inout gnd;
    inout vcca;
    inout vccb;


    initial
        begin
        end

endmodule
