-- generated by newgenasym Thu Jul 11 16:32:00 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sn74lvc2t45 is
    port (    
	A1:        INOUT  STD_LOGIC;    
	A2:        INOUT  STD_LOGIC;    
	B1:        INOUT  STD_LOGIC;    
	B2:        INOUT  STD_LOGIC;    
	DIR:       INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	VCCA:      INOUT  STD_LOGIC;    
	VCCB:      INOUT  STD_LOGIC);
end sn74lvc2t45;
