// generated by newgenasym  Wed Dec 10 10:39:47 2025


module \5_8_wspt  (\1 , \2 , \3 , \4 , \5 , \6 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;
    inout \6 ;


    initial
        begin
        end

endmodule
