-- generated by newgenasym Wed Dec 10 10:39:47 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \5_8_wspt\ is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC);
end \5_8_wspt\;
