-- generated by newgenasym Wed Dec 24 22:09:19 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity blm21pg300sn1d is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end blm21pg300sn1d;
