// generated by newgenasym  Wed Nov 12 21:12:27 2014


module tps2051bdbv (\en* , gnd, in, \oc* , out);
    inout \en* ;
    inout gnd;
    inout in;
    inout \oc* ;
    inout out;


    initial
        begin
        end

endmodule
