-- generated by newgenasym Wed Nov 12 21:12:27 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tps2051bdbv is
    port (    
	\en*\:     INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	\in\:      INOUT  STD_LOGIC;    
	\oc*\:     INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC);
end tps2051bdbv;
