// generated by newgenasym  Wed Mar 27 16:54:25 2013


module \crystal-smt  (gnd1, gnd2, hot1, hot2);
    input gnd1;
    input gnd2;
    inout hot1;
    inout hot2;


    initial
        begin
        end

endmodule
