-- generated by newgenasym Wed Mar 27 16:54:25 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \crystal-smt\ is
    port (    
	GND1:      IN     STD_LOGIC;    
	GND2:      IN     STD_LOGIC;    
	HOT1:      INOUT  STD_LOGIC;    
	HOT2:      INOUT  STD_LOGIC);
end \crystal-smt\;
