// generated by newgenasym  Fri Sep 09 15:36:14 2016


module sn74lvc2g240 (\1a , \1oe , \1y , \2a , \2oe , \2y , gnd, vcc);
    inout \1a ;
    inout \1oe ;
    inout \1y ;
    inout \2a ;
    inout \2oe ;
    inout \2y ;
    inout gnd;
    inout vcc;


    initial
        begin
        end

endmodule
