-- generated by newgenasym Fri Sep 09 15:36:14 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sn74lvc2g240 is
    port (    
	\1a\:      INOUT  STD_LOGIC;    
	\1oe\:     INOUT  STD_LOGIC;    
	\1y\:      INOUT  STD_LOGIC;    
	\2a\:      INOUT  STD_LOGIC;    
	\2oe\:     INOUT  STD_LOGIC;    
	\2y\:      INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	VCC:       INOUT  STD_LOGIC);
end sn74lvc2g240;
