-- generated by newgenasym Sun Jun 19 16:52:36 2005

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity npn is
    port (    
	B:         INOUT  STD_LOGIC;    
	C:         INOUT  STD_LOGIC;    
	C1:        IN     STD_LOGIC;    
	E:         INOUT  STD_LOGIC);
end npn;
