// generated by newgenasym  Tue Nov 25 08:37:32 2025


module ams1117_3_3v (gnd, vin, vout, vout1);
    inout gnd;
    inout vin;
    inout vout;
    inout vout1;


    initial
        begin
        end

endmodule
