// generated by newgenasym  Mon Jan 09 21:39:51 2006


module tps60400 (\c1+ , \c1- , gnd, in, out);
    inout \c1+ ;
    inout \c1- ;
    input gnd;
    input in;
    output out;


    initial
        begin
        end

endmodule
