-- generated by newgenasym Mon Jan 09 21:39:51 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tps60400 is
    port (    
	\c1+\:     INOUT  STD_LOGIC;    
	\c1-\:     INOUT  STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	\in\:      IN     STD_LOGIC;    
	\out\:     OUT    STD_LOGIC);
end tps60400;
