// generated by newgenasym  Tue Jan 10 14:39:41 2006


module \74lvc1g07  (a, gnd, vcc, y);
    input a;
    input gnd;
    input vcc;
    output y;


    initial
        begin
        end

endmodule
