-- generated by newgenasym Tue Jan 10 14:39:41 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74lvc1g07\ is
    port (    
	A:         IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	Y:         OUT    STD_LOGIC);
end \74lvc1g07\;
