// generated by newgenasym  Wed Mar 10 15:57:23 2021


module bl1117 (gnd, vin, vout, \vout/ );
    inout gnd;
    inout vin;
    inout vout;
    inout \vout/ ;


    initial
        begin
        end

endmodule
