-- generated by newgenasym Wed Mar 10 15:57:23 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity bl1117 is
    port (    
	GND:       INOUT  STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC;    
	VOUT:      INOUT  STD_LOGIC;    
	\vout/\:   INOUT  STD_LOGIC);
end bl1117;
