// generated by newgenasym  Mon Jan 09 16:54:29 2006


module \74lvc1g04  (a, gnd, vcc, y);
    input a;
    input gnd;
    input vcc;
    output y;


    initial
        begin
        end

endmodule
