-- generated by newgenasym Mon Jan 09 16:54:29 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \74lvc1g04\ is
    port (    
	A:         IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	Y:         OUT    STD_LOGIC);
end \74lvc1g04\;
