-- generated by newgenasym Wed Jun 10 20:56:20 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \5557_8pin\ is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC;    
	\6\:       INOUT  STD_LOGIC;    
	\7\:       INOUT  STD_LOGIC;    
	\8\:       INOUT  STD_LOGIC);
end \5557_8pin\;
