-- generated by newgenasym Thu Nov 20 22:29:38 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity X322512MSB4SI is
    port (    
	GND:       INOUT  STD_LOGIC;    
	GND1:      INOUT  STD_LOGIC;    
	OSC1:      INOUT  STD_LOGIC;    
	OSC2:      INOUT  STD_LOGIC);
end X322512MSB4SI;
