-- generated by newgenasym Tue Nov 25 08:47:20 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity x322512msb4si is
    port (    
	GND:       INOUT  STD_LOGIC;    
	GND1:      INOUT  STD_LOGIC;    
	OSC1:      INOUT  STD_LOGIC;    
	OSC2:      INOUT  STD_LOGIC);
end x322512msb4si;
