// generated by newgenasym  Sun Oct 09 11:30:27 2005


module rt9164 (adj, gnd, vin, vout);
    input adj;
    input gnd;
    input vin;
    output vout;


    initial
        begin
        end

endmodule
