-- generated by newgenasym Sun Oct 09 11:30:27 2005

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity RT9164 is
    port (    
	ADJ:       IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	VIN:       IN     STD_LOGIC;    
	VOUT:      OUT    STD_LOGIC);
end RT9164;
