// generated by newgenasym  Fri May 30 21:09:32 2008


module ctm1040 (cang, canh, canl, gnd, rxd, txd, vin);
    inout cang;
    inout canh;
    inout canl;
    inout gnd;
    inout rxd;
    inout txd;
    inout vin;


    initial
        begin
        end

endmodule
