-- generated by newgenasym Fri May 30 21:09:32 2008

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ctm1040 is
    port (    
	CANG:      INOUT  STD_LOGIC;    
	CANH:      INOUT  STD_LOGIC;    
	CANL:      INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	RXD:       INOUT  STD_LOGIC;    
	TXD:       INOUT  STD_LOGIC;    
	VIN:       INOUT  STD_LOGIC);
end ctm1040;
