// generated by newgenasym  Fri Dec 26 14:27:46 2025


module lp5907mfx_2p5_nopb (en, gnd, n_c, vin, vout);
    input en;
    input gnd;
    inout n_c;
    input vin;
    input vout;


    initial
        begin
        end

endmodule
