-- generated by newgenasym Fri Dec 26 14:27:46 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity lp5907mfx_2p5_nopb is
    port (    
	EN:        IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	N_C:       INOUT  STD_LOGIC;    
	VIN:       IN     STD_LOGIC;    
	VOUT:      IN     STD_LOGIC);
end lp5907mfx_2p5_nopb;
