// generated by newgenasym  Thu Mar 21 10:02:54 2013


module ads8361 (a0, agnd, avdd, bgnd, busy, bvdd, \ch_a0+ , \ch_a0- , \ch_a1+ ,
        \ch_a1- , \ch_b0+ , \ch_b0- , \ch_b1+ , \ch_b1- , clock, convst, \cs* ,
        \data#20a , \data#20b , m0, m1, rd, refin, refout);
    inout a0;
    inout agnd;
    inout avdd;
    inout bgnd;
    inout busy;
    inout bvdd;
    inout \ch_a0+ ;
    inout \ch_a0- ;
    inout \ch_a1+ ;
    inout \ch_a1- ;
    inout \ch_b0+ ;
    inout \ch_b0- ;
    inout \ch_b1+ ;
    inout \ch_b1- ;
    inout clock;
    inout convst;
    inout \cs* ;
    inout \data#20a ;
    inout \data#20b ;
    inout m0;
    inout m1;
    inout rd;
    inout refin;
    inout refout;


    initial
        begin
        end

endmodule
