-- generated by newgenasym Thu Mar 21 10:02:54 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ads8361 is
    port (    
	A0:        INOUT  STD_LOGIC;    
	AGND:      INOUT  STD_LOGIC;    
	AVDD:      INOUT  STD_LOGIC;    
	BGND:      INOUT  STD_LOGIC;    
	BUSY:      INOUT  STD_LOGIC;    
	BVDD:      INOUT  STD_LOGIC;    
	\ch_a0+\:  INOUT  STD_LOGIC;    
	\ch_a0-\:  INOUT  STD_LOGIC;    
	\ch_a1+\:  INOUT  STD_LOGIC;    
	\ch_a1-\:  INOUT  STD_LOGIC;    
	\ch_b0+\:  INOUT  STD_LOGIC;    
	\ch_b0-\:  INOUT  STD_LOGIC;    
	\ch_b1+\:  INOUT  STD_LOGIC;    
	\ch_b1-\:  INOUT  STD_LOGIC;    
	CLOCK:     INOUT  STD_LOGIC;    
	CONVST:    INOUT  STD_LOGIC;    
	\cs*\:     INOUT  STD_LOGIC;    
	\data a\:  INOUT  STD_LOGIC;    
	\data b\:  INOUT  STD_LOGIC;    
	M0:        INOUT  STD_LOGIC;    
	M1:        INOUT  STD_LOGIC;    
	RD:        INOUT  STD_LOGIC;    
	REFIN:     INOUT  STD_LOGIC;    
	REFOUT:    INOUT  STD_LOGIC);
end ads8361;
