// generated by newgenasym  Fri Sep 02 12:22:11 2016


module stm32f407vgt7 (boot0, nrst, \pa0/wkup/usart2_cts/adc123_in0 ,
        \pa1/usart2_rts/adc123_in1 , \pa10/usart1_rx ,
        \pa11/usart1_cts/can1_rx , \pa12/usart1_rts/can1_tx ,
        \pa13/jtms/swdio , \pa14/jtck/swclk , \pa15/jtdi ,
        \pa2/usart2_tx/adc123_in2 , \pa3/usart2_rx/adc123_in3 ,
        \pa4/spi1_nss/usart2_ck/dac_out1/adc12_in4 ,
        \pa5/spi1_sck/dac_out2/adc12_in5 ,
        \pa6/spi1_miso/adc12_in6/tim3_ch1 ,
        \pa7/spi1_mosi/adc12_in7 , \pa8/usart1_ck , \pa9/usart1_tx ,
        \pb0/adc12_in8 , \pb1/adc12_in9 , \pb10/i2c2_scl/usart3_tx ,
        \pb11/i2c2_sda/usart3_rx ,
        \pb12/spi2_nss/i2s2_ws/i2c2_smba/usart3_ck ,
        \pb13/spi2_sck/i2s2_ck/usart3_cts ,
        \pb14/spi2_miso/usart3_rts , \pb15/spi2_mosi/i2s2_sd ,
        \pb2/boot1 , \pb3/jtdo/traceswo/spi3_sck/i2s3_ck ,
        \pb4/njtrst , \pb5/i2c1_smba/can2_rx/i2s3_sd , \pb6/i2c1_scl ,
        \pb7/i2c1_sda/fsmc_nl , \pb8/sdio_d4 , \pb9/sdio_d5 ,
        \pc0/adc123_in10 , \pc1/adc123_in11 , \pc10/uart4_tx/sdio_d2 ,
        \pc11/uart4_rx/sdio_d3 , \pc12/uart5_tx/sdio_ck ,
        \pc13/rtc_tamp1 , \pc14/osc32_in , \pc15/osc32_out ,
        \pc2/adc123_in12 , \pc3/adc123_in13 , \pc4/adc12_in14 ,
        \pc5/adc12_in15 , \pc6/i2s2_mck/sdio_d6 ,
        \pc7/i2s3_mck/sdio_d7 , \pc8/tim8_ch3/sdio_d0 ,
        \pc9/tim8_ch4/sdio_d1 , \pd0/fsmc_d2 , \pd1/fsmc_d3 ,
        \pd10/fsmc_d15 , \pd11/fsmc_a16 , \pd12/fsmc_a17 ,
        \pd13/fsmc_a18 , \pd14/fsmc_d0 , \pd15/fsmc_d1 ,
        \pd2/uart5_rx/sdio_cmd , \pd3/fsmc_clk , \pd4/fsmc_noe ,
        \pd5/fsmc_nwe , \pd6/fsmc_nwait , \pd7/fsmc_ne1/fsmc_nce2 ,
        \pd8/fsmc_d13 , \pd9/fsmc_d14 , \pe0/fsmc_nbl0 , \pe1/fsmc_nbl1 ,
        \pe10/fsmc_d7 , \pe11/fsmc_d8 , \pe12/fsmc_d9 , \pe13/fsmc_d10 ,
        \pe14/fsmc_d11 , \pe15/fsmc_d12 , \pe2/fsmc_a23 , \pe3/fsmc_a19 ,
        \pe4/fsmc_a20 , \pe5/fsmc_a21 , \pe6/fsmc_a22 , \pe7/fsmc_d4 ,
        \pe8/fsmc_d5 , \pe9/fsmc_d6 , \ph0/osc_in , \ph1/osc_out , vbat,
        vcap_1, vcap_2, \vdd-2 , vdd_1, vdd_3, vdd_4, vdd_5, vdd_6,
        vdda, \vref+ , vss_1, vss_2, vss_3, vss_4, vssa);
    inout boot0;
    inout nrst;
    inout \pa0/wkup/usart2_cts/adc123_in0 ;
    inout \pa1/usart2_rts/adc123_in1 ;
    inout \pa10/usart1_rx ;
    inout \pa11/usart1_cts/can1_rx ;
    inout \pa12/usart1_rts/can1_tx ;
    inout \pa13/jtms/swdio ;
    inout \pa14/jtck/swclk ;
    inout \pa15/jtdi ;
    inout \pa2/usart2_tx/adc123_in2 ;
    inout \pa3/usart2_rx/adc123_in3 ;
    inout \pa4/spi1_nss/usart2_ck/dac_out1/adc12_in4 ;
    inout \pa5/spi1_sck/dac_out2/adc12_in5 ;
    inout \pa6/spi1_miso/adc12_in6/tim3_ch1 ;
    inout \pa7/spi1_mosi/adc12_in7 ;
    inout \pa8/usart1_ck ;
    inout \pa9/usart1_tx ;
    inout \pb0/adc12_in8 ;
    inout \pb1/adc12_in9 ;
    inout \pb10/i2c2_scl/usart3_tx ;
    inout \pb11/i2c2_sda/usart3_rx ;
    inout \pb12/spi2_nss/i2s2_ws/i2c2_smba/usart3_ck ;
    inout \pb13/spi2_sck/i2s2_ck/usart3_cts ;
    inout \pb14/spi2_miso/usart3_rts ;
    inout \pb15/spi2_mosi/i2s2_sd ;
    inout \pb2/boot1 ;
    inout \pb3/jtdo/traceswo/spi3_sck/i2s3_ck ;
    inout \pb4/njtrst ;
    inout \pb5/i2c1_smba/can2_rx/i2s3_sd ;
    inout \pb6/i2c1_scl ;
    inout \pb7/i2c1_sda/fsmc_nl ;
    inout \pb8/sdio_d4 ;
    inout \pb9/sdio_d5 ;
    inout \pc0/adc123_in10 ;
    inout \pc1/adc123_in11 ;
    inout \pc10/uart4_tx/sdio_d2 ;
    inout \pc11/uart4_rx/sdio_d3 ;
    inout \pc12/uart5_tx/sdio_ck ;
    inout \pc13/rtc_tamp1 ;
    inout \pc14/osc32_in ;
    inout \pc15/osc32_out ;
    inout \pc2/adc123_in12 ;
    inout \pc3/adc123_in13 ;
    inout \pc4/adc12_in14 ;
    inout \pc5/adc12_in15 ;
    inout \pc6/i2s2_mck/sdio_d6 ;
    inout \pc7/i2s3_mck/sdio_d7 ;
    inout \pc8/tim8_ch3/sdio_d0 ;
    inout \pc9/tim8_ch4/sdio_d1 ;
    inout \pd0/fsmc_d2 ;
    inout \pd1/fsmc_d3 ;
    inout \pd10/fsmc_d15 ;
    inout \pd11/fsmc_a16 ;
    inout \pd12/fsmc_a17 ;
    inout \pd13/fsmc_a18 ;
    inout \pd14/fsmc_d0 ;
    inout \pd15/fsmc_d1 ;
    inout \pd2/uart5_rx/sdio_cmd ;
    inout \pd3/fsmc_clk ;
    inout \pd4/fsmc_noe ;
    inout \pd5/fsmc_nwe ;
    inout \pd6/fsmc_nwait ;
    inout \pd7/fsmc_ne1/fsmc_nce2 ;
    inout \pd8/fsmc_d13 ;
    inout \pd9/fsmc_d14 ;
    inout \pe0/fsmc_nbl0 ;
    inout \pe1/fsmc_nbl1 ;
    inout \pe10/fsmc_d7 ;
    inout \pe11/fsmc_d8 ;
    inout \pe12/fsmc_d9 ;
    inout \pe13/fsmc_d10 ;
    inout \pe14/fsmc_d11 ;
    inout \pe15/fsmc_d12 ;
    inout \pe2/fsmc_a23 ;
    inout \pe3/fsmc_a19 ;
    inout \pe4/fsmc_a20 ;
    inout \pe5/fsmc_a21 ;
    inout \pe6/fsmc_a22 ;
    inout \pe7/fsmc_d4 ;
    inout \pe8/fsmc_d5 ;
    inout \pe9/fsmc_d6 ;
    inout \ph0/osc_in ;
    inout \ph1/osc_out ;
    input vbat;
    input vcap_1;
    input vcap_2;
    input \vdd-2 ;
    input vdd_1;
    input vdd_3;
    input vdd_4;
    input vdd_5;
    input vdd_6;
    input vdda;
    input \vref+ ;
    input vss_1;
    input vss_2;
    input vss_3;
    input vss_4;
    input vssa;


    initial
        begin
        end

endmodule
