-- generated by newgenasym Wed Oct 23 15:29:18 2024

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity l is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC);
end l;
