// generated by newgenasym  Tue Apr 23 22:16:52 2013


module passive_4pin (gnd1, gnd2, hot1, hot2);
    inout gnd1;
    inout gnd2;
    inout hot1;
    inout hot2;


    initial
        begin
        end

endmodule
