-- generated by newgenasym Tue Apr 23 22:16:52 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity PASSIVE_4PIN is
    port (    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	HOT1:      INOUT  STD_LOGIC;    
	HOT2:      INOUT  STD_LOGIC);
end PASSIVE_4PIN;
