// generated by newgenasym  Tue Sep 01 15:53:28 2009


module iso1050 (canh, canl, gnd1, gnd2, rxd, txd, vcc1, vcc2);
    inout canh;
    inout canl;
    inout gnd1;
    inout gnd2;
    inout rxd;
    inout txd;
    inout vcc1;
    inout vcc2;


    initial
        begin
        end

endmodule
