-- generated by newgenasym Tue Sep 01 15:53:28 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity iso1050 is
    port (    
	CANH:      INOUT  STD_LOGIC;    
	CANL:      INOUT  STD_LOGIC;    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	RXD:       INOUT  STD_LOGIC;    
	TXD:       INOUT  STD_LOGIC;    
	VCC1:      INOUT  STD_LOGIC;    
	VCC2:      INOUT  STD_LOGIC);
end iso1050;
