-- generated by newgenasym Wed Dec 14 15:29:38 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity PO is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC;    
	W:         INOUT  STD_LOGIC);
end PO;
