-- generated by newgenasym Wed Mar 18 14:29:06 2020

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \e-swith\ is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end \e-swith\;
