// generated by newgenasym  Tue Nov 04 20:06:49 2014


module \asp-134603  (\12v0 , \12v1 , \3v3-0 , \3v3-1 , \3v3-2 , \3v3-3 , \3v3aux , \clk0-m2c-n ,
        \clk0-m2c-p , \clk1-m2c-n , \clk1-m2c-p , \dp0-c2m-n , \dp0-c2m-p ,
        \dp0-m2c-n , \dp0-m2c-p , ga0, ga1, \gbtclk0-m2c-n ,
        \gbtclk0-m2c-p , gnd1, gnd10, gnd11, gnd12, gnd13, gnd14,
        gnd15, gnd16, gnd17, gnd18, gnd19, gnd2, gnd20, gnd21, gnd22,
        gnd23, gnd24, gnd25, gnd26, gnd27, gnd28, gnd29, gnd3, gnd30,
        gnd31, gnd32, gnd33, gnd34, gnd35, gnd36, gnd37, gnd38, gnd39,
        gnd4, gnd40, gnd41, gnd42, gnd43, gnd44, gnd45, gnd46, gnd47,
        gnd48, gnd49, gnd5, gnd50, gnd51, gnd52, gnd53, gnd54, gnd55,
        gnd56, gnd57, gnd58, gnd59, gnd6, gnd60, gnd61, gnd7, gnd8,
        gnd9, la00_n_cc, la00_p_cc, la01_n_cc, la01_p_cc, \la02-n ,
        \la02-p , \la03-n , \la03-p , \la04-n , \la04-p , \la05-n , \la05-p ,
        \la06-n , \la06-p , \la07-n , \la07-p , \la08-n , \la08-p , \la09-n ,
        \la09-p , \la10-n , \la10-p , \la11-n , \la11-p , \la12-n , \la12-p ,
        \la13-n , \la13-p , \la14-n , \la14-p , \la15-n , \la15-p , \la16-n ,
        \la16-p , la17_n_cc, la17_p_cc, la18_n_cc, la18_p_cc, \la19-n ,
        \la19-p , \la20-n , \la20-p , \la21-n , \la21-p , \la22-n , \la22-p ,
        \la23-n , \la23-p , \la24-n , \la24-p , \la25-n , \la25-p , \la26-n ,
        \la26-p , \la27-n , \la27-p , \la28-n , \la28-p , \la29-n , \la29-p ,
        \la30-n , \la30-p , \la31-n , \la31-p , \la32-n , \la32-p , \la33-n ,
        \la33-p , pg_c2m, \prsnt-m2c-l , scl, sda, shield, shield1, tck,
        tdi, tdo, tms, trst_l, vadj_3, vadj_4, \vref-a-m2c );
    inout \12v0 ;
    inout \12v1 ;
    inout \3v3-0 ;
    inout \3v3-1 ;
    inout \3v3-2 ;
    inout \3v3-3 ;
    inout \3v3aux ;
    inout \clk0-m2c-n ;
    inout \clk0-m2c-p ;
    inout \clk1-m2c-n ;
    inout \clk1-m2c-p ;
    inout \dp0-c2m-n ;
    inout \dp0-c2m-p ;
    inout \dp0-m2c-n ;
    inout \dp0-m2c-p ;
    inout ga0;
    inout ga1;
    inout \gbtclk0-m2c-n ;
    inout \gbtclk0-m2c-p ;
    inout gnd1;
    inout gnd10;
    inout gnd11;
    inout gnd12;
    inout gnd13;
    inout gnd14;
    inout gnd15;
    inout gnd16;
    inout gnd17;
    inout gnd18;
    inout gnd19;
    inout gnd2;
    inout gnd20;
    inout gnd21;
    inout gnd22;
    inout gnd23;
    inout gnd24;
    inout gnd25;
    inout gnd26;
    inout gnd27;
    inout gnd28;
    inout gnd29;
    inout gnd3;
    inout gnd30;
    inout gnd31;
    inout gnd32;
    inout gnd33;
    inout gnd34;
    inout gnd35;
    inout gnd36;
    inout gnd37;
    inout gnd38;
    inout gnd39;
    inout gnd4;
    inout gnd40;
    inout gnd41;
    inout gnd42;
    inout gnd43;
    inout gnd44;
    inout gnd45;
    inout gnd46;
    inout gnd47;
    inout gnd48;
    inout gnd49;
    inout gnd5;
    inout gnd50;
    inout gnd51;
    inout gnd52;
    inout gnd53;
    inout gnd54;
    inout gnd55;
    inout gnd56;
    inout gnd57;
    inout gnd58;
    inout gnd59;
    inout gnd6;
    inout gnd60;
    inout gnd61;
    inout gnd7;
    inout gnd8;
    inout gnd9;
    inout la00_n_cc;
    inout la00_p_cc;
    inout la01_n_cc;
    inout la01_p_cc;
    inout \la02-n ;
    inout \la02-p ;
    inout \la03-n ;
    inout \la03-p ;
    inout \la04-n ;
    inout \la04-p ;
    inout \la05-n ;
    inout \la05-p ;
    inout \la06-n ;
    inout \la06-p ;
    inout \la07-n ;
    inout \la07-p ;
    inout \la08-n ;
    inout \la08-p ;
    inout \la09-n ;
    inout \la09-p ;
    inout \la10-n ;
    inout \la10-p ;
    inout \la11-n ;
    inout \la11-p ;
    inout \la12-n ;
    inout \la12-p ;
    inout \la13-n ;
    inout \la13-p ;
    inout \la14-n ;
    inout \la14-p ;
    inout \la15-n ;
    inout \la15-p ;
    inout \la16-n ;
    inout \la16-p ;
    inout la17_n_cc;
    inout la17_p_cc;
    inout la18_n_cc;
    inout la18_p_cc;
    inout \la19-n ;
    inout \la19-p ;
    inout \la20-n ;
    inout \la20-p ;
    inout \la21-n ;
    inout \la21-p ;
    inout \la22-n ;
    inout \la22-p ;
    inout \la23-n ;
    inout \la23-p ;
    inout \la24-n ;
    inout \la24-p ;
    inout \la25-n ;
    inout \la25-p ;
    inout \la26-n ;
    inout \la26-p ;
    inout \la27-n ;
    inout \la27-p ;
    inout \la28-n ;
    inout \la28-p ;
    inout \la29-n ;
    inout \la29-p ;
    inout \la30-n ;
    inout \la30-p ;
    inout \la31-n ;
    inout \la31-p ;
    inout \la32-n ;
    inout \la32-p ;
    inout \la33-n ;
    inout \la33-p ;
    inout pg_c2m;
    inout \prsnt-m2c-l ;
    inout scl;
    inout sda;
    inout shield;
    inout shield1;
    inout tck;
    inout tdi;
    inout tdo;
    inout tms;
    inout trst_l;
    inout vadj_3;
    inout vadj_4;
    inout \vref-a-m2c ;


    initial
        begin
        end

endmodule
