// generated by newgenasym  Wed Mar 13 00:39:36 2013


module ad7985 (agnd1, agnd2, avdd, bvdd, cnv, dgnd, dvdd, \in+ , \in- , pad,
        pdref, ref1, ref2, refgnd1, refgnd2, refin, sck, sdi, sdo,
        turbo, vio);
    inout agnd1;
    inout agnd2;
    inout avdd;
    inout bvdd;
    inout cnv;
    inout dgnd;
    inout dvdd;
    inout \in+ ;
    inout \in- ;
    inout pad;
    inout pdref;
    inout ref1;
    inout ref2;
    inout refgnd1;
    inout refgnd2;
    inout refin;
    inout sck;
    inout sdi;
    inout sdo;
    inout turbo;
    inout vio;


    initial
        begin
        end

endmodule
