-- generated by newgenasym Wed Mar 13 00:39:36 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad7985 is
    port (    
	AGND1:     INOUT  STD_LOGIC;    
	AGND2:     INOUT  STD_LOGIC;    
	AVDD:      INOUT  STD_LOGIC;    
	BVDD:      INOUT  STD_LOGIC;    
	CNV:       INOUT  STD_LOGIC;    
	DGND:      INOUT  STD_LOGIC;    
	DVDD:      INOUT  STD_LOGIC;    
	\in+\:     INOUT  STD_LOGIC;    
	\in-\:     INOUT  STD_LOGIC;    
	PAD:       INOUT  STD_LOGIC;    
	PDREF:     INOUT  STD_LOGIC;    
	REF1:      INOUT  STD_LOGIC;    
	REF2:      INOUT  STD_LOGIC;    
	REFGND1:   INOUT  STD_LOGIC;    
	REFGND2:   INOUT  STD_LOGIC;    
	REFIN:     INOUT  STD_LOGIC;    
	SCK:       INOUT  STD_LOGIC;    
	SDI:       INOUT  STD_LOGIC;    
	SDO:       INOUT  STD_LOGIC;    
	TURBO:     INOUT  STD_LOGIC;    
	VIO:       INOUT  STD_LOGIC);
end ad7985;
