-- generated by newgenasym Tue Nov 25 09:08:09 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity l0805 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end l0805;
