// generated by newgenasym  Tue Sep 13 10:58:37 2016


module nthd4102pt1g (d1, d2, g1, g2, s1, s2);
    inout [2:1] d1;
    inout [2:1] d2;
    inout g1;
    inout g2;
    inout s1;
    inout s2;


    initial
        begin
        end

endmodule
