-- generated by newgenasym Tue Sep 13 10:58:37 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity nthd4102pt1g is
    port (    
	D1:        INOUT  STD_LOGIC_VECTOR (2 DOWNTO 1);    
	D2:        INOUT  STD_LOGIC_VECTOR (2 DOWNTO 1);    
	G1:        INOUT  STD_LOGIC;    
	G2:        INOUT  STD_LOGIC;    
	S1:        INOUT  STD_LOGIC;    
	S2:        INOUT  STD_LOGIC);
end nthd4102pt1g;
