-- generated by newgenasym Wed May 15 22:16:11 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity head2x6 is
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (12 DOWNTO 1));
end head2x6;
