// generated by newgenasym  Tue Sep 01 15:50:39 2009


module op1177 (\in+ , \in- , nc1, nc2, nc3, out, \v+ , \v- );
    inout \in+ ;
    inout \in- ;
    inout nc1;
    inout nc2;
    inout nc3;
    inout out;
    inout \v+ ;
    inout \v- ;


    initial
        begin
        end

endmodule
