-- generated by newgenasym Tue Sep 01 15:50:39 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity op1177 is
    port (    
	\in+\:     INOUT  STD_LOGIC;    
	\in-\:     INOUT  STD_LOGIC;    
	NC1:       INOUT  STD_LOGIC;    
	NC2:       INOUT  STD_LOGIC;    
	NC3:       INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	\v+\:      INOUT  STD_LOGIC;    
	\v-\:      INOUT  STD_LOGIC);
end op1177;
