-- generated by newgenasym Tue Feb 10 14:50:42 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity head2x8_socket is
    port (    
	A:         INOUT  STD_LOGIC_VECTOR (16 DOWNTO 1));
end head2x8_socket;
