-- generated by newgenasym Mon Dec  1 14:49:16 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity smbj30a_c19077584 is
    port (    
	A:         INOUT  STD_LOGIC;    
	K:         INOUT  STD_LOGIC);
end smbj30a_c19077584;
