// generated by newgenasym  Thu Nov 20 01:21:07 2025


module \hc-usb2.0-l195-j  (\1 , \2 , \3 , \4 , \5 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;


    initial
        begin
        end

endmodule
