// generated by newgenasym  Thu Nov 20 19:42:27 2025


module usb2_0 (\d+ , \d- , gnd, shield, vbus);
    inout \d+ ;
    inout \d- ;
    inout gnd;
    inout shield;
    inout vbus;


    initial
        begin
        end

endmodule
