-- generated by newgenasym Thu Nov 20 19:42:27 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity usb2_0 is
    port (    
	\d+\:      INOUT  STD_LOGIC;    
	\d-\:      INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	SHIELD:    INOUT  STD_LOGIC;    
	VBUS:      INOUT  STD_LOGIC);
end usb2_0;
