-- generated by newgenasym Thu Nov 20 01:21:07 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \hc-usb2.0-l195-j\ is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC;    
	\3\:       INOUT  STD_LOGIC;    
	\4\:       INOUT  STD_LOGIC;    
	\5\:       INOUT  STD_LOGIC);
end \hc-usb2.0-l195-j\;
