-- generated by newgenasym Wed Dec 24 23:06:40 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity r is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC);
end r;
