// generated by newgenasym  Tue Dec  2 22:34:57 2025


module tpa3116d2dad (am0, am1, am2, avcc, bsnl, bsnr, bspl, bspr, faultz, \gain/slv ,
        gnd, gnd2, gnd3, gnd4, gvdd, linn, linp, modsel, mute, outnl,
        outnr, outpl, outpr, plimit, pvcc, pvcc1, pvcc5, pvcc6, rinn,
        rinp, sdz, sync);
    inout am0;
    inout am1;
    inout am2;
    inout avcc;
    inout bsnl;
    inout bsnr;
    inout bspl;
    inout bspr;
    inout faultz;
    inout \gain/slv ;
    inout gnd;
    inout gnd2;
    inout gnd3;
    inout gnd4;
    inout gvdd;
    inout linn;
    inout linp;
    inout modsel;
    inout mute;
    inout outnl;
    inout outnr;
    inout outpl;
    inout outpr;
    inout plimit;
    inout pvcc;
    inout pvcc1;
    inout pvcc5;
    inout pvcc6;
    inout rinn;
    inout rinp;
    inout sdz;
    inout sync;


    initial
        begin
        end

endmodule
