-- generated by newgenasym Tue Dec  2 22:34:57 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tpa3116d2dad is
    port (    
	AM0:       INOUT  STD_LOGIC;    
	AM1:       INOUT  STD_LOGIC;    
	AM2:       INOUT  STD_LOGIC;    
	AVCC:      INOUT  STD_LOGIC;    
	BSNL:      INOUT  STD_LOGIC;    
	BSNR:      INOUT  STD_LOGIC;    
	BSPL:      INOUT  STD_LOGIC;    
	BSPR:      INOUT  STD_LOGIC;    
	FAULTZ:    INOUT  STD_LOGIC;    
	\gain/slv\: INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	GND3:      INOUT  STD_LOGIC;    
	GND4:      INOUT  STD_LOGIC;    
	GVDD:      INOUT  STD_LOGIC;    
	LINN:      INOUT  STD_LOGIC;    
	LINP:      INOUT  STD_LOGIC;    
	MODSEL:    INOUT  STD_LOGIC;    
	MUTE:      INOUT  STD_LOGIC;    
	OUTNL:     INOUT  STD_LOGIC;    
	OUTNR:     INOUT  STD_LOGIC;    
	OUTPL:     INOUT  STD_LOGIC;    
	OUTPR:     INOUT  STD_LOGIC;    
	PLIMIT:    INOUT  STD_LOGIC;    
	PVCC:      INOUT  STD_LOGIC;    
	PVCC1:     INOUT  STD_LOGIC;    
	PVCC5:     INOUT  STD_LOGIC;    
	PVCC6:     INOUT  STD_LOGIC;    
	RINN:      INOUT  STD_LOGIC;    
	RINP:      INOUT  STD_LOGIC;    
	SDZ:       INOUT  STD_LOGIC;    
	SYNC:      INOUT  STD_LOGIC);
end tpa3116d2dad;
