// generated by newgenasym  Fri Dec 16 13:03:50 2016


module el7156 (gnd, in, oe, out, vh, vl, \vs+ , \vs- );
    inout gnd;
    inout in;
    inout oe;
    inout out;
    inout vh;
    inout vl;
    inout \vs+ ;
    inout \vs- ;


    initial
        begin
        end

endmodule
