-- generated by newgenasym Fri Dec 16 13:03:50 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity el7156 is
    port (    
	GND:       INOUT  STD_LOGIC;    
	\in\:      INOUT  STD_LOGIC;    
	OE:        INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	VH:        INOUT  STD_LOGIC;    
	VL:        INOUT  STD_LOGIC;    
	\vs+\:     INOUT  STD_LOGIC;    
	\vs-\:     INOUT  STD_LOGIC);
end el7156;
