// generated by newgenasym  Wed Apr 19 16:55:04 2006


module sn74lvc1g02 (a, b, gnd, vcc, y);
    inout a;
    input b;
    input gnd;
    input vcc;
    output y;


    initial
        begin
        end

endmodule
