-- generated by newgenasym Wed Apr 19 16:55:04 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity sn74lvc1g02 is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC;    
	Y:         OUT    STD_LOGIC);
end sn74lvc1g02;
