-- generated by newgenasym Sun Nov 16 16:15:57 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity c0603 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end c0603;
