// generated by newgenasym  Sun Sep 16 16:54:49 2012


module w25qxxfvs (clk, \cs* , \di/io0 , \do/io1 , gnd, \hold#/reset#/io3 , vcc,
        \wp#/io2 );
    input clk;
    input \cs* ;
    inout \di/io0 ;
    inout \do/io1 ;
    input gnd;
    inout \hold#/reset#/io3 ;
    input vcc;
    inout \wp#/io2 ;


    initial
        begin
        end

endmodule
