// generated by newgenasym  Mon Jan 09 13:04:54 2012


module sn74avc8t245 (a1, a2, a3, a4, a5, a6, a7, a8, b1, b2, b3, b4, b5, b6, b7, b8, dir,
        gnd1, gnd2, gnd3, \oe# , vcca, vccb1, vccb2);
    inout a1;
    inout a2;
    inout a3;
    inout a4;
    inout a5;
    inout a6;
    inout a7;
    inout a8;
    inout b1;
    inout b2;
    inout b3;
    inout b4;
    inout b5;
    inout b6;
    inout b7;
    inout b8;
    input dir;
    input gnd1;
    input gnd2;
    input gnd3;
    input \oe# ;
    input vcca;
    input vccb1;
    input vccb2;


    initial
        begin
        end

endmodule
