-- generated by newgenasym Wed Dec 24 14:19:03 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity c is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC);
end c;
