// generated by newgenasym  Sun Sep 16 17:43:22 2012


module tps74701drcr (bias, en, fb, gnd, pg, ss, tp, vin1, vin2, vout1, vout2);
    input bias;
    input en;
    input fb;
    input gnd;
    output pg;
    inout ss;
    input tp;
    input vin1;
    input vin2;
    output vout1;
    output vout2;


    initial
        begin
        end

endmodule
