-- generated by newgenasym Sun Sep 16 17:43:22 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tps74701drcr is
    port (    
	BIAS:      IN     STD_LOGIC;    
	EN:        IN     STD_LOGIC;    
	FB:        IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	PG:        OUT    STD_LOGIC;    
	SS:        INOUT  STD_LOGIC;    
	TP:        IN     STD_LOGIC;    
	VIN1:      IN     STD_LOGIC;    
	VIN2:      IN     STD_LOGIC;    
	VOUT1:     OUT    STD_LOGIC;    
	VOUT2:     OUT    STD_LOGIC);
end tps74701drcr;
