// generated by newgenasym  Thu Mar 11 19:50:22 2021


module esd05 (\1 , \2 , \3 , \4 , \5 , \6 );
    inout \1 ;
    inout \2 ;
    inout \3 ;
    inout \4 ;
    inout \5 ;
    inout \6 ;


    initial
        begin
        end

endmodule
