// generated by newgenasym  Wed Oct 24 15:25:43 2012


module \xc6slx16-2ftg256c  (cmpcs_b_2, done_2, gnd_a1, gnd_a16, gnd_b11, gnd_b7,
        gnd_d13, gnd_d4, gnd_e9, gnd_g15, gnd_g2, gnd_g8, gnd_h12,
        gnd_h7, gnd_h9, gnd_j5, gnd_j8, gnd_k7, gnd_k9, gnd_l15,
        gnd_l2, gnd_m8, gnd_n13, gnd_p3, gnd_r10, gnd_r6, gnd_t1,
        gnd_t16, io_l12n_d2_miso3_2, io_l12p_d1_miso2_2,
        io_l13n_d10_2, io_l13p_m1_2, io_l14n_d12_2,
        io_l14p_d11_2, io_l16n_vref_2, io_l16p_2,
        io_l1n_a24_vref_1, io_l1n_m0_cmpmiso_2, io_l1n_vref_0,
        io_l1n_vref_3, io_l1p_3, io_l1p_a25_1, io_l1p_cclk_2,
        io_l1p_hswapen_0, io_l23n_2, io_l23p_2,
        io_l29n_a22_m1a14_1, io_l29n_gclk2_2,
        io_l29p_a23_m1a13_1, io_l29p_gclk3_2, io_l2n_0, io_l2n_3,
        io_l2n_cmpmosi_2, io_l2p_0, io_l2p_3, io_l2p_cmpclk_2,
        io_l30n_a20_m1a11_1, io_l30n_gclk0_usercclk_2,
        io_l30p_a21_m1reset_1, io_l30p_gclk1_d13_2,
        io_l31n_a18_m1a12_1, io_l31n_gclk30_d15_2,
        io_l31p_a19_m1cke_1, io_l31p_gclk31_d14_2,
        io_l32n_a16_m1a9_1, io_l32n_gclk28_2, io_l32n_m3dq15_3,
        io_l32p_a17_m1a8_1, io_l32p_gclk29_2, io_l32p_m3dq14_3,
        io_l33n_0, io_l33n_a14_m1a4_1, io_l33n_m3dq13_3,
        io_l33p_0, io_l33p_a15_m1a10_1, io_l33p_m3dq12_3,
        io_l34n_a12_m1ba2_1, io_l34n_gclk18_0,
        io_l34n_m3udqsn_3, io_l34p_a13_m1we_1, io_l34p_gclk19_0,
        io_l34p_m3udqs_3, io_l35n_a10_m1a2_1, io_l35n_gclk16_0,
        io_l35n_m3dq11_3, io_l35p_a11_m1a7_1, io_l35p_gclk17_0,
        io_l35p_m3dq10_3, io_l36n_a8_m1ba1_1, io_l36n_gclk14_0,
        io_l36n_m3dq9_3, io_l36p_a9_m1ba0_1, io_l36p_gclk15_0,
        io_l36p_m3dq8_3, io_l37n_a6_m1a1_1, io_l37n_gclk12_0,
        io_l37n_m3dq1_3, io_l37p_a7_m1a0_1, io_l37p_gclk13_0,
        io_l37p_m3dq0_3, io_l38n_a4_m1clkn_1, io_l38n_m3dq3_3,
        io_l38n_vref_0, io_l38p_0, io_l38p_a5_m1clk_1,
        io_l38p_m3dq2_3, io_l39n_0, io_l39n_m1odt_1,
        io_l39n_m3ldqsn_3, io_l39p_0, io_l39p_m1a3_1,
        io_l39p_m3ldqs_3, io_l3n_0, io_l3n_mosi_csi_b_miso0_2,
        io_l3p_0, io_l3p_d0_din_miso_miso1_2, io_l40n_0,
        io_l40n_gclk10_m1a6_1, io_l40n_m3dq7_3, io_l40p_0,
        io_l40p_gclk11_m1a5_1, io_l40p_m3dq6_3,
        io_l41n_gclk26_m3dq5_3, io_l41n_gclk8_m1casn_1,
        io_l41p_gclk27_m3dq4_3, io_l41p_gclk9_irdy1_m1rasn_1,
        io_l42n_gclk24_m3ldm_3, io_l42n_gclk6_trdy1_m1ldm_1,
        io_l42p_gclk25_trdy2_m3udm_3, io_l42p_gclk7_m1udm_1,
        io_l43n_gclk22_irdy2_m3casn_3, io_l43n_gclk4_m1dq5_1,
        io_l43p_gclk23_m3rasn_3, io_l43p_gclk5_m1dq4_1,
        io_l44n_a2_m1dq7_1, io_l44n_gclk20_m3a6_3,
        io_l44p_a3_m1dq6_1, io_l44p_gclk21_m3a5_3,
        io_l45n_a0_m1ldqsn_1, io_l45n_m3odt_3,
        io_l45p_a1_m1ldqs_1, io_l45p_m3a3_3,
        io_l46n_foe_b_m1dq3_1, io_l46n_m3clkn_3,
        io_l46p_fcs_b_m1dq2_1, io_l46p_m3clk_3, io_l47n_2,
        io_l47n_ldc_m1dq1_1, io_l47n_m3a1_3, io_l47p_2,
        io_l47p_fwe_b_m1dq0_1, io_l47p_m3a0_3, io_l48n_m1dq9_1,
        io_l48n_m3ba1_3, io_l48n_rdwr_b_vref_2, io_l48p_d7_2,
        io_l48p_hdc_m1dq8_1, io_l48p_m3ba0_3, io_l49n_d4_2,
        io_l49n_m1dq11_1, io_l49n_m3a2_3, io_l49p_d3_2,
        io_l49p_m1dq10_1, io_l49p_m3a7_3, io_l4n_0, io_l4p_0,
        io_l50n_m1udqsn_1, io_l50n_m3ba2_3, io_l50p_m1udqs_1,
        io_l50p_m3we_3, io_l51n_m1dq13_1, io_l51n_m3a4_3,
        io_l51p_m1dq12_1, io_l51p_m3a10_3, io_l52n_m1dq15_1,
        io_l52n_m3a9_3, io_l52p_m1dq14_1, io_l52p_m3a8_3,
        io_l53n_m3a12_3, io_l53n_vref_1, io_l53p_1,
        io_l53p_m3cke_3, io_l54n_m3a11_3, io_l54p_m3reset_3,
        io_l55n_m3a14_3, io_l55p_m3a13_3, io_l5n_0, io_l5p_0,
        io_l62n_d6_2, io_l62n_vref_0, io_l62p_0, io_l62p_d5_2,
        io_l63n_2, io_l63n_scp6_0, io_l63p_2, io_l63p_scp7_0,
        io_l64n_d9_2, io_l64n_scp4_0, io_l64p_d8_2,
        io_l64p_scp5_0, io_l65n_cso_b_2, io_l65n_scp2_0,
        io_l65p_init_b_2, io_l65p_scp3_0, io_l66n_scp0_0,
        io_l66p_scp1_0, io_l6n_0, io_l6p_0, io_l74n_dout_busy_1,
        io_l74p_awake_1, io_l7n_0, io_l7p_0, io_l83n_vref_3,
        io_l83p_3, program_b_2, suspend, tck, tdi, tdo, tms,
        vccaux_e5, vccaux_f11, vccaux_f8, vccaux_g10, vccaux_h6,
        vccaux_j10, vccaux_l6, vccaux_l9, vccint_g7, vccint_g9,
        vccint_h10, vccint_h8, vccint_j7, vccint_j9, vccint_k10,
        vccint_k8, vcco_0_b13, vcco_0_b4, vcco_0_b9, vcco_0_d10,
        vcco_0_d7, vcco_1_d15, vcco_1_g13, vcco_1_j15, vcco_1_k13,
        vcco_1_n15, vcco_1_r13, vcco_2_n10, vcco_2_n7, vcco_2_r4,
        vcco_2_r8, vcco_3_d2, vcco_3_g4, vcco_3_j2, vcco_3_k4,
        vcco_3_n2);
    input cmpcs_b_2;
    inout done_2;
    input gnd_a1;
    input gnd_a16;
    input gnd_b11;
    input gnd_b7;
    input gnd_d13;
    input gnd_d4;
    input gnd_e9;
    input gnd_g15;
    input gnd_g2;
    input gnd_g8;
    input gnd_h12;
    input gnd_h7;
    input gnd_h9;
    input gnd_j5;
    input gnd_j8;
    input gnd_k7;
    input gnd_k9;
    input gnd_l15;
    input gnd_l2;
    input gnd_m8;
    input gnd_n13;
    input gnd_p3;
    input gnd_r10;
    input gnd_r6;
    input gnd_t1;
    input gnd_t16;
    inout io_l12n_d2_miso3_2;
    inout io_l12p_d1_miso2_2;
    inout io_l13n_d10_2;
    inout io_l13p_m1_2;
    inout io_l14n_d12_2;
    inout io_l14p_d11_2;
    inout io_l16n_vref_2;
    inout io_l16p_2;
    inout io_l1n_a24_vref_1;
    inout io_l1n_m0_cmpmiso_2;
    inout io_l1n_vref_0;
    inout io_l1n_vref_3;
    inout io_l1p_3;
    inout io_l1p_a25_1;
    inout io_l1p_cclk_2;
    inout io_l1p_hswapen_0;
    inout io_l23n_2;
    inout io_l23p_2;
    inout io_l29n_a22_m1a14_1;
    inout io_l29n_gclk2_2;
    inout io_l29p_a23_m1a13_1;
    inout io_l29p_gclk3_2;
    inout io_l2n_0;
    inout io_l2n_3;
    inout io_l2n_cmpmosi_2;
    inout io_l2p_0;
    inout io_l2p_3;
    inout io_l2p_cmpclk_2;
    inout io_l30n_a20_m1a11_1;
    inout io_l30n_gclk0_usercclk_2;
    inout io_l30p_a21_m1reset_1;
    inout io_l30p_gclk1_d13_2;
    inout io_l31n_a18_m1a12_1;
    inout io_l31n_gclk30_d15_2;
    inout io_l31p_a19_m1cke_1;
    inout io_l31p_gclk31_d14_2;
    inout io_l32n_a16_m1a9_1;
    inout io_l32n_gclk28_2;
    inout io_l32n_m3dq15_3;
    inout io_l32p_a17_m1a8_1;
    inout io_l32p_gclk29_2;
    inout io_l32p_m3dq14_3;
    inout io_l33n_0;
    inout io_l33n_a14_m1a4_1;
    inout io_l33n_m3dq13_3;
    inout io_l33p_0;
    inout io_l33p_a15_m1a10_1;
    inout io_l33p_m3dq12_3;
    inout io_l34n_a12_m1ba2_1;
    inout io_l34n_gclk18_0;
    inout io_l34n_m3udqsn_3;
    inout io_l34p_a13_m1we_1;
    inout io_l34p_gclk19_0;
    inout io_l34p_m3udqs_3;
    inout io_l35n_a10_m1a2_1;
    inout io_l35n_gclk16_0;
    inout io_l35n_m3dq11_3;
    inout io_l35p_a11_m1a7_1;
    inout io_l35p_gclk17_0;
    inout io_l35p_m3dq10_3;
    inout io_l36n_a8_m1ba1_1;
    inout io_l36n_gclk14_0;
    inout io_l36n_m3dq9_3;
    inout io_l36p_a9_m1ba0_1;
    inout io_l36p_gclk15_0;
    inout io_l36p_m3dq8_3;
    inout io_l37n_a6_m1a1_1;
    inout io_l37n_gclk12_0;
    inout io_l37n_m3dq1_3;
    inout io_l37p_a7_m1a0_1;
    inout io_l37p_gclk13_0;
    inout io_l37p_m3dq0_3;
    inout io_l38n_a4_m1clkn_1;
    inout io_l38n_m3dq3_3;
    inout io_l38n_vref_0;
    inout io_l38p_0;
    inout io_l38p_a5_m1clk_1;
    inout io_l38p_m3dq2_3;
    inout io_l39n_0;
    inout io_l39n_m1odt_1;
    inout io_l39n_m3ldqsn_3;
    inout io_l39p_0;
    inout io_l39p_m1a3_1;
    inout io_l39p_m3ldqs_3;
    inout io_l3n_0;
    inout io_l3n_mosi_csi_b_miso0_2;
    inout io_l3p_0;
    inout io_l3p_d0_din_miso_miso1_2;
    inout io_l40n_0;
    inout io_l40n_gclk10_m1a6_1;
    inout io_l40n_m3dq7_3;
    inout io_l40p_0;
    inout io_l40p_gclk11_m1a5_1;
    inout io_l40p_m3dq6_3;
    inout io_l41n_gclk26_m3dq5_3;
    inout io_l41n_gclk8_m1casn_1;
    inout io_l41p_gclk27_m3dq4_3;
    inout io_l41p_gclk9_irdy1_m1rasn_1;
    inout io_l42n_gclk24_m3ldm_3;
    inout io_l42n_gclk6_trdy1_m1ldm_1;
    inout io_l42p_gclk25_trdy2_m3udm_3;
    inout io_l42p_gclk7_m1udm_1;
    inout io_l43n_gclk22_irdy2_m3casn_3;
    inout io_l43n_gclk4_m1dq5_1;
    inout io_l43p_gclk23_m3rasn_3;
    inout io_l43p_gclk5_m1dq4_1;
    inout io_l44n_a2_m1dq7_1;
    inout io_l44n_gclk20_m3a6_3;
    inout io_l44p_a3_m1dq6_1;
    inout io_l44p_gclk21_m3a5_3;
    inout io_l45n_a0_m1ldqsn_1;
    inout io_l45n_m3odt_3;
    inout io_l45p_a1_m1ldqs_1;
    inout io_l45p_m3a3_3;
    inout io_l46n_foe_b_m1dq3_1;
    inout io_l46n_m3clkn_3;
    inout io_l46p_fcs_b_m1dq2_1;
    inout io_l46p_m3clk_3;
    inout io_l47n_2;
    inout io_l47n_ldc_m1dq1_1;
    inout io_l47n_m3a1_3;
    inout io_l47p_2;
    inout io_l47p_fwe_b_m1dq0_1;
    inout io_l47p_m3a0_3;
    inout io_l48n_m1dq9_1;
    inout io_l48n_m3ba1_3;
    inout io_l48n_rdwr_b_vref_2;
    inout io_l48p_d7_2;
    inout io_l48p_hdc_m1dq8_1;
    inout io_l48p_m3ba0_3;
    inout io_l49n_d4_2;
    inout io_l49n_m1dq11_1;
    inout io_l49n_m3a2_3;
    inout io_l49p_d3_2;
    inout io_l49p_m1dq10_1;
    inout io_l49p_m3a7_3;
    inout io_l4n_0;
    inout io_l4p_0;
    inout io_l50n_m1udqsn_1;
    inout io_l50n_m3ba2_3;
    inout io_l50p_m1udqs_1;
    inout io_l50p_m3we_3;
    inout io_l51n_m1dq13_1;
    inout io_l51n_m3a4_3;
    inout io_l51p_m1dq12_1;
    inout io_l51p_m3a10_3;
    inout io_l52n_m1dq15_1;
    inout io_l52n_m3a9_3;
    inout io_l52p_m1dq14_1;
    inout io_l52p_m3a8_3;
    inout io_l53n_m3a12_3;
    inout io_l53n_vref_1;
    inout io_l53p_1;
    inout io_l53p_m3cke_3;
    inout io_l54n_m3a11_3;
    inout io_l54p_m3reset_3;
    inout io_l55n_m3a14_3;
    inout io_l55p_m3a13_3;
    inout io_l5n_0;
    inout io_l5p_0;
    inout io_l62n_d6_2;
    inout io_l62n_vref_0;
    inout io_l62p_0;
    inout io_l62p_d5_2;
    inout io_l63n_2;
    inout io_l63n_scp6_0;
    inout io_l63p_2;
    inout io_l63p_scp7_0;
    inout io_l64n_d9_2;
    inout io_l64n_scp4_0;
    inout io_l64p_d8_2;
    inout io_l64p_scp5_0;
    inout io_l65n_cso_b_2;
    inout io_l65n_scp2_0;
    inout io_l65p_init_b_2;
    inout io_l65p_scp3_0;
    inout io_l66n_scp0_0;
    inout io_l66p_scp1_0;
    inout io_l6n_0;
    inout io_l6p_0;
    inout io_l74n_dout_busy_1;
    inout io_l74p_awake_1;
    inout io_l7n_0;
    inout io_l7p_0;
    inout io_l83n_vref_3;
    inout io_l83p_3;
    input program_b_2;
    input suspend;
    input tck;
    input tdi;
    output tdo;
    input tms;
    input vccaux_e5;
    input vccaux_f11;
    input vccaux_f8;
    input vccaux_g10;
    input vccaux_h6;
    input vccaux_j10;
    input vccaux_l6;
    input vccaux_l9;
    input vccint_g7;
    input vccint_g9;
    input vccint_h10;
    input vccint_h8;
    input vccint_j7;
    input vccint_j9;
    input vccint_k10;
    input vccint_k8;
    input vcco_0_b13;
    input vcco_0_b4;
    input vcco_0_b9;
    input vcco_0_d10;
    input vcco_0_d7;
    input vcco_1_d15;
    input vcco_1_g13;
    input vcco_1_j15;
    input vcco_1_k13;
    input vcco_1_n15;
    input vcco_1_r13;
    input vcco_2_n10;
    input vcco_2_n7;
    input vcco_2_r4;
    input vcco_2_r8;
    input vcco_3_d2;
    input vcco_3_g4;
    input vcco_3_j2;
    input vcco_3_k4;
    input vcco_3_n2;


    initial
        begin
        end

endmodule
