// generated by newgenasym  Sat Feb 21 15:16:21 2009


module pca9306dctt (enable, gnd, scl1, scl2, sda1, sda2, vref1, vref2);
    input enable;
    input gnd;
    inout scl1;
    inout scl2;
    inout sda1;
    inout sda2;
    input vref1;
    input vref2;


    initial
        begin
        end

endmodule
