-- generated by newgenasym Sat Feb 21 15:16:21 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity pca9306dctt is
    port (    
	ENABLE:    IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	SCL1:      INOUT  STD_LOGIC;    
	SCL2:      INOUT  STD_LOGIC;    
	SDA1:      INOUT  STD_LOGIC;    
	SDA2:      INOUT  STD_LOGIC;    
	VREF1:     IN     STD_LOGIC;    
	VREF2:     IN     STD_LOGIC);
end pca9306dctt;
