// generated by newgenasym  Wed Nov 19 01:00:21 2025


module sa9227a (abclk, adata, alrck, amclk, \dbclk#20/#20dsd_clk ,
        \ddata#20/#20dsd_right , \dlrck#20/#20dsd_left , dm, dmclk, dp,
        dsd_128_flag, dsd_flag, gnd, gnd_2, gnd_3, gnd_4, gnd_5,
        gnd_ldo, gpio0, gpio1, \gpio2#20/#20usb#20(hs/fs)#20sel , gpio3,
        gpio4, gpio5, gpio6, gpio7, gpio8, refclkin, resetn, rext,
        scl_m, scl_s, sda_m, sda_s, sof_flag, spdif_rx, spdif_tx,
        test1, test2, test3, test4, test5, test6, vdd18, vdd18_2,
        vdd18_3, vdd18_4, vdd18_5, vdd18_ldo, vdd33, vdd33_10,
        vdd33_11, vdd33_12, vdd33_2, vdd33_3, vdd33_4, vdd33_5,
        vdd33_6, vdd33_7, vdd33_8, vdd33_9, vdd33_ldo, xi, xo);
    inout abclk;
    inout adata;
    inout alrck;
    inout amclk;
    inout \dbclk#20/#20dsd_clk ;
    output \ddata#20/#20dsd_right ;
    inout \dlrck#20/#20dsd_left ;
    inout dm;
    inout dmclk;
    inout dp;
    output dsd_128_flag;
    output dsd_flag;
    input gnd;
    input gnd_2;
    input gnd_3;
    input gnd_4;
    input gnd_5;
    input gnd_ldo;
    inout gpio0;
    inout gpio1;
    inout \gpio2#20/#20usb#20(hs/fs)#20sel ;
    inout gpio3;
    inout gpio4;
    inout gpio5;
    inout gpio6;
    inout gpio7;
    inout gpio8;
    input refclkin;
    input resetn;
    inout rext;
    inout scl_m;
    inout scl_s;
    inout sda_m;
    inout sda_s;
    output sof_flag;
    input spdif_rx;
    output spdif_tx;
    input test1;
    input test2;
    input test3;
    input test4;
    input test5;
    input test6;
    input vdd18;
    input vdd18_2;
    input vdd18_3;
    input vdd18_4;
    input vdd18_5;
    input vdd18_ldo;
    input vdd33;
    input vdd33_10;
    input vdd33_11;
    input vdd33_12;
    input vdd33_2;
    input vdd33_3;
    input vdd33_4;
    input vdd33_5;
    input vdd33_6;
    input vdd33_7;
    input vdd33_8;
    input vdd33_9;
    input vdd33_ldo;
    input xi;
    output xo;


    initial
        begin
        end

endmodule
