// generated by newgenasym  Sat Jun 09 19:18:36 2012


module tps54331drg4 (boot, comp, en, etp, gnd, ph, ss, vin, vsense);
    inout boot;
    input comp;
    input en;
    input etp;
    input gnd;
    input ph;
    input ss;
    input vin;
    input vsense;


    initial
        begin
        end

endmodule
