-- generated by newgenasym Sat Jun 09 19:18:36 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tps54331drg4 is
    port (    
	BOOT:      INOUT  STD_LOGIC;    
	COMP:      IN     STD_LOGIC;    
	EN:        IN     STD_LOGIC;    
	ETP:       IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	PH:        IN     STD_LOGIC;    
	SS:        IN     STD_LOGIC;    
	VIN:       IN     STD_LOGIC;    
	VSENSE:    IN     STD_LOGIC);
end tps54331drg4;
