-- generated by newgenasym Tue Nov 25 08:45:24 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity res0402 is
    port (    
	\1\:       INOUT  STD_LOGIC;    
	\2\:       INOUT  STD_LOGIC);
end res0402;
