// generated by newgenasym  Tue Nov 25 09:20:33 2025


module x322512msb4si (gnd, gnd1, osc1, osc2);
    inout gnd;
    inout gnd1;
    inout osc1;
    inout osc2;


    initial
        begin
        end

endmodule
