// generated by newgenasym  Tue May 27 21:17:47 2014


module mt41j128m16 (a0, a1, \a10/ap , a11, \a12/bc# , a13, a2, a3, a4, a5, a6, a7, a8, a9,
        ba0, ba1, ba2, \cas# , ck, \ck# , cke, \cs# , dml, dmu, dql0, dql1,
        dql2, dql3, dql4, dql5, dql6, dql7, dqsl, \dqsl# , dqsu, \dqsu# ,
        dqu0, dqu1, dqu2, dqu3, dqu4, dqu5, dqu6, dqu7, \nc/a14 , \nc/a15 ,
        nc_j1, nc_j9, nc_l1, nc_l9, odt, \ras# , \reset# , vdd_b2, vdd_d9,
        vdd_g7, vdd_k2, vdd_k8, vdd_n1, vdd_n9, vdd_r1, vdd_r9,
        vddq_a1, vddq_a8, vddq_c1, vddq_c9, vddq_d2, vddq_e9,
        vddq_f1, vddq_h2, vddq_h9, vrefca, vrefdq, vss_a9, vss_b3,
        vss_e1, vss_g8, vss_j2, vss_j8, vss_m1, vss_m9, vss_p1,
        vss_p9, vss_t1, vss_t9, vssq_b1, vssq_b9, vssq_d1, vssq_d8,
        vssq_e2, vssq_e8, vssq_f9, vssq_g1, vssq_g9, \we# , zq);
    inout a0;
    inout a1;
    inout \a10/ap ;
    inout a11;
    inout \a12/bc# ;
    inout a13;
    inout a2;
    inout a3;
    inout a4;
    inout a5;
    inout a6;
    inout a7;
    inout a8;
    inout a9;
    inout ba0;
    inout ba1;
    inout ba2;
    inout \cas# ;
    inout ck;
    inout \ck# ;
    inout cke;
    inout \cs# ;
    inout dml;
    inout dmu;
    inout dql0;
    inout dql1;
    inout dql2;
    inout dql3;
    inout dql4;
    inout dql5;
    inout dql6;
    inout dql7;
    inout dqsl;
    inout \dqsl# ;
    inout dqsu;
    inout \dqsu# ;
    inout dqu0;
    inout dqu1;
    inout dqu2;
    inout dqu3;
    inout dqu4;
    inout dqu5;
    inout dqu6;
    inout dqu7;
    inout \nc/a14 ;
    inout \nc/a15 ;
    input nc_j1;
    input nc_j9;
    input nc_l1;
    input nc_l9;
    inout odt;
    inout \ras# ;
    inout \reset# ;
    input vdd_b2;
    input vdd_d9;
    input vdd_g7;
    input vdd_k2;
    input vdd_k8;
    input vdd_n1;
    input vdd_n9;
    input vdd_r1;
    input vdd_r9;
    input vddq_a1;
    input vddq_a8;
    input vddq_c1;
    input vddq_c9;
    input vddq_d2;
    input vddq_e9;
    input vddq_f1;
    input vddq_h2;
    input vddq_h9;
    input vrefca;
    input vrefdq;
    input vss_a9;
    input vss_b3;
    input vss_e1;
    input vss_g8;
    input vss_j2;
    input vss_j8;
    input vss_m1;
    input vss_m9;
    input vss_p1;
    input vss_p9;
    input vss_t1;
    input vss_t9;
    input vssq_b1;
    input vssq_b9;
    input vssq_d1;
    input vssq_d8;
    input vssq_e2;
    input vssq_e8;
    input vssq_f9;
    input vssq_g1;
    input vssq_g9;
    inout \we# ;
    inout zq;


    initial
        begin
        end

endmodule
