// generated by newgenasym  Thu Mar 13 11:06:39 2014


module fm25h20 (c, d, \hold# , q, \s# , vdd, vss, \w# );
    inout c;
    inout d;
    inout \hold# ;
    inout q;
    inout \s# ;
    inout vdd;
    inout vss;
    inout \w# ;


    initial
        begin
        end

endmodule
