-- generated by newgenasym Thu Mar 13 11:06:39 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity fm25h20 is
    port (    
	C:         INOUT  STD_LOGIC;    
	D:         INOUT  STD_LOGIC;    
	\hold#\:   INOUT  STD_LOGIC;    
	Q:         INOUT  STD_LOGIC;    
	\s#\:      INOUT  STD_LOGIC;    
	VDD:       INOUT  STD_LOGIC;    
	VSS:       INOUT  STD_LOGIC;    
	\w#\:      INOUT  STD_LOGIC);
end fm25h20;
