// generated by newgenasym  Thu Oct 10 16:18:36 2019


module ad5667r (addr, \clr* , gnd, \ldac* , scl, sda, vdd, vouta, voutb, vref);
    inout addr;
    inout \clr* ;
    inout gnd;
    inout \ldac* ;
    inout scl;
    inout sda;
    inout vdd;
    inout vouta;
    inout voutb;
    inout vref;


    initial
        begin
        end

endmodule
