-- generated by newgenasym Thu Oct 10 16:18:36 2019

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ad5667r is
    port (    
	ADDR:      INOUT  STD_LOGIC;    
	\clr*\:    INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	\ldac*\:   INOUT  STD_LOGIC;    
	SCL:       INOUT  STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC;    
	VDD:       INOUT  STD_LOGIC;    
	VOUTA:     INOUT  STD_LOGIC;    
	VOUTB:     INOUT  STD_LOGIC;    
	VREF:      INOUT  STD_LOGIC);
end ad5667r;
