// generated by newgenasym  Mon Nov 24 15:31:14 2025


module \cs43198-cnzr  (adr, aouta, aoutb, clkout, \dsda/sdin2 , \dsdb/lrck2 ,
        \dsdclk/sclk2 , ep, \filt+ , \filt- , flyc_vcp, flyn_va, flyn_vcp,
        flyp_va, flyp_vcp, gnda, gndcp, gndcp1, gndcp2, gndd,
        hp_detect, \int# , lrck1, nn_pin_18, nn_pin_9, refa, refb,
        \reset# , scl, sclk1, sda, sdin1, tso, va, vcp, \vcp_filt+ , vd, vl,
        vp, \xti/mclk , xto);
    inout adr;
    inout aouta;
    inout aoutb;
    inout clkout;
    inout \dsda/sdin2 ;
    inout \dsdb/lrck2 ;
    inout \dsdclk/sclk2 ;
    inout ep;
    inout \filt+ ;
    inout \filt- ;
    inout flyc_vcp;
    inout flyn_va;
    inout flyn_vcp;
    inout flyp_va;
    inout flyp_vcp;
    inout gnda;
    inout gndcp;
    inout gndcp1;
    inout gndcp2;
    inout gndd;
    inout hp_detect;
    inout \int# ;
    inout lrck1;
    inout nn_pin_18;
    inout nn_pin_9;
    inout refa;
    inout refb;
    inout \reset# ;
    inout scl;
    inout sclk1;
    inout sda;
    inout sdin1;
    inout tso;
    inout va;
    inout vcp;
    inout \vcp_filt+ ;
    inout vd;
    inout vl;
    inout vp;
    inout \xti/mclk ;
    inout xto;


    initial
        begin
        end

endmodule
