-- generated by newgenasym Wed Nov 26 16:43:18 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity \cs43198-cnzr\ is
    port (    
	ADR:       INOUT  STD_LOGIC;    
	AOUTA:     INOUT  STD_LOGIC;    
	AOUTB:     INOUT  STD_LOGIC;    
	CLKOUT:    INOUT  STD_LOGIC;    
	\dsda/sdin2\: INOUT  STD_LOGIC;    
	\dsdb/lrck2\: INOUT  STD_LOGIC;    
	\dsdclk/sclk2\: INOUT  STD_LOGIC;    
	EP:        INOUT  STD_LOGIC;    
	\filt+\:   INOUT  STD_LOGIC;    
	\filt-\:   INOUT  STD_LOGIC;    
	FLYC_VCP:  INOUT  STD_LOGIC;    
	FLYN_VA:   INOUT  STD_LOGIC;    
	FLYN_VCP:  INOUT  STD_LOGIC;    
	FLYP_VA:   INOUT  STD_LOGIC;    
	FLYP_VCP:  INOUT  STD_LOGIC;    
	GNDA:      INOUT  STD_LOGIC;    
	GNDCP:     INOUT  STD_LOGIC;    
	GNDCP1:    INOUT  STD_LOGIC;    
	GNDCP2:    INOUT  STD_LOGIC;    
	GNDD:      INOUT  STD_LOGIC;    
	HP_DETECT: INOUT  STD_LOGIC;    
	\int#\:    INOUT  STD_LOGIC;    
	LRCK1:     INOUT  STD_LOGIC;    
	REFA:      INOUT  STD_LOGIC;    
	REFB:      INOUT  STD_LOGIC;    
	\reset#\:  INOUT  STD_LOGIC;    
	SCL:       INOUT  STD_LOGIC;    
	SCLK1:     INOUT  STD_LOGIC;    
	SDA:       INOUT  STD_LOGIC;    
	SDIN1:     INOUT  STD_LOGIC;    
	TSO:       INOUT  STD_LOGIC;    
	VA:        INOUT  STD_LOGIC;    
	VCP:       INOUT  STD_LOGIC;    
	\vcp_filt+\: INOUT  STD_LOGIC;    
	\VCP_FILT�C\: IN     STD_LOGIC;    
	VD:        INOUT  STD_LOGIC;    
	VL:        INOUT  STD_LOGIC;    
	VP:        INOUT  STD_LOGIC;    
	\xti/mclk\: INOUT  STD_LOGIC;    
	XTO:       INOUT  STD_LOGIC;    
	\�CVA\:  IN     STD_LOGIC);
end \cs43198-cnzr\;
