// generated by newgenasym  Tue Jan 10 11:54:34 2006


module tps54316 (agnd, boot, fsel, pgnd, ph, pwrgd, pwrpad, rt, \ss/ena , vbias,
        vin, vsense);
    input agnd;
    input boot;
    input fsel;
    input [3:1] pgnd;
    inout [5:1] ph;
    output pwrgd;
    input pwrpad;
    input rt;
    inout \ss/ena ;
    output vbias;
    input [3:1] vin;
    input vsense;


    initial
        begin
        end

endmodule
