-- generated by newgenasym Tue Jan 10 11:54:34 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tps54316 is
    port (    
	AGND:      IN     STD_LOGIC;    
	BOOT:      IN     STD_LOGIC;    
	FSEL:      IN     STD_LOGIC;    
	PGND:      IN     STD_LOGIC_VECTOR (3 DOWNTO 1);    
	PH:        INOUT  STD_LOGIC_VECTOR (5 DOWNTO 1);    
	PWRGD:     OUT    STD_LOGIC;    
	PWRPAD:    IN     STD_LOGIC;    
	RT:        IN     STD_LOGIC;    
	\ss/ena\:  INOUT  STD_LOGIC;    
	VBIAS:     OUT    STD_LOGIC;    
	VIN:       IN     STD_LOGIC_VECTOR (3 DOWNTO 1);    
	VSENSE:    IN     STD_LOGIC);
end tps54316;
