-- generated by newgenasym Sat Nov 29 13:22:28 2025

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity ne5532dr is
    port (    
	\in1+\:    INOUT  STD_LOGIC;    
	\in1-\:    INOUT  STD_LOGIC;    
	\in2+\:    INOUT  STD_LOGIC;    
	\in2-\:    INOUT  STD_LOGIC;    
	OUT1:      INOUT  STD_LOGIC;    
	OUT2:      INOUT  STD_LOGIC;    
	\vcc+\:    INOUT  STD_LOGIC;    
	\vcc-/gnd\: INOUT  STD_LOGIC);
end ne5532dr;
