-- generated by newgenasym Thu Feb 13 14:23:10 2014

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity head2x17 is
    port (    
	A1:        INOUT  STD_LOGIC;    
	A10:       INOUT  STD_LOGIC;    
	A11:       INOUT  STD_LOGIC;    
	A12:       INOUT  STD_LOGIC;    
	A13:       INOUT  STD_LOGIC;    
	A14:       INOUT  STD_LOGIC;    
	A15:       INOUT  STD_LOGIC;    
	A16:       INOUT  STD_LOGIC;    
	A17:       INOUT  STD_LOGIC;    
	A18:       INOUT  STD_LOGIC;    
	A19:       INOUT  STD_LOGIC;    
	A2:        INOUT  STD_LOGIC;    
	A20:       INOUT  STD_LOGIC;    
	A21:       INOUT  STD_LOGIC;    
	A22:       INOUT  STD_LOGIC;    
	A23:       INOUT  STD_LOGIC;    
	A24:       INOUT  STD_LOGIC;    
	A25:       INOUT  STD_LOGIC;    
	A26:       INOUT  STD_LOGIC;    
	A27:       INOUT  STD_LOGIC;    
	A28:       INOUT  STD_LOGIC;    
	A29:       INOUT  STD_LOGIC;    
	A3:        INOUT  STD_LOGIC;    
	A30:       INOUT  STD_LOGIC;    
	A31:       INOUT  STD_LOGIC;    
	A32:       INOUT  STD_LOGIC;    
	A33:       INOUT  STD_LOGIC;    
	A34:       INOUT  STD_LOGIC;    
	A4:        INOUT  STD_LOGIC;    
	A5:        INOUT  STD_LOGIC;    
	A6:        INOUT  STD_LOGIC;    
	A7:        INOUT  STD_LOGIC;    
	A8:        INOUT  STD_LOGIC;    
	A9:        INOUT  STD_LOGIC);
end head2x17;
