// generated by newgenasym  Mon May 22 17:41:33 2017


module el7457 (gnd, ina, inb, inc, ind, oe, outa, outb, outc, outd,
        thermalpad, vh1, vh2, vl1, vl2, \vs+ , \vs- );
    inout gnd;
    inout ina;
    inout inb;
    inout inc;
    inout ind;
    inout oe;
    inout outa;
    inout outb;
    inout outc;
    inout outd;
    inout thermalpad;
    inout vh1;
    inout vh2;
    inout vl1;
    inout vl2;
    inout \vs+ ;
    inout \vs- ;


    initial
        begin
        end

endmodule
