-- generated by newgenasym Mon May 22 17:41:33 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity el7457 is
    port (    
	GND:       INOUT  STD_LOGIC;    
	INA:       INOUT  STD_LOGIC;    
	INB:       INOUT  STD_LOGIC;    
	INC:       INOUT  STD_LOGIC;    
	IND:       INOUT  STD_LOGIC;    
	OE:        INOUT  STD_LOGIC;    
	OUTA:      INOUT  STD_LOGIC;    
	OUTB:      INOUT  STD_LOGIC;    
	OUTC:      INOUT  STD_LOGIC;    
	OUTD:      INOUT  STD_LOGIC;    
	THERMALPAD: INOUT  STD_LOGIC;    
	VH1:       INOUT  STD_LOGIC;    
	VH2:       INOUT  STD_LOGIC;    
	VL1:       INOUT  STD_LOGIC;    
	VL2:       INOUT  STD_LOGIC;    
	\vs+\:     INOUT  STD_LOGIC;    
	\vs-\:     INOUT  STD_LOGIC);
end el7457;
