// generated by newgenasym  Fri Nov 16 12:55:53 2012


module cdc340_1 (\1g , \1y1 , \1y2 , \1y3 , \1y4 , \2g , \2y1 , \2y2 , \2y3 , \2y4 , a, gnd1, gnd2,
        gnd3, gnd4, p0, p1, vcc1, vcc2, vcc3);
    inout \1g ;
    inout \1y1 ;
    inout \1y2 ;
    inout \1y3 ;
    inout \1y4 ;
    inout \2g ;
    inout \2y1 ;
    inout \2y2 ;
    inout \2y3 ;
    inout \2y4 ;
    inout a;
    input gnd1;
    input gnd2;
    input gnd3;
    input gnd4;
    inout p0;
    inout p1;
    input vcc1;
    input vcc2;
    input vcc3;


    initial
        begin
        end

endmodule
