-- generated by newgenasym Fri Nov 16 12:55:53 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity cdc340_1 is
    port (    
	\1g\:      INOUT  STD_LOGIC;    
	\1y1\:     INOUT  STD_LOGIC;    
	\1y2\:     INOUT  STD_LOGIC;    
	\1y3\:     INOUT  STD_LOGIC;    
	\1y4\:     INOUT  STD_LOGIC;    
	\2g\:      INOUT  STD_LOGIC;    
	\2y1\:     INOUT  STD_LOGIC;    
	\2y2\:     INOUT  STD_LOGIC;    
	\2y3\:     INOUT  STD_LOGIC;    
	\2y4\:     INOUT  STD_LOGIC;    
	A:         INOUT  STD_LOGIC;    
	GND1:      IN     STD_LOGIC;    
	GND2:      IN     STD_LOGIC;    
	GND3:      IN     STD_LOGIC;    
	GND4:      IN     STD_LOGIC;    
	P0:        INOUT  STD_LOGIC;    
	P1:        INOUT  STD_LOGIC;    
	VCC1:      IN     STD_LOGIC;    
	VCC2:      IN     STD_LOGIC;    
	VCC3:      IN     STD_LOGIC);
end cdc340_1;
