// generated by newgenasym  Sat Aug 20 15:00:34 2005


module max485 (a, \b* , de, di, gnd, \re* , ro, vcc);
    output a;
    output \b* ;
    input de;
    input di;
    input gnd;
    input \re* ;
    input ro;
    input vcc;


    initial
        begin
        end

endmodule
