-- generated by newgenasym Sat Aug 20 15:00:34 2005

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity MAX485 is
    port (    
	A:         OUT    STD_LOGIC;    
	\b*\:      OUT    STD_LOGIC;    
	DE:        IN     STD_LOGIC;    
	DI:        IN     STD_LOGIC;    
	GND:       IN     STD_LOGIC;    
	\re*\:     IN     STD_LOGIC;    
	RO:        IN     STD_LOGIC;    
	VCC:       IN     STD_LOGIC);
end MAX485;
