// generated by newgenasym  Wed Jun 10 20:49:15 2009


module tps54310 (agnd, boot, comp, pgnd1, pgnd2, pgnd3, ph1, ph2, ph3, ph4, ph5,
        powerpad, pwrgd, rt, \ss/en , sync, vbais, vin1, vin2, vin3,
        vsense);
    input agnd;
    input boot;
    input comp;
    input pgnd1;
    input pgnd2;
    input pgnd3;
    output ph1;
    output ph2;
    output ph3;
    output ph4;
    output ph5;
    inout powerpad;
    output pwrgd;
    input rt;
    input \ss/en ;
    input sync;
    input vbais;
    input vin1;
    input vin2;
    input vin3;
    input vsense;


    initial
        begin
        end

endmodule
