-- generated by newgenasym Wed Jun 10 20:49:15 2009

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity TPS54310 is
    port (    
	AGND:      IN     STD_LOGIC;    
	BOOT:      IN     STD_LOGIC;    
	COMP:      IN     STD_LOGIC;    
	PGND1:     IN     STD_LOGIC;    
	PGND2:     IN     STD_LOGIC;    
	PGND3:     IN     STD_LOGIC;    
	PH1:       OUT    STD_LOGIC;    
	PH2:       OUT    STD_LOGIC;    
	PH3:       OUT    STD_LOGIC;    
	PH4:       OUT    STD_LOGIC;    
	PH5:       OUT    STD_LOGIC;    
	POWERPAD:  INOUT  STD_LOGIC;    
	PWRGD:     OUT    STD_LOGIC;    
	RT:        IN     STD_LOGIC;    
	\ss/en\:   IN     STD_LOGIC;    
	SYNC:      IN     STD_LOGIC;    
	VBAIS:     IN     STD_LOGIC;    
	VIN1:      IN     STD_LOGIC;    
	VIN2:      IN     STD_LOGIC;    
	VIN3:      IN     STD_LOGIC;    
	VSENSE:    IN     STD_LOGIC);
end TPS54310;
