// generated by newgenasym  Tue May 23 17:31:07 2017


module tps7a16 (delay, en, fb, gnd, in, nc, out, pg, therpad);
    inout delay;
    inout en;
    inout fb;
    inout gnd;
    inout in;
    inout nc;
    inout out;
    inout pg;
    inout therpad;


    initial
        begin
        end

endmodule
