-- generated by newgenasym Tue May 23 17:31:07 2017

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity tps7a16 is
    port (    
	DELAY:     INOUT  STD_LOGIC;    
	EN:        INOUT  STD_LOGIC;    
	FB:        INOUT  STD_LOGIC;    
	GND:       INOUT  STD_LOGIC;    
	\in\:      INOUT  STD_LOGIC;    
	NC:        INOUT  STD_LOGIC;    
	\out\:     INOUT  STD_LOGIC;    
	PG:        INOUT  STD_LOGIC;    
	THERPAD:   INOUT  STD_LOGIC);
end tps7a16;
