// generated by newgenasym  Thu Sep 14 14:25:37 2006


module h1102 (nc, rcmt, rct, \rd+ , \rd- , \rx+ , \rx- , tcmt, tct, \td+ , \td- , \tx+ , \tx- );
    inout [4:1] nc;
    input rcmt;
    output rct;
    output \rd+ ;
    output \rd- ;
    input \rx+ ;
    input \rx- ;
    output tcmt;
    input tct;
    input \td+ ;
    input \td- ;
    output \tx+ ;
    output \tx- ;


    initial
        begin
        end

endmodule
