-- generated by newgenasym Thu Sep 14 14:25:37 2006

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity h1102 is
    port (    
	NC:        INOUT  STD_LOGIC_VECTOR (4 DOWNTO 1);    
	RCMT:      IN     STD_LOGIC;    
	RCT:       OUT    STD_LOGIC;    
	\rd+\:     OUT    STD_LOGIC;    
	\rd-\:     OUT    STD_LOGIC;    
	\rx+\:     IN     STD_LOGIC;    
	\rx-\:     IN     STD_LOGIC;    
	TCMT:      OUT    STD_LOGIC;    
	TCT:       IN     STD_LOGIC;    
	\td+\:     IN     STD_LOGIC;    
	\td-\:     IN     STD_LOGIC;    
	\tx+\:     OUT    STD_LOGIC;    
	\tx-\:     OUT    STD_LOGIC);
end h1102;
