// generated by newgenasym  Thu Jun 05 15:42:45 2014


module xc7z020clg484 (cfgbvs_0, done_0, dxn_0, dxp_0, gnd_a15, gnd_a5, gnd_aa15,
        gnd_aa5, gnd_ab18, gnd_ab8, gnd_b18, gnd_b8, gnd_c1,
        gnd_c11, gnd_c21, gnd_d14, gnd_d4, gnd_e17, gnd_e7, gnd_f10,
        gnd_f20, gnd_g3, gnd_h12, gnd_h14, gnd_h16, gnd_h6, gnd_h8,
        gnd_j11, gnd_j13, gnd_j19, gnd_j9, gnd_k10, gnd_k14, gnd_k2,
        gnd_k22, gnd_k8, gnd_l13, gnd_l15, gnd_l5, gnd_l9, gnd_m10,
        gnd_m14, gnd_m18, gnd_m8, gnd_n1, gnd_n13, gnd_n21, gnd_n9,
        gnd_p10, gnd_p12, gnd_p14, gnd_p4, gnd_p8, gnd_r11, gnd_r13,
        gnd_r17, gnd_r9, gnd_t20, gnd_u13, gnd_u3, gnd_v16, gnd_v6,
        gnd_w19, gnd_w9, gnd_y12, gnd_y2, gnd_y22, gndadc_0,
        init_b_0, io_0_13, io_0_33, io_0_34, io_0_35, io_25_13,
        io_25_33, io_25_34, io_25_35, io_l10n_t1_13,
        io_l10n_t1_33, io_l10n_t1_34, io_l10n_t1_ad11n_35,
        io_l10p_t1_13, io_l10p_t1_33, io_l10p_t1_34,
        io_l10p_t1_ad11p_35, io_l11n_t1_srcc_13,
        io_l11n_t1_srcc_33, io_l11n_t1_srcc_34,
        io_l11n_t1_srcc_35, io_l11p_t1_srcc_13,
        io_l11p_t1_srcc_33, io_l11p_t1_srcc_34,
        io_l11p_t1_srcc_35, io_l12n_t1_mrcc_13,
        io_l12n_t1_mrcc_33, io_l12n_t1_mrcc_34,
        io_l12n_t1_mrcc_35, io_l12p_t1_mrcc_13,
        io_l12p_t1_mrcc_33, io_l12p_t1_mrcc_34,
        io_l12p_t1_mrcc_35, io_l13n_t2_mrcc_13,
        io_l13n_t2_mrcc_33, io_l13n_t2_mrcc_34,
        io_l13n_t2_mrcc_35, io_l13p_t2_mrcc_13,
        io_l13p_t2_mrcc_33, io_l13p_t2_mrcc_34,
        io_l13p_t2_mrcc_35, io_l14n_t2_ad4n_srcc_35,
        io_l14n_t2_srcc_13, io_l14n_t2_srcc_33,
        io_l14n_t2_srcc_34, io_l14p_t2_ad4p_srcc_35,
        io_l14p_t2_srcc_13, io_l14p_t2_srcc_33,
        io_l14p_t2_srcc_34, io_l15n_t2_dqs_13,
        io_l15n_t2_dqs_33, io_l15n_t2_dqs_34,
        io_l15n_t2_dqs_ad12n_35, io_l15p_t2_dqs_13,
        io_l15p_t2_dqs_33, io_l15p_t2_dqs_34,
        io_l15p_t2_dqs_ad12p_35, io_l16n_t2_13, io_l16n_t2_33,
        io_l16n_t2_34, io_l16n_t2_35, io_l16p_t2_13,
        io_l16p_t2_33, io_l16p_t2_34, io_l16p_t2_35,
        io_l17n_t2_13, io_l17n_t2_33, io_l17n_t2_34,
        io_l17n_t2_ad5n_35, io_l17p_t2_13, io_l17p_t2_33,
        io_l17p_t2_34, io_l17p_t2_ad5p_35, io_l18n_t2_13,
        io_l18n_t2_33, io_l18n_t2_34, io_l18n_t2_ad13n_35,
        io_l18p_t2_13, io_l18p_t2_33, io_l18p_t2_34,
        io_l18p_t2_ad13p_35, io_l19n_t3_vref_13,
        io_l19n_t3_vref_33, io_l19n_t3_vref_34,
        io_l19n_t3_vref_35, io_l19p_t3_13, io_l19p_t3_33,
        io_l19p_t3_34, io_l19p_t3_35, io_l1n_t0_13, io_l1n_t0_33,
        io_l1n_t0_34, io_l1n_t0_ad0n_35, io_l1p_t0_13,
        io_l1p_t0_33, io_l1p_t0_34, io_l1p_t0_ad0p_35,
        io_l20n_t3_13, io_l20n_t3_33, io_l20n_t3_34,
        io_l20n_t3_ad6n_35, io_l20p_t3_13, io_l20p_t3_33,
        io_l20p_t3_34, io_l20p_t3_ad6p_35, io_l21n_t3_dqs_13,
        io_l21n_t3_dqs_33, io_l21n_t3_dqs_34,
        io_l21n_t3_dqs_ad14n_35, io_l21p_t3_dqs_13,
        io_l21p_t3_dqs_33, io_l21p_t3_dqs_34,
        io_l21p_t3_dqs_ad14p_35, io_l22n_t3_13, io_l22n_t3_33,
        io_l22n_t3_34, io_l22n_t3_ad7n_35, io_l22p_t3_13,
        io_l22p_t3_33, io_l22p_t3_34, io_l22p_t3_ad7p_35,
        io_l23n_t3_13, io_l23n_t3_33, io_l23n_t3_34,
        io_l23n_t3_35, io_l23p_t3_13, io_l23p_t3_33,
        io_l23p_t3_34, io_l23p_t3_35, io_l24n_t3_13,
        io_l24n_t3_33, io_l24n_t3_34, io_l24n_t3_ad15n_35,
        io_l24p_t3_13, io_l24p_t3_33, io_l24p_t3_34,
        io_l24p_t3_ad15p_35, io_l2n_t0_13, io_l2n_t0_33,
        io_l2n_t0_34, io_l2n_t0_ad8n_35, io_l2p_t0_13,
        io_l2p_t0_33, io_l2p_t0_34, io_l2p_t0_ad8p_35,
        io_l3n_t0_dqs_13, io_l3n_t0_dqs_33, io_l3n_t0_dqs_34,
        io_l3n_t0_dqs_ad1n_35, io_l3p_t0_dqs_13,
        io_l3p_t0_dqs_33, io_l3p_t0_dqs_ad1p_35,
        io_l3p_t0_dqs_pudc_b_34, io_l4n_t0_13, io_l4n_t0_33,
        io_l4n_t0_34, io_l4n_t0_35, io_l4p_t0_13, io_l4p_t0_33,
        io_l4p_t0_34, io_l4p_t0_35, io_l5n_t0_13, io_l5n_t0_33,
        io_l5n_t0_34, io_l5n_t0_ad9n_35, io_l5p_t0_13,
        io_l5p_t0_33, io_l5p_t0_34, io_l5p_t0_ad9p_35,
        io_l6n_t0_vref_13, io_l6n_t0_vref_33, io_l6n_t0_vref_34,
        io_l6n_t0_vref_35, io_l6p_t0_13, io_l6p_t0_33,
        io_l6p_t0_34, io_l6p_t0_35, io_l7n_t1_13, io_l7n_t1_33,
        io_l7n_t1_34, io_l7n_t1_ad2n_35, io_l7p_t1_13,
        io_l7p_t1_33, io_l7p_t1_34, io_l7p_t1_ad2p_35,
        io_l8n_t1_13, io_l8n_t1_33, io_l8n_t1_34,
        io_l8n_t1_ad10n_35, io_l8p_t1_13, io_l8p_t1_33,
        io_l8p_t1_34, io_l8p_t1_ad10p_35, io_l9n_t1_dqs_13,
        io_l9n_t1_dqs_33, io_l9n_t1_dqs_34,
        io_l9n_t1_dqs_ad3n_35, io_l9p_t1_dqs_13,
        io_l9p_t1_dqs_33, io_l9p_t1_dqs_34,
        io_l9p_t1_dqs_ad3p_35, program_b_0, ps_clk_500,
        ps_ddr_a0_502, ps_ddr_a10_502, ps_ddr_a11_502,
        ps_ddr_a12_502, ps_ddr_a13_502, ps_ddr_a14_502,
        ps_ddr_a1_502, ps_ddr_a2_502, ps_ddr_a3_502,
        ps_ddr_a4_502, ps_ddr_a5_502, ps_ddr_a6_502,
        ps_ddr_a7_502, ps_ddr_a8_502, ps_ddr_a9_502,
        ps_ddr_ba0_502, ps_ddr_ba1_502, ps_ddr_ba2_502,
        ps_ddr_cas_b_502, ps_ddr_cke_502, ps_ddr_ckn_502,
        ps_ddr_ckp_502, ps_ddr_cs_b_502, ps_ddr_dm0_502,
        ps_ddr_dm1_502, ps_ddr_dm2_502, ps_ddr_dm3_502,
        ps_ddr_dq0_502, ps_ddr_dq10_502, ps_ddr_dq11_502,
        ps_ddr_dq12_502, ps_ddr_dq13_502, ps_ddr_dq14_502,
        ps_ddr_dq15_502, ps_ddr_dq16_502, ps_ddr_dq17_502,
        ps_ddr_dq18_502, ps_ddr_dq19_502, ps_ddr_dq1_502,
        ps_ddr_dq20_502, ps_ddr_dq21_502, ps_ddr_dq22_502,
        ps_ddr_dq23_502, ps_ddr_dq24_502, ps_ddr_dq25_502,
        ps_ddr_dq26_502, ps_ddr_dq27_502, ps_ddr_dq28_502,
        ps_ddr_dq29_502, ps_ddr_dq2_502, ps_ddr_dq30_502,
        ps_ddr_dq31_502, ps_ddr_dq3_502, ps_ddr_dq4_502,
        ps_ddr_dq5_502, ps_ddr_dq6_502, ps_ddr_dq7_502,
        ps_ddr_dq8_502, ps_ddr_dq9_502, ps_ddr_dqs_n0_502,
        ps_ddr_dqs_n1_502, ps_ddr_dqs_n2_502, ps_ddr_dqs_n3_502,
        ps_ddr_dqs_p0_502, ps_ddr_dqs_p1_502, ps_ddr_dqs_p2_502,
        ps_ddr_dqs_p3_502, ps_ddr_drst_b_502, ps_ddr_odt_502,
        ps_ddr_ras_b_502, ps_ddr_vref0_502_h7,
        ps_ddr_vref1_502_p7, ps_ddr_vrn_502, ps_ddr_vrp_502,
        ps_ddr_we_b_502, ps_mio0_500, ps_mio10_500, ps_mio11_500,
        ps_mio12_500, ps_mio13_500, ps_mio14_500, ps_mio15_500,
        ps_mio16_501, ps_mio17_501, ps_mio18_501, ps_mio19_501,
        ps_mio1_500, ps_mio20_501, ps_mio21_501, ps_mio22_501,
        ps_mio23_501, ps_mio24_501, ps_mio25_501, ps_mio26_501,
        ps_mio27_501, ps_mio28_501, ps_mio29_501, ps_mio2_500,
        ps_mio30_501, ps_mio31_501, ps_mio32_501, ps_mio33_501,
        ps_mio34_501, ps_mio35_501, ps_mio36_501, ps_mio37_501,
        ps_mio38_501, ps_mio39_501, ps_mio3_500, ps_mio40_501,
        ps_mio41_501, ps_mio42_501, ps_mio43_501, ps_mio44_501,
        ps_mio45_501, ps_mio46_501, ps_mio47_501, ps_mio48_501,
        ps_mio49_501, ps_mio4_500, ps_mio50_501, ps_mio51_501,
        ps_mio52_501, ps_mio53_501, ps_mio5_500, ps_mio6_500,
        ps_mio7_500, ps_mio8_500, ps_mio9_500, ps_mio_vref_501,
        ps_por_b_500, ps_srst_b_501, rsvdgnd, rsvdvcc1, rsvdvcc2,
        rsvdvcc3, tck_0, tdi_0, tdo_0, tms_0, vccadc_0, vccaux_l10,
        vccaux_n10, vccaux_p11, vccaux_r10, vccbatt_0,
        vccbram_h11, vccbram_j10, vccint_j12, vccint_j14,
        vccint_k13, vccint_l14, vccint_m13, vccint_n14,
        vccint_p13, vccint_r14, vcco_0_r12, vcco_13_aa10,
        vcco_13_ab3, vcco_13_t5, vcco_13_u8, vcco_13_v11,
        vcco_13_w4, vcco_13_y7, vcco_33_aa20, vcco_33_ab13,
        vcco_33_u18, vcco_33_v21, vcco_33_w14, vcco_33_y17,
        vcco_34_k17, vcco_34_l20, vcco_34_n16, vcco_34_p19,
        vcco_34_r22, vcco_34_t15, vcco_35_a20, vcco_35_c16,
        vcco_35_d19, vcco_35_e22, vcco_35_f15, vcco_35_g18,
        vcco_35_h21, vcco_ddr_502_e2, vcco_ddr_502_f5,
        vcco_ddr_502_h1, vcco_ddr_502_j4, vcco_ddr_502_k7,
        vcco_ddr_502_m3, vcco_ddr_502_n6, vcco_ddr_502_r2,
        vcco_ddr_502_v1, vcco_mio0_500_b3, vcco_mio0_500_c6,
        vcco_mio1_501_a10, vcco_mio1_501_b13, vcco_mio1_501_d9,
        vcco_mio1_501_e12, vccpaux_k9, vccpaux_m9, vccpaux_p9,
        vccpaux_t9, vccpint_g8, vccpint_h9, vccpint_j8,
        vccpint_l8, vccpint_n8, vccpint_r8, vccpll_h10, vn_0, vp_0,
        vrefn_0, vrefp_0);
    inout cfgbvs_0;
    inout done_0;
    inout dxn_0;
    inout dxp_0;
    inout gnd_a15;
    inout gnd_a5;
    inout gnd_aa15;
    inout gnd_aa5;
    inout gnd_ab18;
    inout gnd_ab8;
    inout gnd_b18;
    inout gnd_b8;
    inout gnd_c1;
    inout gnd_c11;
    inout gnd_c21;
    inout gnd_d14;
    inout gnd_d4;
    inout gnd_e17;
    inout gnd_e7;
    inout gnd_f10;
    inout gnd_f20;
    inout gnd_g3;
    inout gnd_h12;
    inout gnd_h14;
    inout gnd_h16;
    inout gnd_h6;
    inout gnd_h8;
    inout gnd_j11;
    inout gnd_j13;
    inout gnd_j19;
    inout gnd_j9;
    inout gnd_k10;
    inout gnd_k14;
    inout gnd_k2;
    inout gnd_k22;
    inout gnd_k8;
    inout gnd_l13;
    inout gnd_l15;
    inout gnd_l5;
    inout gnd_l9;
    inout gnd_m10;
    inout gnd_m14;
    inout gnd_m18;
    inout gnd_m8;
    inout gnd_n1;
    inout gnd_n13;
    inout gnd_n21;
    inout gnd_n9;
    inout gnd_p10;
    inout gnd_p12;
    inout gnd_p14;
    inout gnd_p4;
    inout gnd_p8;
    inout gnd_r11;
    inout gnd_r13;
    inout gnd_r17;
    inout gnd_r9;
    inout gnd_t20;
    inout gnd_u13;
    inout gnd_u3;
    inout gnd_v16;
    inout gnd_v6;
    inout gnd_w19;
    inout gnd_w9;
    inout gnd_y12;
    inout gnd_y2;
    inout gnd_y22;
    inout gndadc_0;
    inout init_b_0;
    inout io_0_13;
    inout io_0_33;
    inout io_0_34;
    inout io_0_35;
    inout io_25_13;
    inout io_25_33;
    inout io_25_34;
    inout io_25_35;
    inout io_l10n_t1_13;
    inout io_l10n_t1_33;
    inout io_l10n_t1_34;
    inout io_l10n_t1_ad11n_35;
    inout io_l10p_t1_13;
    inout io_l10p_t1_33;
    inout io_l10p_t1_34;
    inout io_l10p_t1_ad11p_35;
    inout io_l11n_t1_srcc_13;
    inout io_l11n_t1_srcc_33;
    inout io_l11n_t1_srcc_34;
    inout io_l11n_t1_srcc_35;
    inout io_l11p_t1_srcc_13;
    inout io_l11p_t1_srcc_33;
    inout io_l11p_t1_srcc_34;
    inout io_l11p_t1_srcc_35;
    inout io_l12n_t1_mrcc_13;
    inout io_l12n_t1_mrcc_33;
    inout io_l12n_t1_mrcc_34;
    inout io_l12n_t1_mrcc_35;
    inout io_l12p_t1_mrcc_13;
    inout io_l12p_t1_mrcc_33;
    inout io_l12p_t1_mrcc_34;
    inout io_l12p_t1_mrcc_35;
    inout io_l13n_t2_mrcc_13;
    inout io_l13n_t2_mrcc_33;
    inout io_l13n_t2_mrcc_34;
    inout io_l13n_t2_mrcc_35;
    inout io_l13p_t2_mrcc_13;
    inout io_l13p_t2_mrcc_33;
    inout io_l13p_t2_mrcc_34;
    inout io_l13p_t2_mrcc_35;
    inout io_l14n_t2_ad4n_srcc_35;
    inout io_l14n_t2_srcc_13;
    inout io_l14n_t2_srcc_33;
    inout io_l14n_t2_srcc_34;
    inout io_l14p_t2_ad4p_srcc_35;
    inout io_l14p_t2_srcc_13;
    inout io_l14p_t2_srcc_33;
    inout io_l14p_t2_srcc_34;
    inout io_l15n_t2_dqs_13;
    inout io_l15n_t2_dqs_33;
    inout io_l15n_t2_dqs_34;
    inout io_l15n_t2_dqs_ad12n_35;
    inout io_l15p_t2_dqs_13;
    inout io_l15p_t2_dqs_33;
    inout io_l15p_t2_dqs_34;
    inout io_l15p_t2_dqs_ad12p_35;
    inout io_l16n_t2_13;
    inout io_l16n_t2_33;
    inout io_l16n_t2_34;
    inout io_l16n_t2_35;
    inout io_l16p_t2_13;
    inout io_l16p_t2_33;
    inout io_l16p_t2_34;
    inout io_l16p_t2_35;
    inout io_l17n_t2_13;
    inout io_l17n_t2_33;
    inout io_l17n_t2_34;
    inout io_l17n_t2_ad5n_35;
    inout io_l17p_t2_13;
    inout io_l17p_t2_33;
    inout io_l17p_t2_34;
    inout io_l17p_t2_ad5p_35;
    inout io_l18n_t2_13;
    inout io_l18n_t2_33;
    inout io_l18n_t2_34;
    inout io_l18n_t2_ad13n_35;
    inout io_l18p_t2_13;
    inout io_l18p_t2_33;
    inout io_l18p_t2_34;
    inout io_l18p_t2_ad13p_35;
    inout io_l19n_t3_vref_13;
    inout io_l19n_t3_vref_33;
    inout io_l19n_t3_vref_34;
    inout io_l19n_t3_vref_35;
    inout io_l19p_t3_13;
    inout io_l19p_t3_33;
    inout io_l19p_t3_34;
    inout io_l19p_t3_35;
    inout io_l1n_t0_13;
    inout io_l1n_t0_33;
    inout io_l1n_t0_34;
    inout io_l1n_t0_ad0n_35;
    inout io_l1p_t0_13;
    inout io_l1p_t0_33;
    inout io_l1p_t0_34;
    inout io_l1p_t0_ad0p_35;
    inout io_l20n_t3_13;
    inout io_l20n_t3_33;
    inout io_l20n_t3_34;
    inout io_l20n_t3_ad6n_35;
    inout io_l20p_t3_13;
    inout io_l20p_t3_33;
    inout io_l20p_t3_34;
    inout io_l20p_t3_ad6p_35;
    inout io_l21n_t3_dqs_13;
    inout io_l21n_t3_dqs_33;
    inout io_l21n_t3_dqs_34;
    inout io_l21n_t3_dqs_ad14n_35;
    inout io_l21p_t3_dqs_13;
    inout io_l21p_t3_dqs_33;
    inout io_l21p_t3_dqs_34;
    inout io_l21p_t3_dqs_ad14p_35;
    inout io_l22n_t3_13;
    inout io_l22n_t3_33;
    inout io_l22n_t3_34;
    inout io_l22n_t3_ad7n_35;
    inout io_l22p_t3_13;
    inout io_l22p_t3_33;
    inout io_l22p_t3_34;
    inout io_l22p_t3_ad7p_35;
    inout io_l23n_t3_13;
    inout io_l23n_t3_33;
    inout io_l23n_t3_34;
    inout io_l23n_t3_35;
    inout io_l23p_t3_13;
    inout io_l23p_t3_33;
    inout io_l23p_t3_34;
    inout io_l23p_t3_35;
    inout io_l24n_t3_13;
    inout io_l24n_t3_33;
    inout io_l24n_t3_34;
    inout io_l24n_t3_ad15n_35;
    inout io_l24p_t3_13;
    inout io_l24p_t3_33;
    inout io_l24p_t3_34;
    inout io_l24p_t3_ad15p_35;
    inout io_l2n_t0_13;
    inout io_l2n_t0_33;
    inout io_l2n_t0_34;
    inout io_l2n_t0_ad8n_35;
    inout io_l2p_t0_13;
    inout io_l2p_t0_33;
    inout io_l2p_t0_34;
    inout io_l2p_t0_ad8p_35;
    inout io_l3n_t0_dqs_13;
    inout io_l3n_t0_dqs_33;
    inout io_l3n_t0_dqs_34;
    inout io_l3n_t0_dqs_ad1n_35;
    inout io_l3p_t0_dqs_13;
    inout io_l3p_t0_dqs_33;
    inout io_l3p_t0_dqs_ad1p_35;
    inout io_l3p_t0_dqs_pudc_b_34;
    inout io_l4n_t0_13;
    inout io_l4n_t0_33;
    inout io_l4n_t0_34;
    inout io_l4n_t0_35;
    inout io_l4p_t0_13;
    inout io_l4p_t0_33;
    inout io_l4p_t0_34;
    inout io_l4p_t0_35;
    inout io_l5n_t0_13;
    inout io_l5n_t0_33;
    inout io_l5n_t0_34;
    inout io_l5n_t0_ad9n_35;
    inout io_l5p_t0_13;
    inout io_l5p_t0_33;
    inout io_l5p_t0_34;
    inout io_l5p_t0_ad9p_35;
    inout io_l6n_t0_vref_13;
    inout io_l6n_t0_vref_33;
    inout io_l6n_t0_vref_34;
    inout io_l6n_t0_vref_35;
    inout io_l6p_t0_13;
    inout io_l6p_t0_33;
    inout io_l6p_t0_34;
    inout io_l6p_t0_35;
    inout io_l7n_t1_13;
    inout io_l7n_t1_33;
    inout io_l7n_t1_34;
    inout io_l7n_t1_ad2n_35;
    inout io_l7p_t1_13;
    inout io_l7p_t1_33;
    inout io_l7p_t1_34;
    inout io_l7p_t1_ad2p_35;
    inout io_l8n_t1_13;
    inout io_l8n_t1_33;
    inout io_l8n_t1_34;
    inout io_l8n_t1_ad10n_35;
    inout io_l8p_t1_13;
    inout io_l8p_t1_33;
    inout io_l8p_t1_34;
    inout io_l8p_t1_ad10p_35;
    inout io_l9n_t1_dqs_13;
    inout io_l9n_t1_dqs_33;
    inout io_l9n_t1_dqs_34;
    inout io_l9n_t1_dqs_ad3n_35;
    inout io_l9p_t1_dqs_13;
    inout io_l9p_t1_dqs_33;
    inout io_l9p_t1_dqs_34;
    inout io_l9p_t1_dqs_ad3p_35;
    inout program_b_0;
    inout ps_clk_500;
    inout ps_ddr_a0_502;
    inout ps_ddr_a10_502;
    inout ps_ddr_a11_502;
    inout ps_ddr_a12_502;
    inout ps_ddr_a13_502;
    inout ps_ddr_a14_502;
    inout ps_ddr_a1_502;
    inout ps_ddr_a2_502;
    inout ps_ddr_a3_502;
    inout ps_ddr_a4_502;
    inout ps_ddr_a5_502;
    inout ps_ddr_a6_502;
    inout ps_ddr_a7_502;
    inout ps_ddr_a8_502;
    inout ps_ddr_a9_502;
    inout ps_ddr_ba0_502;
    inout ps_ddr_ba1_502;
    inout ps_ddr_ba2_502;
    inout ps_ddr_cas_b_502;
    inout ps_ddr_cke_502;
    inout ps_ddr_ckn_502;
    inout ps_ddr_ckp_502;
    inout ps_ddr_cs_b_502;
    inout ps_ddr_dm0_502;
    inout ps_ddr_dm1_502;
    inout ps_ddr_dm2_502;
    inout ps_ddr_dm3_502;
    inout ps_ddr_dq0_502;
    inout ps_ddr_dq10_502;
    inout ps_ddr_dq11_502;
    inout ps_ddr_dq12_502;
    inout ps_ddr_dq13_502;
    inout ps_ddr_dq14_502;
    inout ps_ddr_dq15_502;
    inout ps_ddr_dq16_502;
    inout ps_ddr_dq17_502;
    inout ps_ddr_dq18_502;
    inout ps_ddr_dq19_502;
    inout ps_ddr_dq1_502;
    inout ps_ddr_dq20_502;
    inout ps_ddr_dq21_502;
    inout ps_ddr_dq22_502;
    inout ps_ddr_dq23_502;
    inout ps_ddr_dq24_502;
    inout ps_ddr_dq25_502;
    inout ps_ddr_dq26_502;
    inout ps_ddr_dq27_502;
    inout ps_ddr_dq28_502;
    inout ps_ddr_dq29_502;
    inout ps_ddr_dq2_502;
    inout ps_ddr_dq30_502;
    inout ps_ddr_dq31_502;
    inout ps_ddr_dq3_502;
    inout ps_ddr_dq4_502;
    inout ps_ddr_dq5_502;
    inout ps_ddr_dq6_502;
    inout ps_ddr_dq7_502;
    inout ps_ddr_dq8_502;
    inout ps_ddr_dq9_502;
    inout ps_ddr_dqs_n0_502;
    inout ps_ddr_dqs_n1_502;
    inout ps_ddr_dqs_n2_502;
    inout ps_ddr_dqs_n3_502;
    inout ps_ddr_dqs_p0_502;
    inout ps_ddr_dqs_p1_502;
    inout ps_ddr_dqs_p2_502;
    inout ps_ddr_dqs_p3_502;
    inout ps_ddr_drst_b_502;
    inout ps_ddr_odt_502;
    inout ps_ddr_ras_b_502;
    inout ps_ddr_vref0_502_h7;
    inout ps_ddr_vref1_502_p7;
    inout ps_ddr_vrn_502;
    inout ps_ddr_vrp_502;
    inout ps_ddr_we_b_502;
    inout ps_mio0_500;
    inout ps_mio10_500;
    inout ps_mio11_500;
    inout ps_mio12_500;
    inout ps_mio13_500;
    inout ps_mio14_500;
    inout ps_mio15_500;
    inout ps_mio16_501;
    inout ps_mio17_501;
    inout ps_mio18_501;
    inout ps_mio19_501;
    inout ps_mio1_500;
    inout ps_mio20_501;
    inout ps_mio21_501;
    inout ps_mio22_501;
    inout ps_mio23_501;
    inout ps_mio24_501;
    inout ps_mio25_501;
    inout ps_mio26_501;
    inout ps_mio27_501;
    inout ps_mio28_501;
    inout ps_mio29_501;
    inout ps_mio2_500;
    inout ps_mio30_501;
    inout ps_mio31_501;
    inout ps_mio32_501;
    inout ps_mio33_501;
    inout ps_mio34_501;
    inout ps_mio35_501;
    inout ps_mio36_501;
    inout ps_mio37_501;
    inout ps_mio38_501;
    inout ps_mio39_501;
    inout ps_mio3_500;
    inout ps_mio40_501;
    inout ps_mio41_501;
    inout ps_mio42_501;
    inout ps_mio43_501;
    inout ps_mio44_501;
    inout ps_mio45_501;
    inout ps_mio46_501;
    inout ps_mio47_501;
    inout ps_mio48_501;
    inout ps_mio49_501;
    inout ps_mio4_500;
    inout ps_mio50_501;
    inout ps_mio51_501;
    inout ps_mio52_501;
    inout ps_mio53_501;
    inout ps_mio5_500;
    inout ps_mio6_500;
    inout ps_mio7_500;
    inout ps_mio8_500;
    inout ps_mio9_500;
    inout ps_mio_vref_501;
    inout ps_por_b_500;
    inout ps_srst_b_501;
    inout rsvdgnd;
    inout rsvdvcc1;
    inout rsvdvcc2;
    inout rsvdvcc3;
    inout tck_0;
    inout tdi_0;
    inout tdo_0;
    inout tms_0;
    inout vccadc_0;
    inout vccaux_l10;
    inout vccaux_n10;
    inout vccaux_p11;
    inout vccaux_r10;
    inout vccbatt_0;
    inout vccbram_h11;
    inout vccbram_j10;
    inout vccint_j12;
    inout vccint_j14;
    inout vccint_k13;
    inout vccint_l14;
    inout vccint_m13;
    inout vccint_n14;
    inout vccint_p13;
    inout vccint_r14;
    inout vcco_0_r12;
    inout vcco_13_aa10;
    inout vcco_13_ab3;
    inout vcco_13_t5;
    inout vcco_13_u8;
    inout vcco_13_v11;
    inout vcco_13_w4;
    inout vcco_13_y7;
    inout vcco_33_aa20;
    inout vcco_33_ab13;
    inout vcco_33_u18;
    inout vcco_33_v21;
    inout vcco_33_w14;
    inout vcco_33_y17;
    inout vcco_34_k17;
    inout vcco_34_l20;
    inout vcco_34_n16;
    inout vcco_34_p19;
    inout vcco_34_r22;
    inout vcco_34_t15;
    inout vcco_35_a20;
    inout vcco_35_c16;
    inout vcco_35_d19;
    inout vcco_35_e22;
    inout vcco_35_f15;
    inout vcco_35_g18;
    inout vcco_35_h21;
    inout vcco_ddr_502_e2;
    inout vcco_ddr_502_f5;
    inout vcco_ddr_502_h1;
    inout vcco_ddr_502_j4;
    inout vcco_ddr_502_k7;
    inout vcco_ddr_502_m3;
    inout vcco_ddr_502_n6;
    inout vcco_ddr_502_r2;
    inout vcco_ddr_502_v1;
    inout vcco_mio0_500_b3;
    inout vcco_mio0_500_c6;
    inout vcco_mio1_501_a10;
    inout vcco_mio1_501_b13;
    inout vcco_mio1_501_d9;
    inout vcco_mio1_501_e12;
    inout vccpaux_k9;
    inout vccpaux_m9;
    inout vccpaux_p9;
    inout vccpaux_t9;
    inout vccpint_g8;
    inout vccpint_h9;
    inout vccpint_j8;
    inout vccpint_l8;
    inout vccpint_n8;
    inout vccpint_r8;
    inout vccpll_h10;
    inout vn_0;
    inout vp_0;
    inout vrefn_0;
    inout vrefp_0;


    initial
        begin
        end

endmodule
