// generated by newgenasym  Tue Feb 09 14:59:37 2021


module sy8303 (bs, en, fb, fs, gnd1, gnd2, in, lx);
    inout bs;
    inout en;
    inout fb;
    inout fs;
    inout gnd1;
    inout gnd2;
    inout in;
    inout lx;


    initial
        begin
        end

endmodule
