-- generated by newgenasym Tue Feb 09 14:59:37 2021

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity SY8303 is
    port (    
	BS:        INOUT  STD_LOGIC;    
	EN:        INOUT  STD_LOGIC;    
	FB:        INOUT  STD_LOGIC;    
	FS:        INOUT  STD_LOGIC;    
	GND1:      INOUT  STD_LOGIC;    
	GND2:      INOUT  STD_LOGIC;    
	\in\:      INOUT  STD_LOGIC;    
	LX:        INOUT  STD_LOGIC);
end SY8303;
